### ISSUE TITLE
NoSnapshotTest.update flaky

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#10063]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once on main https://github.com/camunda/zeebe/runs/7746671246?check_suite_focus=true
- Does it block your work? Not yet
- Do we suspect that it is a real failure? Yes.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
io.camunda.zeebe.test.NoSnapshotTest.update(String, UpdateTestCase, ContainerState)[2]  Time elapsed: 76.739 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with alias 'has completed process process' didn't complete within 10 seconds because assertion condition defined as a io.camunda.zeebe.test.ContainerStateAssert expected process process to be completed, but was not.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
	at io.camunda.zeebe.test.ContainerStateAssert.eventuallyHasCompletedProcess(ContainerStateAssert.java:44)
	at io.camunda.zeebe.test.NoSnapshotTest.update(NoSnapshotTest.java:57)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[Integration test results.zip](https://github.com/camunda/zeebe/files/9335551/Integration.test.results.zip)

**Comment by npepinpe** [comment]
Unfortunately, on re-run, flaky tests lose the STDOUT, so we don't really know what went wrong, other than the process was not completed in time. I'd like to time box some time to figure out how to keep the flaky test outputs, unless someone has some other idea how to debug this (other than if you luckily manage to reproduce it locally).

**Comment by megglos** [comment]
@npepinpe unblocked now thanks to your change #10520 ?

**Comment by npepinpe** [comment]
I cannot reproduce it, and am not aware of it happening recently. Since we have no logs, I'll put this in the backlog until the next time it happens.

**Comment by npepinpe** [comment]
Maybe we can close it after some time of inactivity?

**Comment by megglos** [comment]
closing as stale

**Comment by mustafadagher** [comment]
happened again [here](https://github.com/camunda/camunda/actions/runs/9793946486)

[Logs](https://drive.google.com/file/d/1V7-9yabQODJ57v_S3ucliVC5jp-qki2B/view?usp=drive_link)

**Comment by deepthidevaki** [comment]
From the logs, it looks like the container abruptly stopped or crashed. 
* There are no explicit errors in the broker except for a connection error. `io.atomix.cluster.messaging.MessagingException$ConnectionClosed: Channel [id: 0x97cc7de5] for address tc-1sZ5RAkR:26501 was closed unexpectedly before the request was handled`
* There are no broker shutdown logs, which makes me think that the container was abruptly terminated. If the test had simply failed, I would expect that container is shutdown gracefully.

Also see the following log which indicates some issue with the container
```
12:10:46.930 [ForkJoinPool-1-worker-1] [] INFO  tc.localhost:5000/camunda/zeebe:current-test - Container localhost:5000/camunda/zeebe:current-test started in PT15.088257196S
12:10:52.071 [ForkJoinPool-1-worker-1] [] ERROR io.camunda.zeebe.test.ContainerState - 
```
I assume it was some temporary infrastructure problem.

I will close this issue. Please re-open if occurred again.
