### ISSUE TITLE
Extend bors to have dedicated maintenance staging branches

### ISSUE THREAD

**Issue by megglos** [camunda/camunda#10588]
**Description**

Currently bors is only supporting a single staging branch, especially during releases this can cause waiting periods for the release manager as backport merges to the release branch are competing with merges to `main`. This is because bors only supports a single staging branch config.

It would be nice to extend bors for allowing multiple target/staging branch relationships in order to allow multiple merges to run in parallel that used different staging branches if they have different targets. Basically allowing one merge at a time per target branch.

See https://github.com/bors-ng/bors-ng/issues/558

//CC @Zelldon

**Comment by megglos** [comment]
Motivation for this is impacted by the upcoming Merge Queue feature of Github.
From the [docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) it seems these will be configurable per target branch.

**Comment by npepinpe** [comment]
Closing, we don't use bors anymore.
