### ISSUE TITLE
Apply metric labels statically

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#11267]
We use the prometheus client library to create and register metrics like this:
```java
  private static final Gauge CURRENT_LIMIT =
      Gauge.build()
          .namespace("zeebe")
          .name("backpressure_append_limit")
          .help("Current limit for number of inflight appends")
          .labelNames("partition")
          .register();
```
When we update values, we usually have to specify the labels first:
```java
CURRENT_LIMIT.labels(partitionLabel).set(-1)
```
Surprisingly, setting the labels is [fairly expensive](https://github.com/prometheus/client_java/blob/7cf0cc9dc58981198be106a27333653bed7bf688/simpleclient/src/main/java/io/prometheus/client/SimpleCollector.java#L63-L80) so in cases where the labels are static, for example a partition id that doesn't change dynamically, it can be worth it to pre-construct the metric:
```java
this.inflightLimit = CURRENT_LIMIT.labels(partitionLabel);
```
and then use this object (of type `Gauge.Child`) to update values:
```java
inflightLimit.set(-1)
```

This removes a bit of overhead which is especially important if the metric value is updated in a hot path.

**Comment by npepinpe** [comment]
Let's keep going as we've been doing. I don't think we need a big sweeping refactor, but just keep updating all places we touch.
