### ISSUE TITLE
Automate performance tests

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#11561]
Add automated performance tests that ensure that we spot regressions in throughput or process instance execution duration.
For automated performance tests to be useful we must ensure that the tests are somewhat reproducible. That means:
- Running on nodes that are stable for the test duration
- Having an even leader distribution

## Goal

- [ ] Tests can be started and managed similar to QA and E2E tests
- [ ] Alerts when test does not reach expected throughput
- [ ] Alerts when test does not reach expected p99 process instance execution duration

## Breakdown
- [ ] Define performance test workload
  - [ ] Cluster plan/sizing
  - [ ] Process model(s)
  - [ ] Worker and Starter applications
- [ ] Performance test workload can run on a Zeebe Cluster
  - [ ] Performance test sets up a cluster
  - [ ] Performance test deploys defined workload
  - [ ] Performance test can be triggered via GHA 
- [ ] Measure performance goals
  - [ ] Performance test measures throughput in terms of completed process instances per second
  - [ ] Performance test measures p99 process instance execution duration
  - [ ] Performance test makes measurements available
- [ ] Regression alerts
  - [ ] Establish current performance goals
  - [ ] Notify if performance test does not reach expected goals

**Comment by npepinpe** [comment]
Don't we sort of have this via the medic benchmarks? We don't alert or have specific goals, but we do monitor the performance and have some form of red/green/yellow alerting.

**Comment by lenaschoenburg** [comment]
Sure, let's close this then.
