### ISSUE TITLE
Improve logging of benchmark client applications

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#11987]
**Description**

Right now the logging of our starter, worker, etc. are not that useful.

In the starter there is almost nothing logged and in the worker we see endless logs of error/warns because activation might fail or job already have been completed etc.

Ideally, I would like to see always the topology it connects to, the current connected gateway it will speak to and maybe some other useful loggings

Follow up from https://github.com/camunda/zeebe/issues/11975

**Comment by npepinpe** [comment]
We are already printing this, however by default the log level is too low :smile: Closing for now, but nothing stops anyone from improving the benchmarks apps ad-hoc :)
