### ISSUE TITLE
Whether the exported record contains current record scope variables. This is necessary for the analysis and processing of data.

### ISSUE THREAD

**Issue by zxuanhong** [camunda/camunda#11990]
**Is your feature request related to a problem? Please describe.**
1. variables are often used to extend record information, such as business key;
2. The current record does not contain variables within the scope of the current record, which makes integration analysis of variables and records particularly cumbersome.For example, I need to integrate his business key in my job;
![one](https://user-images.githubusercontent.com/62740686/224273907-0ccadc2c-e963-4551-90b2-e7225cdeebb1.jpg)
3. If the exported record contains variables for the current record scope.The integration of data will become very easy.For example, in 2, the situation would look like this(I don't need to get the loop query to see if the stored variable contains the business key);
![two](https://user-images.githubusercontent.com/62740686/224273952-7a81eb9b-bf91-4c77-9f97-b314f7963720.jpg)
4. I have found that some records are supported (e.g. JobRecordValue contains variables) and now I feel that it should be extended to more records.
<img width="592" alt="image" src="https://user-images.githubusercontent.com/62740686/224276251-ae8778f0-8473-4165-b68c-895922ef3391.png">

**Comment by zxiaozhou** [comment]
@korthout If you can configure the best. This allows the user to evaluate whether to open it.

**Comment by zxuanhong** [comment]
@aleksander-dytko @korthout 
If there is a performance issue, I think this is a user decision. For example, http calls are time-consuming, he uses them himself and he writes the scripts or functions himself. Performance should be your own responsibility. But I think the lack of extensibility is particularly bad

**Comment by zxuanhong** [comment]
Because zeebe is not used at the moment, I will not focus on zeebe. So I closed the issue
