### ISSUE TITLE
Move Go client to a dedicated repo

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#12524]
**Description**

We propose moving the Go client to a dedicated repository to support efforts to improve our ability to support it.

**Comment by remcowesterhoud** [comment]
ZPA Triage:
- Let's make sure we save the Git history
- Unsure how much work fixing the CI will be
- Can be a public repository
- Let's work on this after May's releases

**Comment by Zelldon** [comment]
fyi there is a guide on github docs https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by megglos** [comment]
done with https://github.com/camunda/camunda/issues/21817
