### ISSUE TITLE
Leader cannot create channel to a restarted broker

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#12811]
**Describe the bug**

In the past weeks we observed several clusters in integration stage where restarted broker do not receive any heartbeats from the leader. On the leader it logs the following:

```
RaftServer{raft-partition-partition-2} - AppendRequest{term=2, leader=2, prevLogIndex=66318, prevLogTerm=2, entries=1, commitIndex=66318} to 1 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Failed to connect channel for address zeebe-1.zeebe-broker-service.*****-zeebe.svc.cluster.local:26502
```
This repeats until the leader is restarted.

Hypothesis:
It is not clear why it fails to connect channel. This PR https://github.com/camunda/zeebe/pull/12760 adds more context to the error message. But it will be available only in next releases. But a possible reason is DNS caching issues.

Impact:
When this happens, restarted broker cannot become ready. It cannot receive events for the affected partition.

**To Reproduce**

It is not deterministically reproducible.

**Work around**
Restart leader

**Heap dump**

Heap dump of zeebe-2 which was the leader for parition 3 https://drive.google.com/drive/folders/1oqM17Zc2sQZUFpn_bVXB596jx0_MpwH8 
```
"RaftServer{raft-partition-partition-3} - AppendRequest{term=22, leader=2, prevLogIndex=4978589, prevLogTerm=21, entries=0, commitIndex=4982528} to 0 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Failed to connect channel for address zeebe-0.zeebe-broker-service.****-zeebe.svc.cluster.local:26502"
```

**Environment:**
- Zeebe Version: 8.2.* / 8.3.0-alpha1

**Comment by megglos** [comment]
ZDP-Triage:
- woraround is restart of the leader
- would wait on the outcome of SREs investigation

**Comment by npepinpe** [comment]
Do we know if this is still an issue with the new DNS resolver that we use? Have we observed this again since last year?

**Comment by rodrigo-lourenco-lopes** [comment]
This seems to have happened again in one of our DEV clusters:
https://alertmanager-worker-2.internal.dev.ultrawombat.com/#/alerts?receiver=prometheus-operator%2Falertmanager-config%2Fslack-team

Broker 0 was not able to connect to the other 2 brokers. It led to one of the partitions being dead.

https://drive.google.com/file/d/1hmsjx81NQKEoY8XwuLULpPDcAfb4vt4w/view?usp=drive_link
https://drive.google.com/file/d/16kWvcliRaEzjIYBSkX6KXC0kUKbXaRho/view?usp=drive_link
zeebe-version:8.4.3

**Comment by npepinpe** [comment]
We've made further improvements to the DNS resolution (e.g. fallback to TCP in case of errors), I will close this for now, and :crossed_fingers:
