### ISSUE TITLE
too many raft-partition-partition-xx-xx.log files

### ISSUE THREAD

**Issue by codingman1990** [camunda/camunda#13017]
**70 raft-partition-partition-xx-xx.log files with each one has 128MB size data in only one partition**

![image](https://github.com/camunda/zeebe/assets/12196018/a429a922-b272-49ce-a57a-73e11b24dbfa)

The camunda version is 8.1,with data configuration `partitionsCount=3,replicationFactor=3,clusterSize=3`.And now we have about 200 running process instance.The full configuration shown below:

`
{
    "network": {
        "host": "0.0.0.0",
        "portOffset": 0,
        "maxMessageSize": "4MB",
        "advertisedHost": "***",
        "commandApi": {
            "host": "0.0.0.0",
            "port": 26501,
            "advertisedHost": "***",
            "advertisedPort": 26501,
            "address": "0.0.0.0:26501",
            "advertisedAddress": "***"
        },
        "internalApi": {
            "host": "0.0.0.0",
            "port": 26502,
            "advertisedHost": "***",
            "advertisedPort": 26502,
            "address": "0.0.0.0:26502",
            "advertisedAddress": "***"
        },
        "security": {
            "enabled": false,
            "certificateChainPath": null,
            "privateKeyPath": null
        },
        "maxMessageSizeInBytes": 4194304
    },
    "cluster": {
        "initialContactPoints": [
            "***",
            "***",
            "***"
        ],
        "partitionIds": [
            1,
            2,
            3
        ],
        "nodeId": 1,
        "partitionsCount": 3,
        "replicationFactor": 3,
        "clusterSize": 3,
        "clusterName": "camunda-zeebe",
        "heartbeatInterval": "PT0.25S",
        "electionTimeout": "PT2.5S",
        "membership": {
            "broadcastUpdates": false,
            "broadcastDisputes": true,
            "notifySuspect": false,
            "gossipInterval": "PT0.25S",
            "gossipFanout": 2,
            "probeInterval": "PT1S",
            "probeTimeout": "PT0.1S",
            "suspectProbes": 3,
            "failureTimeout": "PT10S",
            "syncInterval": "PT10S"
        },
        "raft": {
            "enablePriorityElection": true
        },
        "messageCompression": "NONE"
    },
    "threads": {
        "cpuThreadCount": 3,
        "ioThreadCount": 3
    },
    "data": {
        "directory": "/usr/local/zeebe/data",
        "logSegmentSize": "128MB",
        "snapshotPeriod": "PT5M",
        "logIndexDensity": 100,
        "diskUsageMonitoringEnabled": true,
        "diskUsageReplicationWatermark": 0.87,
        "diskUsageCommandWatermark": 0.85,
        "diskUsageMonitoringInterval": "PT1S",
        "backup": {
            "store": "S3",
            "s3": {
                "bucketName": "zeebe-proc",
                "endpoint": "***",
                "region": "cn-hangzhou",
                "accessKey": "***",
                "secretKey": "***",
                "apiCallTimeout": "PT3M"
            }
        },
        "logSegmentSizeInBytes": 134217728,
        "freeDiskSpaceCommandWatermark": 5052946022,
        "freeDiskSpaceReplicationWatermark": 4379219886
    },
    "exporters": {
        "elasticsearch": {
            "jarPath": null,
            "className": "io.camunda.zeebe.exporter.ElasticsearchExporter",
            "args": {
                "index": {
                    "prefix": "zeebe-record"
                },
                "authentication": {
                    "password": "***",
                    "username": "***"
                },
                "url": "***"
            },
            "external": false
        }
    },
    "gateway": {
        "network": {
            "host": "0.0.0.0",
            "port": 26500,
            "minKeepAliveInterval": "PT30S"
        },
        "cluster": {
            "initialContactPoints": [
                "0.0.0.0:26502"
            ],
            "requestTimeout": "PT15S",
            "clusterName": "zeebe-cluster",
            "memberId": "gateway",
            "host": "0.0.0.0",
            "advertisedHost": "0.0.0.0",
            "port": 26502,
            "advertisedPort": 26502,
            "membership": {
                "broadcastUpdates": false,
                "broadcastDisputes": true,
                "notifySuspect": false,
                "gossipInterval": "PT0.25S",
                "gossipFanout": 2,
                "probeInterval": "PT1S",
                "probeTimeout": "PT0.1S",
                "suspectProbes": 3,
                "failureTimeout": "PT10S",
                "syncInterval": "PT10S"
            },
            "security": {
                "enabled": false,
                "certificateChainPath": null,
                "privateKeyPath": null
            },
            "messageCompression": "NONE"
        },
        "threads": {
            "managementThreads": 1
        },
        "security": {
            "enabled": false,
            "certificateChainPath": null,
            "privateKeyPath": null
        },
        "longPolling": {
            "enabled": true
        },
        "interceptors": [],
        "initialized": true,
        "enable": false
    },
    "backpressure": {
        "enabled": true,
        "algorithm": "VEGAS",
        "aimd": {
            "requestTimeout": "PT1S",
            "initialLimit": 100,
            "minLimit": 1,
            "maxLimit": 1000,
            "backoffRatio": 0.9
        },
        "fixed": {
            "limit": 20
        },
        "vegas": {
            "alpha": 3,
            "beta": 6,
            "initialLimit": 20
        },
        "gradient": {
            "minLimit": 10,
            "initialLimit": 20,
            "rttTolerance": 2.0
        },
        "gradient2": {
            "minLimit": 10,
            "initialLimit": 20,
            "rttTolerance": 2.0,
            "longWindow": 600
        }
    },
    "experimental": {
        "maxAppendsPerFollower": 2,
        "maxAppendBatchSize": "32KB",
        "disableExplicitRaftFlush": false,
        "rocksdb": {
            "columnFamilyOptions": {},
            "enableStatistics": false,
            "memoryLimit": "512MB",
            "maxOpenFiles": -1,
            "maxWriteBufferNumber": 6,
            "minWriteBufferNumberToMerge": 3,
            "ioRateBytesPerSecond": 0,
            "disableWal": false
        },
        "raft": {
            "requestTimeout": "PT5S",
            "maxQuorumResponseTimeout": "PT0S",
            "minStepDownFailureCount": 3,
            "preferSnapshotReplicationThreshold": 100,
            "preallocateSegmentFiles": true
        },
        "partitioning": {
            "scheme": "ROUND_ROBIN",
            "fixed": []
        },
        "queryApi": {
            "enabled": false
        },
        "consistencyChecks": {
            "enablePreconditions": false,
            "enableForeignKeyChecks": false,
            "settings": {
                "enablePreconditions": false,
                "enableForeignKeyChecks": false
            }
        },
        "engine": {
            "messages": {
                "ttlCheckerBatchLimit": 2147483647,
                "ttlCheckerInterval": "PT1M"
            }
        },
        "features": {
            "enableYieldingDueDateChecker": false,
            "enableActorMetrics": false,
            "enableBackup": true,
            "enableMessageTtlCheckerAsync": false
        },
        "maxAppendBatchSizeInBytes": 32768
    },
    "executionMetricsExporterEnabled": false,
    "processing": {
        "maxCommandsInBatch": 1
    }
}
`

The disk usage is still increasing.Is there anyone who can helps me?The situation is very urgent.

**Comment by Zelldon** [comment]
Hey @codingman1990 

can you make sure that your elastic is available and accepting data? If the elasticsearch exporter cant export, data will not be delete from zeebe.

**Comment by codingman1990** [comment]
Yes,the elasticsearch exporter looks like healthy.

- Granfa view(Data is retained for 2 days only)

![image](https://github.com/camunda/zeebe/assets/12196018/005591a8-1ce2-4213-8cb1-cf904ed0d4b3)


- ES kibana view 

![lQLPJxak98GTr17NAjjNBm6wHDczY6U43m4EeTTBpoCjAA_1646_568](https://github.com/camunda/zeebe/assets/12196018/a018d2e4-7b5d-4599-89a5-8837df103a97)

![lQLPJwMs77cga_7NAVjNBdSwguc0biHjJu4EeTWT6IBoAA_1492_344](https://github.com/camunda/zeebe/assets/12196018/53bdbb90-8d59-4875-a04b-d81be815dd63)

And there are so many ES index,i'm confused which one indicating raft-partition-partition-xx-xx.log file exporting and deleting action.

- zeebe-record_variable-document_8.1.9
- zeebe-record_incident_8.1.9
- zeebe-record_job_8.1.9
- zeebe-record_process-message-subscription_8.1.9
- zeebe-record_message-subscription_8.1.9
- zeebe-record_process-instance-modification_8.1.9
- zeebe-record_decision_8.1.9
- zeebe-record_message_8.1.9
- zeebe-record_decision-requirements_8.1.9
- zeebe-record_variable_8.1.9
- zeebe-record_process-instance-creation_8.1.9
- zeebe-record_decision-evaluation_8.1.9
- zeebe-record_process_8.1.9
- zeebe-record_error_8.1.9
- zeebe-record_process-instance_8.1.9
- zeebe-record_deployment_8.1.9

By the way,is it possible that some process instances have not been completed for two months.Does this sisuation affect the raft-partition-partition-xx-xx.log size?

![image](https://github.com/camunda/zeebe/assets/12196018/540336a3-6c6e-4197-af9b-8d84e6b96263)

**Comment by megglos** [comment]
Hey @codingman1990 ,

could you provide the metrics from the `Processing` section of the dashboard, we wonder if there are unexported records on any partition or specially partition 2.

**Comment by codingman1990** [comment]
@megglos hi,Thanks for your reply.I found the earliest log file was created on May 4th,but our earliest activiting process instance was stared on May 11th,  the log file never be removed. All the `Processing` selection data shows below:
![image](https://github.com/camunda/zeebe/assets/12196018/da3ff6fd-15ad-43c9-a7a1-718fcb7568f5)
![image](https://github.com/camunda/zeebe/assets/12196018/b51f663f-12ef-48df-87b2-4caabddf3e83)
![image](https://github.com/camunda/zeebe/assets/12196018/1c7ce9b9-e3ef-44de-ac13-54535d5a2d92)

**Comment by npepinpe** [comment]
As this is quite stale, I will close this for. Please reopen in case we should continue.
