### ISSUE TITLE
JMHEnginePerformanceTest#runJmhBenchmark

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#13311]
**Summary**

- How often does the test fail? 1
- Does it block your work? no
- Do we suspect that it is a real failure? Probably not

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.lang.AssertionError: Expected reference score is '450.00' got '379.58', deviation 15.649% exceeds maximum allowed deviation 15.000%
	at io.camunda.zeebe.engine.perf.JMHEnginePerformanceTest.assertDeviationWithin(JMHEnginePerformanceTest.java:57)
	at io.camunda.zeebe.engine.perf.JMHEnginePerformanceTest.runJmhBenchmark(JMHEnginePerformanceTest.java:38)
</pre>
</details>

**Hypotheses**

No idea. The changes on the PR are related to the Docker image only, so should have 0 impact on this test. See https://github.com/camunda/zeebe/pull/13302

**Logs**

https://github.com/camunda/zeebe/actions/runs/5452224714/jobs/9919439047?pr=13302

<details><summary>Logs</summary>
<pre>
# JMH version: 1.36
# VM version: JDK 17.0.7, OpenJDK 64-Bit Server VM, 17.0.7+7
# VM invoker: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64/bin/java
# VM options: -Xmx4g -Xms4g
# Blackhole mode: compiler (auto-detected, use -Djmh.blackhole.autoDetect=false to disable)
# Warmup: 100 iterations, 1 s each
# Measurement: 50 iterations, 1 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest.measureProcessExecutionTime

# Run progress: 0.00% complete, ETA 00:02:30
# Fork: 1 of 1
# Warmup Iteration   1: OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
08:00:20.769 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Recovering state of partition 1 from snapshot
08:00:20.782 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
08:00:20.948 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@58501706)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@2f299a3f, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@3abedae2, configuration: Configuration(false)]
08:00:21.088 [Broker-0-StreamProcessor-1] INFO  org.camunda.dmn.DmnEngine - DMN-Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@26e6871)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@6b6e0df, audit-loggers: List(), configuration: Configuration(false,false,false)]
08:00:21.089 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.dmn.NoUnpackValueMapper@71907f19)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@6b6e0df, clock: SystemClock, configuration: Configuration(false)]
08:00:21.108 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@6b842a28)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@6a5213ac, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@14367c73, configuration: Configuration(false)]
08:00:21.127 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@7c818f5)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@3d5ee4fc, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@3cbae37b, configuration: Configuration(false)]
08:00:21.130 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@7b67806f)), function-provider: io.camunda.zeebe.feel.impl.FeelFunctionProvider@7b7ffcad, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@44d212e4, configuration: Configuration(false)]
08:00:21.163 [Broker-0-StreamProcessor-1] INFO  org.camunda.dmn.DmnEngine - DMN-Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.feel.impl.MessagePackValueMapper@8f3271b)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@6b6e0df, audit-loggers: List(), configuration: Configuration(false,false,false)]
08:00:21.163 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.dmn.NoUnpackValueMapper@4922b3c8)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@6b6e0df, clock: SystemClock, configuration: Configuration(false)]
08:00:21.215 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.processor - Processor starts replay of events. [snapshot-position: -1, replay-mode: PROCESSING]
08:00:21.218 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.processor - Processor finished replay, with [lastProcessedPosition: -1, lastWrittenPosition: -1]
08:00:21.240 [Broker-0-LogStream-1] DEBUG io.camunda.zeebe.logstreams.impl.flowcontrol.AppenderFlowControl - Configured log appender back pressure as BackpressureCfgVegas{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
08:00:21.255 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Starting processing of migration tasks (use LogLevel.DEBUG for more details) ... 
08:00:21.256 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.engine.state.migration - Found 5 migration tasks: ProcessMessageSubscriptionSentTimeMigration, MessageSubscriptionSentTimeMigration, TemporaryVariableMigration, DecisionMigration, DecisionRequirementsMigration
08:00:21.263 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping ProcessMessageSubscriptionSentTimeMigration migration (1/5).  It was determined it does not need to run right now.
08:00:21.264 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping MessageSubscriptionSentTimeMigration migration (2/5).  It was determined it does not need to run right now.
08:00:21.264 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping TemporaryVariableMigration migration (3/5).  It was determined it does not need to run right now.
08:00:21.264 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping DecisionMigration migration (4/5).  It was determined it does not need to run right now.
08:00:21.265 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Skipping DecisionRequirementsMigration migration (5/5).  It was determined it does not need to run right now.
08:00:21.265 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.engine.state.migration - Completed processing of migration tasks (use LogLevel.DEBUG for more details) ... 
08:00:21.266 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.engine.state.migration - Executed 0 migration tasks: 
08:00:21.727 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - Starting 200000 process instances, please hold the line...
08:00:21.771 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	0 process instances already started.
08:00:31.188 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	10000 process instances already started.
08:00:39.374 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	20000 process instances already started.
08:00:46.937 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	30000 process instances already started.
08:00:54.162 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	40000 process instances already started.
08:01:01.163 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	50000 process instances already started.
08:01:08.370 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	60000 process instances already started.
08:01:15.769 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	70000 process instances already started.
08:01:23.376 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	80000 process instances already started.
08:01:31.348 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	90000 process instances already started.
08:01:38.976 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	100000 process instances already started.
08:01:46.445 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	110000 process instances already started.
08:01:54.076 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	120000 process instances already started.
08:02:01.536 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	130000 process instances already started.
08:02:08.904 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	140000 process instances already started.
08:02:16.360 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	150000 process instances already started.
08:02:24.008 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	160000 process instances already started.
08:02:31.947 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	170000 process instances already started.
08:02:39.614 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	180000 process instances already started.
08:02:47.660 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - 	190000 process instances already started.
08:02:56.054 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - Started 200000 process instances.
1058.936 ops/s
# Warmup Iteration   2: 1189.386 ops/s
# Warmup Iteration   3: 1272.009 ops/s
# Warmup Iteration   4: 1264.381 ops/s
# Warmup Iteration   5: 1267.467 ops/s
# Warmup Iteration   6: 1365.434 ops/s
# Warmup Iteration   7: 1332.625 ops/s
# Warmup Iteration   8: 1333.860 ops/s
# Warmup Iteration   9: 1281.111 ops/s
# Warmup Iteration  10: 1256.480 ops/s
# Warmup Iteration  11: 1269.551 ops/s
# Warmup Iteration  12: 1310.750 ops/s
# Warmup Iteration  13: 1421.150 ops/s
# Warmup Iteration  14: 1388.381 ops/s
# Warmup Iteration  15: 1330.099 ops/s
# Warmup Iteration  16: 1304.311 ops/s
# Warmup Iteration  17: 1300.647 ops/s
# Warmup Iteration  18: 1228.713 ops/s
# Warmup Iteration  19: 1233.619 ops/s
# Warmup Iteration  20: 1210.366 ops/s
# Warmup Iteration  21: 1235.393 ops/s
# Warmup Iteration  22: 1273.577 ops/s
# Warmup Iteration  23: 1290.483 ops/s
# Warmup Iteration  24: 1344.630 ops/s
# Warmup Iteration  25: 1367.551 ops/s
# Warmup Iteration  26: 1344.643 ops/s
# Warmup Iteration  27: 1385.418 ops/s
# Warmup Iteration  28: 1314.651 ops/s
# Warmup Iteration  29: 1364.745 ops/s
# Warmup Iteration  30: 1310.873 ops/s
# Warmup Iteration  31: 1267.624 ops/s
# Warmup Iteration  32: 1357.525 ops/s
# Warmup Iteration  33: 1339.933 ops/s
# Warmup Iteration  34: 1352.940 ops/s
# Warmup Iteration  35: 1394.701 ops/s
# Warmup Iteration  36: 1410.692 ops/s
# Warmup Iteration  37: 1353.691 ops/s
# Warmup Iteration  38: 1329.117 ops/s
# Warmup Iteration  39: 1277.317 ops/s
# Warmup Iteration  40: 1248.684 ops/s
# Warmup Iteration  41: 1229.072 ops/s
# Warmup Iteration  42: 1219.794 ops/s
# Warmup Iteration  43: 1282.458 ops/s
# Warmup Iteration  44: 1386.413 ops/s
# Warmup Iteration  45: 1279.243 ops/s
# Warmup Iteration  46: 1343.434 ops/s
# Warmup Iteration  47: 1292.701 ops/s
# Warmup Iteration  48: 1387.365 ops/s
# Warmup Iteration  49: 1357.713 ops/s
# Warmup Iteration  50: 1380.035 ops/s
# Warmup Iteration  51: 1371.564 ops/s
# Warmup Iteration  52: 1217.010 ops/s
# Warmup Iteration  53: 1170.827 ops/s
# Warmup Iteration  54: 1307.845 ops/s
# Warmup Iteration  55: 1201.828 ops/s
# Warmup Iteration  56: 1336.684 ops/s
# Warmup Iteration  57: 1356.001 ops/s
# Warmup Iteration  58: 1367.331 ops/s
# Warmup Iteration  59: 1295.552 ops/s
# Warmup Iteration  60: 1232.753 ops/s
# Warmup Iteration  61: 1085.579 ops/s
# Warmup Iteration  62: 1127.241 ops/s
# Warmup Iteration  63: 1254.959 ops/s
# Warmup Iteration  64: 1221.523 ops/s
# Warmup Iteration  65: 1207.187 ops/s
# Warmup Iteration  66: 1226.427 ops/s
# Warmup Iteration  67: 1271.803 ops/s
# Warmup Iteration  68: 769.398 ops/s
# Warmup Iteration  69: 409.215 ops/s
# Warmup Iteration  70: 418.291 ops/s
# Warmup Iteration  71: 395.964 ops/s
# Warmup Iteration  72: 402.158 ops/s
# Warmup Iteration  73: 412.726 ops/s
# Warmup Iteration  74: 374.175 ops/s
# Warmup Iteration  75: 379.001 ops/s
# Warmup Iteration  76: 410.514 ops/s
# Warmup Iteration  77: 409.834 ops/s
# Warmup Iteration  78: 393.869 ops/s
# Warmup Iteration  79: 395.481 ops/s
# Warmup Iteration  80: 379.515 ops/s
# Warmup Iteration  81: 394.250 ops/s
# Warmup Iteration  82: 374.836 ops/s
# Warmup Iteration  83: 413.813 ops/s
# Warmup Iteration  84: 413.308 ops/s
# Warmup Iteration  85: 377.494 ops/s
# Warmup Iteration  86: 376.729 ops/s
# Warmup Iteration  87: 373.932 ops/s
# Warmup Iteration  88: 389.893 ops/s
# Warmup Iteration  89: 390.384 ops/s
# Warmup Iteration  90: 369.681 ops/s
# Warmup Iteration  91: 361.884 ops/s
# Warmup Iteration  92: 367.243 ops/s
# Warmup Iteration  93: 379.373 ops/s
# Warmup Iteration  94: 375.453 ops/s
# Warmup Iteration  95: 366.803 ops/s
# Warmup Iteration  96: 365.917 ops/s
# Warmup Iteration  97: 372.444 ops/s
# Warmup Iteration  98: 375.753 ops/s
# Warmup Iteration  99: 372.137 ops/s
# Warmup Iteration 100: 370.536 ops/s
Iteration   1: 394.018 ops/s
Iteration   2: 360.506 ops/s
Iteration   3: 377.913 ops/s
Iteration   4: 381.760 ops/s
Iteration   5: 388.448 ops/s
Iteration   6: 391.286 ops/s
Iteration   7: 395.079 ops/s
Iteration   8: 375.147 ops/s
Iteration   9: 388.867 ops/s
Iteration  10: 381.903 ops/s
Iteration  11: 387.761 ops/s
Iteration  12: 389.057 ops/s
Iteration  13: 364.821 ops/s
Iteration  14: 368.814 ops/s
Iteration  15: 363.408 ops/s
Iteration  16: 375.466 ops/s
Iteration  17: 370.611 ops/s
Iteration  18: 369.751 ops/s
Iteration  19: 391.987 ops/s
Iteration  20: 389.470 ops/s
Iteration  21: 398.381 ops/s
Iteration  22: 379.885 ops/s
Iteration  23: 389.241 ops/s
Iteration  24: 393.604 ops/s
Iteration  25: 376.960 ops/s
Iteration  26: 354.342 ops/s
Iteration  27: 364.587 ops/s
Iteration  28: 354.848 ops/s
Iteration  29: 360.046 ops/s
Iteration  30: 375.486 ops/s
Iteration  31: 406.090 ops/s
Iteration  32: 384.006 ops/s
Iteration  33: 380.803 ops/s
Iteration  34: 370.009 ops/s
Iteration  35: 363.186 ops/s
Iteration  36: 351.688 ops/s
Iteration  37: 358.123 ops/s
Iteration  38: 357.647 ops/s
Iteration  39: 352.141 ops/s
Iteration  40: 363.145 ops/s
Iteration  41: 381.715 ops/s
Iteration  42: 377.968 ops/s
Iteration  43: 390.405 ops/s
Iteration  44: 399.483 ops/s
Iteration  45: 385.358 ops/s
Iteration  46: 409.024 ops/s
Iteration  47: 391.596 ops/s
Iteration  48: 387.832 ops/s
Iteration  49: 405.488 ops/s
Iteration  50: 08:05:26.291 [] INFO  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest - Started 318798 process instances
08:05:26.294 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
08:05:26.294 [] DEBUG io.camunda.zeebe.broker.logstreams - Close stream processor
08:05:26.395 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - Close appender for log stream stream-1
08:05:26.396 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams.impl.log.Sequencer - Closing sequencer for writing
08:05:26.396 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-1 close 2 readers
08:05:26.397 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
08:05:26.398 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
08:05:26.398 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
08:05:26.398 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
409.873 ops/s

Result "io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest.measureProcessExecutionTime":
  379.581 ?(99.9%) 7.720 ops/s [Average]
  (min, avg, max) = (351.688, 379.581, 409.873), stdev = 15.594
  CI (99.9%): [371.861, 387.300] (assumes normal distribution)

# Run complete. Total time: 00:05:07

REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
experiments, perform baseline and negative tests that provide experimental control, make sure
the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
Do not assume the numbers tell you what you want them to tell.

NOTE: Current JVM experimentally supports Compiler Blackholes, and they are in use. Please exercise
extra caution when trusting the results, look into the generated code to check the benchmark still
works, and factor in a small probability of new VM bugs. Additionally, while comparisons between
different JVMs are already problematic, the performance difference caused by different Blackhole
modes can be very significant. Please make sure you use the consistent Blackhole mode for comparisons.

Benchmark                                                     Mode  Cnt    Score   Error  Units
EngineLargeStatePerformanceTest.measureProcessExecutionTime  thrpt   50  379.581 ? 7.720  ops/s
</pre>
</details>

**Comment by megglos** [comment]
ZDP-Triage:
- we would monitor this for now and increase prio if it happens again

**Comment by deepthidevaki** [comment]
Happened again https://github.com/camunda/zeebe/actions/runs/5551838672/jobs/10138427800
```
Error:    JMHEnginePerformanceTest.runJmhBenchmark:38->assertDeviationWithin:57 Expected reference score is '450.00' got '380.34', deviation 15.480% exceeds maximum allowed deviation 15.000%
```

**Comment by remcowesterhoud** [comment]
Another failure https://github.com/camunda/zeebe/actions/runs/5677820365/job/15386811094

```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 290.9 s <<< FAILURE! -- in io.camunda.zeebe.engine.perf.JMHEnginePerformanceTest
Error:  io.camunda.zeebe.engine.perf.JMHEnginePerformanceTest.runJmhBenchmark -- Time elapsed: 290.9 s <<< FAILURE!
java.lang.AssertionError: Expected reference score is '450.00' got '378.37', deviation 15.918% exceeds maximum allowed deviation 15.000%
	at io.camunda.zeebe.engine.perf.JMHEnginePerformanceTest.assertDeviationWithin(JMHEnginePerformanceTest.java:57
	at io.camunda.zeebe.engine.perf.JMHEnginePerformanceTest.runJmhBenchmark(JMHEnginePerformanceTest.java:38)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by oleschoenburg** [comment]
Another failure https://github.com/camunda/zeebe/actions/runs/5758126262/job/15610182978
```
Error:  Failures: 
Error:    JMHEnginePerformanceTest.runJmhBenchmark:38->assertDeviationWithin:57 Expected reference score is '450.00' got '378.20', deviation 15.955% exceeds maximum allowed deviation 15.000%
```

**Comment by Zelldon** [comment]
https://github.com/camunda/zeebe/actions/runs/5864653017/job/15900074930

```
Error:  Failures: 
Error:    JMHEnginePerformanceTest.runJmhBenchmark:38->assertDeviationWithin:57 Expected reference score is '450.00' got '379.97', deviation 15.563% exceeds maximum allowed deviation 15.000%
```

**Comment by npepinpe** [comment]
Strange that it only occurs every once in a while, and it's in its own job too :thinking:

**Comment by Zelldon** [comment]
Yeah that is really weird, but @oleschoenburg and I also have observed that sometimes VM seem to be quite cold and slower on certain occasions, but Idk how to overcome this.

**Comment by npepinpe** [comment]
But isn't that why JMH runs so many warm up iterations? :thinking: The only thing I can imagine is the node being shared, something we'd observed with Zeebe.

**Comment by Zelldon** [comment]
> But isn't that why JMH runs so many warm up iterations? thinking The only thing I can imagine is the node being shared, something we'd observed with Zeebe.

yes true. Yeah I was also often thinking that we are not really alone at the node, but @oleschoenburg mentioned to me that one node one job, but I'm also still not sure whether this is true 🤷🏼 

Can we find this out somehow? Are there any metrics or stats on which node we were running 🤔

**Comment by npepinpe** [comment]
I checked, the CI job takes the whole node (from the labels), so it should be pretty much by itself (minus some K8s/runner stuff) :shrug: 

The only metrics we have for our CI nodes are the Stackdriver ones. When you start a job, check which runner is assigned to it. Then find that pod in the CI cluster, and check which node. You can then use Stackdriver/Google Console to get some metrics for that node.

**Comment by npepinpe** [comment]
New failure: https://github.com/camunda/zeebe/actions/runs/5928411753/job/16073947300?pr=13970

**Comment by npepinpe** [comment]
Closing, this test was replaced/rewritten.
