### ISSUE TITLE
Dedicated thread pool for exporters

### ISSUE THREAD

**Issue by aivinog1** [camunda/camunda#13344]
**Is your feature request related to a problem? Please describe.**
Right now we are facing the following issue: if our exporter executes blocking requests with a high latency (seconds) - other I/O Broker's tasks couldn't be executed on time which could lead to the high latency in Broker's response and cluster rebalancing. I think, that exporters should affect processing as little as possible.

**Describe the solution you'd like**
I want to create a separate pool (besides CPU and I/O bound) for exporters' activity which could use one thread by default.

**Describe alternatives you've considered**
We could use a separate thread pool inside I/O bound pool, but I don't think that it could be a good idea.

**Comment by korthout** [comment]
As this concerns the ExporterPlatform, I'm removing this from the Zeebe Process Automation board. It's a responsibility for Zeebe Distributed Platform. Please correct me if I'm wrong.

**Comment by npepinpe** [comment]
We've changed how we start partitions in parallel, I don't believe this is an issue anymore.
