### ISSUE TITLE
Allow adding custom FEEL functions through Zeebe

### ISSUE THREAD

**Issue by zxuanhong** [camunda/camunda#13466]
**Description**

1. How to extend zeebe's feel function, similar to how the exporter provides a jar
2. I want to handle some things by writing my own functions, because the built-in functions are no longer enough
3. If it cannot be realized now, I hope it can be considered later, which will greatly increase the flexibility of feel.

**Comment by remcowesterhoud** [comment]
@saig0 Do you know of a way to achieve this?

**Comment by zxuanhong** [comment]
@remcowesterhoud @saig0 This function is similar to c7 expression. And it's a very practical need

**Comment by remcowesterhoud** [comment]
Thanks, in this case I'll turn it into a feature request and ping @aleksander-dytko so he's aware 😄

**Comment by zxuanhong** [comment]
@saig0 I hope you can come up with a plan soon. This requirement is very useful for extending engine functionality

**Comment by aleksander-dytko** [comment]
Hi @zxuanhong, thanks for your request! 

To fully understand your request, I have a few questions:

`I want to handle some things by writing my own functions, because the built-in functions are no longer enough` 
- what functions do you have in mind? 
- is a lack of those functions blocking you?
- what version of C8 (SM or SaaS) do you use today?

For now, I assume the priority is `later` as it has lower priority than items that we have in progress already.

**Comment by zxuanhong** [comment]
@aleksander-dytko 
I'm constantly trying to switch from c7 to c8. But there are many expressions for setting user information.These expressions are mainly used to obtain approval user information from external systems.But for now zeebe is stuck with these expressions. Because of the inability to expand, so that all is stopped.

**Comment by aleksander-dytko** [comment]
@zxuanhong thanks for the context. 

> But there are many expressions for setting the approval user information for the user task.

Could you give a specific example of this kind of expression?

> These expressions are mainly used to obtain approval user information from external systems

How would you obtain user information from external systems with FEEL? 

> Then process the non-feel expression yourself in the task list (such as spring el).This is very troublesome

Would separate service task be an option to solve that?

**Comment by zxuanhong** [comment]
@aleksander-dytko 
1. Could you give a specific example of this kind of expression?(The writing may be a little off spec)
<img width="1022" alt="image" src="https://github.com/camunda/zeebe/assets/62740686/a3459929-8c5a-4a05-825e-566ee3cde2f6">
<img width="999" alt="image" src="https://github.com/camunda/zeebe/assets/62740686/b3766f2f-89a8-40e9-a5c0-c35fdf2a8e44">

3. How would you obtain user information from external systems with FEEL?
I want to be able to inject process context variable information. Through this information and fixed variables to call the remote interface to obtain.For example, the current node approver is the head of the department where the process sponsor resides.

4. Would separate service task be an option to solve that?
Although possible, adding a service task before each user task is redundant and cumbersome

**Comment by zxuanhong** [comment]
@aleksander-dytko Due to the repetition with this, I will close
#14896
https://github.com/camunda/issues/issues/315

**Comment by zxuanhong** [comment]
Due to the fact that in some cases, allowing the feel extension function to execute may be more efficient than the execution listener, I reopened a issue

**Comment by npepinpe** [comment]
Correct me if I'm wrong, but having a custom function implies running third party code, correct? This is a potential security issue in SaaS (and self-managed, but of course in self-managed users can decide for themselves, like with exporters), so I would challenge if we need this in SaaS as well.

**Comment by zxuanhong** [comment]
Because zeebe is not used at the moment, I will not focus on zeebe. So I closed the issue

**Comment by zxuanhong** [comment]
Because zeebe is not used at the moment, I will not focus on zeebe. So I closed the issue
