### ISSUE TITLE
Test `ZeebePartitionTest.shouldUseCurrentTermForInactiveTransition` is flaky

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#13493]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once so far.
- Do we suspect that it is a real failure? Possibly?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Argument(s) are different! Wanted:
partitionTransitionImpl.toInactive(
    3L
);
-> at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.toInactive(PartitionTransitionImpl.java:51)
Actual invocations have different arguments:
partitionTransitionImpl.setConcurrencyControl(
    io.camunda.zeebe.scheduler.ActorControl@520f1862
);
-> at io.camunda.zeebe.broker.system.partitions.ZeebePartition.<init>(ZeebePartition.java:77)
partitionTransitionImpl.updateTransitionContext(
    io.camunda.zeebe.broker.system.partitions.PartitionStartupAndTransitionContextImpl@4ad0465c
);
-> at io.camunda.zeebe.broker.system.partitions.ZeebePartition.lambda$onActorStarting$0(ZeebePartition.java:121)
partitionTransitionImpl.toInactive(
    0L
);
-> at io.camunda.zeebe.broker.system.partitions.ZeebePartition.transitionToInactive(ZeebePartition.java:284)
partitionTransitionImpl.transitionTo(
    0L,
    INACTIVE
);
-> at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.toInactive(PartitionTransitionImpl.java:51)
</pre>
</details>

Occurred in: https://github.com/camunda/zeebe/actions/runs/5553577122/jobs/10142291322

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

[ZeebePartitionTestFlaky.zip](https://github.com/camunda/zeebe/files/12049966/ZeebePartitionTestFlaky.zip)

**Comment by oleschoenburg** [comment]
Not reproducible and the logs are not helpful. I think this was a random fluke, possibly because other tests in this class also failed.

**Comment by nicpuppa** [comment]
This happened again today 🥶 

```
Error:    Run 1: ZeebePartitionTest.shouldUseCurrentTermForInactiveTransition:155 WrongTypeOfReturnValue 
Long cannot be returned by getComponentHealthMonitor()
getComponentHealthMonitor() should return HealthMonitor
```

cc @oleschoenburg

**Comment by nicpuppa** [comment]
Happened again [here](https://github.com/camunda/camunda/actions/runs/9690471129/job/26740361242)

[Test results for unit tests.zip](https://github.com/user-attachments/files/16009229/Test.results.for.unit.tests.zip)

**Comment by mustafadagher** [comment]
happened again [here](https://github.com/camunda/camunda/actions/runs/10183520091)
