### ISSUE TITLE
Remove explicit usage of `zeebe` user for previous version in update tests

### ISSUE THREAD

**Issue by megglos** [camunda/camunda#13528]
**Description**

With https://github.com/camunda/zeebe/pull/13418 the update test setup had to be modified to run the previous zeebe version with the `zeebe` user to prevent the tests from breaking when the default user changed from `root` to `zeebe` in Zeebe 8.3.

The particular cases have been flagged with a TODO:

- https://github.com/camunda/zeebe/pull/13418/files#diff-97463be4427da05eadcad99727ea8eff291e7293f78974c2400f66bbda7348c9R83
- https://github.com/camunda/zeebe/pull/13418/files#diff-5b4b2f8e3a8b2ce01ad4d73926abc94d05adcd88e221e71fd5189f282e874e7aR347

After the 8.3 release, they can be removed from `main`.

**Comment by npepinpe** [comment]
Seems like this was done :+1:
