### ISSUE TITLE
Reduce size of distribution

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#13704]
**Description**

While I was working on the different Docker images, one thing notable is that the Zeebe layer/distribution is 174MB. Looking into it, it's almost entirely 3rd party dependencies. I've listed out the ones whose size are greater than 1MB:

- rocksdbjni 59MB
- grpc-xds 12MB
- grpc-netty-shaded 9.9MB
- scala-library 6MB
- zstdjni 5.5MB
- netty-tcnative-boringssl (1.1MB + 1.2MB + 1MB + 1.1MB + 1.0MB) 5.5MB
- conscrypt 4.5MB
- s3-2.20 3.3MB
- guava-jre 3.0MB
- proto-google-common-protos 2.0MB
- reactor-core 1.8MB
- log4j-core-2 1.8MB
- spring-boot-autoconfigure 1.8MB
- spring-core 1.8MB
- spring-web 1.8MB
- protobuf-java 1.7MB
- jackson-databind 1.6MB
- spring-boot 1.5MB
- kotlin-stdlib 1.5MB
- commons-compact 1.1MB

By specifying an architecture during build, you could easily cut down the size for RocksDB and netty-tcnative, both of which pull in multiple pre-compiled binaries for each architecture:

- rocksdbjni 59MB down to 19MB
- netty-tcnative 5.5MB down to 1.2MB

Then, since already include Netty everywhere, we don't need the `grpc-netty-shaded` dependency. We can simply use `grpc-netty` and our existing Netty dependency. That's another 9.9MB knocked off.

It also seems possible we could exclude `conscrypt` if we're using `netty-tcnative`, so that would be another 4.5MB. But that would need to be verified.

So opportunities to reduce from 174MB down to at least 115 MB. Possibly 103MB if we can also drop the requirement on `grpc-xds` (xDS being a service mesh protocol, a feature we're not really using for the gateway).

No real urgency here, I think. The benefit is a smaller image - meaning faster to push and pull - and for the dependencies we drop, a slightly smaller CVE surface.

**Comment by npepinpe** [comment]
We can possibly not get rid of grpc-xds, conscrypt, or grpc-netty-shaded due to `com.google.cloud:google-cloud-storage` used for backups. Although, that one pulls in so much stuff (also for REST APIs), who knows what we actually need from it :smile:

**Comment by npepinpe** [comment]
Hm, I think you have to specify to use gRPC if you wish with the cloud storage client, and we aren't. Possibly we could then exclude all gRPC related libraries from it?

**Comment by oleschoenburg** [comment]
@npepinpe Possibly, yeah. Although I wouldn't be surprised if the client actually uses gRPC internally anyway, for example to do auto-discovery of configuration.

**Comment by megglos** [comment]
ZDP-Triage:
- smaller images => faster pull and push locally and on nodes
- we could time-box this to at least handle some low-hangin fruits
- smaller chance for CVEs
- putting as later

**Comment by npepinpe** [comment]
Closing - streamlining will completely derail this :upside_down_face:
