### ISSUE TITLE
Backpressure on LogStorageAppender doesn't work as expected with BatchProcessing

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#14316]
**Describe the bug**

We had recently the case reported that the Broker went out of memory, see #14275. This was only possible because more and more records have been written to the log, and have been tried to append/replicate, but commit was not possible. 

The reason for this is that our backpressure algorithm doesn't work as expected on our LogStorageAppender. The limits are too high, because before we haven't adjusted them after implementing batch processing.

Before batch processing, we never batched so much data into one entry, here a higher limit made sense. But now we can have already several hundred records in one sequenced batch (at least observed in the heap dump of #14275). Furthermore, it was differently serialized with the dispatcher and bytebuffers, etc. 

**To Reproduce**

Produce highload, internally and externally and try to disrupt the committing process.

**Expected behavior**

It makes sense to iterate over the current limits and configurations and adjust them such that we are not keeping too much entries inflight, especially if we can't commit. We rather should then not consume the sequencer, which should put natural backpressure to the system, since we can't write. 

**Environment:**
- OS: 
- Zeebe Version: 8.2.x, 8.3.x 
- Configuration: 

```[tasklist]
### Tasks
```

**Comment by megglos** [comment]
ZDP-Triage:
- this was the rootcause for the OOM, which now got mitigated by reducing the amount of data held in memory in such situations
- should only occur if there is already a problem with committing (fast enough), impact => broker might crash
- memory overhead should not depend on the actual record now as it's "only" metadata => we could assess a general new limit

**Comment by megglos** [comment]
ZDP-Planning:
- it blocks https://github.com/camunda/zeebe/issues/14003
- @Zelldon would like to resolve it in this iteration

**Comment by megglos** [comment]
@Zelldon and me synced to move this to the backlog for now. Right now there is no occurrence of this issue since https://github.com/camunda/zeebe/issues/14275 got resolved. There is also no straightforward way to determine a new appropriate value for the backpressure algorithm here, quote @Zelldon  "we would replace a magic number with another magic number"

**Comment by npepinpe** [comment]
Closing as we now have unified flow control.
