### ISSUE TITLE
Set MDC property actor-scheduler/actor-name for non actor threads

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#14648]
**Description**

As a way to unify logging about partition ID/node ID, we should set the MDC properties on `actor-scheduler` and `actor-name` where it makes sense.

- [x] Set `actor-scheduler` to `Broker-<nodeId>` on the Raft threads
- [x] Set `actor-name` to `raft-<threadType>-<partitionId>` on the Raft threads
- [ ] Set `actor-scheduler` to `Broker-<nodeId>` or `Gateway-<nodeId>` on the gossip threads
- [ ] Set `actor-scheduler` to `Broker-<nodeId>` or `Gateway-<nodeId>` on the messaging threads

The left overs are the gRPC threads from the gateway, which we don't have a whole lot of control on. It's likely possible to set some properties on these anyway, but I didn't dig too much into it.

**Comment by megglos** [comment]
ZDP-Triage:
- any thread that we create should be easy to do
- in production deployments the value of the nodeId is not that big as we have that given already by the node itself -> it will be helpful when running locally though
- `The left overs are the gRPC threads from the gateway,` => we could do that by submitting tasks that set the MDC

we could do that once needed as well, no urgency right now
