### ISSUE TITLE
Create new flow control module

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#14688]
**Description**

I was working on https://github.com/camunda/zeebe/issues/14316 (log appender backpressure) and realized that we still have all configurations as ENV variables and not exposed as actual configs on the Broker.

Furthermore, the configuration differs from our other backpressure config. Additionally, the partition request backpressure has more algorithms and configs available.

I think it is worth extracting/introducing a limiter API (to not depend on the Netflix API too much), and use this in Broker, log stream, and for job push in gateway (upcoming).

We can still keep the configuration and how the actual limiters are created in broker or dist and then inject the created limiters via DI to the other modules like logstream, gateway etc. This also allows us to reuse the similar backpressure config for the other parts.

Related to https://github.com/camunda/zeebe/issues/14316
Related to https://github.com/camunda/zeebe/issues/11231

**Comment by megglos** [comment]
ZDP-Triage:

> realized that we still have all configurations as ENV variables and not exposed as actual configs on the Broker.
- this is technical debt from the past

- improvement we could pick up in the context of job push flow control or do right now as a base for #14316

**Comment by megglos** [comment]
We decided to move this to the backlog as there is no urgency right now.

**Comment by npepinpe** [comment]
@lenaschoenburg - will this be closed with your current epic? Sort of? As we're moving it all under the log stream module, correct?

**Comment by lenaschoenburg** [comment]
Yes, I'll close this issue once https://github.com/camunda/camunda/issues/17547 is done.

**Comment by lenaschoenburg** [comment]
Actually, the configuration aspect is already resolved in main. The append limit we have right now is much easier to configure and has more options than before.
