### ISSUE TITLE
Handle custom FEEL expressions through execution listeners

### ISSUE THREAD

**Issue by zxuanhong** [camunda/camunda#14896]
**Is your feature request related to a problem? Please describe.**
1. User task Settings Approver information often needs to be dynamically set based on context.For example: the sponsor's department tie approval, the sponsor's department manager approval and so on.
2. These Settings often make it impossible to add the corresponding variables when the process is initiated (if you want to add the calculation in advance to parse the entire model when the process is initiated, in order to advance the data of these expressions).This is going to make things very difficult.
3. Of course, you can do this by adding service task processing in front of user tasks. But it makes the model very complicated.
4. Therefore, I think it is possible to design a listener like c7, and the listener is handled by an external system. This makes it easy to extend the feel function. This solves the extension of both custom management and sass management feel expressions

5. It's exactly like this https://github.com/camunda/issues/issues/315

**Comment by tmetzke** [comment]
Hey @zxuanhong, thanks for creating this. 

Could you please clarify how your request here differs from the referenced execution listeners issue?

Thanks and cheers,
Tobias

**Comment by tmetzke** [comment]
Hey @zxuanhong, thanks for creating this issue.

Could you please clarify if implementing https://github.com/camunda/issues/issues/315 already fulfills your requirements?
If not, please detail what you would like on top of that feature.

**Comment by zxuanhong** [comment]
@tmetzke This proposal is very perfect. It can meet business needs. 
Of course, it is also necessary to extend functions, as some calculations are only small and there is no need to use a listener method. Using functions for processing may be more efficient (extending the built-in function of feedback). Therefore, I believe that the implementation of a listener method may not necessarily be for external task processing, such as passing in calculation functions (which needs to be supported under Sass)

**Comment by zxuanhong** [comment]
@tmetzke If the listener is finally implemented and the efficiency is very high, then extending the feel function doesn't make much sense to me

**Comment by koevskinikola** [comment]
ZPA triage:
- @aleksander-dytko this seems like an additional feature that we can fold into the user task listeners epic. Can you evaluate it?
- Priority is `not prioritized` until PMs have a chance to review the feature request.

**Comment by tmetzke** [comment]
> ZPA triage:
> 
> * @aleksander-dytko this seems like an additional feature that we can fold into the user task listeners epic. Can you evaluate it?
> * Priority is `not prioritized` until PMs have a chance to review the feature request.

@koevskinikola, I think this fits better into the execution listener topic than the task listener topic.

@zxuanhong, thanks for the details here. When execution listeners are available, please re-evaluate the topic and let us know if this solves your use case. 
Providing custom FEEL functions is a topic on its own, I would argue. If you want to pursue that topic, I think it would be best to reopen https://github.com/camunda/zeebe/issues/13466 and have that prioritized properly.

**Comment by zxuanhong** [comment]
@tmetzke You make a lot of sense. This extension feel should be another subject, so I reopened #13466

**Comment by zxuanhong** [comment]
Because zeebe is not used at the moment, I will not focus on zeebe. So I closed the issue
