### ISSUE TITLE
8.2.x release benchmark is below minimum throughput threshold

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#15244]
**Describe the bug**

All partitions of the `8.2.x` release benchmark are marked as `UNHEALTHY`.
* [Grafana dashboard (internal)](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&refresh=1m&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=release-8-2-x&var-pod=All&var-partition=All&from=now-24h&to=now)

Looks like the Gateway is down and processing has stopped ([internal GCP logs](https://console.cloud.google.com/logs/query;query=resource.labels.namespace_name%3D%22release-8-2-x%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aseverity%3DWARNING;cursorTimestamp=2023-11-16T06:56:35.487894443Z;startTime=2023-11-14T15:22:20.810Z;endTime=2023-11-16T16:22:20.810Z?project=zeebe-io)).

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Detected 'UNHEALTHY' components. The current health status of components: [Partition-2{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=null, cause=StreamProcessor-2{status=UNHEALTHY, issue=HealthIssue[message=actor appears blocked, throwable=null, cause=null]}]}, Partition-1{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=null, cause=StreamProcessor-1{status=UNHEALTHY, issue=HealthIssue[message=actor appears blocked, throwable=null, cause=null]}]}, Partition-3{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=null, cause=StreamProcessor-3{status=UNHEALTHY, issue=HealthIssue[message=actor appears blocked, throwable=null, cause=null]}]}]
```

</p>
</details>

**Environment:**
- OS:  zeebe-io
- Zeebe Version:  `8.2.17`
- Configuration:

**Comment by megglos** [comment]
ZDP-Triage:
- right now it's back to the normal throughput and healthy, it latest ~1day,
- @koevskinikola did you do anything to recover the cluster?

**Comment by Zelldon** [comment]
I had no time for it sorry and I guess also forgot as well

**Comment by npepinpe** [comment]
As 8.2 is going out of support, I will close this.
