### ISSUE TITLE
Safely handle flush exceptions in Raft

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#15463]
> @deepthidevaki @oleschoenburg - could we implement minimal fault tolerance to flush error with the following:
> 
> 1. Follower/passive role truncates the log and retries the full append on flush error
> 2. Leader truncates the log to commit index and steps down on flush error
> 
> In both cases, truncating should invalidate the buffers/page cache. Since we only update the commit index on successful flush, then truncating to the last known commit index should be safe. 
> 
> This can cause a lot of disruption, but it will at least avoid inconsistencies. WDYT?
> 
> I would be happy to implement at least safety (even if performance/availability is terrible) first, and leave performance to the NFS feature request in the future.

_Originally posted by @npepinpe in https://github.com/camunda/zeebe/issues/14843#issuecomment-1783143543_

**Comment by npepinpe** [comment]
I've put both high and low likelihood, since:

1. This has a low likelihood to occur with standard block devices
2. This has a high likelihood to occur with network file systems (e.g. NFS, SMB, etc.)

**Comment by megglos** [comment]
ZDP-Planning:
* relates to NFS support, will be handled once we have decision on that
