### ISSUE TITLE
Allow instance modification reactivating a multi instance activity

### ISSUE THREAD

**Issue by zxuanhong** [camunda/camunda#15656]
**Is your feature request related to a problem? Please describe.**
1. In c7, the number of instances can be dynamically increased on multi-instance nodes, which is currently prohibited by zeebe. Whether to consider implementation in the later stage
2. Existing services in multi-instance user task nodes need to dynamically add participating users. In other words, increase the number of instances

**Comment by tmetzke** [comment]
Hi @zxuanhong, 

thanks for creating this.

Could you provide a specific example (e.g. a BPMN) that is supported in C7 and should be supported in C8 respectively?

Thank you!

**Comment by tmetzke** [comment]
Thanks, @zxuanhong, for those details. I'll check this in C7 again and have a look at the options in the C8 modification API. I'll get back with feedback as soon as I can 👍

**Comment by tmetzke** [comment]
Personal triage:
- Moved this into the backlog with no prioritization. I'll investigate what's currently possible in C7 and what can be done with C8 modification.

**Comment by zxuanhong** [comment]
Because zeebe is not used at the moment, I will not focus on zeebe. So I closed the issue
