### ISSUE TITLE
Improve `Interceptor` management by the `InterceptorRepository` class

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#15695]
**Description**

Zeebe supports adding [Gateway Interceptors](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/zeebe-gateway/interceptors/#loading-an-interceptor-into-a-gateway).

The order of execution of these Interceptors is defined by the order they are added in the Zeebe configuration. Unfortunately, this wasn't the case due to using a `HashMap` (which doesn't guarantee ordering) [in the `InterceptorRepository`](https://github.com/camunda/zeebe/blob/main/gateway/src/main/java/io/camunda/zeebe/gateway/interceptors/impl/InterceptorRepository.java#L31), the class that is responsible for the instantiation of the Interceptors.

A quick fix was provided with https://github.com/camunda/zeebe/issues/15677 (to avoid more complex changes before an upcoming Zeebe release) by switching to a `SortedMap`. A better approach would be to use an `ArrayList` or a `Queue` to guarantee the same ordering from the configuration.

**Comment by korthout** [comment]
@koevskinikola Do I understand correctly that this may affect users: they cannot reliably define an ordering for the interceptors?

If so, this is a bug rather than tech-debt. It would be a bug rather than a feature because some order is expected, and changing the ordering later would not be backward compatible (it changes the behavior on upgrade for the same config).

**Comment by koevskinikola** [comment]
Hey @korthout, the bug is already fixed, I reported it with https://github.com/camunda/zeebe/issues/15677. 

However, the fix was done in the scope of implementing a tenant-providing interceptor, and I was hesitant to optimize the code so close to the `8.4.0` release. So I created this issue as a tech debt to improve the code.

> It would be a bug rather than a feature because some order is expected, and changing the ordering later would not be backward compatible (it changes the behavior on upgrade for the same config).

That's what I described in https://github.com/camunda/zeebe/issues/15677. Our [docs state](https://docs.camunda.io/docs/self-managed/zeebe-deployment/zeebe-gateway/interceptors/#loading-an-interceptor-into-a-gateway) that the config ordering is respected, but the ordering (from what I saw) is actually arbitrary. So if ordering was important to our users, it wouldn't have worked until the #15677 fix.

**Comment by korthout** [comment]
Ah I see. Thanks for elaborating.

>A better approach would be to use an ArrayList or a Queue to guarantee the same ordering from the configuration.

So what is the tech debt here then? Why is ArrayList/Queue better than SortedMap? What do we gain from changing the implementation?

**Comment by koevskinikola** [comment]
@korthout elements in an `ArrayList` or a `Queue` are sorted by default. 

For a `SortedMap` we need to explicitly handle the sorting logic to ensure that the Map contains properly sorted entries. It makes the code more complex and more difficult to understand.

Do you think it doesn't qualify as a tech debt?

**Comment by korthout** [comment]
Thanks @koevskinikola I get it now 🙇 Makes sense to me 👍
