### ISSUE TITLE
Send rejection if partition's stream processor is not active

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#16180]
When a stream processor has crashed and is not processing anymore, the command API still accepts requests and writes them to the log stream. Since nothing is handling the request, clients will simply see a timeout.

Instead, the command api could reject the request if it already knows that the stream processor won't be able to process it.

This came up in https://app.incident.io/camunda/incidents/876 because the timeouts were misleading.

**Comment by Zelldon** [comment]
Discussed this issue [via internal slack](https://camunda.slack.com/archives/C037RS2JHB8/p1710768723298089), right now the solution doesn't look as easy as we thought.

> Message from slack: 
> Hey team I was today looking at https://github.com/camunda/zeebe/issues/16180 and checking how we could fix or approach this.
> 
> Right now I see as a challenge that the CommandAPI is unaware that the StreamProcessor has failed. I tested with simply failing in the ReplayStateMachine (when deploying a process model I get a deadline exceeding)
How could we approach this?
> * We could somehow make it better visible to the API that the processing is not available/healthy (maybe via a listener?)
This would allows us to better distinguish between different "error" cases
> * Close other dependencies like the writer, so we could better detect that we are not able to process?
Here it is harder to distinguish between not the right leader and a leader which failed during installation.
> * Step down when a dependency fails, this sounds like a clean solution (which we also discussed multiple times) but I'm unsure here as we will likely end up in a loop of becoming a leader again (this might make it even harder to detect the problem)
>   * We could add metrics/alerts about the rate of leader changes/step downs to better detect this.
>   * We could have a threshold (like tried 10 or 100 times to become leader but failed) after we become inactive :thinking_face:

Inputs from @oleschoenburg 

> My ideal solution:
>- Make the CommandApi a partition-scoped service.
>-  If the stream processor fails, it takes down the whole partition
> - As a result: stream processor fails => command api is shut down
> - Gateway responds with correct error code when it can't find a matching command API that is running (probably already the case)

We discussed whether partition stepping down or just closing other dependencies would be a preferred approach. Steping down has its own negative effects, as we might end up in a election loop, as we getting leader afterwards again (likely).

@deepthidevaki also proposed the same either step down or closing dependencies. She also highlighted that this might be already possible.


> Fun fact: We are actually kind of almost doing that
> 
> - When the partition health = DEAD, we stop the partition including raft server. https://github.com/camunda/zeebe/blob/9c348143ae752e879929432b647116e63ff74a1c/zeebe/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java#L329
> - What is missing is StreamProcessor is set to UNHEALTHY, not DEAD when it "fails". May be we can revisit this and mark it as dead in this case. When we introduce "DEAD" state it was intended for cases where even restarts won't help such as corruption errors. But there is no harm in revisiting the semantics.
> 


I think it would be worth to explore this further. I just want to highlight that I might not be available or can't make as much progress as I want on this topic or in general on issues related to Zeebe (as I'm working mostly on the streamlining project, and try to do these issues part-time). If we need this early/quick we might want to think about whether someone else can take this over, if we are ok that it takes maybe a bit I can continue here. \cc @megglos

**Comment by Zelldon** [comment]
@npepinpe I will not work on this in the next future, I think the approaches above sound interesting and are worth checking.

**Comment by EuroLew** [comment]
The issue was resolved by verifying the prerequisite leader and partition health for a request and rejecting early in the client if not satisfied.

Given a cluster with 3 brokers, 1 partition and a replication factor of 3, an exception thrown in the `ProcessingStateMachine` will bring down the stream processor and thus set the partition to `INACTIVE`. An election occurs the message retried and it also then brings the second replica down. Now for a state with inactive partition replicas and no leader it will return the correct error message.

### BEFORE:
<img width="905" alt="image" src="https://github.com/camunda/camunda/assets/168723167/c83f808a-1fa3-4dc9-a082-10e32d717713">

### AFTER:

<img width="1102" alt="image" src="https://github.com/camunda/camunda/assets/168723167/543abe16-0a14-4d1b-be2a-ef4518bdbe35">
