### ISSUE TITLE
Log an easy to understand message when Zeebe broker is starting from scratch because the disk is empty

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#16181]
We've had several cases where users failed to recognize that restoring from backup was not successful. For everyone involved, from user, over support agent to Zeebe engineer, it would have been helpful if Zeebe would log an easy to understand message during startup if the data directory is empty and we are starting from scratch.

Related to https://app.incident.io/camunda/incidents/914

**Comment by npepinpe** [comment]
ZDP: let's do it next week as the assumption is it would cut down a lot on diagnosis time.

**Comment by Zelldon** [comment]
@npepinpe i will not come to it, removing my assignment.

**Comment by rodrigo-lourenco-lopes** [comment]
Closed with https://github.com/camunda/camunda/pull/21589
