### ISSUE TITLE
Proposal: Extend FailJobResponse and ThrowErrorResponse with incidentKey

### ISSUE THREAD

**Issue by ivsokol-ht** [camunda/camunda#16580]
Hi all,

As per documentation on https://docs.camunda.io/docs/apis-tools/zeebe-api/gateway-service/#failjob-rpc , if the retries argument is zero or negative, an incident is raised. Also, when calling ThrowError, incident can also be raised - https://docs.camunda.io/docs/apis-tools/zeebe-api/gateway-service/#throwerror-rpc.

In order to resolve the incident, ResolveIncident RPC must be invoked (https://docs.camunda.io/docs/apis-tools/zeebe-api/gateway-service/#resolveincident-rpc).
My issue is that input in ResolveIncident is incidentKey, which cannot be found in any RPC response. As per forum comment https://forum.camunda.io/t/how-to-resolveincident/36643, incidentKey must be retrieved from exported data. This means that input in RPC API depends on totally different domain (exporters).

Proposal is to extend FailJobResponse and ThrowErrorResponse with 
`int64 incidentKey = 1`
that will be populated if corresponding method creates an incident.

Alternative option is as discussed in forum - rely on exporter storage (elastic or something else) to correlate job and incident.

Thanks in advance,
Ivan Sokol

**Comment by megglos** [comment]
@aleksander-dytko can you please assess this feature request in terms of prio?

**Comment by aleksander-dytko** [comment]
Hi @ivsokol-ht, thanks for raising this feature request. 

The problem makes sense to solve - I want to get the necessary data from Zeebe API to resolve the incident. 

@megglos Let's prioritize `the problem to solve` for 8.6 release to provide a better developer experience. I would propose to find do a quick spike to find the solution for that.

**Comment by megglos** [comment]
@aleksander-dytko can you please follow-up with the team in an upcoming planning how this compares in terms of priority to other topics.

**Comment by korthout** [comment]
@aleksander-dytko Please have a look at the comments in #18681 as well.

**Comment by megglos** [comment]
@korthout please close this as well and create a new proposal issue

**Comment by korthout** [comment]
Closing this in favor of decoupled incident handling, see arguments [here](https://github.com/camunda/camunda/pull/18681#issuecomment-2133214996):
- [incident search API](https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/search-3/) is available in Operate already, and will come in C8 REST API eventually
- incident streaming, I'll open an issue to support this
