### ISSUE TITLE
Adapt the backup process to the new data flow from Zeebe to Elasticsearch

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#16919]
**Description**

* If we let the [Zeebe exporter write directly to the Operate indexes](https://github.com/camunda/product-hub/issues/2128), then users will have the risk of skipping data with our [current backup process](https://docs.camunda.io/docs/8.3/self-managed/operational-guides/backup-restore/backup-and-restore/#backup-process). In particular, it can happen that the Operate indexes reflect a state for a position in a Zeebe partition that is lower than the position at which the exporter was stopped before taking the Zeebe backup. Accordingly, on restore the exporter would restart at a position that is too high and records would effectively be skipped. See the [Product hub epic](https://docs.google.com/presentation/d/1W6bGUbVY1fNYhkSwH_GhEfJQVCF1iiNoSbJ_7ERUOQo/edit#slide=id.g2be6e3750a9_0_0) for a more detailed explanation of the problem.
* To avoid the problem, we must stop exporting (or stop acknowledging) 
* Note that we are concurrently working on [hot backups](https://github.com/camunda/zeebe/issues/16149) that would no longer fully stop the exporter but only stop acknowledging exported events.
* Note that I am adding the ticket to the Zeebe component, because that is where the DRIship for backups originally was. Essentially, this is a topic between the components though, so it's not required for a Zeebe engineer to work on it.
* [Product hub epic](https://github.com/camunda/product-hub/issues/2128)

**Proposed solution**

* In the [backup process](https://docs.camunda.io/docs/8.3/self-managed/operational-guides/backup-restore/backup-and-restore/#backup-process), move the step of stopping (disabling acknowledgements of) the exporter to a point before the Operate backup is taken.
* Optional: If needed, we can separate the backup of the Operate runtime indexes (that the exporter writes to) and the other Operate indexes. Stopping the exporter beforehand is only relevant for the former. We could take this step if we consider the time frame in which the exporter is not progressing/acknowledging too large. However, it also makes our backups more complex.
* Update the [SaaS controller ticket](https://github.com/camunda-cloud/camunda-operator/issues/2590) with the details what they need to change

**Comment by megglos** [comment]
Removing from ZPA board as this is at most affecting ZDP but seems more related to controller.

**Comment by ThorbenLindhauer** [comment]
@megglos correct

**Comment by Zelldon** [comment]
Supersed by https://github.com/camunda/camunda/issues/24456
