### ISSUE TITLE
Validate the new Elasticsearch exporter with a real-world-inspired benchmark

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#16910]
### Description

* Same as https://github.com/camunda/zeebe/issues/16909 but do it when the implementation is done (or sufficiently far)
* Gives us more confidence in shipping the new exporter with little interuption for users on migration
* [Product hub epic](https://github.com/camunda/product-hub/issues/2128)

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by Zelldon** [comment]
superseded with https://github.com/camunda/camunda/issues/21472
