### ISSUE TITLE
Incident records provide tree path properties that locate the incident in a hierarchy of process instances

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#16915]
**Is your feature request related to a problem? Please describe.**

* For the [new Elasticsearch exporter that writes Operate entities](https://github.com/camunda/product-hub/issues/2128), we need to provide the so-called tree path. It is a concept to assign entities their location in a tree of process instances and BPMN scopes, so that we can query for it and find all entities within a particular subtree. Find the full context and explanation in the [design document](https://docs.google.com/document/d/1Nh8Jln5_aWIS1O5NnC-SGRblijizDTSujG7zIfc-GOY/edit).
* With this feature, we want to provide the tree path for incident records, because that is where Operate currently needs the functionality. In the future and as the feature set evolves, we may roll it out to more records.
* [Product hub epic](https://github.com/camunda/product-hub/issues/2128)

**Describe the solution you'd like**

* The following uses this example process hierarchy: 
  * Process A (2 sub processes + call activity X)
    * Process B (plain call activity Y)
      * Process C (1 sub process)

* Incident records should have three new fields:
  * BPMN scope instance path: 
    * One entry per process instance in the hierarchy of the incident
    * Each process instance entry contains all the BPMN scope and call activity instance keys
    * Example path: 101/102/103/104;105/106;107/108 (we could also add the leaf instance key)
  * Calling process definition path:
    * One entry per process definition in the hierarchy
    * Each entry is the key of the process definition the corresponding process instance
    * Example (for same hierarchy as above): A/B
    * The leaf process definition can but doesn’t have to be included
  * Calling element path:
    * One entry per call activity in the hierarchy, 
    * Each entry is a reference to the call activity in BPMN
    * Exact format to be decided during implementation. Should not be the flow node id (as that would require a lot of space), but a numerical reference into the BPMN model. Accordingly, that requires the process definition to decode.
      * Idea: could be the index of the BPMN element's position in the XML model (counted by start tag)
    * Example (for same hierarchy as above): encode(X)/encode(Y) = 3/5

**Describe alternatives you've considered**

* See the [design document](https://docs.google.com/document/d/1Nh8Jln5_aWIS1O5NnC-SGRblijizDTSujG7zIfc-GOY/edit) for how we got to this proposal

**Additional context**

* See the [design document](https://docs.google.com/document/d/1Nh8Jln5_aWIS1O5NnC-SGRblijizDTSujG7zIfc-GOY/edit)

**Comment by sdorokhova** [comment]
Hi @megglos , is there any timeline for this issue? We depend on it in big part of our [Export directly to Operate](https://github.com/camunda/zeebe/issues/16912) epic.

**Comment by oleschoenburg** [comment]
Probably something for @korthout now.

**Comment by korthout** [comment]
@sdorokhova As part of https://github.com/camunda/product-hub/issues/2128, I believe this is an issue that @mustafadagher will continue after finishing:
- https://github.com/camunda/zeebe/issues/16916

The current estimate is alpha2.
