### ISSUE TITLE
Train the Operate team in writing performance-sensitive Java code in the exporter

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#16921]
### Description

* We need to be aware that the exporter code is performance-critical and competes with other critical Zeebe features for resources like CPU and memory. Inefficient implementations can have effects beyond the exporter. Slowing down the exporter's throughput can directly reduce overall system throughput for users. Let's prepare and coach each other for how we can best ensure that we continue building the exporter with sensitivity for performance.

### TODO

Suggestions:

* Share with all backend engineers of the team how the exporter works and in which context it operates. Explain why this is performance-critical, talk about best practices and examples of performance-sensitive Java coding.
  * Could be in the form of a tech talk 
  * Zeebe teams, especially ZDP, are very knowledgeable here and could support/mentor
* Create a knowledge base how to develop it (integrating or reusing what Zeebe might already have) so that every engineer can understand this topic on their own and this knowledge doesn't get lost easily
* Position the DRI as a sparring partner for their peers in day-to-day business

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by Zelldon** [comment]
AFAIK people are aware and I feel there is nothing actionable from this issue right now. Plus most of the implementation work is already done. I will close this one.
