### ISSUE TITLE
Write integration tests for the Operate business logic with Opensearch

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#16923]
### Description

* There should be integration tests that validate the (ex Operatea) business logic against Opensearch
* This should use the same tests that we create with https://github.com/camunda/camunda/issues/22642
* Note: the implementation of Opensearch support is covered via https://github.com/camunda/camunda/issues/20910 or a follow up ticket

### TODO

* to be filled out by DRI

### Additional Information

* Consider separating/extracing the exporter's business logic from its persistence logic (interactions with Opensearch/Elasticsearch), so that we can ship two different artifacts but have a single codebase for anything not directly related to *search

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by Zelldon** [comment]
We wrote always our tests against both ES and OS, so I think this is covered already.
