### ISSUE TITLE
Zeebe latency increased over the last releases

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#17092]
**Describe the bug**

It looks like Zeebe's performance has decreased since 8.3. 

> [!Note]
> 8.1 and was 8.2, was bad because of missing features like batch processing and SST partioning. 
>
> https://camunda.com/blog/2024/02/zeebe-performance-2023-year-in-review/ 

After reaching with 8.3 a good latency we seem to not able to keep it up, with 8.4 and 8.5-alphaX it seems that the latency has been increased again.

![latency](https://github.com/camunda/zeebe/assets/2758593/40ac547b-90a6-48ff-85bd-7d2cfb642272)

**P50**
![p50-release-latency](https://github.com/camunda/zeebe/assets/2758593/f23ed0f5-2766-4012-9967-0de1fa9c2fbb)

**P90**
![p90-release-latency](https://github.com/camunda/zeebe/assets/2758593/55b6e3ad-d4b3-48dd-b610-38d647df364a)

@megglos we should better look into this, as this is the ZDP mission.

**To Reproduce**

Run the different latency benchmarks and compare the corresponding latencies. 

I think it was raised before by @npepinpe that the medic perform different (or better than the release benchmarks). This might be related to the nodes type and also using stable nodes. 

But I feel they have performed also better before.  I guess this changed tiptoeing, and we only compare 4 weeks so we might not have seen it (but we should have seen it in the release benchmarks).

![medic-latency](https://github.com/camunda/zeebe/assets/2758593/6efc1bec-7807-42bc-8683-4d4485b95741)

**Expected behavior**

We have the same latency as within 8.3.

**Comment by Zelldon** [comment]
I haven't assigned the likelihood and severity yet, as we should better assess it first. But depending on the use case of a customer the severity can become quite high. Likelihood also be high, as it looks like a general issue with the release \cc @megglos 

I would propose to check/assess this more deeply and verify whether it is indeed an issue and then we can decide on the next steps.

**Comment by npepinpe** [comment]
I'd be curious to see if the job push back pressure feature introduced in 8.4 is causing this, as we didn't change our worker config between 8.3 and 8.4 (but we were already using job push in 8.3). Although I think it's unlikely, since I don't see any job yielded events reported :thinking:

**Comment by npepinpe** [comment]
Some things that jump out:

Number of journal seek is higher in 8.4 than 8.3:

| | 8.3 | 8.4 |
|-|-----|-----|
|Seek|![image](https://github.com/camunda/zeebe/assets/43373/fbce1e61-db69-4780-a949-c42266045a41)|![image](https://github.com/camunda/zeebe/assets/43373/9fc1e4ec-1e6f-4a24-80bb-0e4ecf1802a3)|

Overall processing latency is much higher in 8.4, but that's to be expected (left is 8.3, right is 8.4):

![image](https://github.com/camunda/zeebe/assets/43373/9fa4792b-5d5f-4a48-a6a1-0fb54217e9c4)

Record writes is mostly same, but commit latency is slightly higher in 8.4 (left is 8.3, right is 8.4):

![image](https://github.com/camunda/zeebe/assets/43373/77116b70-9d8b-4f5b-8203-c7a26b755185)

I think useful would be to backport all the new per-intent performance metrics we added in 8.4 to 8.3 to properly compare, as these are missing for 8.3.

**Comment by Zelldon** [comment]
Looks like that the release-8.5 is back to "normal".

![releases-latency](https://github.com/camunda/zeebe/assets/2758593/ed0c9790-ca8a-4236-8933-49691bb80a1e)

Would be interesting whether this is just because it is "newer" (and maybe we haven't accumulated state here) or whether we have really improved performance again?

**Comment by Zelldon** [comment]
Looks like our snapshot size grows in the alpha-2 up to 40 MB, and then suddenly it gets cleaned up again? Then starts to grow again. Maybe something related to compaction? Unfortunatelty, we can see anything in the RocksDB metrics.

![alpha2-snapshot-size](https://github.com/camunda/zeebe/assets/2758593/a11f4dd7-c61d-40c5-8623-7b5ac94621da)

The same happens for 8.4, but only up to 30 MB.

![84-snapshot-size](https://github.com/camunda/zeebe/assets/2758593/dbf263be-06a9-40fa-bb86-e746a8edd984)


And for 8.3 it is only up to 20 MB, likely why it is always faster than the others? 

![83-snapshotsize](https://github.com/camunda/zeebe/assets/2758593/833ca548-d23d-4ccf-8277-e46e0098cfea)


I feel like this has something to do with the decreased latency, as we have seen in the past larger state has an influence on our performance. 

\cc @megglos I feel we should better look into it and also think about how we could improve our observability into RocksDB and what happens inside.

**Comment by Zelldon** [comment]
I shortly checked the state of alpha-2, and nothing related to the data that would explain this, but right now the state is only 5 MB, not 40 MB big.

```
$ zdb state -p partitions/1/snapshots/337282334-5-3031356828-3031356100 | jq
{
  "DEFAULT": 1,
  "KEY": 1,
  "ELEMENT_INSTANCE_PARENT_CHILD": 30,
  "ELEMENT_INSTANCE_KEY": 30,
  "ELEMENT_INSTANCE_CHILD_PARENT": 30,
  "VARIABLES": 60,
  "JOBS": 15,
  "JOB_STATES": 15,
  "JOB_DEADLINES": 15,
  "EVENT_SCOPE": 15,
  "EXPORTER": 2,
  "PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY": 15,
  "MIGRATIONS_STATE": 1,
  "PROCESS_VERSION": 1,
  "PROCESS_CACHE": 1,
  "PROCESS_CACHE_BY_ID_AND_VERSION": 1,
  "PROCESS_CACHE_DIGEST_BY_ID": 1
}
[cqjawa release-85-alpha2/ cluster: zeebe-cluster ns:release-8-5-0-alpha2]$ zdb state -p partitions/2/snapshots/346327334-6-3112700702-3112686630 | jq
{
  "DEFAULT": 1,
  "KEY": 1,
  "ELEMENT_INSTANCE_PARENT_CHILD": 8,
  "ELEMENT_INSTANCE_KEY": 8,
  "ELEMENT_INSTANCE_CHILD_PARENT": 8,
  "VARIABLES": 16,
  "JOBS": 4,
  "JOB_STATES": 4,
  "JOB_DEADLINES": 4,
  "EVENT_SCOPE": 4,
  "EXPORTER": 2,
  "PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY": 4,
  "MIGRATIONS_STATE": 1,
  "PROCESS_VERSION": 1,
  "PROCESS_CACHE": 1,
  "PROCESS_CACHE_BY_ID_AND_VERSION": 1,
  "PROCESS_CACHE_DIGEST_BY_ID": 1
}
[cqjawa release-85-alpha2/ cluster: zeebe-cluster ns:release-8-5-0-alpha2]$ zdb state -p partitions/3/snapshots/336773632-5-3026730644-3026711537 | jq
{
  "DEFAULT": 1,
  "KEY": 1,
  "ELEMENT_INSTANCE_PARENT_CHILD": 32,
  "ELEMENT_INSTANCE_KEY": 32,
  "ELEMENT_INSTANCE_CHILD_PARENT": 32,
  "VARIABLES": 64,
  "JOBS": 16,
  "JOB_STATES": 16,
  "JOB_DEADLINES": 16,
  "EVENT_SCOPE": 16,
  "EXPORTER": 2,
  "PROCESS_INSTANCE_KEY_BY_DEFINITION_KEY": 16,
  "MIGRATIONS_STATE": 1,
  "PROCESS_VERSION": 1,
  "PROCESS_CACHE": 1,
  "PROCESS_CACHE_BY_ID_AND_VERSION": 1,
  "PROCESS_CACHE_DIGEST_BY_ID": 1
}
```

**Comment by megglos** [comment]
I would rate performance regression as a high severity as users who rely on the latency would not expect performance to become worse when updating. Likelihood also seems high given benchmarks are consistently affected. Let's look into this next, has anyone capacity next week to continue here? @camunda/zeebe-distributed-platform

**Comment by korthout** [comment]
I strongly urge you to look at my investigation of this topic in Medic CW12 ([see handover doc](https://docs.google.com/document/d/10WRX41PnCbVnwdATC2owILGZ8_c1J8YvoSnxENfEpGc/edit#heading=h.9epfjratzuet)).

- I don’t know what caused this, but **at least it wasn’t a code change, because it also happened on 8.5.0-alpha2**
- What I mean with that is that on `8.5.0-alpha2` the performance was as usual until Mar 17, 2024 3:00 AM GMT+1 at which point the latency performance degraded
- Since no patches are created for alpha versions, this must have been running the same code
- I think this is hardware related

**Comment by deepthidevaki** [comment]
The recent values looks okay to me. 
![image](https://github.com/camunda/zeebe/assets/1997478/850186a5-d362-4171-84f3-89a241888b86)

**Comment by JiangZih** [comment]
@npepinpe @deepthidevaki @Zelldon  
Hello, sorry to bother you. I have used Zeebe to logically split a complex RPC interface to make it more flexible. However, after refactoring, the processing time has increased significantly. If I aim for optimal performance, what configurations should I change? I don't need to ensure data persistence or consistency specifically; I just want to minimize processing time.

![image](https://github.com/camunda/zeebe/assets/130624264/ffb5e7c1-6d48-413a-a3e8-a930dcc1f541)

My process 
![image](https://github.com/camunda/zeebe/assets/130624264/b422bc0c-0c6d-4de2-804c-7211db7bf44d)

**Comment by npepinpe** [comment]
This is at worst a sequence of tasks, so worst execution time would be whatever time it takes to execute each. Your best bet is to use Zeebe > 8.4, and enable job streaming for your workers, and maximize the parallelism of both Zeebe and your workers to spread the load out horizontally and keep latency low/consistent. 

For workers this means having a good number of threads based on their workload, and scaling them out based on expected throughput. You don't want a worker to queue too many jobs, as time spent in the queue increases latency.

For Zeebe itself, it means scaling the number of partitions and brokers horizontally. It's mostly more partitions, but each partition has a resource cost, so depending on your fleet of nodes, it's worth spreading them across multiple instances. Replication factor can likely stay 3, as that's just about resilience, not performance.

**Comment by JiangZih** [comment]
Thank you very much for your reply. Currently, I am deploying the cluster using Docker images with three instances, version zeebe:8.5.0. The ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT is set to 3, and ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR is also set to 3. There are 12 CPUs, but the CPU utilization is very low, only around 2%. I will first try to reduce the number of CPUs and expand more pods and partitions. I would like to understand the specific reasons affecting the latency between the two nodes. Where should I look in the source code? Thanks again.

**Comment by korthout** [comment]
@JiangZih I recommend discussing your case on our forums (https://forum.camunda.io/) instead of in this issue. [This issue](https://github.com/camunda/zeebe/issues/17092) is specifically about an observed drop in latency performance in our benchmarks, and I'd like to continue discussing that now.

---

[This week](https://docs.google.com/document/d/1LgL6MmodSKRZmFIK5rYB_atdxAFfPBHXf69Bdfp-tBU/edit#heading=h.9epfjratzuet), the latency performance has degraded again (i.e. increased latency). 

<img width="1704" alt="Screenshot 2024-05-01 at 11 56 47" src="https://github.com/camunda/zeebe/assets/3511026/989ceff8-1d53-4242-8c7e-c3a79d31b7d0">
