### ISSUE TITLE
CI (self-hosted runners) seem to be more unstable since last week

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#17090]
I observed since last week more and more builds failing because of `The self-hosted runner: actions-runner-amd64-16-vmxsl-wrmqg lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that termina`

It looks like that our self-hosted runners are getting preempted more and more due to more load on the CI? Could that be because we have more jobs to run and they have to be rescheduled on nodes?

Examples:

 * https://github.com/camunda/zeebe/actions/runs/8392653963
 * https://github.com/camunda/zeebe/actions/runs/8416149926/job/23042386723
 * there are more

**Comment by Zelldon** [comment]
Also raised here https://camunda.slack.com/archives/C06HTSPD5AP/p1711636891137509

**Comment by npepinpe** [comment]
ZDP: long term makes sense to migrate to infra supported to nodes, as with the monorepo we will just have more work maintaining our own CI. I'll coordinate with Christian on that to see how we can do this. If it becomes more than an annoyance, we can reassess and block time for it.

**Comment by npepinpe** [comment]
I think we can close this, we're now monitoring the state, and we plan on moving to the infra self hosted runners. If we see it happen a lot in the near future, then we can take action, otherwise there's nothing to do for us at the moment.
