### ISSUE TITLE
go client jobWorkerBuilder can't set tenantIds

### ISSUE THREAD

**Issue by tsfans** [camunda/camunda#17167]
**Describe the bug**
go client jobWorkerBuilder can't set tenantIds, but ActivateJobsRequest needs TenantIds when zeebe enabled multi-tenancy.
relate https://github.com/camunda/zeebe/issues/15095 is closed, Do we have any plan on this feature?

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**
`2024/03/28 14:17:35 Failed to activate jobs for worker 'default': rpc error: code = InvalidArgument desc = Expected to handle gRPC request ActivateJobs with tenant identifiers '[]', but no tenant identifiers were provided.`

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: windows11
- Zeebe Version: 8.4.5
- go-client: v8.4.5
- Configuration:

**Comment by megglos** [comment]
ZPA-Triage:
- relabeling as feature request as multi tenancy support was deliberately not added to the go client as indicated in #15095

**Comment by megglos** [comment]
@tsfans if you are interested to contribute, we are happy to assist

**Comment by aleksander-dytko** [comment]
Hi @tsfans, we don't see a high product priority to support this functionality in zbctl due to the [decision](https://camunda.com/blog/2024/03/streamlining-camunda-apis-zeebe-rest-api/) to move zbctl to the camunda community hub in 8.6. Feel free to contribute and we're happy to assist here ;)
