### ISSUE TITLE
gRPC logging is not handled by slf4j

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#17414]
Since gRPC uses `java.util.logging` and we don't use the `jul-to-slf4j` bridge, logs produced by gRPC do not respect the usual logging configuration. For example, they are not logged as JSON when Stackdriver logging is enabled and they cannot be silenced through the usual slf4j configuration.

We should consider including `jul-to-slf4j`: https://www.slf4j.org/legacy.html#jul-to-slf4j. To prevent potential performance impact, the `LevelChangePropagator` should be used too: https://logback.qos.ch/manual/configuration.html#LevelChangePropagator

Related to https://jira.camunda.com/browse/SUPPORT-21429

**Comment by npepinpe** [comment]
ZDP:
- Looks like a good first issue, well defined, and the solution is already provided above thanks to @oleschoenburg

**Comment by npepinpe** [comment]
This looks to be fixed on main (so 8.6.0-SNAPSHOT), because of the merging of the applications, the dependency log4j-jul is now part of the classpath.

I would propose doing this as a fix to keep things aligned, but just backport to older versions.
