### ISSUE TITLE
Log stream flow control protects the raft thread from overloading

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#17669]
The log stream flow control ensures that user commands can be processed in time, that the raft thread is not overwhelmed by write bursts and that everything can be exported in time.

As a first step, it will only protect the raft thread, essentially taking over from `AppenderFlowControl`.
As a result, this flow control will be easier to configure and have sensible defaults.

Relates to https://github.com/camunda/zeebe/issues/14316

**Comment by oleschoenburg** [comment]
@rodrigo-lourenco-lopes and I tested the existing default limits for the appender with different models that produce high write load. We also increased network latency to make commits slower.

We can see the limit for in-flight appends growing out of control, reaching it's maximum of 32k!
![image](https://github.com/camunda/zeebe/assets/1379753/9a4b201d-1b18-4f3c-8679-3c1712df3d1b)

This limit seems to be utilized, the number of actual in-flight appends is also very high: 
![image](https://github.com/camunda/zeebe/assets/1379753/cb026c23-db55-4185-b1b5-b29f0a36018d)


The rate at which we reject writes is still very high during this: 
![image](https://github.com/camunda/zeebe/assets/1379753/2a85230e-8415-4a8a-988e-64f84eb9fb10)

We didn't see any signs that this is a problem for the raft thread. For example, we did not observe OOMs or timeouts. Still, it seems obvious that these limits are way too high and that we should not have 32k in-flight appends.
