### ISSUE TITLE
Flaky io.atomix.raft.roles.LeaderRoleTest.shouldNotAppendFollowingEntryOnException

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#17882]
**Summary**

- How often does the test fail? 1
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

```
Warning:  Flakes: 
Warning:  io.atomix.raft.roles.LeaderRoleTest.shouldNotAppendFollowingEntryOnException
Error:    Run 1: LeaderRoleTest.shouldNotAppendFollowingEntryOnException:300 
raftContext.transition(FOLLOWER);
Wanted 1 time:
-> at io.atomix.raft.impl.RaftContext.transition(RaftContext.java:653)
But was 2 times:
-> at io.atomix.raft.roles.LeaderRole.appendEntry(LeaderRole.java:616)
-> at io.atomix.raft.roles.LeaderRole.appendEntry(LeaderRole.java:616)

```

**Hypotheses**
None

**Logs**

[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/15127345/Test.results.for.unit.tests.zip)

**Comment by lenaschoenburg** [comment]
I can't tell from the log files what happened in that failed run.
I failed to reproduce this in >30k runs of this test and our flaky test reporting doesn't mention this test either.

I'm going to close this for now, please reopen if it occurs again.
