### ISSUE TITLE
Investigate splitting Operate front-end build out of maven

### ISSUE THREAD

**Issue by matt-whiteman** [camunda/camunda#17926]
### Description

Tasklist separates the frontend built out of maven which keeps the build job from hanging if the frontend runner times out. Investigate exactly what Tasklist does and if we could do the same on Operate. Some previous discussion on the [reasons can be found here](https://camunda.slack.com/archives/C071KP5BTHB/p1719396423980429?thread_ts=1719393029.526679&cid=C071KP5BTHB).

This would be a possible fix for the issue where the build hangs "Waiting for other projects to finish" then times out after 20 minutes and fails the build. Example:

* https://github.com/camunda/camunda/actions/runs/8847129914/job/24294343499#step:7:8619
* https://github.com/camunda/camunda/actions/runs/9675535964/job/26693229353 in merge queue (raised [via Slack](https://camunda.slack.com/archives/C071KP5BTHB/p1719393029526679))
* https://github.com/camunda/camunda/actions/runs/10181725006/job/28162596301 in merge queue (raised [via Slack](https://camunda.slack.com/archives/C071KP5BTHB/p1722502636108589))
* https://github.com/camunda/camunda/actions/runs/10194109942/job/28200021145 in merge queue
* https://github.com/camunda/camunda/actions/runs/10183726649/job/28169364404 in merge queue
* https://github.com/camunda/camunda/actions/runs/10182295451/job/28164460822 in merge queue

**Workaround: retry merging affected PRs**

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by johanwelgemoed** [comment]
I asked Vinicius and this was his response:
it's basically just this https://github.com/camunda/zeebe/blob/main/.github/workflows/tasklist-ci-build-reusable.yml#L88-L94
another thing I recommend you do is to implement the operate ci for the checks that are not flaky like we did on tasklist [here](https://github.com/camunda/zeebe/blob/main/.github/workflows/tasklist-ci.yml)
this will prevent the auto-merge from going crazy and merge broken things
in our case for frontend only the e2e are still flaky

**Comment by cmur2** [comment]
@ThorbenLindhauer I'd like to talk about this issue during our sync today and get it prioritized. The issue tracked in this ticket is known since April and leads to periodic build failure spikes → those prevent merges to `main` and impact other engineers.

It is the top failure reason in the last couple of days:

![image](https://github.com/user-attachments/assets/1975bd57-fac2-49ea-9e6b-3c88acb4d936)
