### ISSUE TITLE
Non existing date for timer event is never triggered

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#18167]
**Describe the bug**

When specifying a timer date (via variable) to a nonexisting date `"2024-04-31T10:00:00Z"` it happens that the timer catch event is never triggered.

![2024-05-02_11-02](https://github.com/camunda/zeebe/assets/2758593/397aeac3-2627-4b4b-8db7-810d4ec9ee48)

**To Reproduce**

Specify a date which doesn't exist.

**Expected behavior**

Either we create an incident, that clearly marks that the date is invalid or it simply triggers the day after 🤷🏼

**Comment by korthout** [comment]
ZPA triage:
- we should investigate whether this can be produced from both static as well as feel expression
- fixing the bug could be achieved by creating an incident
- we should discuss with product whether we want to auto-infer correct date from wrong date, then we can build this separately (reasoning is that this could be more in line with friendliness of other FEEL-expressions)
- prio: next

**Comment by korthout** [comment]
@Zelldon We tried reproducing this issue at today's mob programming session but did not succeed. Can you confirm the following the following for us?

- The used expression in the process at the time was `date and time(date and time(code_freeze_date), time("T04:00:00Z")) - now() - duration("P1D")`
- The variable `code_freeze_date` at the time was `"2024-04-31T10:00:00Z"`
- The current time at the moment the timer was created was `2024-04-04T12:57:49`

This case creates the timer to trigger at `2024-04-29T04:00:00`. And it is triggered after time travel past that moment.

Any help to reproduce this is appreciated :bow:

**Comment by Zelldon** [comment]
I don't have more data than you have. I tried to [check the data on the cluster but it was already gone](https://app.slack.com/client/T0PM0P1SA/C074MJ58Q86)

**Comment by Zelldon** [comment]
Likely we could still check the ES data? 🤔

**Comment by Zelldon** [comment]
I tried several ways to reproduce without success.

## First try:

- Set up a cluster in SaaS (latest version)
- Deploy a process model with a timer using the same expression
- creating an instance with code freeze time set as in our report
- Observe success

## Second Try

Do the same with 8.4-gen7 cluster

## Third Try 

Do the same with 8.4.6 cluster.


## Screenshots

I added also some more output mappings to see the actual calculations

![2024-05-23_16-56_1](https://github.com/camunda/camunda/assets/2758593/2d2ae200-48b6-4239-8c5b-e62988b87f8a)
![2024-05-23_16-56](https://github.com/camunda/camunda/assets/2758593/fa7095c3-5f1f-4b0a-bb83-068f841aece7)


-----

As we can't reproduce it, I would close it for now. Feel free to reopen this if we run into this issue again.

**Comment by Zelldon** [comment]
To add what happens when you specify a 31.06 and 30.06 -> results in the same values

![2024-05-23_17-04](https://github.com/camunda/camunda/assets/2758593/2ea48e9d-acb1-4115-b539-fc6b65c96f84)


And if you use a total wrong value like 32.06 (no month has 32 days) 

![Uploading 2024-05-23_17-06.png…]()

**Comment by korthout** [comment]
Thanks @Zelldon for looking into it as well 🙇
