### ISSUE TITLE
Do not log MessagingException$ConnectionClosed as an error in the gateway

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#18339]
**Description**

We recently introduced a new exception to represent when a connection was closed in the messaging service before it was completed, usually because we're closing the service itself. This triggers logging lots of errors when we have in flight connections, which aren't particularly useful, since you're shutting down.

Instead, we should treat this as upstream being temporarily unavailable, return `UNAVAILABLE`, and log it like we do with the `ConnectException` in `GrpcErrorMapper` (see line 120 for 8.2).

Context:

- https://console.cloud.google.com/errors/detail/CKCP-c-I5-3zkQE;service=zeebe;time=P7D?project=zeebe-io
- https://console.cloud.google.com/errors/detail/CIr23a-H74DG8QE;service=zeebe;time=P7D?project=zeebe-io
- https://console.cloud.google.com/errors/detail/CIr23a-H74DG8QE;service=zeebe;time=P7D;locations=global?project=camunda-saas-prod-lhr

**Comment by npepinpe** [comment]
I would propose to return ABORTED instead. Why? Because UNAVAILABLE typically implies you should just restart. In this case, the connection was closed but may have been accepted, meaning we don't know if it's safe to retry blindly.

**Comment by lenaschoenburg** [comment]
[Occured again](https://console.cloud.google.com/errors/detail/CIr23a-H74DG8QE;service=zeebe;time=P7D;locations=global?project=camunda-saas-prod-lhr), can we get the [PR](https://github.com/camunda/camunda/pull/20066) reviewed and merged @rodrigo-lourenco-lopes?

**Comment by korthout** [comment]
🤔 That's strange. The job was [skipped](https://github.com/camunda/camunda/actions/runs/12047781326) but the PRs have been created. No comments were posted here though.
 
<img width="1317" alt="Screenshot 2024-11-27 at 11 16 03" src="https://github.com/user-attachments/assets/f6a80a22-2aff-4468-8df7-91cbd8b0c36e">

**Comment by npepinpe** [comment]
Yes, I commented on the issue initially which is wrong, I then commented on the PR :smile:
