### ISSUE TITLE
Operate exporter: rework ProcessCache

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#18364]
### Description

Currently we use `ProcessCache` to store/get process definition names and flow node names. The cache has limited size and therefore the entries may be evicted and be requested from Elasticsearch again. We need to make it as performant as possible:  minimize the data stored in cache and fill it in the most performant manner.

### Tasks

Based on proposal 1 described here: https://docs.google.com/document/d/1No2WPUtLg22x9CFlw2dA8uJmk7wwNC50MsuHenAkHis/edit#heading=h.dtgya6ciylb

- [x] #24154
- [x] #24179
- [x] #24208
- [x] #24345
- [x] #24346

##### Optimizations (next iteration)

- [ ] Asynchronously fill cache on startup to reduce chances of cache miss during exporting.
- [ ] Shared cache for all partitions in the same broker.

### Additional Information

There is some description in Slack: https://camunda.slack.com/archives/C06F0GLJNFM/p1720788578770879

**Comment by sdorokhova** [comment]
Will put the older (outdated) TODO items here, some of the points may be valuable during implementation: 
* rework current `ProcessCache` structure to normal cache (without size limitations and evictions)
* fill the cache on exporter startup from exporter metadata
* add data to cache during export (when new process definitions are being processed)
* [update exporter metadata](https://github.com/camunda/zeebe/blob/fa3919f106b653f02dec43365450679719edca4f/zeebe/exporter-api/src/main/java/io/camunda/zeebe/exporter/api/context/Controller.java#L40) with every persisted entities batch
* TBD can we remove data from cache when process definitions are deleted? We did not process process definition deletion records so far. Could we start doing that to keep cache up to date?

**Comment by deepthidevaki** [comment]
Following our discussion in https://docs.google.com/document/d/1No2WPUtLg22x9CFlw2dA8uJmk7wwNC50MsuHenAkHis/edit#heading=h.dtgya6ciylb, we have to provide the following interface in the ProcessCache.

```
String getProcessName(final long processDefinitionKey);
void put(final long processDefinitionKey, final String processName);
void delete(final long processDefinitionKey);
void clear();
```

In the current implementation of ProcessCache in Operate, I see the following methods. 
```
String getProcessNameOrDefaultValue(Long processDefinitionKey, String defaultValue);
String getProcessNameOrBpmnProcessId(Long processDefinitionKey, String defaultValue);
String getProcessVersionTag(Long processDefinitionKey);

// Following ones, we decided that we don't need them for the exporter.
getFlowNodeNameOrDefaultValue
```

@sdorokhova What is the use case for `getProcessNameOrDefaultValue` and `getProcessNameOrBpmnProcessId`. Should we provide them in the new process cache? Should we also cache versionTag?

**Comment by Zelldon** [comment]
> The cache will be empty on startup or leader change and will be populated on demand

We could also think about pre-filling on start-up. But doesn't need to be done necessarily on the first iteration I guess.

**Comment by npepinpe** [comment]
@Zelldon - as Deepthi is on leave, can you assign someone else?

**Comment by Zelldon** [comment]
Yes i discussed with her im taking this over.
