### ISSUE TITLE
Operate exporter: rework tree path fields

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#18378]
### Description

We need to fully get rid of tree path caches and call activity id cache.
Details are in the document: https://docs.google.com/document/d/1Nh8Jln5_aWIS1O5NnC-SGRblijizDTSujG7zIfc-GOY/edit

* [x] #24061
* [x] #24063
* [x] #25223
* [x] #24542
* [x] #24733
* [x] #25237

### Additional Information

Related Zeebe changes with description of the new incident fields: #16915 and #20293

**Comment by ThorbenLindhauer** [comment]
Moving this to Blocked, because it requires Zeebe work first.
