### ISSUE TITLE
Provide observation context to exporters

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#18467]
**Is your feature request related to a problem? Please describe.**

I would like to add metrics from my own custom exporter and have them scraped along with the rest of the Zeebe metrics. However, using the default `CollectorRegistry.defaultRegistry` (or the Micrometer equivalent one) fails, as the exporter is loaded in a different class loader. This also implies that Zeebe will always rely on the default registry, which may not be true forever.

**Describe the solution you'd like**

Much like the `Context` provided to the exporter on configuration has a `Logger` member, I would like the same for metrics. I think using `Micrometer` (which is to metrics what SLF4J is to logging) would make more sense, but I'm OK with Prometheus :)

**Describe alternatives you've considered**

You can work around this by loading the `CollectorRegistry` class directly from the system class loader, e.g.:

```java
final Class<?> registryClass =
    ClassLoader.getSystemClassLoader().loadClass(CollectorRegistry.class.getName());
final Field registryField = registryClass.getDeclaredField("defaultRegistry");
final CollectorRegistry registry = (CollectorRegistry) registryField.get(null);
Counter.build().name("test").namespace("test").register(registry);
```

As you can see, this is cumbersome, and ignores all the try-catch and possible errors. It also relies on the `defaultRegistry` global, which makes it harder if we ever more to Micrometer across the board.

**Comment by Zelldon** [comment]
Triage:

 * Moving to backlog, as we don't see an urgency for this
 * Please speak up if you think otherwise

**Comment by npepinpe** [comment]
Priority will move up as we will need metrics with the upcoming web apps exporter refactor.
