### ISSUE TITLE
Flaky io.camunda.zeebe.engine.processing.multitenancy.TenantAwareTimerCatchEventTest.shouldApplyTenantToLifecycleEvents

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#18462]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

```
java.lang.AssertionError: 

Expecting actual:
  [("tenant-a", ACTIVATE_ELEMENT),
    ("tenant-a", ELEMENT_ACTIVATING),
    ("tenant-a", ELEMENT_ACTIVATED)]
to contain sequence:
  [("tenant-a", ACTIVATE_ELEMENT),
    ("tenant-a", ELEMENT_ACTIVATING),
    ("tenant-a", ELEMENT_ACTIVATED),
    ("tenant-a", COMPLETE_ELEMENT),
    ("tenant-a", ELEMENT_COMPLETING),
    ("tenant-a", ELEMENT_COMPLETED)]

	at io.camunda.zeebe.engine.processing.multitenancy.TenantAwareTimerCatchEventTest.shouldApplyTenantToLifecycleEvents(TenantAwareTimerCatchEventTest.java:202)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```
**Hypotheses**

**Logs**

https://github.com/camunda/zeebe/actions/runs/9063534548
[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/15295192/Test.results.for.unit.tests.zip)

**Comment by korthout** [comment]
I've checked and this is another case where the timer did not trigger after traveling through time more than 5 seconds (i.e. 1 minute). It will be resolved by #18508.
