### ISSUE TITLE
Support call activity mapping in instance migration mode

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#18492]
### Description
Zeebe will support migration of process instances with call activities.
Operate needs to enable users to map call activities in instance migration mode.

### User Story

```Gherkin
Scenario: As an Operate user
    Given I am in instance migration mode (mapping step)
    When I select a call activity as source element
    Then I can select a call activity as target element
```
### Acceptance Criteria

- [x] Call activities are available in the list of source elements
- [x] Call activities are selectable in the source diagram
- [x] Source call activities are mappable to target call activities
- [x] Source call activities can only be mapped to call activities (not to other element types)
- [ ] https://github.com/camunda/camunda-docs/issues/3834
- [ ] https://github.com/camunda/zeebe/pull/18742

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by aleksander-dytko** [comment]
@johanwelgemoed can we please prioritze this one? ☝️
