### ISSUE TITLE
Start form in a process with public link is not displayed on iPhone

### ISSUE THREAD

**Issue by volodymyr-melnykc** [camunda/camunda#18525]
Support ticket: https://jira.camunda.com/browse/SUPPORT-22977

### Describe the bug

There is an issue with a public link to a process when opening it on iPhone: in Safari and Chrome browsers. A blank page is shown instead of a start form.
The link works fine when opening it on a Desktop (both in Safari and Chrome).

### To Reproduce

1. Create a public link to a process with a start form.
2. Open the link on iPhone, in Safari or Chrome browser.
3. A blank page is displayed instead of the form.

### Actual behavior

A blank web page is displayed instead of the start form.

### Expected behavior

The start form should be displayed.

### Environment

- OS: iOS
- Browser: Chrome, Safari
- Tasklist Version: 8.5

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by esraagamal6** [comment]
Tested OK on chrome, safari and firefox on iphone.
Another bug reported that can be fixed later "[Submit button in public forms is hidden under the nav bar ios phone](https://github.com/camunda/camunda/issues/21052)"

**Comment by marcosgvieira** [comment]
@vsgoulart can we close this one?

**Comment by renzpatriarca** [comment]
Hi @marcosgvieira / @vsgoulart , 
Please confirm if this has been released as part of 8.5+gen9-patch (Tasklist 8.5.7)? 
From release, it was only tagged for Tasklist 8.6.0-alpha5.
