### ISSUE TITLE
I can copy all variables from a process instance

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#18578]
### Description

In Operate, the user can see all process instance variables and their values based on the workflow. In certain scenarios it’s useful to let users copy those variables and use them elsewhere.

Here’s a more specific example. When the user wants to test and validate Camunda forms, the process instance variables which are available in Operate are helpful to use as a form input. A big limitation with our forms right now is that there is no context about available data. Even when a form is part of a BPMN process, when reviewing it individually (in the Form Editor), it’s not clear what data the user can operate with. A proper data management for Camunda forms is our long-term goal, though before we get there, as a quick win, we can enable the user to copy all variables from Operate (as a JSON) to use as a form input. In this case, the user can quickly test a form and define how it should be handled based on data source.

### User Story

```Gherkin
Scenario: As an Operate user
    Given I am in instance details view
    When I click the button "Copy all variables"
    Then All variables are copied to clipboard in JSON format
```
### Designs

![image](https://github.com/camunda/zeebe/assets/2543743/0d258fac-e37b-4675-9a3d-8ba1b63d2718)

### Acceptance Criteria

- [x] The variables footer contains a button "Copy variables"
- [x] On button click all variables are copied to clipboard in JSON format
- [x] The button is disabled when pagination is active (50 or more variables)
- [x] The button is disabled when at least one variable value exceeds 8192 characters
- [x] The button is disabled when there are no variables 

Proposed JSON format:

```
{
  "<variableName>": <variableValue>
}
```

Example:
```json
{
  "firstName":"Paul",
  "lastName":"Young",
  "passNo":"P59909399",
  "ticketNo":"783"
}
```

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by sdorokhova** [comment]
@aleksander-dytko could you please check this new feature request and prioritize it?
