### ISSUE TITLE
zeebe cluster when node 0 fail cluster fail 

### ISSUE THREAD

**Issue by ahmedbeledy** [camunda/camunda#18583]
problem
I have a basic problem with my setup. I have 4 servers: one gateway and three nodes acting as brokers. The nodes are named as follows:

Node 0
Node 1
Node 2
Here is the issue:

If either Node 1 or Node 2 fails, the system continues to work as expected.
However, if Node 0 fails, the entire system stops working.
This issue does not occur when using Docker. The problem only happens on the local machine setup. Additionally, I've attached my configuration files at the bottom of this message.

Can you help me understand why this behavior is occurring and how to fix it?

 Environment:

OS:  Windows 10
Zeebe Version:8.5.1
installed : locally 4 machines one gateway and other node broker
configration : 

gatway config 

 zeebe:
   gateway:
     network:
         host: 192.168.8.115
            port: 26500
     cluster:
       host: 192.168.8.115
       port: 26502
      initialContactPoints: [192.168.8.114:26502 , 192.168.8.110:26502  , 192.168.8.105:26502]
      #  initialContactPoints: [192.168.8.114:26502 ]
     security:
       enabled: false
     multiTenancy:
         enabled: false

nodes config
first node
zeebe:
  broker:
    gateway:
        enable: false

    network:
      host: 192.168.8.114
      port: 26500
      security:
            enabled: false
    data:
      directory: data
    cluster:
      nodeId: 0
      partitionsCount: 2
      replicationFactor: 3
      clusterSize: 3
      initialContactPoints: [ 192.168.8.110:26502 , 192.168.8.114:26502 , 192.168.8.105:26502  ]
     second node
zeebe:
  broker:
    gateway:
        enable: false

    network:
      host: 192.168.8.110
      port: 26500
      security:
            enabled: false
    data:
      directory: data
    cluster:
      nodeId: 1
      partitionsCount: 2
      replicationFactor: 3
      clusterSize: 3
      initialContactPoints: [ 192.168.8.110:26502 , 192.168.8.114:26502 , 192.168.8.105:26502  ]
     
zeebe:
  broker:
    gateway:
        enable: false

    network:
      host: 192.168.8.105
      port: 26500
      security:
            enabled: false
    data:
      directory: data
    cluster:
      nodeId: 2
      partitionsCount: 2
      replicationFactor: 3
      clusterSize: 3
      initialContactPoints: [ 192.168.8.110:26502 , 192.168.8.114:26502 , 192.168.8.105:26502  ]

i try in docker and its works fine my docker file
 
 version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  gateway:
    restart: always
    container_name: gateway
    image: camunda/zeebe:${ZEEBE_VERSION}
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_STANDALONE_GATEWAY=true
      - ZEEBE_GATEWAY_NETWORK_HOST=0.0.0.0
      - ZEEBE_GATEWAY_NETWORK_PORT=26500
      - ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT=node0:26502
      - ZEEBE_GATEWAY_CLUSTER_PORT=26502
      - ZEEBE_GATEWAY_CLUSTER_HOST=gateway
    ports:
      - "26500:26500"
    networks:
      - zeebe_network
  node0:
    container_name: zeebe_broker_1
    image: camunda/zeebe:${ZEEBE_VERSION}
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_NODEID=0
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502,node1:26502,node2:26502
      
    networks:
      - zeebe_network
  node1:
    container_name: zeebe_broker_2
    image: camunda/zeebe:${ZEEBE_VERSION}
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_NODEID=1
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502,node1:26502,node2:26502
    networks:
      - zeebe_network
    depends_on:
      - node0
  node2:
    container_name: zeebe_broker_3
    image: camunda/zeebe:${ZEEBE_VERSION}
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_NODEID=2
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502,node1:26502,node2:26502
    networks:
      - zeebe_network
    depends_on:
      - node0      
      i try contactpoint like docker and not work

**Comment by ahmedbeledy** [comment]
i try in docker and its works fine my docker file
 
 version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  gateway:
    restart: always
    container_name: gateway
    image: camunda/zeebe:${ZEEBE_VERSION}
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_STANDALONE_GATEWAY=true
      - ZEEBE_GATEWAY_NETWORK_HOST=0.0.0.0
      - ZEEBE_GATEWAY_NETWORK_PORT=26500
      - ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT=node0:26502
      - ZEEBE_GATEWAY_CLUSTER_PORT=26502
      - ZEEBE_GATEWAY_CLUSTER_HOST=gateway
    ports:
      - "26500:26500"
    networks:
      - zeebe_network
  node0:
    container_name: zeebe_broker_1
    image: camunda/zeebe:${ZEEBE_VERSION}
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_NODEID=0
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502,node1:26502,node2:26502
      
    networks:
      - zeebe_network
  node1:
    container_name: zeebe_broker_2
    image: camunda/zeebe:${ZEEBE_VERSION}
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_NODEID=1
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502,node1:26502,node2:26502
    networks:
      - zeebe_network
    depends_on:
      - node0
  node2:
    container_name: zeebe_broker_3
    image: camunda/zeebe:${ZEEBE_VERSION}
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_NODEID=2
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=2
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
      - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=node0:26502,node1:26502,node2:26502
    networks:
      - zeebe_network
    depends_on:
      - node0      
      i try contactpoint like docker and not work

**Comment by ahmedbeledy** [comment]
hello @Zelldon  
I have a basic problem with my setup. I have 4 servers: one gateway and three nodes acting as brokers. The nodes are named as follows:

Node 0
Node 1
Node 2
Here is the issue:

If either Node 1 or Node 2 fails, the system continues to work as expected.
However, if Node 0 fails, the entire system stops working.
This issue does not occur when using Docker. The problem only happens on the local machine setup. Additionally, I've attached my configuration files at the top of this message.

Can you help me understand why this behavior is occurring and how to fix it?

Thank you.

**Comment by Zelldon** [comment]
Thanks @ahmedbeledy 

Could you answer the following questions:

1. What do you mean by local setup? Using KIND? Using docker compose?
2. Is the configuration the same locally as with the other setup?
3. "Entire system stops working." What does this mean and implies? 

In general I would recommend to have this kind of discussion in the forum https://forum.camunda.io/ and if you found a clear bug/issue, open an issue here.

**Comment by ahmedbeledy** [comment]
1- local setup i not use kind or docker i download release and run it from bin 
2- yes 
3- i mean my requests to the gateway fail

**Comment by Zelldon** [comment]
Could you post the logs from the different brokers and gateway please and also tell me to which gateway you connect. What is the port and IP? Maybe you connect to an embedded gateway from the broker 0 ? 🤔

**Comment by ahmedbeledy** [comment]
this log before node 0 fail
  ______  ______   ______   ____    ______      _____              _______   ______  __          __            __     __                                                                                                                         |___  / |  ____| |  ____| |  _ \  |  ____|    / ____|     /\     |__   __| |  ____| \ \        / /     /\     \ \   / /                                                                                                                            / /  | |__    | |__    | |_) | | |__      | |  __     /  \       | |    | |__     \ \  /\  / /     /  \     \ \_/ /    / /   |  __|   |  __|   |  _ <  |  __|     | | |_ |   / /\ \      | |    |  __|     \ \/  \/ /     / /\ \     \   /    / /__  | |____  | |____  | |_) | | |____    | |__| |  / ____ \     | |    | |____     \  /\  /     / ____ \     | |    /_____| |______| |______| |____/  |______|    \_____| /_/    \_\    |_|    |______|     \/  \/     /_/    \_\    |_|                                                                                                                           2024-05-22 17:15:04.759 [] [main] [] INFO                                                                                     io.camunda.zeebe.gateway.StandaloneGateway - Starting StandaloneGateway v8.5.1 using Java 21.0.3 with PID 21368 (C:\Users\ahmed.beledy\Downloads\camunda-zeebe-8.5.1\camunda-zeebe-8.5.1\lib\camunda-zeebe-8.5.1.jar started by ahmed.beledy in C:\Users\ahmed.beledy\Downloads\camunda-zeebe-8.5.1\camunda-zeebe-8.5.1\bin)                                      2024-05-22 17:15:04.765 [] [main] [] INFO                                                                                     io.camunda.zeebe.gateway.StandaloneGateway - The following 1 profile is active: "gateway"                         2024-05-22 17:15:09.481 [] [main] [] INFO                                                                                     org.springframework.boot.web.embedded.netty.NettyWebServer - Netty started on port 8080                           2024-05-22 17:15:09.595 [] [main] [] INFO                                                                                     org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver - Exposing 12 endpoint(s) beneath base path '/actuator'                                                                                                               2024-05-22 17:15:09.682 [] [main] [] INFO                                                                                     org.springframework.boot.web.embedded.netty.NettyWebServer - Netty started on port 9600                           2024-05-22 17:15:09.706 [] [main] [] INFO                                                                                     io.camunda.zeebe.gateway.StandaloneGateway - Started StandaloneGateway in 5.597 seconds (process running for 7.6) 2024-05-22 17:15:09.716 [] [main] [] INFO                                                                                     io.camunda.zeebe.gateway - Starting standalone gateway gateway with version 8.5.1                                 2024-05-22 17:15:09.796 [] [netty-messaging-event-nio-server-0] [] INFO                                                       io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 192.168.1.3:26502                                                                                                                        2024-05-22 17:15:09.871 [] [netty-messaging-event-nio-server-0] [] INFO                                                       io.atomix.cluster.messaging.impl.NettyMessagingService - Started messaging service bound to [192.168.1.3:26502], advertising 192.168.1.3:26502, and using plaintext                                                                       2024-05-22 17:15:09.917 [] [netty-unicast-event-nio-client-0] [] INFO                                                         io.atomix.cluster.messaging.impl.NettyUnicastService - Started plaintext unicast service bound to 0.0.0.0:26502, advertising 192.168.1.3:26502                                                                                            2024-05-22 17:15:09.921 [] [atomix-cluster-0] [] INFO                                                                         io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Local node Node{id=gateway, address=192.168.1.3:26502} joined the bootstrap service                                                                                              2024-05-22 17:15:09.926 [] [atomix-cluster-0] [] INFO                                                                         io.atomix.cluster.protocol.swim - Started                                                                         2024-05-22 17:15:09.928 [] [atomix-cluster-0] [] INFO                                                                         io.atomix.cluster.impl.DefaultClusterMembershipService - Started cluster membership service for member Member{id=gateway, address=192.168.1.3:26502, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}               2024-05-22 17:15:09.928 [] [atomix-cluster-0] [] INFO                                                                         io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started                                     2024-05-22 17:15:09.931 [] [atomix-cluster-0] [] INFO                                                                         io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started                                             2024-05-22 17:15:10.081 [] [main] [] INFO                                                                                     io.camunda.zeebe.gateway - Standalone gateway is started!                                                         2024-05-22 17:15:11.040 [] [atomix-cluster-heartbeat-sender] [] INFO                                                          io.atomix.cluster.protocol.swim - gateway - Member added Member{id=1, address=192.168.1.13:26502, properties={brokerInfo=EADJAAAABAABAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkSAAAAMTkyLjE2OC4xLjEzOjI2NTAxBQAADAAABQAAADguNS4xBQAA, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}                                                                 2024-05-22 17:15:12.109 [] [atomix-cluster-heartbeat-sender] [] INFO                                                          io.atomix.cluster.protocol.swim - gateway - Member added Member{id=2, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAABAACAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAAwAAAUAAAA4LjUuMQUAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}                                                                          2024-05-22 17:15:13.120 [] [atomix-cluster-heartbeat-sender] [] WARN                                                          io.atomix.cluster.protocol.swim.probe - gateway - Failed to probe 2                                               java.net.ConnectException: Failed to connect channel for address 0.0.0.0:26502 (resolved: null) : io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: getsockopt: /0.0.0.0:26502                                            at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bootstrapClient$39(NettyMessagingService.java:753) ~[zeebe-atomix-cluster-8.5.1.jar:8.5.1]                                                                                     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]                                                                                                             at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]                                                                                                            at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]                                                                                                          at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]                                                                                                             at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]                                                                                                                   at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]                                                                                                                 at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]                                                                                                                  at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:326) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]                                                                              at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:342) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]                                                                                      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]                                                                                                               at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]                                                                                                     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]                                                                                                              at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.109.Final.jar:4.1.109.Final]                                                                                                                              at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]                                                                                                 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]                                                                                                                    at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]                                                       2024-05-22 17:15:13.171 [] [atomix-cluster-heartbeat-sender] [] INFO                                                          io.atomix.cluster.protocol.swim.probe - gateway - Failed all probes of Member{id=2, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAABAACAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAAwAAAUAAAA4LjUuMQUAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}. Marking as suspect.                                       2024-05-22 17:15:13.172 [] [atomix-cluster-heartbeat-sender] [] INFO                                                          io.atomix.cluster.protocol.swim - gateway - Member unreachable Member{id=2, address=0.0.0.0:26502, properties={brokerInfo=EADJAAAABAACAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkNAAAAMC4wLjAuMDoyNjUwMQUAAAwAAAUAAAA4LjUuMQUAAA==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}                                                                    2024-05-22 17:15:15.282 [] [atomix-cluster-heartbeat-sender] [] INFO                                                          io.atomix.cluster.protocol.swim - gateway - Member added Member{id=0, address=192.168.1.16:26502, properties={brokerInfo=EADJAAAABAAAAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkSAAAAMTkyLjE2OC4xLjE2OjI2NTAxBQABAQAAAAAMAAEBAAAAjAAAAAAAAAAFAAAAOC41LjEFAAEBAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}

**Comment by ahmedbeledy** [comment]
```shell

``` /
  ______  ______   ______   ____    ______      _____              _______   ______  __          __            __     __                                                                                            |___  / |  ____| |  ____| |  _ \  |  ____|    / ____|     /\     |__   __| |  ____| \ \        / /     /\     \ \   / /                                                                                               / /  | |__    | |__    | |_) | | |__      | |  __     /  \       | |    | |__     \ \  /\  / /     /  \     \ \_/ /                                                                                               / /   |  __|   |  __|   |  _ <  |  __|     | | |_ |   / /\ \      | |    |  __|     \ \/  \/ /     / /\ \     \   /                                                                                               / /__  | |____  | |____  | |_) | | |____    | |__| |  / ____ \     | |    | |____     \  /\  /     / ____ \     | |                                                                                               /_____| |______| |______| |____/  |______|    \_____| /_/    \_\    |_|    |______|     \/  \/     /_/    \_\    |_|                                                                                                                                                                                                                                                                                                                 2024-05-22 17:21:41.040 [] [main] [] INFO                                                                                                                                                                                io.camunda.zeebe.gateway.StandaloneGateway - Starting StandaloneGateway v8.5.1 using Java 21.0.3 with PID 29912 (C:\Users\ahmed.beledy\Downloads\camunda-zeebe-8.5.1\camunda-zeebe-8.5.1\lib\camunda-zeebe-8.5.1.jar started by ahmed.beledy in C:\Users\ahmed.beledy\Downloads\camunda-zeebe-8.5.1\camunda-zeebe-8.5.1\bin)                                                                                                    2024-05-22 17:21:41.047 [] [main] [] INFO                                                                                                                                                                                io.camunda.zeebe.gateway.StandaloneGateway - The following 1 profile is active: "gateway"                                                                                                                    2024-05-22 17:21:45.773 [] [main] [] INFO                                                                                                                                                                                org.springframework.boot.web.embedded.netty.NettyWebServer - Netty started on port 8080                                                                                                                      2024-05-22 17:21:45.890 [] [main] [] INFO                                                                                                                                                                                org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver - Exposing 12 endpoint(s) beneath base path '/actuator'                                                                                  2024-05-22 17:21:45.970 [] [main] [] INFO                                                                                                                                                                                org.springframework.boot.web.embedded.netty.NettyWebServer - Netty started on port 9600                                                                                                                      2024-05-22 17:21:45.993 [] [main] [] INFO                                                                                                                                                                                io.camunda.zeebe.gateway.StandaloneGateway - Started StandaloneGateway in 5.64 seconds (process running for 7.609)                                                                                           2024-05-22 17:21:46.005 [] [main] [] INFO                                                                                                                                                                                io.camunda.zeebe.gateway - Starting standalone gateway gateway with version 8.5.1                                                                                                                            2024-05-22 17:21:46.082 [] [netty-messaging-event-nio-server-0] [] INFO                                                                                                                                                  io.atomix.cluster.messaging.impl.NettyMessagingService - TCP server listening for connections on 192.168.1.3:26502                                                                                           2024-05-22 17:21:46.177 [] [netty-messaging-event-nio-server-0] [] INFO                                                                                                                                                  io.atomix.cluster.messaging.impl.NettyMessagingService - Started messaging service bound to [192.168.1.3:26502], advertising 192.168.1.3:26502, and using plaintext                                          2024-05-22 17:21:46.233 [] [netty-unicast-event-nio-client-0] [] INFO                                                                                                                                                    io.atomix.cluster.messaging.impl.NettyUnicastService - Started plaintext unicast service bound to 0.0.0.0:26502, advertising 192.168.1.3:26502                                                               2024-05-22 17:21:46.236 [] [atomix-cluster-0] [] INFO                                                                                                                                                                    io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Local node Node{id=gateway, address=192.168.1.3:26502} joined the bootstrap service                                                                 2024-05-22 17:21:46.241 [] [atomix-cluster-0] [] INFO                                                                                                                                                                    io.atomix.cluster.protocol.swim - Started                                                                                                                                                                    2024-05-22 17:21:46.242 [] [atomix-cluster-0] [] INFO                                                                                                                                                                    io.atomix.cluster.impl.DefaultClusterMembershipService - Started cluster membership service for member Member{id=gateway, address=192.168.1.3:26502, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}                                                                                                                                                                                                     2024-05-22 17:21:46.243 [] [atomix-cluster-0] [] INFO                                                                                                                                                                    io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService - Started                                                                                                                                2024-05-22 17:21:46.246 [] [atomix-cluster-0] [] INFO                                                                                                                                                                    io.atomix.cluster.messaging.impl.DefaultClusterEventService - Started                                                                                                                                        2024-05-22 17:21:46.405 [] [main] [] INFO                                                                                                                                                                                io.camunda.zeebe.gateway - Standalone gateway is started!                                                                                                                                                    2024-05-22 17:21:47.347 [] [atomix-cluster-heartbeat-sender] [] INFO                                                                                                                                                     io.atomix.cluster.protocol.swim - gateway - Member added Member{id=0, address=192.168.1.16:26502, properties={brokerInfo=EADJAAAABAAAAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkSAAAAMTkyLjE2OC4xLjE2OjI2NTAxBQABAQAAAAAMAAEBAAAAjAAAAAAAAAAFAAAAOC41LjEFAAEBAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}                                                                                               2024-05-22 17:21:48.385 [] [atomix-cluster-heartbeat-sender] [] INFO                                                                                                                                                     io.atomix.cluster.protocol.swim - gateway - Member added Member{id=1, address=192.168.1.13:26502, properties={brokerInfo=EADJAAAABAABAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkSAAAAMTkyLjE2OC4xLjEzOjI2NTAxBQAADAAABQAAADguNS4xBQAA, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}                                                                                                                               2024-05-22 17:21:51.523 [] [atomix-cluster-heartbeat-sender] [] INFO                                                                                                                                                     io.atomix.cluster.protocol.swim - gateway - Member added Member{id=2, address=192.168.1.14:26502, properties={brokerInfo=EADJAAAABAACAAAAAwAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGkSAAAAMTkyLjE2OC4xLjE0OjI2NTAxBQAADAAABQAAADguNS4xBQAA, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}

**Comment by ahmedbeledy** [comment]
logs of gateway after node 0 stop
![image](https://github.com/camunda/zeebe/assets/48006435/a9f24aff-fa9c-4903-802c-2ad2a72919f5)

**Comment by ahmedbeledy** [comment]
gateway config 

  gateway:
    cluster:
      #contactPoint: 127.0.0.1:26502
      host: 192.168.1.3
      initialContactPoints: [192.168.1.16:26502 , 192.168.1.13:26502  , 192.168.1.14:26502]
      port: 26502
    network:
      host: 0.0.0.0
      port: 26500

**Comment by ahmedbeledy** [comment]
@Zelldon

**Comment by Zelldon** [comment]
Hey @ahmedbeledy 

sorry but the provided screenshots are not really useful. I would need to see more than that. Furthermore, see my questions above https://github.com/camunda/camunda/issues/18583#issuecomment-2124771667 that haven't been covered yet.


I will close this issue as this is mostly investigating and troubleshooting and no actual issue to work on. Please raise your problem in the forum https://forum.camunda.io/ 

Make sure to provide as much as possible information, like configurations, logs (upload them directly, no screenshots), explain what your expectation is and your observation, etc.
