### ISSUE TITLE
POST backups endpoint fails with 403 when CSRF protection is enabled

### ISSUE THREAD

**Issue by matt-whiteman** [camunda/camunda#18588]
### Description

When CSRF protection is enabled (default) backup creating endpoint POST /actuator/backups/ is failing with 403 Forbidden.

Same problem with DELETE /actuator/backups/{id} endpoint.

Backup/restore test is failing with the same exception:
https://github.com/camunda/zeebe/actions/workflows/operate-test-backup-restore.yml
Error:  io.camunda.operate.qa.backup.BackupRestoreTest.testBackupRestore -- Time elapsed: 220.2 s <<< ERROR!
io.camunda.operate.exceptions.OperateRuntimeException: org.springframework.web.client.HttpClientErrorException$Forbidden: 403 : "<Map><timestamp>2024-05-16T05:17:50.492+00:00</timestamp><status>403</status><error>Forbidden</error><message>Forbidden</message><path>/api/process-instances</path></Map>"

### TODO

* Start Operate
* Try to call 
```
POST /actuator/backups/
{
    "backupId": 5
}
```

### Current behavior

Reponse is 
```
{
    "timestamp": "2024-05-22T14:23:13.817+00:00",
    "status": 403,
    "error": "Forbidden",
    "message": "Forbidden",
    "path": "/operate/actuator/backups"
}
```

### Expected behavior

Currently all our actuator endpoints should be available without authentication and authorization as it can be protected on transport layer (by restricting the management port access).

### Additional Information

* Versions affected: 8.5.1, 8.4.8, 8.6.1-alpha1
* The workaround is to disable CSRF: `CAMUNDA_OPERATE_CSRFPREVENTIONENABLED=false`
* Incident: https://camunda.slack.com/archives/C074H652CAH/p1716381922276239
* Tasklist seems to work fine

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by romansmirnov** [comment]
I just stumbled over this issue because I fixed a similar issue last week in the context of a single application, see #18568. To resolve that, I introduced a separate security filter chain that applies to the actuator endpoints: https://github.com/camunda/zeebe/blob/5a613271c3dc8ae2abfdc22b1a79f2c088fae812/dist/src/main/java/io/camunda/zeebe/shared/security/SecurityConfiguration.java#L42-L60 - That would allow to disable CSRF for the actuator endpoints.

Hopefully this helps.
