### ISSUE TITLE
Test `ZeebePartitionTest.shouldReportUnhealthyIfTransitionStepIsStuck` is unstable

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#18590]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 
   - Once
- Does it block your work?
  - No, but it decreases confidence in the CI. 
- Do we suspect that it is a real failure?
  - Not sure. 

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 23, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.838 s <<< FAILURE! -- in io.camunda.zeebe.broker.system.partitions.ZeebePartitionTest
Error:  io.camunda.zeebe.broker.system.partitions.ZeebePartitionTest.shouldReportUnhealthyIfTransitionStepIsStuck -- Time elapsed: 0.073 s <<< FAILURE!
java.lang.AssertionError: 

Expecting actual:
  "Transition from null on term 0 appears blocked, step null has been running for PT2M0.013S"
to contain:
  "Transition from FOLLOWER on term 0 appears blocked" 
	at io.camunda.zeebe.broker.system.partitions.ZeebePartitionTest.shouldReportUnhealthyIfTransitionStepIsStuck(ZeebePartitionTest.java:419)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

-  [Downloaded CI logs](https://drive.google.com/file/d/1W_ZsO04nsEU7qKXhsLkU9g-S2YzdzGt_/view?usp=sharing)

**Comment by koevskinikola** [comment]
The flakiness might be related to #13493

**Comment by rodrigo-lourenco-lopes** [comment]
It happend again here: https://github.com/camunda/camunda/actions/runs/9562045254/job/26357593164


[Unit Test Results (3).zip](https://github.com/user-attachments/files/15883531/Unit.Test.Results.3.zip)

**Comment by rodrigo-lourenco-lopes** [comment]
It happened again: https://github.com/camunda/camunda/commit/efbfaf4f5082e7c2a5fced8f46cec20ec4c657e8

**Comment by tmetzke** [comment]
Failed again: https://github.com/camunda/camunda/actions/runs/10175422059/job/28142931751

[Test results for unit tests.zip](https://github.com/user-attachments/files/16437787/Test.results.for.unit.tests.zip)

**Comment by rodrigo-lourenco-lopes** [comment]
This hopefully was resolved by https://github.com/camunda/camunda/pull/21043, will close for now.
