### ISSUE TITLE
[Stable/8.5] add dummy workflow for CI

### ISSUE THREAD

**Issue by nicpuppa** [camunda/camunda#18718]
**Describe the bug**

In order to unblock CI not related to Zeebe project (eg Spring SDK) we need to add a dummy workflow that only complete successfully the `Test Summary`, according to the [branch protection rule settings](https://github.com/camunda/zeebe/settings/branch_protection_rules/48749287)

**Comment by ana-vinogradova-camunda** [comment]
Closing the issue as the PR is already merged.
