### ISSUE TITLE
when bpmn diagram has two process in different pools only relevant process should be displayed

### ISSUE THREAD

**Issue by esraagamal6** [camunda/camunda#18723]
### Describe the bug
When  we have a bpmn diagram with two process, on opening the process view, we should display only the process which is containing the task since each of them has it's own process ID

### To Reproduce

1. Deploy a bpmn diagram with two processes each in a separate pool Process A and Process B
2. On tasklist start process A
3. Open the created task details and navigate to process tab

https://github.com/camunda/zeebe/assets/129334285/086efa0f-daaa-4e81-b06d-bc9691a0fa38

![Screenshot 2024-05-22 at 12 55 10 PM](https://github.com/camunda/zeebe/assets/129334285/0b633583-93e1-4dcb-ba29-b0fec329a8c0)

### Actual behavior
Process A and Process B are displayed

### Expected behavior
Only process A is displayed since  can set read permission for only one of them

### Environment

- Tasklist Version: tasklist/17645-process-view

### Additional context

BPMN diagram to test with:
[two processes copy.bpmn.zip](https://github.com/camunda/zeebe/files/15403857/two.processes.copy.bpmn.zip)

relates to https://github.com/camunda/zeebe/issues/17643

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by marcosgvieira** [comment]
We don't support having two start events.
