### ISSUE TITLE
Operate: address CodeQL security findings

### ISSUE THREAD

**Issue by matt-whiteman** [camunda/camunda#18741]
### Description

There are 5 CodeQL findings in operate codebase that need to be addressed, either with code changes or dismissing the alert after analyzing it.

Deserialization of user-controlled data  (Critical, prod code)
operate/webapp/src/main/java/io/camunda/operate/webapp/rest/dto/listview/SortValuesWrapper.java:63
https://github.com/camunda/zeebe/security/code-scanning/4944

Implicit narrowing conversion in compound assignment  (High, test code)
operate/qa/integration-tests/src/test/java/io/camunda/operate/zeebeimport/FlowNodeInstanceZeebeImportIT.java:191
https://github.com/camunda/zeebe/security/code-scanning/5240

Implicit narrowing conversion in compound assignment  (High, test code)
operate/qa/integration-tests/src/test/java/io/camunda/operate/zeebeimport/FlowNodeInstanceZeebeImportIT.java:177
https://github.com/camunda/zeebe/security/code-scanning/5239

Disabled Spring CSRF protection (High, prod code)
operate/importer/src/main/java/io/camunda/operate/zeebeimport/security/DefaultWebSecurityConfig.java:28
https://github.com/camunda/zeebe/security/code-scanning/4946

Disabled Spring CSRF protection (High, prod code)
operate/archiver/src/main/java/io/camunda/operate/archiver/security/DefaultWebSecurityConfig.java:28
https://github.com/camunda/zeebe/security/code-scanning/4945

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by matt-whiteman** [comment]
One note on the deserialization issue:

When we get a page of data from Elasticsearch, it returns a sortValue field that is used as a reference in the next request to retrieve the next page of data. This is an Object array, which contains values that generally are an ID, though it can be whatever type was sorted on (String, Integer, etc). This information is stored in a SortValueWrapper which converts the value to a string and stores the class type, this sortValueWrapper is part of several different DTOs. 

https://github.com/camunda/zeebe/blob/6145ac280995d7f26006cf3f45845709fa62ed0a/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/dto/listview/SortValuesWrapper.java#L46

Later, when the subsequent DTO request is processed and converted to an Elasticsearch request, the SortValueWrapper is converted back to an Object array, which requires the objectMapper to use the serialized string and class type stored in the SortValueWrapper, which is what codeQL is complaining about:

https://github.com/camunda/zeebe/blob/6145ac280995d7f26006cf3f45845709fa62ed0a/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/dto/listview/SortValuesWrapper.java#L63

The DTOs appear to only be part of the internal APIs and not the public APIs, so any changes would not necessarily impact customers. Questions:
- Would it be possible to remove the SortValueWrapper serialization and deserialization and just use the raw searchBefore/searchAfter object array?
- If refactoring is not feasible, then analysis on the existing code needs to be done. The core issue that causes this to be flagged is that the input can theoretically set any class type in this SortValueWrapper. What needs to be answered is, is it possible to inject a malicious class type and specify that class on the input and cause the deserialization to execute malicious or arbitrary code?

**Comment by kristinkomschow** [comment]
> Possible short-term fix: #18779 for the issue flagged Critical (untrusted deserialization). This would need to be backported to all supported versions.
> 
> Please check with @ralfpuchert and @sdorokhova as they may have the most context knowledge about elasticsearch/opensearch and are the team's security champions
> 
> Note: The fix would not prevent CodeQL from flagging the code with the same vulnerability, it would need to be dismissed manually as 'false positive' assuming our analysis concludes it is safe.

This fix has been approved and will be merged. The CodeQL flag has been dismissed as 'false positive'
I created a separate issue for backporting the fix: https://github.com/camunda/camunda/issues/18862

**Comment by johanwelgemoed** [comment]
@kristinkomschow Is it only the critical issues that got fixed? ie. rest still open?

**Comment by matt-whiteman** [comment]
> @kristinkomschow Is it only the critical issues that got fixed? ie. rest still open?

@johanwelgemoed @kristinkomschow Of the remaining related to operate, two are for test code and very minor, the other are because we disable CSRF intentionally in certain configurations. Assuming the intent is correct, they can just be manually dismissed as false positives.

**Comment by kristinkomschow** [comment]
I'd only looked at the Deserialization so far and had assigned this to me when I did that. @matt-whiteman if you have capacity, feel free to take this issue over.

**Comment by ThorbenLindhauer** [comment]
* I have dismissed the two findings for the tests, they are not problematic
* About the web app configurations:
  * We disable CSRF protection for actuator endpoints, when the importer or archiver are deployed in standalone mode without the webapp backend (see the [condition](https://github.com/camunda/camunda/blob/ad3707c49855c80ebb5429541cd07052cb310385/operate/importer/src/main/java/io/camunda/operate/zeebeimport/security/DefaultWebSecurityConfig.java#L22) on a `webSecurityConfig` bean and the [corresponding bean in the webapp backend](https://github.com/camunda/camunda/blob/ad3707c49855c80ebb5429541cd07052cb310385/operate/webapp/src/main/java/io/camunda/operate/webapp/security/WebSecurityConfig.java#L25))
  * CSRF is only relevant for browser-based access, for which these actuator endpoints are not relevant; the browser will always use the V1 REST API and not have access to a standalone importer/archiver node
  * Accordingly, it is fine that CSRF protection is disabled in these cases. I am dismissing the two findings.

As the deserialization bug has been fixed and the other findings dismissed, I am closing the ticket.
