### ISSUE TITLE
Pre-select target proceess versions in instance migration mode

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#18761]
### Description
Target process versions should be pre-selected in instance migration view, because in most cases users want to migrate to the next version of the same process.

See slack discussion: https://camunda.slack.com/archives/C061QD0H6DS/p1716450868113569

### User Story

```Gherkin
Scenario: As an Operate user
    Given I am in instances list view
    Given I selected a process with at least 3 version (i.e. complexProcess from demo data)
    Given I selected version 1
    Given I selected a process instance and clicked "Migrate" button
    When I enter instance migration mode
    Then I can see that a target process is pre-selected (same as source process)  
    Then I can see that a target version is pre-selected (latest available versions)
```

#### Target dropdowns
- [ ] The target process is pre-selected when there is more than one version available
- [ ] The target version is pre-selected to the latest available version
- [ ] The target version is only pre-selected when later versions are available
- [ ] When no other versions of the source process are available, no process is pre-selected
- [ ] When no later versions of the source process are available, no version is pre-selected

#### Target diagram
- [ ] The target diagram is loaded and visible when both target process and version are pre-selected in the dropdowns

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [x] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by Szik** [comment]
Tests according to "User Story" and "Acceptance Criteria" have passed.

Minor issue: the point in "Acceptance Criteria":
"When no other versions of the source process are available, no process is pre-selected"
Specification for what these other versions are in this condition should be clarified.
