### ISSUE TITLE
Can't install latest go client

### ISSUE THREAD

**Issue by akkie** [camunda/camunda#18795]
**Description**

It's not possible to install the latest go client.

Steps to reproduce:
```
go mod init example/hello
go get github.com/camunda/camunda/clients/go/v8
```

Output:

```
go: downloading github.com/camunda/camunda v0.0.0-20240524071313-2c67cd01f665
go: downloading github.com/camunda/camunda/clients/go v1.3.14
go: downloading github.com/camunda/camunda/clients/go/v8 v8.5.1
go: github.com/camunda/camunda/clients/go/v8@upgrade (v8.5.1) requires github.com/camunda/camunda/clients/go/v8@v8.5.1: parsing go.mod:
	module declares its path as: github.com/camunda/zeebe/clients/go/v8
	        but was required as: github.com/camunda/camunda/clients/go/v8
```

**Comment by Zelldon** [comment]
Thanks @akkie please still use the old module name. Even when the renaming is already done, just realized that the modules are still available under the old name (which makes sense, as they have been released with that name). This means a module with the new name will be released as soon we create a new tag/release.

**Comment by npepinpe** [comment]
@Zelldon I'm assigning to you as you're already working on this.

**Comment by Zelldon** [comment]
Hey @akkie 

sorry for the confusion around the module name change. I have investigated this further, and realized that this is actually not an issue.

What you have to do is to still use the old module name, like `go get github.com/camunda/zeebe/clients/go/v8@v8.5.1`

As GitHub will resolve the old name (via redirects), and the old tags/version still contain the old module name. In this regard nothing has changed for now. On new released versions you have to use the new module name, but until a release is out you can keep the old module name.

I hope this helps.
