### ISSUE TITLE
Filtering tasks by process retrieves only tasks from latest deployed process version

### ISSUE THREAD

**Issue by esraagamal6** [camunda/camunda#18813]
### Describe the bug
When having multiple versions of a process, only tasks from latest versions are retrieved on filtering by process name in the custom filters

### To Reproduce

1. Deploy a process with userTask
2. Start the process
3. Re-deploy the process with making an update (ex: update task name)
4. Run the re-deployed process
5. Open tasklist custom filters and filter by the deployed process name

https://github.com/camunda/camunda/assets/129334285/1f534a74-884c-4e47-81ce-1bd0c8f719d0

### Actual behavior
Only task from version2 is retrieved

### Expected behavior
Tasks from version 1 and version 2 are retrieved

### Environment

- Tasklist Version: 8.5.0

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by volodymyr-melnykc** [comment]
Since the endpoint `/v1/internal/processes` returns only the latest process version, as of now we'll be explicit in the filter dialog and update the header text for the dropdown with processes to state that filtered tasks will be related to the latest version.

![image](https://github.com/camunda/camunda/assets/143816833/cc02368e-9402-409a-964c-fa271d45feb2)
