### ISSUE TITLE
CI build failed on protocol reading due to lock

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#18821]
## Description

[Merge build failed](https://github.com/camunda/camunda/actions/runs/9226120982/job/25385192985) with obscure error:

```
  Failed to execute goal com.salesforce.servicelibs:proto-backwards-compatibility:1.0.7:backwards-compatibility-check (default) on project zeebe-gateway-protocol: An error occurred while running protolock: Cannot run program "/home/runner/work/camunda/camunda/zeebe/gateway-protocol/target/protolock-bin/protolock" (in directory "/home/runner/work/camunda/camunda/zeebe/gateway-protocol"): error=26, Text file busy -> [Help 1]
Error:  
```

Looks like there were multiple builds referencing the same file?

**Comment by npepinpe** [comment]
ZDP Triage:
- So far only seen it once.
- Leave in the backlog unless it happens more often and blocks us.

**Comment by deepthidevaki** [comment]
Happened again https://github.com/camunda/camunda/actions/runs/9360843730/job/25766841876 
```
Failed to execute goal com.salesforce.servicelibs:proto-backwards-compatibility:1.0.7:backwards-compatibility-check (default) on project zeebe-gateway-protocol: An error occurred while running protolock: Cannot run program "/runner/_work/camunda/camunda/zeebe/gateway-protocol/target/protolock-bin/protolock" (in directory "/runner/_work/camunda/camunda/zeebe/gateway-protocol"): error=26, Text file busy -> [Help 1]
```

**Comment by korthout** [comment]
ZPA triage:
- We'll put it in our backlog for same reason as ZDP
- Please comment if this occurs again

**Comment by sdorokhova** [comment]
Happened again: https://github.com/camunda/camunda/actions/runs/9842149374/job/27170461841
```
 Failed to execute goal com.salesforce.servicelibs:proto-backwards-compatibility:1.0.7:backwards-compatibility-check (default) on project zeebe-gateway-protocol: An error occurred while running protolock: Cannot run program "/home/runner/work/camunda/camunda/zeebe/gateway-protocol/target/protolock-bin/protolock" (in directory "/home/runner/work/camunda/camunda/zeebe/gateway-protocol"): error=26, Text file busy -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.salesforce.servicelibs:proto-backwards-compatibility:1.0.7:backwards-compatibility-check (default) on project zeebe-gateway-protocol: An error occurred while running protolock
<..>
Caused by: java.io.IOException: Cannot run program "/home/runner/work/camunda/camunda/zeebe/gateway-protocol/target/protolock-bin/protolock" (in directory "/home/runner/work/camunda/camunda/zeebe/gateway-protocol"): error=26, Text file busy
```

**Comment by npepinpe** [comment]
So `Text file busy` in Linux (I guess maybe Unix in general?) occurs when a process is trying to modify an executable that is currently running. So it's likely something to do with concurrent access - maybe the plugin is trying to download the executable while it's also running?

That said, the plugin seems largely unmaintained. I wonder if we shouldn't just move that step to use protolock directly in GHA (so not in the Maven pipeline, but part of CI), or migrate to the [buf CLI which has a lot more features anyway](https://buf.build/docs/breaking/overview#defaults-and-configuration).

**Comment by Zelldon** [comment]
https://github.com/camunda/camunda/actions/runs/10561422487/job/29257143645

```
Caused by: java.io.IOException: Cannot run program "/runner/_work/camunda/camunda/zeebe/gateway-protocol/target/protolock-bin/protolock" (in directory "/runner/_work/camunda/camunda/zeebe/gateway-protocol"): error=26, Text file busy 
```

**Comment by npepinpe** [comment]
I'm on it, don't pressure me :see_no_evil:

**Comment by Zelldon** [comment]
Again https://github.com/camunda/camunda/actions/runs/10576761042/job/29303278815

**Comment by lenaschoenburg** [comment]
Actually only closed by https://github.com/camunda/camunda/pull/21616, not yet resolved.
