### ISSUE TITLE
io.camunda.zeebe.engine.processing.bpmn.subprocess.MultipleEventSubprocessTest.shouldInterruptOtherActiveEventSubprocess is flaky

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#18861]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? no
- Do we suspect that it is a real failure? not sure

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.253 s <<< FAILURE! -- in io.camunda.zeebe.engine.processing.bpmn.subprocess.MultipleEventSubprocessTest
Error:  io.camunda.zeebe.engine.processing.bpmn.subprocess.MultipleEventSubprocessTest.shouldInterruptOtherActiveEventSubprocess -- Time elapsed: 5.156 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 
[Expected service task after timer start event to exist] 
Expecting value to be true but was false
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at io.camunda.zeebe.engine.processing.bpmn.subprocess.MultipleEventSubprocessTest.shouldInterruptOtherActiveEventSubprocess(MultipleEventSubprocessTest.java:79)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Logs**

Downloaded logs [link](https://drive.google.com/drive/folders/1T6K5GRliL3LADm6Xnt4lMdEdJV4B8TfR)

**Comment by korthout** [comment]
This test travels through time more than 5 seconds, making it a possible case that can be fixed by:
- #18508

This run did not yet have that fix yet though:
- this test run: 7bd45afb08d5aa397ddee0a6dab896f9fcacaa84
- the fix: 3cf914c

As that fix is now merged to main. I'm closing this issue as resolved. Please re-open when you encounter it again.

**Comment by korthout** [comment]
@berkaycanbc The following can help the investigation when reporting flaky tests:
- link [the failed workflow run](https://github.com/camunda/camunda/actions/runs/9229744993) in which the test was flaky, makes it easier to find the exact commit
- Download the test results artifact (from the workflow run) and upload those to Google Drive to provide more detailed logs from the exact test cases/runs
<img width="1357" alt="Screenshot 2024-05-28 at 18 36 57" src="https://github.com/camunda/camunda/assets/3511026/d3fd2639-6b5f-448a-92b1-261874b26ed0">
