### ISSUE TITLE
Copy business logic for `list-view` index from importer to exporter

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#18908]
### Description

As a continuation for #18886 we need to copy all importer logic to corresponding `ExportHandlers`.

### TODO

* move logic from `ListViewZeebeRecordProcessor` (latest from `importer-8_6` module) to several corresponding `ExportHandlers` (e.g. `ListViewFromIncidentHandler`, `ListViewFromVariableHandler` etc.)

### AT

* when creating the process instance with variable, with incident, all the necessary data is exported to Operate `list-view` index

### Additional Information

* check `ProcessHandler` as an example

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by mihail-ca** [comment]
Hello @sdorokhova I am not sure where to copy this block from ListViewZeebeRecordProcessor (https://github.com/camunda/camunda/blob/main/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java#L162)
<img width="415" alt="image" src="https://github.com/camunda/camunda/assets/122792941/d22c4bf1-f2a5-4554-aca7-f54549275360">

Any ideas ? Thank you.

**Comment by sdorokhova** [comment]
Hi @mihail-ca , yes, in general we need to copy that. This is important for the transition period, when both importer and exporter may run for some time together. The idea is that we don't want exporter and importer to process earlier records, when later were already processed. Though I see that it will involve additional effort to also move the logic to read `concurrencyMode` flag from Elastic. I propose to hardcode `false` for now and I will create an issue to work on concurrency mode separately. Sounds ok?

@matt-whiteman fyi

**Comment by mihail-ca** [comment]
Hello @sdorokhova for the following cases, I am not sure how to port from Importer to Exporer:

`ListViewFromVariableHandler` based on `processVariableRecords()` method (https://github.com/camunda/camunda/blob/main/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java#L180)
The method `processVariableRecords() `handles multiple variables at once, which seem to be related, whereas the Handler in exporter only supports a single variable at once

`ListViewFromProcessInstanceHandler` based on `processProcessInstanceRecord()` method (https://github.com/camunda/camunda/blob/main/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/ListViewZeebeRecordProcessor.java#L238)
The method `processProcessInstanceRecord() `
- handles multiple records at once
- has additional parameter ImportBatch
- updated multiple types of entities (ProcessInstance and FlowNode)
- updates operations via OperationManager

So I am not sure how to port these two cases. Any hints ? Thank you.

**Comment by sdorokhova** [comment]
Hi @mihail-ca , will try to address your questions:
1) 
> The method processVariableRecords() handles multiple variables at once, which seem to be related, whereas the Handler in exporter only supports a single variable at once.
> The method processProcessInstanceRecord() 
> handles multiple records at once

This we already discussed this with Matt, I will simply copy what I wrote him:

regarding the grouping, this was some performance optimization in importer. So that if in one batch we get several records for one and the same variable, we first "accumulate" all changes in one entity and only at the end execute [upsert](https://github.com/camunda/camunda/blob/95e929f1720cb99cb0199e5cd9c41a4d6f695407/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/VariableZeebeRecordProcessor.java#L97).
As for additional grouping by scope, this is important for variables as they can't be identified by only name. There may be several variables with one name in one process definition, but assigned to different scopes. Just in case you're not familiar with that you can check [the docs](https://docs.camunda.io/docs/1.3/components/concepts/variables/#variable-scopes).
That's why we first group by scope, and for each scope we group by name in temporaryVariableCache.
In case of exporter we don't need all this, as this "accumulating" behavior is implemented by `ExportBatchWriter`  in `cachedEntities` field [here](https://github.com/camunda/camunda/pull/18886/files#diff-daf7ecae6282e9f542d58a035acb19b9140bd0284d290dc6c81283b5036dc0eeR34). So the handler must be all simple, just update all necessary fields in the entity which will be then put or updated in cache.

2)
> The method processProcessInstanceRecord() has additional parameter ImportBatch

This I would need to check separately. This affect the usage metrics. Looks like we will need to record them differently 🤔 

3) 
> updated multiple types of entities (ProcessInstance and FlowNode)

This means that we would need to have 2 handlers: `ListViewFromProcessInstanceHandler` and `FlowNodeInstanceFromProcessInstanceHandler`.

4) 

>The method processProcessInstanceRecord() updates operations via OperationManager

Here we have 2 ways. Either we copy the full logic that we have now to exporter and later adjust it to avoid reading of operations [here](https://github.com/camunda/camunda/issues/18372) or we leave the TODO item with the proper comment.
