### ISSUE TITLE
Copy business logic for `sequence-flows`, `user-task` and `variable` indices from importer to exporter

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#18915]
### Description

As a continuation for https://github.com/camunda/camunda/pull/18886 we need to copy all importer logic to corresponding `ExportHandlers`.

### TODO

* copy logic from `SequenceFlowZeebeRecordProcessor`, `UserTaskZeebeRecordProcessor` and `VariableZeebeRecordProcessor` (latest version from importer-8_6 module) to several corresponding `ExportHandlers`

### Additional Information

* check `ProcessHandler` as an example

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by matt-whiteman** [comment]
Issue with UserTaskZeebeRecordProcessor. In the existing logic, we examine the Intent to determine whether to insert or update a UserTask. The Intent is only available in the original record and is not stored in the created entity. The new ExportHandler flow does not include the original Record when the updateEntity() function is called, so we lose the ability to tell there whether we need to follow the insert or update logic, each of which involves updating different fields and doing different types of saves.

- Do we only create new user task entities and not port any of the update logic? That feels like we are leaving out a lot and if so, where is that update going to be handled?
- Does that mean in handlesRecord() we only accept records with CREATE_STATE.CREATED and throw out all other records (including any with UPDATE_STATES)?
- It feels like we need to split CREATE and UPDATE into separate handlers possibly, but the new pattern always requires creation of a new entity object so UPDATE would still not be handled properly it seems.

**Comment by sdorokhova** [comment]
Hey @ralfpuchert , one question about user task import. Is it actually important [to check the intent](https://github.com/camunda/camunda/blob/9e5f5fbe07bd9b4de50a0b7a6fd1baded67d2787/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/UserTaskZeebeRecordProcessor.java#L145-L150) and either `addWithId` or `upsert`? Can't we always upsert?

**Comment by matt-whiteman** [comment]
SequenceFlowZeebeRecordProcessor and VariableZeebeRecordProcessor have had their logic ported and merged into the exporter feature branch. UserTaskZeebeRecordProcessor cannot be ported until above issue is addressed.

**Comment by ralfpuchert** [comment]
> Hey @ralfpuchert , one question about user task import. Is it actually important [to check the intent](https://github.com/camunda/camunda/blob/9e5f5fbe07bd9b4de50a0b7a6fd1baded67d2787/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/UserTaskZeebeRecordProcessor.java#L145-L150) and either `addWithId` or `upsert`? Can't we always upsert?

The `BatchRequest::upsert` implementation use this:

The `UpdateRequest::upsert` method specifies the document to be inserted if it doesn't exist, while the `UpdateRequest::doc` method specifies the fields to be updated if the document already exists (https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-document-update.html):

```java
 .doc(objectMapper.readValue(
      objectMapper.writeValueAsString(updateFields), HashMap.class)) 
 .upsert(objectMapper.writeValueAsString(entity), XContentType.JSON));
```
So I think we can use always `BatchRequest::upsert`

**Comment by sdorokhova** [comment]
@matt-whiteman so according to Ralf's answer, we don't really need to pass and check the intent, but simply update the fields (and later upsert)

**Comment by matt-whiteman** [comment]
@sdorokhova There is one additional unknown that should be mentioned: The existing logic in UserTaskZeebeRecordProcessor uses an object mapper to serialize the variables from the record into a string. It looks like it specifically wants the operate object mapper injected via spring. I can create a default object mapper, but it won't have any custom modules registered (like date/time ones). This is also one of those areas that can be a potential performance issue in the future.

**Comment by matt-whiteman** [comment]
@sdorokhova @ralfpuchert  I'm not sure upsert still fits into this new pattern. The reason we check the intent is to then determine which fields are updated and specified as part of upsert: https://github.com/camunda/camunda/blob/9e5f5fbe07bd9b4de50a0b7a6fd1baded67d2787/operate/importer-8_6/src/main/java/io/camunda/operate/zeebeimport/processors/UserTaskZeebeRecordProcessor.java#L46

Multiple maps are checked that specify the fields to update based on the intent, some of these maps return single fields and others return tuples. Either way, we don't have a way to correlate these fields in flush(): We can't retrieve the intent when already in flush() to build the list of updated fields, and we can't persist the collection of updated fields in update() to use later in flush.

Are you sure we don't want to just use addWithId(), will that overwrite the existing entity if the id is specified?

**Comment by ralfpuchert** [comment]
Regarding to [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html)

> Adds a JSON document to the specified data stream or index and makes it searchable. If the target is an index and the document already exists, the request updates the document and increments its version.

the existing entity will be overwritten.

**Comment by matt-whiteman** [comment]
Discussed with @ThorbenLindhauer and the decision is we will use upsert and pass in a map of all entity fields
