### ISSUE TITLE
C8 License - Add new properties to License Generator and Checker

### ISSUE THREAD

**Issue by matthewBearCamunda** [camunda/camunda#18968]
## Related to

Epic: https://github.com/camunda/product-hub/issues/2359

## Overview

Two new properties need to be added for a C8 License when a license is being generated, `startDate` and `licenseType`.

The new fields will need to be read by the license checker and outputted when validation occurs. The `startDate` field is not taken into account when determining license validity 

- `startDate` - will be set to either the creation timestamp of the license OR a passed in date
- `licenseType` - will be set to `production` for now when generating, but will likely have different values over time
  - A getter for license type will also need to be implemented for the checker

## Actions

- A license key can be generated with two new properties, `startDate` and `licenseType`
- A generated license with the new properties can be read by the license checker
- A C8 License will output validity and license properties when validation occurs

**Links**

- https://github.com/camunda/camunda-license-check
- https://github.com/camunda/camunda-license-generator

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-license-check/pull/32
- [ ] https://github.com/camunda/camunda-license-generator/pull/37
```

**Comment by matthewBearCamunda** [comment]
@ultraschuppi 

When a license is generated as `unlimited`, does this only affect the `validUntil` check? Or would it affect the new `startDate` check as well?

In other words, does an `unlimited` license also have an 'unlimited' start date?

**Comment by tasso94** [comment]
Hi @matthewBearCamunda,

I just tried out your changes in C7, and our tests fail since old license keys don't have the now expected new property `startDate`, which leads to the following exception:

```
org.camunda.bpm.licensecheck.InvalidLicenseException: License Key has wrong format.

	at org.camunda.bpm.licensecheck.LicenseKeyImpl.parseProperties(LicenseKeyImpl.java:280)
	at org.camunda.bpm.licensecheck.LicenseKeyImpl.<init>(LicenseKeyImpl.java:56)
```

What is the migration journey here for existing Camunda 7 customers? Do we need to reissue new licenses for all of them?

You can find our tests here: https://github.com/camunda/camunda-bpm-platform-ee/tree/master/webapps/camunda-webapp/plugins/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/license

Best,
Tassilo

**Comment by matthewBearCamunda** [comment]
@tasso94 - Thanks for letting me know about that! I just pushed a change so that the checker will be able to handle those existing C7 keys (the ones without `startDate`). I tested with some of the keys used in the tests you linked, and the the checker was able to correctly validate them

**Comment by matthewBearCamunda** [comment]
Changes to the license checker and license generator are both complete. This ticket can be marked as Done
