### ISSUE TITLE
Add gateway endpoints for exporter enable request

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#19022]
Ref https://github.com/camunda/camunda/issues/18421 

Similar to disable endpoint we will provide a `POST actuator/exporters/{exporterId}/enable`

**Comment by deepthidevaki** [comment]
While writing integration test for this, I observed one issue. When there are no exporters enabled/configured `ExporterDirector` closes itself. When we disable the only existing exporter, `ExporterDirector` will be closed. When we re-enable it, it wouldn't resume exporting because `ExporterDirector` is not restarted until a role change which might not happen for a long time.

I see two options to solve this.
1. `PartitionManager` re-installs `ExporterDirector` if the state changed from 0 exporters to 1 exporter. However, this is a bit complex especially to coordinate with any concurrent role transitions that may also re-installs the ExporterDirector.
2. `ExporterDirector` never closes if there are no exporters configured. The problem here is it might be doing some unnecessary works like periodically distributing the exporter positions, reads logstream when ever a commit is notified etc. To address this, instead of closing the `ExporterDirector` we can move it to an "idle" state. In the `idle` state the actor is not closed, but it is not actively doing anything. That means it should stop the distribution, or reacting to commit notification. When a new exporter is added, it should switch from idle state to active and restart all necessary services to resume exporting.

I think option 2 seems reasonable. It is easy to implement. I also think the overhead caused by an idle actor is negligible. What do you think @npepinpe

**Comment by npepinpe** [comment]
Option 2 sounds good :+1:
