### ISSUE TITLE
Authorized pull requests are no longer auto-merged

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#19059]
**Description**

Since the repo rename, authorized pull requests (those authored by @backport-action or `renovate[bot]` or @camundait, are no longer auto approved/merged.

The problem is that condition specifically refers to `camunda/zeebe` rather than the new `camunda/camunda`.

https://github.com/camunda/camunda/blob/c4b8287ff3953aefbafd6a189aa39f24200099fd/.github/workflows/zeebe-ci.yml#L731-L737

**Comment by korthout** [comment]
I believe we need to backport:
- https://github.com/camunda/camunda/pull/18507

@cmur2 @lenaschoenburg Do you agree?

**Comment by cmur2** [comment]
> @cmur2 @lenaschoenburg Do you agree? Or do you see any issues with backporting this?

Makes sense from my POV 👍🏼

**Comment by npepinpe** [comment]
Can we mark this as done? It seems everything was backported?

**Comment by korthout** [comment]
Yes, I believe so. Thanks for noting
