### ISSUE TITLE
Operate Webjar CI build failed due to Node.js download error

### ISSUE THREAD

**Issue by cmur2** [camunda/camunda#19085]
## Description

[`main` branch build failed](https://github.com/camunda/camunda/actions/runs/9316608213/job/25645751227) with error:

`Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-yarn (install node and yarn) on project operate-webjar: Could not download Node.js: Could not download https://nodejs.org/dist/v20.12.2/node-v20.12.2-linux-x64.tar.gz: Premature end of Content-Length delimited message body (expected: 46,672,067; received: 26,673,152) -> [Help 1]`

or

`Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-yarn (install node and yarn) on project operate-webjar: Could not download Node.js: Got error code 520 from the server. -> [Help 1]`

This comes from the https://github.com/eirslett/frontend-maven-plugin downloading a copy of Node.js on-the-fly during a build. This is prone to network problems or problems with the download server leading to build failures.

### Examples of failed builds

* https://github.com/camunda/camunda/actions/runs/9316608213/job/25645751227 on `main` branch
* https://github.com/camunda/camunda/actions/runs/9314496869/job/25639151022 on `main` branch
* https://github.com/camunda/camunda/actions/runs/9314140725/job/25638072062 on `main` branch
* https://github.com/camunda/camunda/actions/runs/9642580509/job/26590748987 in merge queue

### Impact

As mentioned in https://github.com/eirslett/frontend-maven-plugin/pull/1098 the Node.js download server is known to be unreliable. This leads to build failures in the monorepo CI impacting potentially all developers that want to build Operate (or other frontends).

#### Possible solutions

* using GitHub cache
* using retries in case of network errors:
    * the chosen Maven plugin does not have an option to retry failing downloads: https://github.com/eirslett/frontend-maven-plugin/pull/1098

**Comment by ThorbenLindhauer** [comment]
Moving back to backlog. Added it to a [list of tickets that I will consider for mid-term prioritization](https://github.com/camunda/camunda/labels/operate%3Aprioritized-backlog).

**Comment by korthout** [comment]
Same as last week, prevented to complete the deployment of all snapshot artifacts: https://github.com/camunda/camunda/actions/runs/10165148268/job/28112887150

**Comment by ana-vinogradova-camunda** [comment]
Happened again:

```
Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-yarn (install node and yarn) on project client: Could not download Node.js: Could not download https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-x64.tar.gz: Premature end of Content-Length delimited message body (expected: 46,459,247; received: 1,777,664) -> [Help 1]
```

Build: https://github.com/camunda/camunda/actions/runs/10318089419/job/28563721384

**Comment by korthout** [comment]
Happened again in [`Deploy snapshot artifacts`](https://github.com/camunda/camunda/commit/91df4cb77b1f433c7730aec8bc23da6463e85b56):
> Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-yarn (install node and yarn) on project operate-webjar: Could not download Node.js: Got error code 522 from the server. -> [Help 1]

Different error code 522 instead of 520.

**Comment by cmur2** [comment]
Happened today in the morning in https://github.com/camunda/camunda/actions/runs/10383537404/job/28749481656 with `Could not download Node.js: Could not download https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-x64.tar.gz: Premature end of Content-Length delimited message body (expected: 46,459,247; received: 1,081,344)`
