### ISSUE TITLE
Daily release dry run on stable branches is not running 

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#19092]
**Describe the bug**
https://github.com/camunda/camunda/actions/workflows/zeebe-release-stable-dry-run.yml

The last successful run was on May 22nd, probably coinciding with the repo rename.

**Comment by npepinpe** [comment]
ZDP Triage:
- I will leave this as an open topic for the medic :)

**Comment by korthout** [comment]
ZPA triage:
- medic is planning to work on this
- if not, ZPA still wants to track this issue, and prioritizes it as upcoming

**Comment by lenaschoenburg** [comment]
Fixed by https://github.com/camunda/camunda/pull/19206
