### ISSUE TITLE
[CPT] I can assert the process flow

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#19175]
## Description

In Camunda Process Test, I want to write a process test and verify that the process took the expected path. Take inspiration from [zeebe-process-test](https://docs.camunda.io/docs/apis-tools/java-client/zeebe-process-test/#assertions). 

## Tasks
- Assert that a process is deployed
- Assert that a process instance is active/completed/terminated
- Assert that an element of a process instance is active/completed/terminated (a given number of times)
- Assert that a user task has a given property (e.g. an assignee)
- Assert that a variable of a process instance exists and has a given value
- Assert that an incident is created/resolved
- Handle the asynchronous nature of the Camunda engine transparently 

requires #18997

**Comment by korthout** [comment]
@saig0 I remember you told me you want to build this using the available APIs. Does this somehow depend on:
- https://github.com/camunda/product-hub/issues/2041?

**Comment by saig0** [comment]
@korthout in general, CPT depends on the API. We could use the GET endpoints in some cases instead of the search API. 

However, for the first iteration, we will use what is currently available. So, we are not blocked by the GET endpoints.

**Comment by saig0** [comment]
We implemented the basic assertions for the process instance state, the element instance state, and variables. 

Let's close the issue and create follow-up issues for the other assertions.
