### ISSUE TITLE
Move Operate importer tests into nightly job

### ISSUE THREAD

**Issue by matt-whiteman** [camunda/camunda#19186]
### Description

Move all the long-running Operate integration tests dealing with the importer into a nightly job rather than run on every PR.

This involves renaming existing ITs to follow a unique naming pattern that can be picked up by a maven profile: *ZeebeImportIT

Create a new maven profile to run only these ITs: operateImportIT

Create a new workflow file to run these ITs once at night, see backup/restore tests and other nightly jobs for examples

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by matt-whiteman** [comment]
Closed with https://github.com/camunda/camunda/pull/17556

**Comment by ThorbenLindhauer** [comment]
The tests have been moved into this CI workflow: https://github.com/camunda/camunda/blob/main/.github/workflows/operate-test-importer.yml
They are covered by the `operateItImport` profile, which is why there is no CI build that runs the `operateItStage2` profile.
