### ISSUE TITLE
TaskSearchResponse should not return the "draft" attribute for variables

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#19190]
The TaskSearchResponse (https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/controllers/tasklist-api-rest-task-controller/#search-tasks) should not return the "draft" attribute for variables that are queried via includeVariables.

It returns "draft": null, which causes confusion as users believe the drafts were cleared, c.f. https://jira.camunda.com/browse/SUPPORT-20308

### Additional Information
Same as: https://github.com/camunda/tasklist/issues/4393

**Comment by marcosgvieira** [comment]
Closing as duplicated https://github.com/camunda/tasklist/issues/4393
