### ISSUE TITLE
`Sequencer#isEntryValid` is slow because it has to calculate the full record size

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#19225]
This method checks that record value and metadata don't have size 0. This validation was copied over from the dispatcher.
The method shows up in profiling because calculating the length of `UnifiedRecordValue` is a fairly expensive operation. The length is calculated by recursively walking the object graph until we find primitive types such as `long`.

We should be able to remove this checks because `RecordMetadata` can never have length 1 and `UnifiedRecordValue` also offers an optimized `isEmpty` method.

**Comment by jawaharbabugit** [comment]
@lenaschoenburg I am interested in working on this issue.

**Comment by jawaharbabugit** [comment]
@lenaschoenburg  I am new to this project and I would like to get a bit more context on this issue to work on. What needs to be done apart from using isEmpty for `UnifiedRecordValue`? Also, Did you mean to remove the length check for `RecordMetadata` in the description?  Thanks in Advance!

**Comment by lenaschoenburg** [comment]
Yes, I think using `isEmpty` for the record value and _no_ length check for record metadata is the right approach :+1: 
Make sure you read the [contributing guide](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md).

**Comment by jawaharbabugit** [comment]
@lenaschoenburg FYI I think we can't use UnifiedRecordValue's `isEmpty()` instead of `getLength()`, because isEmpty returns true even though the length of the record is non-zero, which leads to false negatives (isEntryValid returns false for valid methods).

I logged the record length and isEmpty; even though the length was 1, isEmtpy returns true.
```
17:34:35.998 [] [main] INFO  io.camunda.zeebe.logstreams.impl.log.Sequencer -  record value length : 1
17:34:35.999 [] [main] INFO  io.camunda.zeebe.logstreams.impl.log.Sequencer -  record value isEmpty : true
```

**Comment by lenaschoenburg** [comment]
@jawaharbabus That's right, `isEmpty` is not correct either. I checked again and actually we can remove the length check for record values altogether. So `isEntryValid` just checks for non-null record value and metadata. This is because all record values are ultimately `ObjectValue`s which always have non-zero length.

**Comment by jawaharbabus** [comment]
@lenaschoenburg  Thanks for the input. I will remove the length checks altogether.

**Comment by jawaharbabus** [comment]
@lenaschoenburg I made the necessary changes. Let me test it and add it to my pull request right away. Thanks.

**Comment by lenaschoenburg** [comment]
FYI @jawaharbabus, since your PR https://github.com/camunda/camunda/pull/19286 was closed I opened a new PR https://github.com/camunda/camunda/pull/21311 here.
