### ISSUE TITLE
Switch on/off concurrency mode in `import-position` index

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#19388]
### Description

TBD

### TODO

* When the exporter starts it should activate the concurrency mode for the importer to pick up
* The importer should only continue importing Zeebe records from the previous minor release. It must ignore any Zeebe indexes for the current minor release and higher (as the exporter will take care of this data)

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by Zelldon** [comment]
We decided against this and will run Importing/Exporter in sequence https://github.com/camunda/camunda/issues/24440
