### ISSUE TITLE
Bring Spring into new Operate exporter

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#19387]
### Description

Convert Operate exporter to Spring module, which will allow us to inject Operate Spring beans from dependent Operate modules and in general simplify things.
Note: prefer using constructor bean injections to simplify testing.

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by ThorbenLindhauer** [comment]
We decided to not have Spring in the exporter.
