### ISSUE TITLE
Improve and unify the filter deletion dialog

### ISSUE THREAD

**Issue by volodymyr-melnykc** [camunda/camunda#19425]
### Description

The filter deletion dialog needs to be updated to follow the design guidelines.
- Please reach out to the Camunda design team for a design reference if needed.

The current version:
![Image](https://github.com/camunda/camunda/assets/143816833/f93df4f0-0d48-42db-ae09-acfb037db514)

Needed updates:
- Only use title, no additional label
- Mention the name of the filter that will be deleted
- The name of the filter should be highlighted in semi-bold.

Please reach out to the Camunda design team for a design reference.

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by iamviqar** [comment]
@volodymyr-melnykc  I have requested access for figma design, please provide the access
