### ISSUE TITLE
[C8 Unified V2 API] Implement Process Definition Search Query Service

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#19557]
### Description

Implement Process Definition Search Query Service.

### Acceptance Criteria

- [ ] Create queries to find process definition
- [ ] Unit tests

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by ThorbenLindhauer** [comment]
@ralfpuchert as discussed, let's rather create tickets for each endpoint and build those end-to-end across all layers at once. I will close this ticket as not planned accordingly.
