### ISSUE TITLE
Flaky test RaftTest.shouldTriggerHeartbeatTimeouts

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#19574]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once so far. 
- Does it block your work? No.
- Do we suspect that it is a real failure? Not sure.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
org.awaitility.core.ConditionTimeoutException: Lambda expression in org.awaitility.core.ConditionFactory expected a value greater than <2L> but <2L> was equal to <2L> within 4 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.untilAdder(ConditionFactory.java:882)
	at io.atomix.raft.RaftTest.shouldTriggerHeartbeatTimeouts(RaftTest.java:477)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

https://github.com/camunda/camunda/actions/runs/9593212011/job/26453221721

[Unit Test Results.zip](https://github.com/user-attachments/files/15911832/Unit.Test.Results.5.zip)

**Comment by tmetzke** [comment]
Happened again on `main`: https://github.com/camunda/camunda/actions/runs/9752319481/job/26915601671

[Test results for unit tests](https://github.com/user-attachments/files/16062765/Test.results.for.unit.tests.zip)

**Comment by berkaycanbc** [comment]
Happened again on `main`: https://github.com/camunda/camunda/actions/runs/9776016966/job/26987681587

[Test results](https://github.com/user-attachments/files/16082751/4_java-unit-tests.txt.zip)
