### ISSUE TITLE
Flaky test CancelProcessInstanceConcurrentlyTest because Actor closed before tests finish.

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#19604]
**Summary**

It seems that the actor is closing before the test competition.

- How often does the test fail? Once so far.
- Does it block your work? 
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Warning:  Flakes: 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleted[multi-instance]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleted[parallel flow]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleted[sequential flow]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleted:253 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleted[sub-process]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleting[multi-instance]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleting[parallel flow]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleting[sub-process]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterJobComplete[multi-instance]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterJobComplete[parallel flow]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterJobComplete[sequential flow]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterJobComplete[sub-process]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterJobCompleted[multi-instance]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterJobCompleted[parallel flow]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterJobCompleted[sub-process]
Error:    Run 1: CancelProcessInstanceConcurrentlyTest.init:131 ? Execution Actor is closed
[INFO]   Run 2: PASS</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

https://github.com/camunda/camunda/actions/runs/9600392665/job/26476490140

[Uploading Unit Test Results.zip…]()

**Comment by npepinpe** [comment]
May be related to https://github.com/camunda/camunda/issues/19633 and https://github.com/camunda/camunda/issues/18461, where the actor is _also_ closed prematurely.

**Comment by mustafadagher** [comment]
This is the log of the thrown error
```
Error:  io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleted[sequential flow] -- Time elapsed: 0.125 s <<< ERROR!
java.util.concurrent.ExecutionException: Actor is closed
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:147)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:114)
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:21)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:203)
	at io.camunda.zeebe.logstreams.util.SyncLogStream.newLogStreamWriter(SyncLogStream.java:77)
	at io.camunda.zeebe.engine.util.TestStreams$LogContext.newLogStreamWriter(TestStreams.java:442)
	at io.camunda.zeebe.engine.util.TestStreams.newLogStreamWriter(TestStreams.java:171)
	at io.camunda.zeebe.engine.util.StreamProcessingComposite.writeBatch(StreamProcessingComposite.java:145)
	at io.camunda.zeebe.engine.util.StreamProcessorRule.writeBatch(StreamProcessorRule.java:194)
	at io.camunda.zeebe.engine.util.EngineRule.writeRecords(EngineRule.java:356)
	at io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleted(CancelProcessInstanceConcurrentlyTest.java:253)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: java.lang.RuntimeException: Actor is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamWriter(LogStreamImpl.java:159)
	... 8 more
```

I'm hoping this might have been fixed with https://github.com/camunda/camunda/pull/20339

**Comment by lenaschoenburg** [comment]
I agree, I think we can close it. If it occurs again, it'll be with a different error.
