### ISSUE TITLE
Spring SDK 8.5.3 requires JDK 21+

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#19658]
**Describe the bug**

The Spring SDK's [version compatibility](https://docs.camunda.io/docs/next/apis-tools/spring-zeebe-sdk/getting-started/#version-compatibility) is documented to require JDK 17+. However, since 8.5.2/8.5.3, it requires JDK 21+.

This may be a documentation issue if not a defect.

**To Reproduce**

- use spring SDK in a project
- build the project with JDK 17
- note the following error:

>has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

**Expected behavior**

Spring SDK 8.5.x should require JDK 17+ only. Or the documentation should be adjusted.

**Comment by korthout** [comment]
The required version was updated in:
- https://github.com/camunda/camunda/pull/18255

@nicpuppa Do you know remember why this was changed?

**Comment by nicpuppa** [comment]
> @nicpuppa Do you remember why this was changed?

I think I changed it by mistake. What should we do now ?

**Comment by korthout** [comment]
I suggest we try to tackle this as a bug first. Re-enabling the ability to use JDK 17+ for future patches of 8.5. Unless we run into a good reason why we need JDK 21+, in which case we should simply update the docs.

**Comment by nicpuppa** [comment]
Do we need to release a new patch release to fix this ? 

This problem affect `8.5.2` and `8.5.3` releases. We are on time to add this fix into the next patch ? Or we might need to create a new patch release just after

**Comment by nicpuppa** [comment]
I will work on this today 👍
