### ISSUE TITLE
Resolve deployment-bound resource links within same deployment

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda#19710]
### Description
Resource links with `bindingType=deployment` must be resolved within the same deployment; this applies to called processes, called decisions and linked forms.

### Acceptance Criteria
- [x] When model elements are transformed, the `bindingType` is registered in `ExecutableCallActivity`/`ExecutableBusinessRuleTask`/`ExecutableUserTask` (`UserTaskProperties`).
- [x] When the target resource is resolved in `CallActivityProcessor`/`BusinessRuleTaskProcessor`/`UserTaskProcessor`, the `bindingType` is checked:
  - [x] in case of `latest`: no change; the current behavior is used
  - [x] in case of `deployment`:
    - Use the `processDefinitionKey` (available from the `BpmnElementContext`) to look up the `deploymentKey` (which will be added to a `PersistedProcess` with #19709).
    - Use the `deploymentKey` + target `processId`/`decisionId`/`formId` to retrieve the resource from the state.
    - In case the target resource cannot be found in the same deployment, return a `Failure`.
    (this case should be prevented for static IDs in the future by #19712)

### Dependencies
- requires #19461
- requires #19709

**Comment by korthout** [comment]
>add deploymentKey to ProcessInstanceRecord/BpmnElementContext

I think we can avoid this by doing a lookup of the process definition of the `call activity` / `user task` / `business rule task` instance to find the `deploymentKey`. We can then use the `deploymentKey` together with the `processId` to lookup the process definition to call. This additional lookup slows down call activity execution slightly, but avoids having to add an extra field to all element instance records which.

**Comment by jfriedenstab** [comment]
Thanks, @korthout, good suggestion 👍🏻. I've updated the issue description accordingly.
