### ISSUE TITLE
Operate | Migration of tasks with Boundary Events does not work

### ISSUE THREAD

**Issue by hoellamike** [camunda/camunda#19783]
### Describe the bug

If a process has a task with a boundary event and is migrated to a version with no boundary event (or vi­ce ver­sa) the migration silently fails.

### To Reproduce

1. Have two versions of a deployed process (one with a boundary event on a task and one without) (Examples in Attachments)
2. Migrate between the two versions
3. Migrations seems to work (Operations window shows progress of migration and finishes)
4. Selected process instances still stay on the same version (and are not migrated)

### Current behavior
<img width="399" alt="image" src="https://github.com/camunda/camunda/assets/24242678/6cc220a3-2ab4-439d-87d6-0c691ca2747c">
<img width="1561" alt="image" src="https://github.com/camunda/camunda/assets/24242678/fac44803-4869-493d-9137-28c3575a337c">
<img width="449" alt="image" src="https://github.com/camunda/camunda/assets/24242678/7eebc729-4ed1-4c79-9f87-20313df562e7">

Process instances still stay in the old version
<img width="647" alt="image" src="https://github.com/camunda/camunda/assets/24242678/ff6595ab-3330-46f6-8eaf-ccd6e69b1278">

### Expected behavior

Sucessfull migration of instances

### Environment

    Browser: Firefox
    Operate Version: Version 8.5.4
    Zeebe Version: 8.5.3

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [x] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [x] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [x] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

**Comment by pedesen** [comment]
Hey @hoellamike, thanks for reaching out. 

Migrating active elements with error boundary events is not yet supported by zeebe. You can follow [this issue](https://github.com/camunda/camunda/issues/17349) to track when this will be available.

In your case the operation starts, but fails silently. We already acknowledged that this needs improvement, so we added a feature called "operation status monitoring", which will be available in Operate 8.6+. This feature makes it more obvious that an operation fails and also makes the reason transparent in the UI. 

I closed this issue for now. Feel free to reopen if you have any further questions.
