### ISSUE TITLE
Create new version of every resource in multi-resource deployment if at least one has changed

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda#19859]
### Description
To properly support the new [`deployment` binding type](https://github.com/camunda/camunda/issues/19384), the deployment behavior in Zeebe should be adapted: When multiple resources are deployed together and at least one of them has changed (compared to the latest already deployed version), a new version of _every_ resource that is part of the deployment should be created (even if this particular resource has not changed).

The new behavior should ensure that:
- if `deployment` binding is used, a process instance will only call other resources (e.g. a sub process from a call activity) that were part of the same deployment
- this happens in a way that is transparent and easy to understand for users (an instance of a particular version of a process should always call the same version of the target resource)

### Acceptance Criteria
- [x] If multiple resources are deployed together in a single request and at least one of them has changed (i.e. is not marked as a duplicate), a new version of _every_ resource in the deployment is created, i.e. a new `CREATED` record is written with an increased version number and unique key (this applies to processes, decisions, decision requirements and forms).
- [x] If the deployment request contains duplicates only, the behavior is not changed (i.e. no new records are written).

### Implementation Plan
Introduce a two-step resource transformation:
1. Validate resources and create metadata, but do not write records yet. After this iteration it will be possible to tell if at least one non-duplicate resource is contained in the deployment.
2. Iterate over the resources again. If the deployment contains at least one non-duplicate resource, update the metadata of previously marked duplicates to make them non-duplicates and increase the version. Eventually, write the `CREATED` records.

_Note_: Most probably, a two-step approach will also be required for #19712 to check if the targets of all deployment-bound resource links are contained in the deployment.

### Example
**Given**:
  - two processes `A` and `B`
  - process `A` contains a call activity that calls process `B` with binding type `deployment`

**Scenario**:
  1. deploy both processes together
    -> process definition versions `A:v1` and `B:v1` are created
  4. start a new instance `i1` of `A:v1`
  5. assume that `i1` has not reached the call activity yet that would call `B`
  6. make some changes to process `B` only
  7. deploy both processes together again
    -> process definition versions `A:v2` and `B:v2` are created
    (⚠️ this is the new behavior: a **new version** of `A` is created although it has not changed)
  8. `i1` reaches the call activity -> it calls `B:v1`
  9. start a new instance `i2` of `A:v2` -> it calls `B:v2`

#### Considered alternative solution
The `deployment` binding strategy could probably also be achieved without changing the deployment/versioning behavior. However, this would come with some downsides which can be explained with the example from above:
- in step 5, process `A` would stay in version `A:v1`
- when `deployment` binding is used, it still needs to be ensured that instance `i1` calls `B:v1` and `i2` calls `B:v2`
- this would mean that the same version of the calling process (`A:v1`) would call _different_ versions of the target process (`B:v1` or `B:v2`), making it harder to understand for users
- the logic to determine the right version to call would also be more complex to implement

#### Possible enhancements
- Keep the current behavior by default, but provide a way to opt in to the new behavior, for example by providing a flag like `isProcessApplication` or `isAtomicallyVersioned` with the deployment request. This would have the advantage of not surprising users with the new behavior, but would also require them to understand that they have to set an extra flag if they want to use "deployment" binding.
- Make the new behavior the default, but provide the possibility to opt out, for example by providing a flag like `isDeployChangedOnly` (similar to what [Camunda 7 provides](https://docs.camunda.org/manual/7.21/reference/deployment-descriptors/tags/process-archive/#configuration-properties)). If users do not intend to use "deployment" binding, the new behavior will not be needed anyway.

Both options are **out of scope** for this issue, but we could still decide to implement one of them as a follow-up.

**Comment by korthout** [comment]
Thanks @jfriedenstab for describing an alternative approach. Users may wonder why this still requires changing the behavior. Specifically keeping the default behavior and allowing to use the new behavior through a flag like `isProcessApplication`, or `isAtomicallyVersioned`. Could you add some notes to the alternative context section regarding this approach?
