### ISSUE TITLE
Support message and timer boundary events migration

### ISSUE THREAD

**Issue by vitorwtavares** [camunda/camunda#19886]
### Description
Zeebe [supports the migration](https://github.com/camunda/camunda/issues/16386) of message boundary events and soon [timer boundary events](https://github.com/camunda/camunda/issues/15918).
Operate needs to enable users to migrate both types of boundary events.

### User Story

```Gherkin
Scenario: As an Operate user
    Given I am in the process instance list
    Then I can define the migration plan and migrate message boundary events
```

```Gherkin
Scenario: As an Operate user
    Given I am in the process instance list
    Then I can define the migration plan and migrate timer boundary events
```

### Acceptance Criteria
- [x] Frontend
  - [x] Message and timer boundary events are selectable in the instance list to migrate
  - [x] I can not map a message boundary event to a timer boundary event and vice versa
  - [x] I can map interrupting to non-interrupting events (and vice versa) as soon as it's the same event type
  - [x] I can define the migration plan for message and timer boundary events
  - [x] I can execute migration for message and timer boundary events
  - ~~Optional: The edge cases limitations ([set 1](https://github.com/camunda/camunda/issues/19640), [set 2](https://github.com/camunda/camunda/issues/20906), [set 3](https://github.com/camunda/camunda/issues/19956)) are validated and not allowed in the frontend~~ moved to separate issue: https://github.com/camunda/camunda/issues/23165
- [x] Backend: https://github.com/camunda/camunda/issues/21542
- [ ] [Docs](https://docs.camunda.io/docs/next/components/operate/userguide/process-instance-migration/) are updated: message and timer boundary events are added to the list of mappable elements

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by ThorbenLindhauer** [comment]
I will generalize this ticket for message and timer events that we both want to support with 8.6

**Comment by ThorbenLindhauer** [comment]
No backporting to 8.5 required (or for other migration features that we are currently building). Removed that from the description.

**Comment by ThorbenLindhauer** [comment]
# Assessment of scope for message boundary events

Goal is to confirm what we need to do. See models attached for the different process versions. Where the migration was not possible via UI, I used this Java client project: https://github.com/ThorbenLindhauer/zeebe-client-playground

Cases:

* V1 -> V2: Adding a message boundary event to an activity that had previously none
  * Trigger it via UI: OK
  * Batch success: OK
  * Token state in UI: OK
  * Message name and correlation key in UI: OK
* V2 -> V3: Migrating an activity with a message boundary event in place (i.e. message not changed)
  * Trigger it via UI: **not OK**
    * I cannot create a mapping instruction between the boundary events
    * The boundary events are not auto-mapped
  * Batch success: n/a
  * Token state in UI: OK
  * Message name and correlation key in UI: OK
    * but only because the properties have the same values as before
* V3 -> V4: Migrating an activity with a message boundary event in place (i.e. message not changed) to a new message
  * Trigger it via UI: **not OK**
    * same reason as previous case
  * Batch success: n/a
  * Token state in UI: OK
  * Message name and correlation key in UI: **not OK**
    * Message name wasn't updated; correlation key has the same problem
V4 -> V1: Removing a message boundary event
  * Trigger it via UI: OK
  * Batch success: OK
  * Token state in UI: OK
  * Message name and correlation key in UI: **not OK**
    * Message name and correlation key are not removed from flow node instance details

**Comment by ThorbenLindhauer** [comment]
# Assessment of scope for timer boundary events

* V1 -> V2: Adding a timer boundary event to an activity that had previously none
  * Trigger it via UI: OK
  * Batch success: OK
  * Token state in UI: OK
* V2 -> V3: Migrating an activity with a timer boundary event in place without mapping the timers (i.e. timer cancels and starts)
  * Trigger it via UI: OK
  * Batch success: OK
  * Token state in UI: OK
* V2 -> V3: Migrating an activity with a timer boundary event in place and mapping the timers (i.e. timer subscription is migrated so that it keeps running)
  * Trigger it via UI: **not OK**
    * I cannot create the mapping instruction
  * Batch success: n/a
  * Token state in UI: n/a

Confirms the following changes that we need to make

* Frontend: Make it possible to map timer boundary events
