### ISSUE TITLE
Tasklist Form - Radio group rendering cut-off

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#19945]
### Describe the bug
Selecting an item from a Radio Group in Tasklist form creates a cutoff in the selection rendering.

### To Reproduce

1. Create a form with a radio group
2. Open it in tasklist

### Actual behavior

The circle on the selected radio item rendering has a cut-off.

### Expected behavior

The circle on the selected radio item rendering should not have a cut-off.

### Environment

- Browser: Chrome
- Tasklist Version: 8.5+gen5

### Additional context

Reference support report: https://jira.camunda.com/browse/SUPPORT-22599?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by marcosgvieira** [comment]
@Skaiir please have a look here: https://github.com/camunda/tasklist/issues/3688 - Douglas had created a fix for that before, should be simple to put it back.

**Comment by Skaiir** [comment]
Fixed via https://github.com/bpmn-io/form-js/pull/1261, needs integration and we're good.

**Comment by vsgoulart** [comment]
Fixed via https://github.com/camunda/camunda/pull/22297
