### ISSUE TITLE
Update RocksDB to 9.x

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#19981]
**Description**

RocksDB released a new major version with many features. While 8.x is still maintained, it's not clear to me for how long, so we should migrate sooner than later. However, there are some breaking changes which require manual effort, hence why we have an issue and aren't relying on Renovate here.

It should still be compatible with previous versions however, the breaking changes are in the APIs and not the database itself as far as I know - this should be verified with our compatibility tests, of course.

**Comment by npepinpe** [comment]
ZDP Triage:
- Evaluate how much effort is required. If small (in the order of a few hours), let's do it for the next iteration.

**Comment by EuroLew** [comment]
Upgraded to 9.4.0 however the abstraction layer Zeebe uses which is built on top of RocksDB reflects private methods for legacy reasons which could cause issues with future upgrades if the types change further.
