### ISSUE TITLE
Why `zeebe-record-timer` doesn't have field `bpmnProcessId`?

### ISSUE THREAD

**Issue by meetyouinthepouringrain** [camunda/camunda#19982]
- It is useful to define `bpmnProcessId`, but we find that there is no `bpmnProcessId` in the `zeebe-record-timer` event. Why?

- Although there is a `processDefinitionKey` in zeebe-record-timer, it is not easy to do associative queries in `es`

**Comment by berkaycanbc** [comment]
Hey @meetyouinthepouringrain, there is no specific reason to not include bpmn process id to the timer record. However you do not need an associative query to retrieve the bpmn process id for the timer record. You can simply use a term query over index `zeebe-record-process-instance` as such:

```java
{
  "query": {
    "term": {
      "value.processInstanceKey": {
        "value": <your_process_instance_key>
      }
    }
  }
}

```

**Comment by megglos** [comment]
closing as stale, if you have follow-up questions please reach out
