### ISSUE TITLE
Shared `build-platform-docker` action output `image` is missing

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#20001]
The action [build-platform-docker](https://github.com/camunda/camunda/blob/4cc32dc75502b49b85122e401e6329481aa0fb1d/.github/actions/build-platform-docker/action.yml) say's that there should be a `image` output that contains "Fully qualified image name available in your local Docker daemon".

This does not work, the `image` output is always empty. See this example run: https://github.com/camunda/camunda/actions/runs/9777854271/job/26993894405?pr=19999

The `image` output is coming from `steps.get-image.outputs.result`. But the  `docker/metadata-action@v5`  used in that step does not define a `result` output.

This blocks https://github.com/camunda/camunda/pull/19999.

**Comment by cmur2** [comment]
> The image output is coming from steps.get-image.outputs.result. But the docker/metadata-action@v5 used in that step does not define a result output.

This analysis is correct, the only outputs available are https://github.com/docker/metadata-action?tab=readme-ov-file#outputs

**Comment by cmur2** [comment]
Fix in https://github.com/camunda/camunda/pull/20087 is in review currently
