### ISSUE TITLE
Snyk scan for Zeebe is broken after moving modules around

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#20011]
**Description**

We are not scanning Snyk vulnerabilities properly for Zeebe anymore since we moved repositories around, since we were scanning specific modules and the paths for them has changed. 

We have to fix the paths so they point to the appropriate repositories, and also fail the workflow to prevent future issues like this.

**Comment by npepinpe** [comment]
Should be done ASAP as we may be missing alerts for high CVEs.

**Comment by korthout** [comment]
Changes result in broken snyk scan in Release Dry Run on `stable/8.5`:
- https://github.com/camunda/camunda/actions/runs/10172841501/job/28136429868

```
+ for project in "${JAVA_PROJECTS[@]}"
+ PROJECT_NAME='zeebe(0.8):clients/java/pom.xml'
+ ensureExists clients/java/pom.xml
+ local projectFile=clients/java/pom.xml
+ '[' '!' -f clients/java/pom.xml ']'
+ echo 'Cannot find project file to scan: [ clients/java/pom.xml ]'
+ exit 1
Cannot find project file to scan: [ clients/java/pom.xml ]
Error: Process completed with exit code 1.
```

@npepinpe I believe you missed the zeebe java client here: 65c3473ca2ebfe1b57bb29dfb3e659a3f041384e

**Comment by nicpuppa** [comment]
@korthout https://github.com/camunda/camunda/pull/20646

**Comment by korthout** [comment]
Thanks @nicpuppa
