### ISSUE TITLE
ResourceDeletionTest fails due to Maven fork error

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#20078]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Twice so far
- Does it block your work? No
- Do we suspect that it is a real failure? Definitely not. It seems to be an issue with the test setup/Maven.

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Paste the failure here
</pre>
</details>

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.3.0:test (default-test) on project zeebe-workflow-engine: 
Error:  
Error:  Please refer to /runner/_work/camunda/camunda/zeebe/engine/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/runner/_work/camunda/camunda/zeebe/engine' && '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.3-9.0.LTS/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/runner/_work/camunda/camunda/zeebe/engine/target/jacoco.exec' '-jar' '/runner/_work/camunda/camunda/zeebe/engine/target/surefire/surefirebooter-20240704144644510_1284.jar' '/runner/_work/camunda/camunda/zeebe/engine/target/surefire' '2024-07-04T14-44-09_108-jvmRun5' 'surefire-20240704144644510_1270tmp' 'surefire_137-20240704144644510_1279tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.engine.processing.resource.ResourceDeletionTest
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/runner/_work/camunda/camunda/zeebe/engine' && '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.3-9.0.LTS/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/runner/_work/camunda/camunda/zeebe/engine/target/jacoco.exec' '-jar' '/runner/_work/camunda/camunda/zeebe/engine/target/surefire/surefirebooter-20240704144644510_1284.jar' '/runner/_work/camunda/camunda/zeebe/engine/target/surefire' '2024-07-04T14-44-09_108-jvmRun5' 'surefire-20240704144644510_1270tmp' 'surefire_137-20240704144644510_1279tmp'
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 134
Error:  Crashed tests:
Error:  io.camunda.zeebe.engine.processing.resource.ResourceDeletionTest
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:456)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:358)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:296)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1224)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1073)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:907)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
Error:  	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
Error:  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
Error:  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Error:  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Error:  	at java.base/java.lang.Thread.run(Thread.java:1583)
Error:  Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd '/runner/_work/camunda/camunda/zeebe/engine' && '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.3-9.0.LTS/x64/bin/java' '-javaagent:/home/runner/.m2/repository/cached/releases/org/jacoco/org.jacoco.agent/0.8.12/org.jacoco.agent-0.8.12-runtime.jar=destfile=/runner/_work/camunda/camunda/zeebe/engine/target/jacoco.exec' '-jar' '/runner/_work/camunda/camunda/zeebe/engine/target/surefire/surefirebooter-20240704144644510_1284.jar' '/runner/_work/camunda/camunda/zeebe/engine/target/surefire' '2024-07-04T14-44-09_108-jvmRun5' 'surefire-20240704144644510_1270tmp' 'surefire_137-20240704144644510_1279tmp'
</pre>
</details>

**Additional information**
* Failure 1: https://github.com/camunda/camunda/actions/runs/9796281491/job/27050363968
* Failure 2: https://github.com/camunda/camunda/actions/runs/9804416099/job/27073374326
* Test results from failure 1 (internal): https://drive.google.com/file/d/1QlEAwcJntfbtZFpxtsQx35RBmD-X1KX5/view?usp=sharing

**Comment by mustafadagher** [comment]
I ran this locally for over 10,000 times, with not a single failure.
This seems to me like a JVM crash issue.

Reading about it, I found out that The `Process Exit Code: 134` is often associated with a fatal error in the JVM, such as a segmentation fault. On Unix-like systems, an exit code of 134 typically indicates that the process was terminated by a SIGABRT signal, which is used to abort the process.

I think if this happens again, we might need to look into the memory and the number of forks assigned to the `maven-surefire-plugin` configs

**Comment by megglos** [comment]
@mustafadagher so we could close it for now until observed again to reprioritize?

**Comment by nicpuppa** [comment]
Happened again: https://github.com/camunda/camunda/actions/runs/10450915063/job/28936224333

**Comment by Zelldon** [comment]
Happened again on merging https://github.com/camunda/camunda/actions/runs/10508343618/job/29112060617

**Comment by megglos** [comment]
Let's validate the frequency of it from the metrics and reevalute.

**Comment by korthout** [comment]
Closing until raised again by CI monitoring
