### ISSUE TITLE
Exporting decision evaluation records breaks with large `evaluationFailureMessage` values

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#20248]
**Describe the bug**

When decision evaluation fails with a long error message, Zeebe fails to export the record to ES. It get's rejected because the `evaluationFailureMessage` is supposed to be parsed as `keyword` but ElasticSearch fails to do so.
The impact is that exporting is fully blocked until a temporary workaround is applied.

**To Reproduce**

Use a large FEEL expression that fails for some input. The automatically generated error message includes the entire FEEL expression and more, making it too large for ES to handle.

**Workaround**

Modify the template ad-hoc:
```
PUT zeebe-record-decision-evaluation/_mapping
{
  "properties": {
    "value.evaluationFailureMessage": {
      "type": "keyword",
      "ignore_above": 1024
    }
  }
}
```

**Expected behavior**

Exporting should never fail. Comparable fields such as `exceptionMessage` from the error record are configured to ignore values above a certain size.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to flush bulk request: [Failed to flush 1 item(s) of bulk request [type: document_parsing_exception, reason: [1:99] failed to parse field [value.evaluationFailureMessage] of type [keyword] in document with id '1-1019381702'.
```

</p>
</details>

**Related**

Incident: https://app.incident.io/camunda/incidents/1557

**Comment by megglos** [comment]
Question for Triage, is there even a need to index this field?

**Comment by lenaschoenburg** [comment]
I think all fields are indexed at the moment. As far as I know, our primary users (the webapps), don't rely on any fields being indexed (apart from maybe `position`). Seems wasteful to me but changing that might be breaking other consumers.

**Comment by megglos** [comment]
occured again on https://slack.com/app_redirect?team=T0PM0P1SA&channel=C07FC0F97DZ

**Comment by korthout** [comment]
ZPA triage:
- increasing likelihood as it occurred again -> mid
- severity mid + mid likelihood -> upcoming
- effort seems a low hanging fruit so we can just move it into next

**Comment by korthout** [comment]
@berkaycanbc wants to take a look

**Comment by nicpuppa** [comment]
@berkaycanbc please consider this:
- Maybe we can change the type of the field, using `text` instead of `keyword`. In this case I think we don't need to add `ignore_above` property (please double check)
- Backporting the fix to older releases

**Comment by berkaycanbc** [comment]
@nicpuppa changing the field type could introduce backward compatibility problems. For example, `keyword` type can be queried with `term` query whereas `text` field is designed to be queried by `match` or `match_phrase` query (see [link](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html#:~:text=Avoid%20using%20the%20term%20query,use%20the%20match%20query%20instead.)). Another problem is that we might need to re-index existing data because if we don't, we will have a mix of `keyword` and `text` data types which can cause issues in applications expecting `keyword` data type for this field.
