### ISSUE TITLE
Use common global env variable for authorization checks

### ISSUE THREAD

**Issue by maryarm** [camunda/camunda#20460]
### Description
There are currently two feature flags for controlling authorization checks in the single application, one is Zeebe scoped (`ZEEBE_BROKER_EXPERIMENTAL_ENGINE_AUTHORIZATIONS_ENABLEAUTHORIZATION`) the other is globally scoped (`CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED`). The Zeebe scoped variable was added as a time to help progress however we should align and use the global variable in the engine level checks and remove/deprecate the Zeebe scoped feature flag.

### Acceptance Criteria

- [ ] Only one authorizations feature flag is used, that being `CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED`

**Comment by remcowesterhoud** [comment]
This is fixed in https://github.com/camunda/camunda/pull/25556
