### ISSUE TITLE
`OAuthCredentialsCache` in Zeebe Java client does not work correctly in multi-tenancy setup

### ISSUE THREAD

**Issue by jfriedenstab** [camunda/camunda#20471]
**Describe the bug**
The `OAuthCredentialsCache` in the Zeebe Java client does not work well with multi-tenancy and the Camunda Identity-based client authorization / token validation.
If you use the Java client to deploy to tenant 1 first and then try to deploy to tenant 2 (using different client credentials that are only valid for tenant 2), the first deployment request succeeds, but the second one will fail with a `PERMISSION_DENIED` error status. This is because the Zeebe Java client tries to re-use the cached OAuth token from the first request that is only authorized for tenant 1.
The underlying problem seems to be that the OAuth token audience is used as the cache key. The audience is usually the constant value `zeebe-api`, so that the cache will not be tenant-aware.

**To Reproduce**
The easiest way to reproduce the problem is to run Camunda 8 Self-Managed with [Docker Compose](https://github.com/camunda/camunda-platform) and deploy from Web Modeler.
1. Enable multi-tenancy (`MULTI_TENANCY_ENABLED=true`)
1. Enable client authorization (`ZEEBE_AUTHENTICATION_MODE=identity`)
1. Start Camunda 8 (including Web Modeler)
1. Create two tenants in Identity: `tenant-1` and `tenant-2`
1. Create two M2M applications in Identity: `app-tenant-1` and `app-tenant-2`
    - Assign `app-tenant-1` to `tenant-1` and assign permissions for the Zeebe API
    - Assign `app-tenant-2` to `tenant-2` and assign permissions for the Zeebe API
1. Create a new BPMN diagram in Web Modeler
1. Deploy to `tenant-1` with the client credentials for `app-tenant-1` -> deployment succeeds
1. Try to deploy to `tenant-2` with the client credentials for `app-tenant-2` -> deployment fails with `Expected to handle gRPC request DeployResource with tenant identifier 'tenant-2', but tenant is not authorized to perform this request`

<img width="716" alt="deploy" src="https://github.com/user-attachments/assets/22b2786b-e88e-4578-bb44-4e0df11c5808">

**Expected behavior**
It should be possible to deploy to different tenants using different client credentials.

**Additional Context**
- related to https://jira.camunda.com/browse/SUPPORT-22768
- also related to https://jira.camunda.com/browse/SUPPORT-23752

**Environment:**
- Camunda / Zeebe Version: 8.5.2

**Comment by jfriedenstab** [comment]
**Additional Context**
- I noticed that the provided audience is not actually checked in Self-Managed, so as a workaround you could just use different values for different tenants. That doesn't sound very intuitive though. From the documentation on [Camunda Identity authorization](https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/client-authorization/#camunda-identity-authorization) I would also understand that the expected value is `zeebe-api`:
  
  > With authentication enabled, every request to the Gateway requires a valid auth token in the `Authorization` header, granting access to the configured `security.authentication.identity.audience`, issued by the configured `security.authentication.identity.issuerBackendUrl`. The `zeebe-api` audience is already pre-configured in Camunda Identity.

- Using the audience as the cache key does not seem to be ideal when deploying to different clusters on C8 SaaS either. As the audience is constant here (e.g. `zeebe.camunda.io` in production), the cache would contain a single entry that is only valid for the most recent cluster you deployed to. If you deploy to a different cluster, the deployment request will fail with an `UNAUTHENTICATED` error first, but it will be retried internally with freshly fetched credentials.

**Comment by megglos** [comment]
ZPA-Triage:
- this seems like a general bug, on credential config change a token obtained previously stored in the cache is still used until it expires
- workaround for the use case described => have credentials allowed to access both tenants
- we consider likelihood generally to be low, the particular scenario is specific to web modeler usage here

**Comment by megglos** [comment]
@jfriedenstab let's follow-up on the whole user experience in SaaS here

**Comment by korthout** [comment]
@megglos Please inform [here](https://camunda.slack.com/archives/C07DLH75SRX/p1722850540447339?thread_ts=1722325295.332489&cid=C07DLH75SRX) about any changes to prio/issue.

**Comment by wollefitz** [comment]
> @jfriedenstab let's follow-up on the whole user experience in SM

@megglos Starting from `8.7`, we're planning to drop the usage of M2M tokens for authenticating against target Zeebe clusters as part of https://github.com/camunda/product-hub/issues/2073. This will implicitly remove Web Modeler's dependency on the [`OAuthCredentialsCache`](https://github.com/camunda/camunda/blob/7f65315e10e8629a979cd055ad4560bd81dae8fd/clients/java/src/main/java/io/camunda/zeebe/client/impl/oauth/OAuthCredentialsCache.java) causing this behavior.

I think the reported issue is still valid (using the token audience as a cache key is not sufficient in multi-tenancy setups) but for the Web Modeler team, it is not a priority to be fixed anymore.

**Comment by remcowesterhoud** [comment]
This same issue happened in another support case https://jira.camunda.com/browse/SUPPORT-23752

**Comment by megglos** [comment]
@wollefitz @remcowesterhoud effectively switching to the clientId as cache key should resolve this, right? As then you don't have any cache hits when using eventually a different client credentials or a different cluster, as in both cases the clientId will be different.

**Comment by felicijus** [comment]
@megglos Can confirm this works for us.

https://jira.camunda.com/browse/SUPPORT- 23752

**Comment by megglos** [comment]
@felicijus thanks for the feedback, with "this works for us" you mean you changed the code yourself and use a custom client already? Or you mean this would work from your perspective if we change it?

**Comment by felicijus** [comment]
We tested it with a few of our webmodeler users setting the audience manually to the Client ID in Webmodeler UI, when doing so we don't get authentication errors.

What I meant is that your proposed change should resolve this issue based on our tests.

**Comment by megglos** [comment]
Perfect, thanks for the insights, I will look into creating a PR for this.
