### ISSUE TITLE
Flaky io.camunda.zeebe.engine.processing.job.ActivatableJobsPushTest shouldPushForMultipleJobsCreated

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#20485]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1598)
	at io.camunda.zeebe.engine.processing.job.ActivatableJobsPushTest.shouldPushForMultipleJobsCreated(ActivatableJobsPushTest.java:160)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

https://github.com/camunda/camunda/actions/runs/10074344534
[zeebe.zip](https://github.com/user-attachments/files/16361293/zeebe.zip)

**Comment by mustafadagher** [comment]
I investigated this failure locally. 
What happens (rarely) is that we arrive [here](https://github.com/camunda/camunda/blob/71a57964869e0f39d70448794802b69a410e444b/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java#L159) at `jobStream.getActivatedJobs().forEach()` when we don't yet have all the activated jobs in the stream. But in the meantime, they get added while iterating over them, causing the `ConcurrentModificationException` to be thrown.

To solve this I shall wait first for the stream to have the expected count, before looping on the stream items.

**Comment by nicpuppa** [comment]
> I investigated this failure locally. What happens (rarely) is that we arrive [here](https://github.com/camunda/camunda/blob/71a57964869e0f39d70448794802b69a410e444b/zeebe/engine/src/test/java/io/camunda/zeebe/engine/processing/job/ActivatableJobsPushTest.java#L159) at `jobStream.getActivatedJobs().forEach()` when we don't yet have all the activated jobs in the stream. But in the meantime, they get added while iterating over them, causing the `ConcurrentModificationException` to be thrown.
> 
> To solve this I shall wait first for the stream to have the expected count, before looping on the stream items.

I was looking also at the Flakyness, what about using other type of collections for `getActivatedJobs()`, instead of a list using `CopyOnWriteArrayList ` for example

**Comment by mustafadagher** [comment]
> I was looking also at the Flakyness, what about using other type of collections for `getActivatedJobs()`, instead of a list using `CopyOnWriteArrayList ` for example @mustafadagher

`CopyOnWriteArrayList ` shall indeed prevent the `ConcurrentModificationException`. But might lead to false positives in other scenarios. 
For example, in this case, if the stream will only ever have 2 (out of total 3) job batches activated, the test will pass when it should not.

**Comment by nicpuppa** [comment]
Mmm ok got it, it make sense 👍
