### ISSUE TITLE
Are Zeebe process instance key unique across multiple clusters

### ISSUE THREAD

**Issue by ashprojects** [camunda/camunda#20533]
We are planning to deploy two separate Zeebe clusters in our environment based upon different business use cases (+SLAs).

We wanted to understand if process instance keys generated by Zeebe would be unique across multiple clusters having same number of partitions?
In other words, is there any deterministic key generator which would generate same set of keys for clusters with same number of partitions?

**Comment by korthout** [comment]
Hi @ashprojects 👋 Short answer: while undocumented, keys are unique per cluster only, and not across clusters.

Currently (8.6 and prior), each partition has a key generator that hands out keys on that partition. The generator simply keeps track of a number starting at 1 that is incremented each time when a new key is requested. The partition id is encoded into this number to form the key. Please note that this is an undocumented implementation detail that we may change if we need to. We recommend users to not rely on this structure.

https://github.com/camunda/camunda/blob/1a51f42951ee507dcaea9029f05e2b91efe6f002/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/Protocol.java#L98-L100

For questions like these, it is always better to open a help request topic on the Camunda forums: [https://forum.camunda.io/](https://forum.camunda.io/). By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.

I'm closing this issue as we aim to use the GitHub issues for development purposes only.

**Comment by ashprojects** [comment]
Thank you @korthout .
I have tried raising multiple things in forum, but not much activeness. 
One of the important one was this:
https://forum.camunda.io/t/strategy-for-scaling-job-workers-in-zeebe/53509
