### ISSUE TITLE
 C8 License - Create API endpoint to expose license status

### ISSUE THREAD

**Issue by matthewBearCamunda** [camunda/camunda#20540]
## Related to

Epic: https://github.com/camunda/product-hub/issues/2359

Dependent On: https://github.com/camunda/camunda/issues/18970

## Overview

A basic GET endpoint was developed with https://github.com/camunda/camunda/issues/18970. Expand on the basic structure and ensure that it adheres to the following

```
GET /license
{
   "validLicense": true,
   "environment": "self-managed"
}
```

The endpoint can be accessed through something like this `http://localhost:8080/v2/license`

- `validLicense` will be `true` or `false`. The value is determined whether the Camunda license is valid or not
- `environment` will return one of two strings, `saas` or `self-managed`. The value reflects the current running mode Camunda is in

Write tests for the `/license` endpoint to ensure its working as intended. 

Documentation for this new API endpoint will need to be made

## Actions

- The new endpoint will read from `ManagementService`, and will use that to gather license information
- Generate a new response entity for the API payload
- Extend the ZeebeClient with the new endpoint

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/21156
```

## Links

- Helpful guide for developing a new REST endpoint for the monorepo

**Comment by tmetzke** [comment]
Hey @matthewBearCamunda, I have just looked at the REST API proposal.
For comparison, in C7, we have an [endpoint that fetches telemetry data](https://docs.camunda.org/rest/camunda-bpm-platform/7.21/#tag/Telemetry/operation/getTelemetryData). While this is of course way broader in scope than what we have here currently, I was wondering about the following:
- Do we only want to provide the fact that it is valid or would we want to return more details, e.g. until when the license is still valid?
- Do we want to hardwire `"selfManaged": true` or does a bit more flexibility help us in the longer run, e.g. `"environment": "self-managed"` which could also be `"environment": "saas"` or maybe `"environment": "hybrid"` at some point? That is a speculative question, I am aware. Just food for thought whether hardcoding "self-managed" is the best option here or not.
- Since this is the Camunda 8 REST API, would `GET /v2/license` suffice? Do we expect any other "license" endpoint that could otherwise collide here?

**Comment by matthewBearCamunda** [comment]
@tmetzke - Going through your bullet points one by one

- For what's currently in scope, the front end needs to know two things. One, if the license is valid or not. Two, if the license status should be shown or not. [The front end header component was updated to handle the message to the user ](https://camunda-composite-components.pages.dev/?path=/story/uishell-c3navigation--basic )
  - The details of the license are not exposed to the front end, but they are logged on startup. If we do want to make this endpoint have more license details like the C7 one,  

- I think that's a great point, I'll switch this over to return a string and which mode it is in. It'll be much more extensible 

- `GET /v2/license` works, I'll change the endpoint to that. I don't expect any other license endpoints to be added at this point

With all that said, this is what the endpoint would be after these updates

```
GET /license
{
   "validLicense": true,
   "environment": "self-managed"
}
```
The endpoint can be accessed through something like this http://localhost:8080/v2/license

- `validLicense` will be `true` or `false`. The value is determined whether the Camunda license is valid or not
- `environment` will return one of two strings, `saas` or `self-managed`. The value reflects the current running mode Camunda is in

**Comment by tmetzke** [comment]
Thanks, @matthewBearCamunda 👍 

Regarding 
> For what's currently in scope, the front end needs to know two things. One, if the license is valid or not. Two, if the license status should be shown or not. The message should only show in self-managed mode, and not in SaaS. [The front end header component was updated to handle the message to the user ](https://camunda-composite-components.pages.dev/?path=/story/uishell-c3navigation--basic) The message is controlled in the `navbar` section

So, should the license be displayed if the FRONTEND is in SaaS or if the cluster lives in SaaS? We can, if I'm not mistaken, also have the web apps run locally and communicate with a SaaS cluster. Should the license be displayed or not? Just trying to figure out if the environment the cluster runs in is relevant information here.

> With all that said, this is what the endpoint would be after these updates
> ```
> GET /license
> {
>    "validLicense": true,
>    "environment": "self-managed"
> }
> ```
> 
> The endpoint can be accessed through something like this http://localhost:8080/v2/license
> 
> * `validLicense` will be `true` or `false`. The value is determined whether the Camunda license is valid or not
> * `environment` will return one of two strings, `saas` or `self-managed`. The value reflects the current running mode Camunda is in

The design makes sense from my point of view. Let's see if the environment stays or goes 👍
