### ISSUE TITLE
A process instance is stuck after modifing to an inclusive gateway

### ISSUE THREAD

**Issue by lzgabel** [camunda/camunda#20587]
**Describe the bug**
I have the following process with an inclusive gateway:

![image](https://github.com/user-attachments/assets/e5c9a1d7-6453-426f-ac86-956324d104a9)

Given:

* The task `A` is active

When:
* Modify task `A` to `Gateway` through the `ModifyProcessInstance` RPC.

Then:
* The process instance is stuck at the inclusive gateway.

**To Reproduce**
1. Deploy the following process [inclusive-gateway-stuck.bpmn](https://github.com/user-attachments/files/16411829/inclusive-gateway-stuck.bpmn.txt)
2. Modify task `A` to `Gateway` via `Operate`

**Expected behavior**
The inclusive gateway should be activated correctly.

**Environment:**
- OS:  
- Zeebe Version:  `8.6.0-SNAPSHOT`
- Configuration:

**Comment by lzgabel** [comment]
This issue is introduced due to the [feature](https://github.com/camunda/camunda/pull/16846)  of inclusive converging gateway. 

Related context：
https://github.com/camunda/camunda/blob/c14c0722ab9943b877009db9a0ff4092c45d5e14/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/ProcessInstanceStateTransitionGuard.java#L222-L228


cc @saig0.

**Comment by saig0** [comment]
@lzgabel good catch. Thank you for raising it. :+1:

**Comment by megglos** [comment]
Hey @lzgabel, thanks for raising and root-causing this, may you also have capacity to work on a fix for this!?

**Comment by lzgabel** [comment]
Hi @megglos. I'll try to fix this issue, but I'm not sure if it can be fixed before `8.6` is released.

**Comment by korthout** [comment]
@lzgabel Could you explain to me how this bug works? Shouldn't a migration from service task A to gateway lead to a rejection because of changing the type?

**Comment by lzgabel** [comment]
👋 Hi @korthout .


>  Shouldn't a migration from service task A to gateway lead to a rejection because of changing the type?

No.

> Could you explain to me how this bug works?

When we try to migrate from task A to the inclusive gateway, we will append an `Activate` command and then process it.  
Due to the inclusive gateway does not have any taken sequence flow, so the command is rejected. For details, please see the following code:

https://github.com/camunda/camunda/blob/c14c0722ab9943b877009db9a0ff4092c45d5e14/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/bpmn/ProcessInstanceStateTransitionGuard.java#L209-L228



See those comments below for more information about edge case:
https://github.com/camunda/camunda/issues/10031#issuecomment-1962983707
https://github.com/camunda/camunda/issues/10031#issuecomment-1966241232

**Comment by korthout** [comment]
>we will append an Activate command and then process it.

We only append `Activate` command with a [Process Instance Modification](https://docs.camunda.io/docs/components/concepts/process-instance-modification/), but not with [Process Instance Migration](https://docs.camunda.io/docs/components/concepts/process-instance-migration/). I think this is why I was confused.

Thanks for clarifying @lzgabel 🙇

**Comment by lzgabel** [comment]
Oh, I'm sorry for my mistake.  I didn't describe the problem correctly and caused misunderstanding. 🙇 

This is indeed a process instance modification, not a migration. @korthout  Thanks for your correction. :heart:

**Comment by mustafadagher** [comment]
ZPA Triage:
- It doesn't seem so urgent to fix before 8.6 since we can also modify the gateway to the task the gateway goes to.
- We can wait for a contribution from @lzgabel

**Comment by tmetzke** [comment]
Some more input here:
* The joining behavior we could document to not being supported if it's too complex to fix
  * A workaround would be manual modification using the next element AFTER the joining gateway instead. This should be feasible enough in most cases.
* The forking behavior however is harder to work around. There are two possibilities here:
  1. You have to manually activate the incoming flow of the gateway. That implies activating the element BEFORE the gateway again. This is not feasible in most cases as it executes the behavior again and you usually don't want that.
  2. You manually activate the outgoing flows that the gateway would activate. While this might be feasible in some cases, it might be harder to determine in others and is inconvenient. You have to take over the logic of the gateway yourself via instance modification.
* While the joining behavior might be harder to support, the forking behavior we can at least investigate again. The exclusive and parallel gateways support this already. Thus, it might be possible for the inclusive gateway as well.

**Comment by tmetzke** [comment]
> @tmetzke Did we make any progress on solving the case with a single incoming sequence flow?
> 
> There's a new issue (related to support) that may be a duplicate: #25099

The customer doesn't need this fix asap so we haven't looked into it any further with priority yet.
The #25099 issue is meant to prevent users from executing this operation on inclusive gateways since we don't have any progress and/or priority here currently.
