### ISSUE TITLE
Make Priority field available on Tasklist V1 REST API - we will still use this on the FE until Job Workers tasks are retired

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#20605]
The new imported _Priority_ field must be present into the API Data models. It also should be included in search & sorting requests.

**Comment by esraagamal6** [comment]
Tested OK below scenarios on OS and ES

[v1/tasks/search retrieves priority value ](https://camunda.testrail.com/index.php?/cases/view/504365)			
[v1/tasks/search user can sort results](https://camunda.testrail.com/index.php?/cases/view/504366)			
[v1/tasks/search Filter by priority](https://camunda.testrail.com/index.php?/cases/view/504367)
