### ISSUE TITLE
C8 License - Show C8 License status in Optimize

### ISSUE THREAD

**Issue by matthewBearCamunda** [camunda/camunda#20639]
## Related to

Epic: https://github.com/camunda/product-hub/issues/2359

Dependent On: https://github.com/camunda/camunda/issues/20540

## Overview

Once the License endpoint in the monorepo is available, the front end needs to consume data from the endpoint and display it to the user. Use the `C3Navigation` component to display the status. The label will only show in Self Managed, it will not show in SaaS

The `ui-configuration` endpoint was updated with the following two fields. These fields contain the license information

```
GET /ui-configuration
{
   ...
   "validLicense": true,
   "licenseType": "self-managed"
   ...
}
```
`validLicense` will be `true` or `false`. The value is determined whether the Camunda license is valid or not
`licenseType` will return one of three strings, `saas`, `production`, or `unknown`. The value reflects the current running mode Camunda is in. `unknown` is returned when a license is invalid or missing

The C3 Navbar component contains a feature which can easily display the license status. [See here for the prop to use](https://camunda-composite-components.pages.dev/?path=/docs/uishell-c3navigation--docs#navbar-prop). The license prop is available in `@camunda/camunda-composite-components` version `0.7.0` and higher

The value of `validLicense` maps directly to the `isProductionLicense` prop for the header. `show` will be `true` when `environment` is equal to `self-managed`

Console Self-Managed has implemented a license status already: https://github.com/camunda-cloud/camunda-cloud-management-apps/blob/ff518c29429d34363e9fd678b66da7762cadb7d2/apps/console-sm-frontend/src/components/navbar.tsx#L104

## Actions

- Consume the `camunda-license` endpoint and read the license status. The status is then displayed on the front end for the user

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/21406
- [ ] https://github.com/camunda/camunda/pull/21629
- [ ] https://github.com/camunda/camunda/pull/21621
```

## Example Screenshot with Navbar props

![Screenshot 2024-08-07 at 7 25 17 AM](https://github.com/user-attachments/assets/a48a6450-dee0-450f-9eba-305a3b9eb181)

**Comment by RomanJRW** [comment]
@misiekhardcore / @OmranAbazid - I just realised that the issue description here is incorrect and therefore the implementation is slightly incorrect too. There is no such license type as "self-managed", rather it will be "production". It is well summarised [here](https://camunda.slack.com/archives/C06V2SR6U9G/p1724334811481549?thread_ts=1724327761.971029&cid=C06V2SR6U9G)

**Comment by misiekhardcore** [comment]
@RomanJRW I am looking at the linked convo, but I can't see anything useful there

**Comment by RomanJRW** [comment]
@misiekhardcore - the difference being that there is no longer such thing as a "self-managed" license, it's now "production". @matthewBearCamunda - please confirm the correct details here

**Comment by matthewBearCamunda** [comment]
@RomanJRW / @misiekhardcore - That's correct. The expected license types are `production`, `saas`, and `unknown`

**Comment by misiekhardcore** [comment]
okay, I updated my PR to use these proper types

**Comment by RobertDorlan** [comment]
Successfully tested agains 3.14.0-alpha5-rc2

**Comment by RomanJRW** [comment]
@RobertDorlan - how was this tested against 3.14.0-alpha5? This change is scoped to Optimize 8.

cc @matthewBearCamunda
