### ISSUE TITLE
[C8 API] Implement `Flownode instance` endpoints

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20657]
### Description

Flow node instance endpoints provides searching for flow node instances and metadata.

[Issue for statistic endpoint](https://github.com/camunda/camunda/issues/21719)

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* Flow node instance objects are defined in
  * [Flow node instance](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.wcm9xzmzyzor) 
 
### Endpoints

- [x] Search Flow node instances - `/v2/flownode-instances/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.gkjsn89wc5pe)
- [x] Get flow node instance - `GET /v2/flownode-instances/{flowNodeInstanceKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.ku4woahmdfen)
   https://github.com/camunda/camunda/pull/22453
~~- [ ] Search Flow node metadata  - `/v2/flownode-instances/metadata` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.q5ljdfnepda4)~~ 8.8

### Acceptance Criteria

- [ ] Unit tests
- [ ] Integration tests

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by tmetzke** [comment]
Added `Get flow node instance` endpoint
