### ISSUE TITLE
[C8 API] Implement `Decision definition` endpoints

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20654]
### Description

Decision definition endpoints provides searching for decision definitions and the DMN description as XML.

[Issue for statistic](https://github.com/camunda/camunda/issues/21717)

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* `{place-holder}` is the placeholder for parameters like `decisionDefinitionKey`
* Decision definitions objects are defined in
  * [Decision definition](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.ttejsuinuoa0) 

### Endpoints

- [x] https://github.com/camunda/camunda/issues/22650
- [x] https://github.com/camunda/camunda/issues/22652
- [x] https://github.com/camunda/camunda/issues/22653

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-helm](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by houssain-barouni** [comment]
Hi @ralfpuchert 
I had added some comments in the API definition doc, can you please have a look
- [Decision Definition fields naming](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit?disco=AAABOxCQEw8), checkout the discussion in [Slack](https://camunda.slack.com/archives/C06UKS51QV9/p1722414816974799)
- [The removal of id field](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit?disco=AAABOxCQEw0) , same thing in the [filter](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit?disco=AAABOxahvLA)
