### ISSUE TITLE
[EPIC] Implement `Variable` endpoints

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20664]
### Description

Variable endpoints provides searching for variable.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* Variable objects are defined in
  * [Variable](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.i5jd4xzabhje) 
 
 
### Endpoints

- [x] #22629
- [x] #22630

**Comment by tmetzke** [comment]
Added `Get variable` endpoint
