### ISSUE TITLE
[C8 API] Implement `Incident` endpoints

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20661]
### Description

Incident endpoints provides searching for incidents.

[Issue for statistic endpoints](https://github.com/camunda/camunda/issues/21721)

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* Incident objects are defined in
  * [Incident](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.62bj2m285hxd) 
 
### Endpoints

- [x] Search incident - `/v2/incidents/search` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.8xthsdktfnb2)
- [x] Get incident - `GET /v2/incidents/{incidentKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.d152kb3ezmjd)

### Acceptance Criteria

- [x] Unit tests
- [x] Integration tests

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by tmetzke** [comment]
Added `Get incident` endpoint
