### ISSUE TITLE
Migrate renovate config file to the new structure

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#20693]
## Description

Some time ago, renovate has updated their config file structure and we should merge our config file to meet the new standards.

Config can be validated using [renovate-config-validator](https://docs.renovatebot.com/config-validation/)
Using this validator shows that the config file needs migration and it also provides the new config

**Comment by misiekhardcore** [comment]
@cmur2 I created this issue as a result of our discussion [here](https://github.com/camunda/camunda/pull/19381#issuecomment-2262613150). This is my first issue in the monorepo which targets the whole repo, so let me know if it needs changing/updating

**Comment by cmur2** [comment]
> I created this issue as a result of our discussion https://github.com/camunda/camunda/pull/19381#issuecomment-2262613150. > This is my first issue in the monorepo which targets the whole repo, so let me know if it needs changing/updating

When creating issues in the monorepo make sure to pick a relevant project since by default issues will go to the Zeebe project (catch-all which might annoy Zeebe engineers)
