### ISSUE TITLE
[Doc Handling / Tasklist] Document upload in user task forms

### ISSUE THREAD

**Issue by chillleader** [camunda/camunda#20709]
### Description

As part of the document handling epic, users should be able to upload files when submitting a form to complete a user task. File upload is performed by invoking the new API endpoint.

- API contract: [Google Doc](https://docs.google.com/document/d/1fe4nYImFqCqGV1y0MXG4xe4a3U7Nb3cq_1n8OgJTSjk/edit#heading=h.aesesrj8lmz8)

User should be able to upload multiple files at once (can be skipped in the first iteration).

As discussed with the team, public forms will be out of scope in the first iteration but should also be eventually supported.

```mermaid
sequenceDiagram
    participant TPS as Third-party system
    participant C as Connectors
    actor User
    participant TFE as Tasklist UI
    box lightyellow Monorepo components
    participant API as C8 REST API
    participant TBE as Tasklist service
    participant Document service
    participant Zeebe
    end
    participant Cloud Storage
    User->>TFE: Provide document in a form via upload component
    TFE->>API: Upload document
    API->>Document service: Create document
    Document service->>Cloud Storage: 
    Cloud Storage-->>Document service: 
    Document service-->>API: 
    API-->>TFE: Return reference
    TFE->>API: Complete user task
    API->>TBE: 
    TBE-)Zeebe: Start process with reference as a variable
    TBE-->>API: 
    API-->>TFE: Task completed
    destroy User 
    TFE-->>User: Form submitted / Process started
    Zeebe->>Zeebe: Process execution
    Zeebe-)+C: Execute connector task
    C->>API: Get document content
    API->>Document service: 
    Document service->>Cloud Storage: 
    Cloud Storage-->>Document service: 
    Document service-->>API: 
    API-->>C: Return document content
    C-)TPS: Provide file
    Note right of TPS: e.g. send email with attachment
    C--)-Zeebe: Connector task finished
    Zeebe->>Zeebe: Process execution
    
    

```

### User Story

```Gherkin
Scenario: As an Tasklist user
    When I submit a form to complete a user task
    I should be able to upload files to the Camunda document store
```

### Acceptance Criteria

- [ ]

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria

Optional:
- [ ] Design input has been collected by the assignee

**Comment by chillleader** [comment]
The mock API implementation will be provided as part of this issue: https://github.com/camunda/camunda/issues/20759

**Comment by vsgoulart** [comment]
Done via https://github.com/camunda/camunda/pull/24086
