### ISSUE TITLE
[C8 API] Implement `Decision requirement` endpoints

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#20704]
### Description

Decision requirement endpoints provides searching for decision requirement.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* `{place-holder}` is the placeholder for parameters like `decisionDefinitionKey`
* Decision requirement objects are defined in
  * [Decision requirement](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.pe9vw4ocuyy8)

### Endpoints

- [x] Search Decision requirements - `POST /v2/decision-requirements/search
` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.3gvs1btxwocy)
- [x] Get decision requirements by key - `GET /v2/decision-requirements/{decisionRequirementsKey}` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.xp6iv6345btw)
- [x] Get decision requirements XML - `GET /v2/decision-requirements/{decisionRequirementsKey}/xml` - [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.u59mvpqo1amd)

### Implementation
- [x] Service implementation - https://github.com/camunda/camunda/pull/20722
- [x] Controller implementation  - https://github.com/camunda/camunda/pull/20769
- [x] Client implementation -  https://github.com/camunda/camunda/pull/20786
- [x] Integration Tests - https://github.com/camunda/camunda/pull/20821

- [x] Get Decision Requirements by Key - https://github.com/camunda/camunda/pull/22651

### Acceptance Criteria

- [x] Unit tests
- [x] Integration tests
### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by esraagamal6** [comment]
@nathansandi  Tested OK below scenarios

[/v2/decision-requirements/search filter by dmnDecisionRequirements Key ](https://camunda.testrail.com/index.php?/cases/view/503735)			
[/v2/decision-requirements/search filter by dmnDecisionRequirements Id](https://camunda.testrail.com/index.php?/cases/view/503818)			
[/v2/decision-requirements/search filter by dmnDecisionRequirements name](https://camunda.testrail.com/index.php?/cases/view/503820)			
[/v2/decision-requirements/search filter by dmnDecisionRequirements version](https://camunda.testrail.com/index.php?/cases/view/503819)			
[/v2/decision-requirements/search filter by dmnDecisionRequirements tenantId](https://camunda.testrail.com/index.php?/cases/view/503821)
And checked sorting options, page limit and searchBefore/After on both elasticSearch and openSearch
1 bug reported: [/v2/decision-requirements/search return 200 for Invalid dmnDecisionRequirementsId Data Type](https://github.com/camunda/camunda/issues/21483)

**Comment by tmetzke** [comment]
Added `Get decision requirements by key` endpoint
