### ISSUE TITLE
C8 License - Show C8 License status in Operate

### ISSUE THREAD

**Issue by matthewBearCamunda** [camunda/camunda#20738]
## Related to

Epic: https://github.com/camunda/product-hub/issues/2359

Dependent On: https://github.com/camunda/camunda/issues/20540

## Overview

Once the License endpoint in the monorepo is available, the front end needs to consume data from the endpoint and display it to the user. Use the `C3Navigation` component to display the status. The label will only show in Self Managed, it will not show in SaaS

The endpoint: 
```
GET /license
{
   "validLicense": true,
   "licenseType": "production"
}
```
`validLicense` will be `true` or `false`. The value is determined whether the Camunda license is valid or not
`licenseType` will return one of three strings, `saas`, `production`, or `unknown`. The value reflects the current license type. `unknown` is returned when a license is invalid or missing

The C3 Navbar component contains a feature which can easily display the license status. [See here for the prop to use](https://camunda-composite-components.pages.dev/?path=/docs/uishell-c3navigation--docs#navbar-prop). The license prop is available in `@camunda/camunda-composite-components` version `0.7.0` and higher

The value of `validLicense` maps directly to the `isProductionLicense` prop for the header. `show` will be `true` when `licenseType` is not equal to `saas`

Console Self-Managed has implemented a license status already: https://github.com/camunda-cloud/camunda-cloud-management-apps/blob/ff518c29429d34363e9fd678b66da7762cadb7d2/apps/console-sm-frontend/src/components/navbar.tsx#L104

## Actions

- Consume the `camunda-license` endpoint and read the license status. The status is then displayed on the front end for the user

```[tasklist]
### Pull Requests
- [ ] tbd
```

## Example Screenshot with Navbar props

![Screenshot 2024-08-07 at 7 25 17 AM](https://github.com/user-attachments/assets/bfbdfdc4-1944-4b18-8ab5-24c9bf624bd7)

**Comment by matthewBearCamunda** [comment]
The `GET /license` endpoint for the monorepo was merged in with https://github.com/camunda/camunda/pull/21156, and its ticket https://github.com/camunda/camunda/issues/20540 is complete

This ticket is ready to be worked on!

**Comment by pedesen** [comment]
###  Acceptance criteria

**in SaaS environment**
* [ ]  No license tag is shown

**in self-managed environment**
* [ ] "Production License" tag is shown if `validLicense` is true
* [ ] "Non-Production License" tag is shown if `validLicense` is false (this is also the case if the license is invalid or missing)

### Implementation details

The fields from the API endpoint are mapped to the C3Nav properties as followed:

```js
{
    show: licenseType !== 'saas',
    isProductionLicense: validLicense,
}
```
