### ISSUE TITLE
Remove dangling references to snapshot checksum.

### ISSUE THREAD

**Issue by EuroLew** [camunda/camunda#20760]
**Description**

Remove the fields in `io.atomix.raft.snapshot.impl.SnapshotChunkImpl` regarding `snapshotChecksum` this field was removed as it was not used anywhere in #20100 however the value had to remain in this implementation for backwards compatibility. Once the removal of combined checksum is in a minor version this change should follow to ensure rolling updates do not break the brokers.

**Comment by deepthidevaki** [comment]
Moving it to backlog because this can be done only after release of 8.6.

**Comment by lenaschoenburg** [comment]
@EuroLew or @deepthidevaki, could you elaborate where `snapshotChecksum` is still used that can now be removed? Because pretty much the only reference I find is in the SBE message where we can't easily remove it without breaking compatibility.

**Comment by deepthidevaki** [comment]
I can't remember any more. @EuroLew can you take a look?
