### ISSUE TITLE
Update rejection message for resubscribing to the same message name during instance migration

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#20906]
## Description

Error message for rejection and the explanation in the document should be aligned. E.g. use closing and opening instead of re-subscribing.

**Comment by ThorbenLindhauer** [comment]
resubscribing = two `attachedTo` activities are mapped to each other, but their message boundary events are not

The edge case is when that happens and the boundary events have the same message name.

**Comment by berkaycanbc** [comment]
@ThorbenLindhauer I am trying to refresh my mind why we needed this issue. We already have the rejection message as follows https://github.com/camunda/camunda/blob/a91f33721d983bd4afad0d5a906d9b8054f8afc1/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/processinstance/ProcessInstanceMigrationPreconditions.java#L905-L914

Do you remember why we needed to change the rejection message?

**Comment by ThorbenLindhauer** [comment]
I don't know. Reading through the error message, I think it could be more precise what is really happening here. I think especially this sentence is confusing for a user: 

> Migrating active elements that subscribe to a message they are already subscribed to is not possible yet.

Try to forget all you know about the internal workings of instance migration and re-read it as a user who only knows the migration UI and some basic docs.
