### ISSUE TITLE
Add a common exporter for webapps

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#20910]
This issue is part of https://github.com/camunda/product-hub/issues/2128. 

The goal is to have a single exporter that can transform Zeebe records to webapps entities and write them to ElasticSearch/OpenSearch indices. The initial scope is to integrate Operate and Identity to the new exporter.

The scope of this issue is to add basic functionalities which can then be extended by the corresponding component to add their business logic.

For reference see the draft PR #20240

*Tasks* 
- [x] #20951
- [x] #20952
- [x] #21132
     * Can register handler(s) for each record type (value type)
     * Can transform the records using the registered handler(s)
     * Define interfaces to the storage (supported storage will be ElasticSearch and OpenSearch)
     * Write the transformed entities to the backend 
     * Provide concrete implementations for ElasticSearch backend
- [x] #22865
- [x] #22854
- [x] #22866
- [x] #22867
- [x] #21177
- [x] #22869

Misc/Bugs
- [x] #23083

**Comment by korthout** [comment]
Do we plan to extract and re-use parts of the ES/OS exporters for the Camunda Exporter's interaction with ES/OS? This would help avoid us having to maintain two implementations for exporting to ES and two for exporting to OS.

**Comment by deepthidevaki** [comment]
> Do we plan to extract and re-use parts of the ES/OS exporters for the Camunda Exporter's interaction with ES/OS? This would help avoid us having to maintain two implementations for exporting to ES and two for exporting to OS.

It is not currently in the scope. But can be considered later.
