### ISSUE TITLE
Export cluster load metric

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#20944]
**Is your feature request related to a problem? Please describe.**

As a user, I want to visualize how close my cluster is to its limits. Specifically in SaaS, I want to know if I should use a bigger cluster or not when my workload changes.

**Describe the solution you'd like**

A single metric, gauge, which shows the current cluster load, from 0 to 100%. The percentage is based on current write rate over current write rate limit. Under normal load, clusters will show a reasonable load metric such as 15%. While throttled, the cluster load will be at 100% which is a sensible value that is easy to understand.

> [!Note]
> Admittedly the fact your write limit is the maximum doesn't mean there is no load, but this would be for a first iteration. We can make it smarter in the future and include different ways to compute it.

**Describe alternatives you've considered**

**Additional context**

- https://github.com/camunda/product-hub/issues/1426
- https://github.com/camunda/product-hub/issues/2346

**Comment by lenaschoenburg** [comment]
> when you are throttled down the minimum writes, your load is 100%. When you are at the maximum, your load is 0%.

I'd suggest a different calculation: current write rate / current limit.

That way we get useful values (e.g. "15% utilization") before throttling starts. Once a cluster _is_ throttled, we expect utilization to always be 100% which also makes sense from a UX perspective.

**Comment by npepinpe** [comment]
Can you update the issue description with this?

**Comment by rodrigo-lourenco-lopes** [comment]
@lenaschoenburg here it probably makes sense to reuse the metric FLOW_CONTROL_OUTCOME agregating by partition right? In this case, we would only have to add the new panels.

**Comment by lenaschoenburg** [comment]
I think we need a new metric because the goal is to have a single metric that shows load as percentage and not require any calculations on top.

**Comment by rodrigo-lourenco-lopes** [comment]
What should we display if the write rate limit and throttling are not enabled? 🤔 
It makes more since to leave if blank, right?

**Comment by lenaschoenburg** [comment]
Hm good question. I don't see a better option than leaving it blank.
