### ISSUE TITLE
Stream platform time is controllable

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#21051]
To support a [clock control API](https://github.com/camunda/product-hub/issues/2379), we will extend the stream platform.
The idea is that the engine uses and controls a partition-scoped clock that is then used to assign record timestamps, trigger scheduled tasks, and generally drive all business logic.

### Acceptance Criteria
- [x] All records are written with a controllable timestamp
- [x] Engine only uses controllable clock, no other sources of time
- [x] Scheduled tasks are executed according to the controllable clock
- [x] Controllable clock is only used within one partition

```[tasklist]
### Implementation
- [x] `RecordProcessorContext` contains a controllable clock
- [x] `Engine` uses controllable clock instead of `ActorClock`
- [x] `Engine` can modify the controllable clock by pinning or applying an offset
- [x] `Sequencer` uses controllable clock to assign record timestamps
- [x] `ProcessingScheduleService` uses controllable clock
- [x] `MetricsExporter` uses controllable clock
- [ ] `ProcessingStateMachine` uses controllable clock for latency metrics
```

**Comment by npepinpe** [comment]
Do we need to pin the clock, or is applying an offset sufficient? Just wondering.

**Comment by lenaschoenburg** [comment]
Based on the [feedback from consulting](https://camunda.slack.com/archives/C037RS2JHB8/p1723024208080989?thread_ts=1723023003.670619&cid=C037RS2JHB8), they might only use `pin`, not offset. That's because they want exact control over the timestamps.

**Comment by npepinpe** [comment]
Let's clarify this, since that's less stuff for us to do. I assume we would still need a `reset` intent or something, though.

**Comment by npepinpe** [comment]
[See this issue for the persistence/synchronization part](https://github.com/camunda/camunda/issues/21068)
