### ISSUE TITLE
MessageCorrelationRejectionTest#shouldWriteNotCorrelatedEvent

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#21083]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 32
- Does it block your work? yes
- Do we suspect that it is a real failure? not clear

**Failures**
![2024-08-13_14-55](https://github.com/user-attachments/assets/79228089-b5e5-48cd-ac7e-94208a852ddf)
https://dashboard.int.camunda.com/d/bdmo5l8puugaoc/ci-health-camunda-camunda-monorepo?orgId=1&viewPanel=16
> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Paste the failure here
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by remcowesterhoud** [comment]
Closing this in favor of #21084 as that one contains the logs
