### ISSUE TITLE
Improve Java client with REST API exceptional flow

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#21173]
**Is your feature request related to a problem? Please describe.**

As a user, if I'm using the REST API it's possible that my request gets denied for several reasons. Using the Java client the way I'd make my request is like this:

```java
client
    .newFooCommand()
    .propertyBar(bar)
    .send()
```

This `send()` method will return me a `ZeebeFuture<FooResponse>`. There's no guarantee my request succeeded so I need to do some exception handling when joining this future:

```java
try {
    final var response = future.join();
} catch (ProblemException e) {
   // handle unhappy path
}
```

The above is what I'd expect to be able to do. However, the exception thrown by the future is not a `ProblemException`. Instead I get a `CompletionException` with the `ProblemException` as a cause. That means if I as a user want to know what the problem was, I need to handle the exceptional future like this:

```java
try {
    final var response = future.join();
} catch (CompletionException e) {
    if (e.getCause() instanceof ProblemException) {
    final ProblemException acutalException = (ProblemException) e.getCause();
        // handle unhappy path
    }
}
```

It's quite tedious for users to get to the original failure of the request.

**Describe the solution you'd like**
Joining the future should return the `ProblemException` directly in cases like this.

<details><summary><b>Example test case</b></summary>

```java
  @Test
  void shouldNotCorrelateWhenNoExistingSubscription() {
    // given
    final var messageName = "messageName";
    final var correlationKey = "correlationKey";

    // when
    final var responseFuture =
        client
            .newCorrelateMessageCommand()
            .messageName(messageName)
            .correlationKey(correlationKey)
            .send();

    //     then
    assertThatThrownBy(responseFuture::join)
        .isInstanceOf(ProblemException.class)
        .hasMessageContaining("title: NOT_FOUND")
        .hasMessageContaining("status: 404")
        .hasMessageContaining(
            "Expected to find subscription for message with name '%s' and correlation key '%s', but none was found."
                .formatted(messageName, correlationKey));
  }
```

</details>

**Comment by remcowesterhoud** [comment]
Fyi @tmetzke @nicpuppa @koevskinikola

**Comment by nicpuppa** [comment]
Hey @remcowesterhoud, I think this it might be related to https://github.com/camunda/camunda/issues/17441

**Comment by remcowesterhoud** [comment]
> Hey @remcowesterhoud, I think this it might be related to #17441

I don't think it is. That issue seems to be about errors that occur on the Broker, which always are mapped to an internal server error (500) in the REST API, instead of to their more specific counterparts (501, 502, etc).

This issue is really about the Java client. When it makes a request and it receives an exception response from the REST API (code 400+), user should be able to work with the exceptional response. Currently that's not straightforward as shown in the examples I listed. If you use the client you get an exception containing the actual relevant exception listed within. As a result a user has to get the root cause, check what kind of exception is the root-cause. Cast it to this exception and only then they can actually access the error message and status code.

**Comment by tmetzke** [comment]
I added this to https://github.com/camunda/camunda/issues/18254

**Comment by tmetzke** [comment]
We currently won't have time to deliver this with 8.6.
If we see any priority to still add it there, we need additional resources to achieve that.
It is still on the roadmap for 8.7 though.
