### ISSUE TITLE
Setting number of shards in ES does not work for Optimize

### ISSUE THREAD

**Issue by igor-msk** [camunda/camunda#21206]
### Describe the bug

Setting number of shards in ES stopped working  for Optimize (it worked fine in older versions)
It stays with 1 shard no matter what I set in number_of_shards
By the way - setting number_of_replicas works fine
![image](https://github.com/user-attachments/assets/c7b4d4b3-e1aa-4abd-8342-86d26d64e74e)

AND IT WOULD BE NICE IF I COULD SET THE NUMBER OF REPLICAS|SHARDS FOR OPTIMIZE IN VALUES.YAML WITH ENV instead of modifiing its configMap. At the moment it is impossible because the properties have an underscore in its name and it is treated as a sublevel when converted back from var name (env var names would be CAMUNDA_OPTIMIZE_ES_SETTINGS_INDEX_NUMBER_OF_SHARDS & CAMUNDA_OPTIMIZE_ES_SETTINGS_INDEX_NUMBER_OF_REPLICAS)

### Expected behaviour
I get the number of shards I set in configmap.

### To Reproduce
This is my configMap for optimize (2 lines at the end)
```
{{- if .Values.optimize.enabled -}}
kind: ConfigMap
metadata:
  name: {{ include "optimize.fullname" . }}-configuration
  labels:
    {{- include "optimize.labels" . | nindent 4 }}
apiVersion: v1
data:
  {{- if .Values.optimize.configuration }}
  environment-config.yaml: |
    {{ .Values.optimize.configuration | indent 4 | trim }}
  {{- else }}
  environment-config.yaml: |
    {{- if .Values.optimize.contextPath }}
    container:
      contextPath: {{ .Values.optimize.contextPath | quote }}
    {{- end }}

    {{- if .Values.global.elasticsearch.enabled }}
    es:
      settings:
        index:
          number_of_replicas: 2
          number_of_shards: 3
...
```

### Environment observed:

- Optimize version(s): 8.5.4 & 8.5.3
- Database(s) (Elasticsearch/OpenSearch): ES

### Breakdown

```[tasklist]
### Pull Requests
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [ ] Yes. If so:
  - [ ] The bug description is clear
  - [ ] The steps to reproduce are clear
  - [ ] The environments observed are correct and complete
- [ ] No

#### Review Resources

- Feature PR: {Link to PR targeting the main branch}
- Preview environments: {Link(s) to preview environments}

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RomanJRW** [comment]
Hi @igor-msk
The number of shards can only be configured and is applied to process instance indices. This explains why in your case you cannot see the custom shards being applied to the event trace index.

This is not a regression, and is something briefly explained in our [documentation](https://docs.camunda.io/optimize/next/self-managed/optimize-deployment/configuration/system-configuration/#index-settings).

I am going to close this issue accordingly, but please feel free to comment here if you have any further questions.
