### ISSUE TITLE
Revert Lucene version update

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#21321]
### Description

Lucene was updated to version 9 with a [recent Renovate PR](https://github.com/camunda/camunda/pull/21280). However, that version is not compatible with the ES 7 client that we use. Accordingly, the CI fails ([example](https://github.com/camunda/camunda/actions/runs/10448951740/job/28940770934); the ES 7 Java client library doesn't find the constant `org.apache.lucene.util.Version LUCENE_7_0_0'`). Note that the corresponding Lucene version was ignored on main by closing [the PR](https://github.com/camunda/camunda/pull/20711).

### TODO

* Revert version update on 8.5 branch
* Add a note that this version must remain coupled with the ES client on main and 8.5 branches

### Additional Information

* main PR: https://github.com/camunda/camunda/pull/21323
* 8.5 PR: https://github.com/camunda/camunda/pull/21322

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by npepinpe** [comment]
Should we then configure Renovate to not update Lucene except patch then?

**Comment by ThorbenLindhauer** [comment]
@npepinpe Yes, sounds like a good idea. Wasn't aware that's possible, do you have a pointer where to do this?

**Comment by lenaschoenburg** [comment]
Looks like this should already be prevented: https://github.com/camunda/camunda/blob/5665602e53a6c60ef5482a59ba8092e3061cb36a/.github/renovate.json#L50-L56

**Comment by ThorbenLindhauer** [comment]
Thanks for sharing that. Renovate raising PRs regardless seems to be an issue related to [recent version and configuration updates that we made](https://github.com/camunda/camunda/pull/21060#discussion_r1723022376). [Christian will follow up on that aspect](https://camunda.slack.com/archives/C071KP5BTHB/p1724147032048869).

**Comment by ThorbenLindhauer** [comment]
[I have also updated the branch protection rules](https://camunda.slack.com/archives/C02ECLP1M7W/p1724228942726929) for `stable/operate-8.5` to prevent a similar auto-merge in the future.
