### ISSUE TITLE
Add `Authorization search` REST endpoint

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#21341]
### Description
- [x] Add `/search` endpoint following [the guidelines](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)

**Comment by tmetzke** [comment]
@Ben-Sheppard, please add more context for the endpoint here so a reviewer can check if the requirements and specification was adhered to.
You can have a look at https://github.com/camunda/camunda/issues/23812 for an example. It's probably also not perfect but hopefully gives a good idea what to include.

I will create a template for REST endpoint issues to streamline this a bit more.
