### ISSUE TITLE
Command distribution can write a custom continuation command

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#21449]
Command distribution is fire-and-forget in the sense that processors that submit records for distribution don't get a notification when distribution is completed. While command distribution itself does write `ACKNOWLEDGE` and `FINISHED` events, these are not observable by other processors.

For scaling partitions, we need to redistribute all resources to new partitions. Because resources tend to be large, this needs to be incremental. Additionally, redistributing resources is just the first of many steps, so we need a way to _continue_ after distribution of all resources is finished.

To support this, we propose the ability to register a _continuation command_ for a [queue](https://github.com/camunda/camunda/issues/21447). The command can be registered at any time, not only when the queue is "created" for the first time.

When a continuation command is registered and the queue is already empty or later becomes empty, the continuation command is written to the log.

Depends on https://github.com/camunda/camunda/issues/21447.

## Acceptance Criteria
- [ ] Any arbitrary command can be registered as continuation
- [ ] The command is persisted in the state and survives a restart
- [ ] On registration, if the queue is empty, the command is written immediately
- [ ] If the queue is not empty on registration, the command is written when the queue becomes empty

**Comment by npepinpe** [comment]
ZDP Triage:
- I'm putting it in the backlog on the basis that it depends on other issues first.
