### ISSUE TITLE
Fix version validation for patch release builds

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#21499]
### Description

* The validation of Zeebe and Identity versions is currently broken. When the versions of Operate/Zeebe/Identity are not aligned (i.e. different patch levels), then the [validation check](https://modeler.ultrawombat.com/diagrams/6ceb331b-db4b-40d1-9ad0-05d02d81520f--validate-versions?v=469,322,1) never succeeds because it expects the versions to be exactly the same. We typically resolve that by process instance modification. It broke when we decided to decouple patch levels of components.

### TODO

* Let the release manager put in the Zeebe and Identity versions
* Let the version check github workflow use those versions for validation instead of the Operate version
* Fix on branches and in release processes for versions 8.5, 8.4, 8.3, 8.2

#### main

* Remove version validation workflow: https://github.com/camunda/camunda/pull/21600

#### 8.5

* Changed 8.5 release workflow: https://modeler.ultrawombat.com/diagrams/d1b69504-9d76-4272-914c-2f84fc3af3ff--initialize-release
  * Fetches the identity releases
  * Extracts the Zeebe and Identity release versions from the selected releases in the user task (check output mappings of the user task)
* 8.5 validation workflow PR: https://github.com/camunda/camunda/pull/21502
* Changed validation release process to call the workflow with the updated parameters: https://modeler.ultrawombat.com/diagrams/ef8e109c-acb4-4471-b9f0-35214cd2c319--validate-versions?v=439,295,1

#### 8.4 and lower

* Changed <= 8.4 release workflow: https://modeler.ultrawombat.com/diagrams/efe19c23-5eaf-4e87-9ba7-92283a8da409--initialize-release
  * Same changes as for 8.5
* 8.4 validation workflow PR: https://github.com/camunda/operate/pull/6801
* 8.3 validation workflow PR: https://github.com/camunda/operate/pull/6802
* 8.2 validation workflow PR: https://github.com/camunda/operate/pull/6803
* Changed validation release process to call the workflow with the updated parameters: https://modeler.ultrawombat.com/diagrams/6ceb331b-db4b-40d1-9ad0-05d02d81520f--validate-versions?v=439,295,1

TODO next:
* Get the workflow PRs merged
* Change the release processes to hand the correct parameters to the changed workflows

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by ThorbenLindhauer** [comment]
@pedesen could you please do another round of reviews:

* I have merged the PRs that fix the validation workflow
* I have raised a PR to remove the workflow from the main branch where we no longer require it: https://github.com/camunda/camunda/pull/21600
* I have adapted the validation release processes:
  * 8.5: https://modeler.ultrawombat.com/diagrams/ef8e109c-acb4-4471-b9f0-35214cd2c319--validate-versions?v=439,295,1
  * 8.4 and lower: https://modeler.ultrawombat.com/diagrams/6ceb331b-db4b-40d1-9ad0-05d02d81520f--validate-versions?v=439,295,1
  * I'm sorry I didn't use the milestone feature here. The diff is in the Validate Versions activity and how it calls the workflow.

**Comment by pedesen** [comment]
@ThorbenLindhauer I approved https://github.com/camunda/camunda/pull/21600 and checked the processes. Both looks good to me.

**Comment by ThorbenLindhauer** [comment]
Pending backport PRs:

* 8.8: https://github.com/camunda/camunda/pull/40096
* 8.7: https://github.com/camunda/camunda/pull/40100
* 8.6: https://github.com/camunda/camunda/pull/40098
