### ISSUE TITLE
Question: why operate API always return 403 #798

### ISSUE THREAD

**Issue by iambiglee** [camunda/camunda#21541]
> Note: Remember to link this QA issue to the parent Epic

### Description

Hello zeebe team

For some business of my company, I am trying to use zeebe.
My operatation like below
1. run docker compose up with this file : https://github.com/camunda/camunda-platform/blob/main/docker-compose/camunda-8.6/docker-compose-core.yaml.   and it successful running 
2. run
```shell
 $ curl -c cookie.txt -X POST 'http://localhost:8081/api/login?username=demo&password=demo'  
```
 successful
and cookie .txt like below

```TXT
# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	OPERATE-X-CSRF-TOKEN	e0129165-5557-4d13-90bb-e31b339c4716
#HttpOnly_localhost	FALSE	/	FALSE	0	OPERATE-SESSION	5CC602E63D5959F863788E11DFEE0DA2
```
4. error occur when I run 
```shell
$ curl -b cookie.txt -X POST  'http://localhost:8081/v1/process-instances/search' -H 'Content-Type: application/json' -d '{}'
```
error is 
```json
{"timestamp":"2024-08-22T13:24:13.306+00:00","status":403,"error":"Forbidden","message":"Forbidden","path":"/v1/process-instances/search"}
```
I'd like to know why this happen, is there any setting I missed?

### Supported Environments

- [ ✅ ] Self Managed ， docker compse

### Documentation

Please add here any available documentation or discussion regarding the feature.

### Test Cases link

[Link to Test Rail](https://camunda.testrail.com/index.php?/suites/view/1&group_by=cases:section_id&group_order=asc&display_deleted_cases=0)

**Comment by iambiglee** [comment]
nobody is cara about this problem?

**Comment by ThorbenLindhauer** [comment]
Hi,

you have to provide the CSRF token via the `OPERATE-X-CSRF-TOKEN` header. Closing as a duplicate of https://github.com/camunda/camunda-docs/issues/3825. Please raise usage questions in the forum in the future.

Cheers,
Thorben
