### ISSUE TITLE
When no license key is provided check fails with `License Key has wrong format`

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#21566]
## Description

The newest license key check seem to fail in our weekly benchmark (when no license key is provided) with: `License Key has wrong format`.

**Why I think is this an issue?**

It should be fine to deploy the application without a license, this means we are using it in a development environment. For development purposes, it is fine to do such (this is supported by our license) _That is the case for our benchmarks for example._

**Expectation:**

* The license key should not fail when no key is provided
* It should not log on `ERROR`, probably warn makes more sense. Furthermore, we want to display it in the UI.

Removing the error logs is important here, as otherwise this unnecessary floods our error reporting tooling.

**Related error logs and error groups:**

 * https://console.cloud.google.com/errors/detail/CIuF-sCc46vafA;service=zeebe;time=P7D;locations=global?project=zeebe-io `License Key has wrong format.`
 * https://console.cloud.google.com/errors/detail/COmL9oDChoiiaw;service=zeebe;time=P7D;locations=global?project=zeebe-io `No license detected when one is expected. Please provide a license through the CAMUNDA_LICENSE_KEY environment variable.`

**Comment by matthewBearCamunda** [comment]
This will be fixed by https://github.com/camunda/camunda/pull/21199

The logging level for license errors has been downgraded to `warn`

**Comment by matthewBearCamunda** [comment]
@Zelldon https://github.com/camunda/camunda/pull/21199 is merged into `main`

When does the weekly benchmark run, and where can I look at the results? I can close this ticket if the errors are resolved the next time it is run

**Comment by matthewBearCamunda** [comment]
Closing ticket. https://github.com/camunda/camunda/pull/21199 removed the error being logged on startup
