### ISSUE TITLE
CI: some Zeebe checks randomly take long to execute

### ISSUE THREAD

**Issue by cmur2** [camunda/camunda#21602]
**Summary**

Starting recently authors of unrelated PRs noticed that some of 3 [zeebe-ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/zeebe-ci.yml) jobs ran into their timeouts more frequently. The affected jobs are `go-client`, `smoke-tests` on MacOS and `smoke-tests` on Windows which all have had a 20-minute timeout. In [some](https://github.com/camunda/camunda/actions/runs/10559502550) cases these builds complete in less than [10 minutes](https://github.com/camunda/camunda/actions/runs/10559932185). On slow builds (but not on fast ones!) Maven outputs many messages like:

`[INFO] Artifact com.fasterxml.jackson:jackson-bom:pom:2.17.2 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context, verifying that is downloadable from [central (https://repo1.maven.org/maven2, default, releases), zeebe (https://artifacts.camunda.com/artifactory/zeebe-io/, default, releases), zeebe-snapshots (https://artifacts.camunda.com/artifactory/zeebe-io-snapshots/, default, snapshots), camunda-identity (https://artifacts.camunda.com/artifactory/camunda-identity/, default, releases), camunda-identity-snapshots (https://artifacts.camunda.com/artifactory/camunda-identity-snapshots/, default, snapshots), camunda-cpm (https://artifacts.camunda.com/artifactory/camunda-bpm/, default, releases), camunda-bpm-snapshots (https://artifacts.camunda.com/artifactory/camunda-bpm-snapshots/, default, snapshots), elasticsearch (https://artifacts.elastic.co/maven/, default, releases)]`

A connection to Maven caching behavior is suspected but couldn't be proven since also on slow builds a GHA cache is successfully restored, e.g. with logs like:

```
Received 0 of 573504878 (0.0%), 0.0 MBs/sec
Received 71303168 of 573504878 (12.4%), 34.0 MBs/sec
Received 171966464 of 573504878 (30.0%), 54.6 MBs/sec
Received 276824064 of 573504878 (48.3%), 66.0 MBs/sec
Received 381681664 of 573504878 (66.6%), 72.8 MBs/sec
Received 482344960 of 573504878 (84.1%), 76.6 MBs/sec
Cache Size: ~547 MB (573504878 B)
/usr/bin/tar -xf /home/runner/work/_temp/527543bc-bd91-4a0a-8b92-2524ed54b73b/cache.tzst -P -C /home/runner/work/camunda/camunda --use-compress-program unzstd
Received 573504878 of 573504878 (100.0%), 78.1 MBs/sec
Cache restored successfully
Cache restored from key: github-hosted-Linux-mvn-shared-bb1f617435c2f406c68f7951cb13b420a9ddfeda63272eedb4294d90f73a9b19
```

See also [Slack discussion](https://camunda.slack.com/archives/C071KP5BTHB/p1724244579643549) that didn't come to a conclusion besides increasing the timeouts.

Some affected PRs (unsuccessful merge queue builds due to this failure):

* https://github.com/camunda/camunda/pull/21063
* https://github.com/camunda/camunda/pull/21495
* https://github.com/camunda/camunda/pull/21607

In one case this could only be prevented via https://github.com/camunda/camunda/commit/62ee0bacbd726aaf2ad575d9810f63331b8ee0c4 increasing the timeout from 20 to 25 minutes (!) and I suspect a similar fix may be needed for `go-client` to increase stability short term. (EDIT: it was done https://github.com/camunda/camunda/pull/21607/commits/769ff686a47feccafeccf1a9c7388a98ce7f7c70 as well)

This is a problem since starting with https://github.com/camunda/camunda/pull/21074 the Zeebe CI is invoked from the [Unified CI](https://github.com/camunda/camunda/wiki/CI-&-Automation#unified-ci) which aims for pretty strict timeouts of [at most 10 minutes on the job level](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria) (happy to do compromises but runtimes should trend downwards, not upwards). If jobs cannot comply with those requirements, that may ultimately mean they have to be removed from the Unified CI again to avoid creeping runtime increase that lowers developer productivity.

**Failures**

* https://github.com/camunda/camunda/actions/runs/10557641021/job/29245603632
* https://github.com/camunda/camunda/actions/runs/10558105948/job/29246950646
* https://github.com/camunda/camunda/actions/runs/10560602508/job/29254485199
* https://github.com/camunda/camunda/actions/runs/10583957648/job/29327124992

**Comment by cmur2** [comment]
fyi @npepinpe, not sure to which Zeebe board to add - from my POV investigating this has a high priority as outlined in the description

**Comment by npepinpe** [comment]
It should be either, but if I'm honest, will likely end up on my team's, what with capacity constraints, knowledge base, and so on :sweat_smile:

**Comment by npepinpe** [comment]
Let's put it on both anyway for visibility

**Comment by cmur2** [comment]
Happened for `go-client` job again on merge queue check for unrelated PR: https://github.com/camunda/camunda/actions/runs/10578267369/job/29308041315

**Comment by npepinpe** [comment]
Honestly, from the message, I don't know what's going on, and I suspect nobody on either teams will have a good idea. I'm confused where this remote ID not available is. Is it possible that the cache is being saved by different jobs which sometimes have access to our own artifact repository, and sometimes they don't so it needs to be redownloaded?

I assume if we fix how the cache is populated everywhere this would go away.

**Comment by cmur2** [comment]
> Is it possible that the cache is being saved by different jobs which sometimes have access to our own artifact repository, and sometimes they don't so it needs to be redownloaded?

This is also my best guess for a hypothesis but I didn't fully look into which Zeebe jobs populate the cache where under which conditions. I assume this to be specific to Zeebe jobs due to this only happening for cases where `setup-zeebe` was used afais.

**Comment by cmur2** [comment]
@npepinpe you may be exited to learn that this ticket can probably be closed if https://github.com/camunda/camunda/pull/21669 fixes the root cause of this and https://github.com/camunda/camunda/issues/21664 in one go 🥳

**Comment by cmur2** [comment]
Execution times are back to <10mins, see e.g.:

* https://github.com/camunda/camunda/actions/runs/10595252214/job/29360629856
* https://github.com/camunda/camunda/actions/runs/10595252214/job/29360630119
* https://github.com/camunda/camunda/actions/runs/10595252214/job/29360630922
