### ISSUE TITLE
The return value issue of DelegateExecution. getProcessInstance()

### ISSUE THREAD

**Issue by J-cafe** [camunda/camunda#21657]
## Description

Why does DelegateExecution. getProcessInstance() return a type of DelegateExecution instead of ProcessInstance? Is this a mistake?

## Decisions

_Will be filled in by the project DRIs after a peer review phase._

**Comment by aleksander-dytko** [comment]
Hi @J-cafe, thank you for raising this ticket in Camunda 8 repository. 

Could you please elaborate on your issue? What behaviour do you expect from Camunda 8, and what is the use case for it?

For transparency, we have removed labels, as they are used to track internal Camunda 8 REST API design proposals. Once you provide a bit more detail, we will assign new labels based on the issue type. 

Thank you,
Aleksander

**Comment by korthout** [comment]
Closing this as stale
