### ISSUE TITLE
CI: monitor Maven flaky tests without failing the build

### ISSUE THREAD

**Issue by cmur2** [camunda/camunda#21674]
## Description

This ticket captures the goal if reducing the impact that detected flaky tests (e.g. in Zeebe, Operate, Optimize) cause on the build process and developer productivity. It is an outcome of [this Slack discussion](https://camunda.slack.com/archives/C071KP5BTHB/p1724831897911649?thread_ts=1721394058.950209&cid=C071KP5BTHB) that helped to understand which options we have regarding dealing with flaky tests.

Flaky tests of Java tests executed with Maven are tests that fail on some of multiple retries (`failsafe.rerunFailingTestsCount=x` sets [the number of retries](https://maven.apache.org/surefire/maven-failsafe-plugin/examples/rerun-failing-tests.html)) but eventually succeed. We use the https://github.com/zeebe-io/flaky-test-extractor-maven-plugin which is currently configured to fail the build if flaky tests were encountered even though eventually all tests succeeded.

Example: https://github.com/camunda/camunda/actions/runs/9711321464/job/26803827757

### Impact

Due to the nature of the monorepo CI containing tests from multiple different teams there are 2 behaviors that happen when builds fail on e.g. PRs/in the merge queue:

1. if the author/DRI identifies the problem to be related to their change, they will iterate on it
2. if the author/DRI sees a problem related to flaky tests (of another component) and the check is [required](https://github.com/camunda/camunda/wiki/CI-&-Automation#faq-1), they will just retry the CI

Case 2 has a negative impact on developer productivity since it requires manual attention, context switches and extends lead time before changes get to `main`(without the developer actually making a decision, just click the "rerun"). The higher the number of teams collaborating on the monorepo, the more likely it gets that case 2 will happen. Also, a larger number of tests required to be green increases the likelihood of flaky tests manifesting.

### Possible solution

Configure https://github.com/zeebe-io/flaky-test-extractor-maven-plugin to use `failBuild: false` and come up with a less disruptive way of monitoring and notifying stakeholders of flaky tests besides failing an (unrelated) build:

* get information about flaky tests via https://github.com/camunda/camunda/wiki/CI-&-Automation#ci-health-metrics e.g. via the `user-reason` field alongside a `build_status: success` result.
    *  improved even more with https://github.com/camunda/team-infrastructure/issues/608
* Zeebe team can get visibility e.g. via Grafana

**Comment by cmur2** [comment]
> * Zeebe team gets notification via Slack like in [example](https://camunda.slack.com/archives/C013MEVQ4M9/p1724348100216119) via GHA glue code that triggers when steps.analyze-test-run.outputs.flakyTests != ''

@npepinpe given the movement of https://github.com/camunda/camunda/pull/21727 which removes all Slack notifications and you approved, do you still want to have this for flaky tests?

**Comment by npepinpe** [comment]
I would still like to get alerted on the flaky tests, but if we opt to go for alerting in Grafana, then let's go with that :+1: It can be done whenever alerting is available, no need to wait for it before we start with the rest of this issue.

**Comment by cmur2** [comment]
Starting Friday, 2024-08-30 around noon UTC all jobs that detect flaky tests do exit with status `success` and not with `failure` anymore so rollout was successful:

![image](https://github.com/user-attachments/assets/ad168a8a-cf8d-4a25-90b5-b158b37b62bd)

I will look into alerting in #21820 later.
