### ISSUE TITLE
Operate does not allow changing Content Security Policy header in SM

### ISSUE THREAD

**Issue by mihail-ca** [camunda/camunda#21741]
### Describe the bug

CSP header cannot be changed via parameter `camunda.operate.websecurity.contentSecurityPolicy` in SM environment, as documented in https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#security. Instead, it always contains the default values.

Introduced by: https://github.com/camunda/operate/issues/6484

Should be back-ported to:
- [x] Operate 8.4
- [x] Operate 8.5
- [x] Operate 8.6

### To Reproduce

1. Set custom CSP values via parameter `camunda.operate.websecurity.contentSecurityPolicy`
2. Access with the browser to a SM instance of the Operate UI
3. Browse the network tab and point to an API call
4. Look at response headers, Content-Security-Policy should contain the custom values
<img width="404" alt="image" src="https://github.com/user-attachments/assets/ac6e8dd3-4c28-423b-b6a7-4faf909dbfa3">

### Current behavior

CSP cannot be changed via parameter `camunda.operate.websecurity.contentSecurityPolicy` in SM environment, always contains the default values

### Expected behavior

CSP can be changed via parameter `camunda.operate.websecurity.contentSecurityPolicy` in SM environment

### Environment

- OS: [e.g. MacOS]
- Browser: [e.g. chrome, safari]
- Operate Version: [e.g. 8.1]

### Additional context
**SUPPORT CASE**: [SUPPORT-23378](https://jira.camunda.com/browse/SUPPORT-23378)

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [x] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [x] The issue has a meaningful title, description, and testable acceptance criteria
- [x] The issue has been labeled with an appropriate `Bug-area` label
- [x] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

#### :mag: Root Cause Analysis

* Caused by this statement: https://github.com/camunda/camunda/blob/8.6.0-alpha5-rc2/operate/webapp/src/main/java/io/camunda/operate/webapp/security/BaseWebConfigurer.java#L115-L119

#### :thought_balloon: Proposed Solution

* Change the implementation so that:
  * If the user provides no config, it decides the default value based on if it's SaaS or self managed
  * If the user provides a config, it always chooses this
* Note that this will likely require to change the default value of the option, which chooses the SaaS defaults as of today

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

**Comment by Szik** [comment]
QA tests for 8.4 SM in Helm passed
the following specs in operate deployment were used
```
- name: CAMUNDA_OPERATE_WEBSECURITY_CONTENTSECURITYPOLICY
  value: "default-src 'self'; img-src 'self' *; script-src 'self' *; style-src 'self' * 'unsafe-inline'; font-src 'self' *; connect-src 'self';"

```

**Comment by ThorbenLindhauer** [comment]
@sdorokhova the ticket is on the board in state Done, but it's not closed. Which one is wrong?

**Comment by kristinkomschow** [comment]
> @sdorokhova the ticket is on the board in state Done, but it's not closed. Which one is wrong?

The 8.4 backport for this is not merged yet because there were test failures that I'm looking into today.
