### ISSUE TITLE
CI: all Zeebe CI jobs need to specify GHA timeouts

### ISSUE THREAD

**Issue by cmur2** [camunda/camunda#21766]
## Description

Triggered by [the docker-checks job that hangs for 45min+](https://github.com/camunda/camunda/actions/runs/10629661115/job/29467254387?pr=21734) but usually [takes <10min](https://github.com/camunda/camunda/actions/runs/10595057280/job/29360001799), I noticed that a couple of jobs in [zeebe-ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/zeebe-ci.yml) do not specify any `timeout-minutes` values. This means they fall back to the default of 6 hours on GitHub Actions which is bad UX and wastes resources.

It is a best practice (and requirement of [Unified CI](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria) which Zeebe is now part of) to specify reasonable `timeout-minutes` values with a small buffer based on the actual execution times to avoid these situations of hanging jobs.

## Goal

All jobs in [zeebe-ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/zeebe-ci.yml) have `timeout-minutes` values defined. Currently missing are at least: `go-lint`, `go-apidiff`, `docker-checks`,`deploy-docker-snapshot`, `deploy-benchmark-images`, `deploy-snyk-projects`.

How:

* look e.g. at how long execution of a job usually takes on `main`
* add a buffer of 10-15%
* round up to next multiple of 5 minutes
* specify `timeout-minutes` field ([GH docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes))

(Any timeout is better than none. Preferably the numbers here should be around 10-15 minutes on the job level if achievable since that is the goal for the [Unified CI](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)).

**Comment by cmur2** [comment]
Small change so should be quick to implement (~1 hour) /cc @megglos @npepinpe

**Comment by npepinpe** [comment]
ZDP Triage:
- As ZDP has done a bunch of CI work recently, and this is a low hanging fruit, I'd kindly ask if ZPA can take this one @megglos 🙂

**Comment by megglos** [comment]
`go-lint`, `go-apidiff` can be left out of scope, they are to be removed with https://github.com/camunda/camunda/issues/21817

**Comment by cmur2** [comment]
This happened again in https://github.com/camunda/camunda/actions/runs/10884581027/job/30200228453 (timeout after 6 hours only)

**Comment by megglos** [comment]
closing due to https://github.com/camunda/camunda/issues/21817

**Comment by cmur2** [comment]
Without actively looking for it, found a build where it happened again: https://github.com/camunda/camunda/actions/runs/11673124267/job/32503262847

Since the fix is known and very straightforward, @megglos can we make progress on this please?
