### ISSUE TITLE
Date picker is not fitting into in the form

### ISSUE THREAD

**Issue by esraagamal6** [camunda/camunda#21775]
### Describe the bug
When having a form with date picker on the right, on opening the picker calendar is not fitting to the form and user has to scroll

### To Reproduce

1. Start a process with userTask having a form with date picker in the right - attached
2. Expand the date picker

![Screenshot 2024-08-30 at 8 58 09 AM](https://github.com/user-attachments/assets/676827ac-bca1-4435-8b7b-4b2b1767f92e)
[Archive 3.zip](https://github.com/user-attachments/files/16816025/Archive.3.zip)

### Actual behavior
Date picker fits to the form

### Expected behavior
User has to scroll to the right to view the calendar

### Environment

- OS: [e.g. MacOS]
- Browser: [e.g. chrome, safari]
- Tasklist Version: 8.6.0-alpha5

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by marcosgvieira** [comment]
Closing as duplicated of https://github.com/bpmn-io/form-js/issues/1193
