### ISSUE TITLE
CI: Protobuf backwards compatibility check runs even when no proto changes

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#21780]
**Description**

It seems the backwards compatibility check is running even when there are no proto changes. That said, it's not a huge deal, because it's very fast and uses GitHub runners. Still, we should avoid running something if we don't need to, and fix the check.

**Comment by npepinpe** [comment]
You can find examples on any of the push triggered builds, e.g.: https://github.com/camunda/camunda/actions/runs/10632199134

**Comment by cmur2** [comment]
@npepinpe given the way [the filter is coded](https://github.com/camunda/camunda/blob/9524ebc02e639f335f73daf85b770b86067c4d0f/.github/actions/paths-filter/action.yml#L81) it is the expected result that the protobuf backwards compatibility check runs on `push` events.

I started the best practice to always return `true` from the change detection on `push` events to make sure all Unified CI is ran consistently on `main` so issues don't go unnoticed until next time someone touches a very sporadic file (makes debugging hard). If this behavior is undesired/not useful for the protobuf backwards compatibility check, we can change the condition there with a comment 🙂

**Comment by npepinpe** [comment]
No, let's leave like that then, it's just me who misunderstood how the filters work :+1:
