### ISSUE TITLE
CI: alerting on problems based on CI health metrics

### ISSUE THREAD

**Issue by cmur2** [camunda/camunda#21820]
## Description

Use the metrics collected for [CI health](https://github.com/camunda/camunda/wiki/CI-&-Automation#ci-health-metrics) to notify stakeholders of relevant problems in the CI. Consider using [Grafana Alerting](https://grafana.com/docs/grafana/latest/alerting/fundamentals/) for this, together with e.g. Slack notifications. As always alerts should be actionable and should not be noisy.

Relevant problems:
* [CI DRI](https://github.com/cmur2) is interested in noticing issues of [highest severity](https://github.com/camunda/camunda/wiki/CI-&-Automation#prioritization) to start triage/incident resolution
    * relevant metrics are: unsuccessful job rates on `main` + merge queue, job cancellations due runner problems, stuck/long merge queue and many PR merge attempts (needs https://github.com/camunda/camunda/issues/21730)
* @npepinpe is interested in Zeebe flaky tests (from https://github.com/camunda/camunda/issues/21674)

## Goal

This ticket is about creating a framework that allows to configure which stakeholders want to be notified about which problem when. It should be extensible and in the first iteration cover some of the relevant problems above.

Implementation:

* ✔️ create dedicated monorepo CI alert [Slack channel](https://camunda.slack.com/archives/C07NZ85EF1Q)
* ✔️ create new [Slack app for Infra Grafana](https://api.slack.com/apps/A07PBUKTVJM), approved by IT
* ✔️ configure https://dashboard.int.camunda.com/ with [new Slack app](https://api.slack.com/apps) + credentials, using [configuration-as-code](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/): https://github.com/camunda/infra-core/pull/8398
* ✔️ setup Slack-compatible notification templates in Grafana (formatting, important information like summary + runbook first): https://github.com/camunda/infra-core/pull/8402
* ✔️ create one alert rule e.g. for unsuccessful job rates on `main` + merge queue: https://github.com/camunda/infra-core/pull/8433

**Comment by andromaqui** [comment]
When opening the [url](https://api.slack.com/apps/A07PBUKTVJM) for the infra grafana slack app I get the error shown in the picture. Is this expected?

<img width="1673" alt="Screenshot 2024-09-26 at 08 29 48" src="https://github.com/user-attachments/assets/81ab56df-92f1-4117-9adb-93de4d66c4ea">

**Comment by cmur2** [comment]
> When opening the [url](https://api.slack.com/apps/A07PBUKTVJM) for the infra grafana slack app I get the error shown in the picture. Is this expected?

@andromaqui I forgot to add you, collaborators are manually managed (no groups etc) so I added you now and it should work 👍🏼

**Comment by cmur2** [comment]
Alert setup is now completed end-to-end and should be working. Will monitor that for validation.

**Comment by cmur2** [comment]
The alerts tend to be a bit noise so I propose to introduce recovery thresholds in https://github.com/camunda/infra-core/pull/8495
