### ISSUE TITLE
[C8 API] Implement Process instance search - calculated fields

### ISSUE THREAD

**Issue by mihail-ca** [camunda/camunda#21945]
### Description

Add calculated fields for `/v2/process-instances/search` endpoint.

More specifically, the following limitation must be fixed:
- The following fields are calculated, or stored in other indices: `rootProcessInstanceKey`
- The fields cannot be used as filters, and are not returned in the response. These fields must be calculated, or fetched from other indices, which requires additional requests.

### Update

As per comment, `rootProcessInstanceKey` field should be removed for now, because it is not available in v1.

**Comment by mihail-ca** [comment]
@ralfpuchert could you please suggest here, how do we handle the field `hasActiveOperation` ? Setting this field requires an additional database request, to get the operations. See https://github.com/camunda/camunda/blob/main/operate/webapp/src/main/java/io/camunda/operate/webapp/rest/dto/listview/ListViewProcessInstanceDto.java#L105

I am not sure what are guidelines for handling such cases, thank you.

**Comment by ralfpuchert** [comment]
Thank you @mihail-ca for raising this. Because we need operations to determine the state of operation this field can only be filled if [Operation endpoint](https://github.com/camunda/camunda/issues/20663) is implemented
as we can see [in existing code](https://github.com/camunda/camunda/blob/f701eea3f20cada882cfbafc8786f32598618298/operate/webapp/src/main/java/io/camunda/operate/webapp/elasticsearch/reader/ProcessInstanceReader.java#L61-L61)
Until the Operation endpoint is available just use an default value.

**Comment by ralfpuchert** [comment]
Hello @mihail-ca , we don't need `processName` and `rootProcessInstanceKey` because they are note available in v1. `treePath` exists in `list-view` index.

That means you can remove the `rootProcessInstanceKey` field from ProcessInstanceItem filter etc.

**Comment by tmetzke** [comment]
@ralfpuchert and @mihail-ca, is `processName` referring to the `processDefinitionName` in our current implementation? Should this be removed as well from the V2 API?

**Comment by ralfpuchert** [comment]
@tmetzke , @mihail-ca This was used in internal API and does not exist in v1. So should be removed.
I will check if this is already done.

**Comment by ralfpuchert** [comment]
`processName` is already removed.

**Comment by mihail-ca** [comment]
@ralfpuchert `processName` is the same as `processDefinitionName`, which I left. So should I remove `processDefinitionName` as well ? https://github.com/camunda/camunda/pull/23299/files#diff-a18635d76659a781a6e8d301bd0fed7c77fd6cc5c8cfc57e11c5bbc19c78c9cdR2756
