### ISSUE TITLE
fix/Spring Boot SDK: do not ignore json field names from annotations

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda#21962]
**Description**

A fix for a bug that is also present in the SDK here has been implemented: https://github.com/camunda-community-hub/spring-zeebe/pull/934

Original issue https://github.com/camunda-community-hub/spring-zeebe/issues/903

This fix should also be done here.

**Comment by korthout** [comment]
@jonathanlukas Can you expand a bit more on what you're asking for here?

**Comment by jonathanlukas** [comment]
@korthout I adjusted the header and the comment. Sorry for the confusion. Is this clear now?

**Comment by korthout** [comment]
@remcowesterhoud has no time available for this. @ana-vinogradova-camunda may have some time for it.
