### ISSUE TITLE
Add validation for pinning time to ensure non-negative values

### ISSUE THREAD

**Issue by ce-dmelnych** [camunda/camunda#21964]
###Description:

To ensure that time manipulation commands in the Zeebe system are safe and avoid causing instability, we need to validate the values provided when pinning the clock. Specifically, the `pin` clock command should not allow negative timestamps or instants before the Unix epoch `1970-01-01T00:00:00Z`. This task involves adding validation to both the REST endpoint and the Zeebe client to enforce this rule and prevent issues such as repeated errors or system crashes observed durning manual QA testing with negative timestamp values.

1. Add validation for non-negative time values in `ClockProcessor` for `PIN` command.
   - If a negative time is provided, reject this command with appropriate rejection message: 
      `"Expected pin time to be not negative but it was %d"`

2. Add validation for non-negative timestamp values in the `PUT /v2/administration/clock` REST endpoint:
   - Ensure that when the clock is pinned using a timestamp, the value must be **greater than or equal to 0** .
   - If a negative timestamp is provided, return an appropriate error message: 
     `"The value for timestamp is '%d' but must be non-negative."`.

3. Update `ZeebeClient.newClockPinCommand().time(long timestamp)`:
   - Add a validation that ensures the `timestamp` is **non-negative**.
   - If a negative value is provided, throw an `IllegalArgumentException` with the message:
     `"timestamp must be not negative"`.

4. Update `ZeebeClient.newClockPinCommand().time(Instant instant)`:
   - Add a validation to check that the provided `Instant` is **not before `Instant.EPOCH`**.
   - If the `Instant` is before the epoch, throw an `IllegalArgumentException` with the message:
     `"instant must be equal to or after '1970-01-01T00:00:00Z'"`

**Comment by lenaschoenburg** [comment]
I think ideally this would be done in the `Clock.Pin` command itself, not in the API layer.

**Comment by lenaschoenburg** [comment]
Go for it if you think it's worth it and easy enough to do. Personally I'd lean towards having validation in just one place instead of duplicating it on the API layer.
