### ISSUE TITLE
ZeebeDbInconsistentException MESSAGE_CORRELATED already exists

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#21989]
**Description**

The affected clulster is trial cluster 8.6.0-alpha4.

Similar issue to https://github.com/camunda/camunda/issues/10309 where one of the partitions is marked as dead due to consistency check that safeguards against corrupted data. 

One of the partitions was marked as dead after the streamProcessor has failed with the reason:

> StreamProcessor-1 failed, marking it as dead: StreamProcessor-1{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=DbForeignKey[inner=DbLong{2251799814408769}, columnFamily=MESSAGE_KEY, match=Full, skip=io.camunda.zeebe.db.impl.DbForeignKey$$Lambda/0x00007cfb64c54b50@3836ebcf], second=Process_15eyfee} in ColumnFamily MESSAGE_CORRELATED already exists, cause=null]}

This seems to have happened after transitioning to the leader of the partition.

[Logs Sept 5.json](https://github.com/user-attachments/files/16897828/Downloaded.Logs.Sept.5.2.json)

[contents of partittion1 in broker 0.zip](https://github.com/user-attachments/files/16897831/partittion1.zip)

Link to the incident channel [#inc-inc-zbdbinconsistency-exception-message-correlated](https://camunda.slack.com/archives/C07L2T613MY)

**To Reproduce**

- unclear at this time

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

</p>
</details>

**Environment:**
- Instance: `1a0ae311-a7fe-4d83-bb30-34dcff28f3f0`
- Zeebe Version: 8.6.0-alpha4
- Configuration: G3-Trial cluster

**Comment by lenaschoenburg** [comment]
Marking as critical because it's a state inconsistency that we need to address ASAP

**Comment by remcowesterhoud** [comment]
This will occur when you have a a message start event and a regular message catch event within the same process. These events must both be subscribed to messages with the same message name.
Generally when you publish a message it'll only correlate with 1 subscription within a process instance. If you have an intermediate message catch event which subscribes to the same message as a message start event, the expectation is that the intermediate catch event correlates, and the message start event subscription doesn't. So no new process instance would be created. With this bug that condition fails. After correlating with the intermediate catch event we will also try to correlate to the message start event. As a result the consistency checks will fail.
