### ISSUE TITLE
StackOverflow during process cancelation 

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#21991]
**Describe the bug**

This issue originated from a the following [support case](https://jira.camunda.com/browse/SUPPORT-23461?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D) where the client deployed a recursive model where P1 calls upon P2 which calls P3 which in turn calls again P1, this created a huge nest of PIs that started wondering performance.

Upon trying to cancel the PI which also in turn also deletes their children, the client had a stackOverflow Exception due to the large number of nested PIs. This issue is quite similar to [StackOverflowError during process instance modification · Issue #20307 · camunda/camunda · GitHub](https://github.com/camunda/camunda/issues/20307).

Work around:

To address this they would need to ban all the PIs that are calling each other before this renders their cluster unusable.
https://github.com/camunda-cloud/runbook/blob/main/zeebe/troubleshooting-guide.md#endless-recursion-loop-in-process-instances

- Forward to the affected Leader broker managment port 9600, e.g. kubectl port-forward zeebe-0 9600
- Pause processing via `curl -XPOST localhost:9600/actuator/partitions/pauseProcessing`
- Follow this [guide](https://github.com/camunda-cloud/runbook/blob/main/zeebe/zeebe-investigate-data.md#investigate-state) to find all process instances
- Follow this [guide](https://github.com/camunda-cloud/runbook/blob/main/zeebe/zeebe-investigate-data.md#force-banning-all-existing-instances) to ban all instances.
- Resume processing `curl -XPOST localhost:9600/actuator/partitions/resumeProcessing`.

**To Reproduce**

-->Deploy a process model as described above, let it grow (we don't know what is the threshold of nested children where this happens), and try to ban the parent process instance. 

**Expected behavior**

It should ban the PI and all its children without problems.

**Log/Stacktrace**

![image](https://github.com/user-attachments/assets/d35c847a-0c03-41ad-b8b9-f65da6679e87)

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration: 

**Support Cases:**
https://jira.camunda.com/browse/SUPPORT-23461

**Comment by rodrigo-lourenco-lopes** [comment]
Ideally, we should have a way to notice this growing uncontrolled nested process. Could a metric be used as an alert for prod?

**Comment by jesusAlvarezSwissre** [comment]
Hello, this is not related to how fix the ticket but I am very interested in the workaround mentioned on this ticket.

Unfortunately, I see 404 errors when trying to access those links. In case the links are correct and I cannot access them because I do not work in Camunda, could you please copy the relevant content within the ticket description?

![image](https://github.com/user-attachments/assets/61de2a0f-85e5-4e9e-ba57-2ad6c9c0779d)

**Comment by rodrigo-lourenco-lopes** [comment]
Hi @jesusAlvarezSwissre, apologies, this runbook links are in one of our closed repos.
I pasted the relevant sections below.

#### Get all keys of all processes

Sometimes you need all instance keys of a specific process or even of all processes.

In the following you see an example to get this data out of a Zeebe snapshot with `zdb`.
```shell
snapshot=/tmp/snapshot-directory
for process in $(zdb process list -p $snapshot | jq '.data[].Key'); do
   zdb process instances $process -p $snapshot | jq '.data[].elementRecord.processInstanceRecord.processInstanceKey';
done
```

#### Cancel all existing instances

There might be cases where we want to clean up the state, e.g. cancel all instance. Then the following might help:

```shell
snapshot=/tmp/snapshot-directory
for process in $(zdb process list -p $snapshot | jq '.data[].Key'); do
  for instance in $(zdb process instances $process -p $snapshot | jq '.data[].elementRecord.processInstanceRecord.processInstanceKey'); do
    kubectl exec zeebe-0 -- zbctl --insecure cancel instance $instance; # or how ever you run an command against your zeebe instance
  done
done
```

#### Force ban an existing instance

In some cases, it might not be possible to cancel all instances, e.g. there is a huge record back log and processing cannot happen. You can use the new banning API endpoint from a gateway. First, port-forward the monitoring server, e.g. if you have a gateway service under `zeebe-service`, and an instance 123:

```sh
kubectl port-forward svc/zeebe-broker-service 9600:9600
curl -XPOST http://localhost:9600/actuator/banning/123
```

#### Force banning all existing instances

Similar to cancelling all instances, you can use `zdb` to grab the list of PI keys, and ban them all:

```shell
kubectl port-forward svc/zeebe-broker-service 9600:9600
snapshot=/tmp/snapshot-directory
for process in $(zdb process list -p $snapshot | jq '.data[].Key'); do
  for instance in $(zdb process instances $process -p $snapshot | jq '.data[].elementRecord.processInstanceRecord.processInstanceKey'); do
    curl -XPOST "http://localhost:9600/actuator/banning/${instance}"
  done
done
```

Alternatively, if the cluster has Elasticsearch and it's up to date, you can use Elasticsearch to get the list of process instance keys. For example, if the exporter prefix is `zeebe-record` (the default):

```shell
kubectl port-forward svc/elasticsearch 9200:9200
for instance in $(curl -s -XPOST -d '{ "fields": ["value.processInstanceKey"], "_source": false, "size": 3000 }' -H 'Content-Type: application/json' 'http://localhost:9200/zeebe-record_process-instance_*/_search' | jq '.hits.hits[].fields."value.processInstanceKey"[0]'); do
  curl -XPOST "http://localhost:45357/actuator/banning/${instance}"
done
```

**Comment by korthout** [comment]
ZPA triage:
- There's a recursive loop in `CancelProcessInstanceProcessor` that we need to replace: `getRootProcessInstanceKey`
- High severity, because the workaround isn't really applicable or easy to use
- Likelihood is low, because we still believe it's not a common use case to go arbitrarily deep with call activities
- That makes this prio: upcoming

**Comment by phudgins-ciena** [comment]
Unfortunately we have found ourselves in this situation for a v7.18.0 environment.  Any recommendation on how to workaround the StackOverflowError?  Our flow inadvertently made a call to itself resulting in 14K instances before it stopped.  We are using the http DELETE engine/default/process-instance/{id} API.

**Comment by phudgins-ciena** [comment]
For the v7 environment referenced in our case above, we were able to workaround the StackOverflowError by setting the parameter skipSubprocesses to true via the REST API call.
![ProcessInstanceDelete](https://github.com/user-attachments/assets/24dbb410-00c0-46bb-9152-cac18bd1f835)

**Comment by korthout** [comment]
@phudgins-ciena Thanks for reporting. This repository focuses on Camunda 8 only. For Camunda 7 topics, you can use https://github.com/camunda/camunda-bpm-platform. Additionally, you could search for your question (or ask it) in [the Camunda 7 section of our forums](https://forum.camunda.io/c/camunda-platform-7-topics/39).
