### ISSUE TITLE
Migrate sequential multi-instance element instances

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#22184]
## Description

All cases under [the issue for parallel multi-instance element instances](https://github.com/camunda/camunda/issues/22129) should be supported:

- Migrate multi-instance service tasks
- Migrate multi-instance receive tasks
- Migrate multi-instance embedded subprocess
- Migrate multi-instance call activities

All cases above should work with 3 item input collection: 1 completed, 1 active, and 1 still to come.

**Comment by korthout** [comment]
As the main difference between parallel and sequential multi-instance lies in when inner instances are activated (all at once "in batches" vs. one after the other), we need to add some additional test cases for:
- input collection expression changes
- input element changes
