### ISSUE TITLE
When using Opensearch in a AWS environment with IRSA, Optimize fails on bulk Opensearch operations

### ISSUE THREAD

**Issue by matthewBearCamunda** [camunda/camunda#22278]
Engineering DRI: @matthewBearCamunda

### Describe the bug

`bulk` Opersearch operations fail when using Optimize in AWS with IRSA. The error does not occur when using basic authentication
[optimize-logs.txt](https://github.com/user-attachments/files/16989033/optimize-logs.txt)
It is unclear if this affects all bulk operations or only the specific operation of writing to the position based index

### Expected behaviour

`bulk` Opensearch operations behave as expected and successfully execute

### Environment observed:

- Optimize mode(s):
- Optimize version(s):
- Database(s) (Elasticsearch/OpenSearch): Opensearch

### Breakdown

```[tasklist]
### Pull Requests
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [x] Yes. If so:
  - [ ] The bug description is clear
  - [ ] The steps to reproduce are clear
  - [ ] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by grlimacan** [comment]
After the recent changes done to the code in other PRs in the run-up to the release the bug is no longer present.
Here is a log excerpt showing the execution with no errors:
[optimize-logs-resolved.txt](https://github.com/user-attachments/files/17041673/optimize-logs-resolved.txt)
