### ISSUE TITLE
Upgrade netty version. grpc-netty breaks with Netty 4.1.111.Final in zeebe-gateway

### ISSUE THREAD

**Issue by ivanovpavel1983** [camunda/camunda#22298]
The netty version in zeebe and zeebe-gateway needs to be updated due to a bug with gRPC (https://github.com/grpc/grpc-java/issues/11284), which causes the error: io.grpc.StatusRuntimeException: INTERNAL: Encountered end-of-stream mid-frame.

**Comment by megglos** [comment]
ZPA Triage:
- it's updated on `main` already

@ivanovpavel1983 what Zeebe version are you using right now?

**Comment by ivanovpavel1983** [comment]
We are currently testing Camunda Zeebe 8.5.7, where the problem is fixed. We manually specified this version for the gateway, but the latest Helm charts contain a different version of Zeebe in the gateway. The error appeared in the zeebe-gateway module.

Additionally, there is an issue with the response header size in Netty. This header cannot be configured, and when there are too many errors in the diagram, it leads to an error:

https://github.com/grpc/grpc-java/issues/8919  
https://github.com/netty/netty/issues/7825  

Unlike Jetty and Tomcat, adjusting this parameter in Netty is not possible. Is it possible to add this parameter to Zeebe?

**Comment by korthout** [comment]
>We manually specified this version for the gateway, but the latest Helm charts contain a different version of Zeebe in the gateway. 

@ivanovpavel1983 which version of the helm charts are you using? These should align the same Zeebe and Gateway versions.

**Comment by korthout** [comment]
> Camunda Zeebe 8.5.7, where the problem is fixed.

I'm closing this as fixed. [Helm charts 10.4.0](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-10.4.0) specify Zeebe `8.5.7`. 

@ivanovpavel1983 please reopen if this is unresolved for you.
