### ISSUE TITLE
Jetty is not respecting the Maximum Header Size configration

### ISSUE THREAD

**Issue by matthewBearCamunda** [camunda/camunda#22326]
Engineering DRI: @matthewBearCamunda

### Describe the bug

When running, jetty does not respect the configured `CONTAINER_MAX_REQUEST_HEADER_IN_BYTES` value, and will always use the default of `8192`

### Expected behaviour

Jetty uses the value of the `CONTAINER_MAX_RESPONSE_HEADER_IN_BYTES` configuration as is max header size

### To Reproduce

- Configure the CONTAINER_MAX_RESPONSE_HEADER_IN_BYTES field to be something other than the default value
- Build a new & instrumented version of jetty that will print out the max header size value
- Change the version of jetty used by Optimize to be the instrumented version you just built
- Run Optimize and load a page
- Look at the logs for the actual response size configuration jetty is using

### Notes
- The `CONTAINER_MAX_REQUEST_HEADER_IN_BYTES` configuration has the same issue
- See this patch for how I instrumented jetty: [instrumented_jetty.patch](https://github.com/user-attachments/files/17019883/instrumented_jetty.patch)

### Environment observed:

- Optimize mode(s):
- Optimize version(s):
- Database(s) (Elasticsearch/OpenSearch):

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14435
- [ ] https://github.com/camunda/camunda/pull/23170
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [x] Yes. If so:
  - [x] The bug description is clear
  - [x] The steps to reproduce are clear
  - [x] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by grlimacan** [comment]
Hey @matthewBearCamunda , I have reviewed both PRs (monorepo and C7). I noticed that neither PR had backporting labels, so in the the mono-repo one I applied the backport so that it goes into the stable 8.6 . For C7 I am not sure which versions we want to get it backport into? For now I just applied 3.14, but in case you need this fix in 3.13, 3.12, etc please apply the respective labels before merging

**Comment by grlimacan** [comment]
Hey @matthewBearCamunda , please make sure to add a reference to all backporting PRs in the `Breakdown` list as well

**Comment by RobertDorlan** [comment]
Tested along with @matthewBearCamunda 

Jetty uses the value of the CONTAINER_MAX_RESPONSE_HEADER_IN_BYTES configuration as is max header size ✅

**Comment by matthewBearCamunda** [comment]
3.12 Backport - https://github.com/camunda/camunda-optimize/pull/14498
