### ISSUE TITLE
[Zeebe/FEEL]: Add `is blank(string)` function

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda#22380]
**Is your feature request related to a problem? Please describe.**

Checking whether a string is null is easy. Checking whether a string is blank is much harder. One could start replacing spaces and line breaks. The `8.6`, we will have the `trim(string)` function for that. But still, it has to be combined with a `string length(string)` to check whether the original string is blank, resulting in `string length(trim(string)) = 0`. All of this could be replaced with `is blank(string)`.

**Describe the solution you'd like**

I would like to have a feel function (camunda extension) that is called `is blank`, takes a `string` as an argument and checks whether this `string` is _blank_. Should work like this: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank(java.lang.CharSequence).

**Describe alternatives you've considered**
The alternative is described above, a lengthy function combining two other functions.

**Additional context**
Slack thread: https://camunda.slack.com/archives/C01QYD808A3/p1726483246619779

**Comment by saig0** [comment]
Your Camunda champion contributed the function to the FEEL engine: https://github.com/camunda/feel-scala/pull/927.

After merging the PR, we should add the documentation of the new function ([ref](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-string/#containsstring-match)).
