### ISSUE TITLE
Requesting elementName field in zeebe-record-process-instance-template for opensearch exporter

### ISSUE THREAD

**Issue by anumolurahul** [camunda/camunda#22423]
https://github.com/camunda/camunda/blob/main/zeebe/exporters/opensearch-exporter/src/main/resources/zeebe-record-process-instance-template.json

**Is your feature request related to a problem? Please describe.**
elementName is not being exported to opensearch zeebe-process-instance index

**Describe the solution you'd like**
elementId is present but it would be helpful to have elementName as well specially when we are surfacing the data to business users

**Describe alternatives you've considered**
We can lookup zeebe-record-deployment to fetch the BPMN xml by using  processDefinitionKey and lookup the elementName but isn't ideal

**Comment by megglos** [comment]
Hey @anumolurahul ,
thanks for reaching out, right now we would not prefer to add meta-data to exported records that can be extracted from the actual model. To keep the overhead of exported records as low as possible.

I hope resolving the name from the model is acceptable for your use case.
