### ISSUE TITLE
Optimize backup fails with ElasticsearchStatusException when retrieving snapshots 

### ISSUE THREAD

**Issue by PHWaechtler** [camunda/camunda#22430]
Engineering DRI: @PHWaechtler

### Describe the bug

When trying to check if a given backup exists, Optimize fails as it encounters an ES exception. It is quite possible that this is related to the recent ES client migration.

### Expected behaviour

Backup process should work without errors.

### To Reproduce

1. Follow [this](https://confluence.camunda.com/display/CO/Backup) guide to setup an environment for snapshot creation.
2. Once everything is set up, attempt to take a backup and check logs
3. When Optimize checks if a backup with the given ID exists, it encounters an ES exception that prevents it from proceeding with the snapshot taking.

### Environment observed:

- Optimize mode(s): SaaS, but affects all
- Optimize version(s): snapshot
- Database(s) (Elasticsearch/OpenSearch): newest client

### Links

Slack thread [here](https://camunda.slack.com/archives/C55U06YRG/p1726562979327929)

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/22431
- [ ] https://github.com/camunda/camunda/pull/22431
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [x] Yes. If so:
  - [x] The bug description is clear
  - [x] The steps to reproduce are clear
  - [x] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Successfully tested agains C8- 8.6.0-SNAPSHOT

Backup process working as expected without errors.
