### ISSUE TITLE
Fix github workflow check for 8.5 releases

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#22523]
### Description

* The [Operate Frontend](https://github.com/camunda/camunda/blob/stable/operate-8.5/.github/workflows/operate-frontend.yml) github workflow currently doesn't run on the 8.5 stable branch. Rootcause: on the branch, it's only defined to run on main (see https://www.kenmuse.com/blog/understanding-push-triggers-and-branches-in-github/ for background on why it needs to be present on the stable branch)
* The release process still has a task to check the CI in Jenkins, however in the mono repo it's all in github workflows (here is the corresponding 8.4 build: https://ci.operate.camunda.cloud/blue/organizations/jenkins/camunda-operate/detail/stable%2F8.4/331/pipeline)
* The release process does currently not check the state of any github workflows for backend CI on the 8.5 stable branch
* After renaming the `zeebe` repo `camunda`, the workflow URLs in the connectors need to be adjusted. Otherwise, they receive a 301 response that the Connector doesn't follow

### TODO

* add a workflow trigger for the `stable/operate-8.5` branch for the  [Operate Frontend](https://github.com/camunda/camunda/blob/stable/operate-8.5/.github/workflows/operate-frontend.yml) build
* Remove the Jenkins CI check from the 8.5 release process
* Add the following backend github workflows to the automated workflow status check:
  * [Operate CI](https://github.com/camunda/camunda/actions/workflows/operate-ci.yml?query=branch%3Astable%2Foperate-8.5): workflow id 88459732

### Changes

* 8.5 PR for frontend build: https://github.com/camunda/camunda/pull/22524
* Removed the Jenkins checks CI from [Trigger the release process](https://modeler.ultrawombat.com/diagrams/6c87c8c7-ab23-474b-b385-2d3df6844f91--trigger-the-release)
* Removed any other checks for non-patch releases from [Trigger the release process](https://modeler.ultrawombat.com/diagrams/6c87c8c7-ab23-474b-b385-2d3df6844f91--trigger-the-release), because 8.5 releases are always patch releases now.
* Added the workflow with id 88459732 to the list of workflowIds on the "Trigger the release" call activity in [Operate release procedure](https://modeler.ultrawombat.com/diagrams/8feadbbe-6284-4a4e-85a4-6d6d1a4f4f8a--operate-release-procedure)
### Additional Information

[Operate 8.5 release process](https://modeler.ultrawombat.com/diagrams/8feadbbe-6284-4a4e-85a4-6d6d1a4f4f8a--operate-release-procedure)

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by pedesen** [comment]
Hey @ThorbenLindhauer I finished all todo items and added the changes to the issue description. It would be great if you could review these and close the issue when you approve them.

All changes were made in the modeler, so there are no additional PRs.

**Comment by ThorbenLindhauer** [comment]
Thank you very much, @pedesen! Looks good.
