### ISSUE TITLE
[Doc Handling] Support uploading multiple files via the API

### ISSUE THREAD

**Issue by chillleader** [camunda/camunda#22577]
Currently the document API only supports single file upload. We would like to extend the API by providing a method to upload multiple files at the same time.

Primary use case: uploading files from Tasklist

For simplicity, we can omit the metadata for such requests.

Example request body:

```
Content-Type: multipart/form-data; boundary=---
---
Content-Disposition: form-data; name="file1"; filename="a.txt"
Content-Type: text/plain

Content of a.txt.
---
Content-Disposition: form-data; name="file2"; filename="a.html"
Content-Type: text/html

<!DOCTYPE html><title>Content of a.html.</title>

---
```

Open question:
- Should we rely on part names (e.g. file1, file2)? If so, we can also allow passing the metadata (e.g. metadata1, metadata2)
  - An alternative approach would be to ignore the part names, expect all parts to be files and not support metadata

**Comment by tmetzke** [comment]
Proposal for bodies we accept here:

```
Content-Type: multipart/form-data; boundary=---
---
Content-Disposition: form-data; name="files"; filename="a.txt"
Content-Type: text/plain
X-Metadata-Foo: my Foo metadata
X-Metadata-Bar: my Bar metadata

Content of a.txt.
---
Content-Disposition: form-data; name="files"; filename="a.html"
Content-Type: text/html
X-Metadata-Bar: my Bar metadata

<!DOCTYPE html><title>Content of a.html.</title>
---
```

If I'm not mistaken, each file in `files` is considered a multipart file now and has custom headers you can use in the controller. In the API description, you need to accept a `@RequestPart("files") final List<MultipartFile> files` parameter that contains the files.
