### ISSUE TITLE
Prevent instance migration mapping if elements are from different process definitions / participants

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#22612]
Support case: [SUPPORT-23647](https://jira.camunda.com/browse/SUPPORT-23647)

### Description

Currently it is possible in the Operate UI to map source elements to a process definition which is not the target process definition when the diagram is modeled as a collaboration.

We should allow mapping only between elements which are part of the process definitions the user selected as source and target.

![image](https://github.com/user-attachments/assets/45213204-affe-4b46-b043-0ae7f988dd6a)

###  Acceptance criteria

- [x] List only source elements from the selected source process definition
- [x] Do not list source elements from other process definitions (when the diagram contains multiple of them)
- [x] Allow mapping only to target elements from the selected target process definition
- [x] Do not allow mapping to target elements from other process definitions (when the diagram contains multiple of them)

### Additional Information

Internal slack discussion: https://camunda.slack.com/archives/C048HTV50PJ/p1727085528606909

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by korthout** [comment]
For completeness, this came up in [SUPPORT-23647](https://jira.camunda.com/browse/SUPPORT-23647)
