### ISSUE TITLE
Implement `Search variable` REST API

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#22629]
### Description

Variables endpoint providing search for variables.

* The endpoints should be implemented as described in [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)
* Variable objects are defined in
  * [Variable](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.i5jd4xzabhje) 
 
### Endpoint

* `POST /v2/variables/search`
* [API specification](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.v5rl44cy4o9o)

### Acceptance Criteria

- [x] REST API endpoint incl. OpenAPI spec
- [x] Java client support
- [x] Integration tests

**Comment by tmetzke** [comment]
Reopened as Java client support and integration tests tasks are still open

**Comment by nathansandi** [comment]
@tmetzke  Is there a way to turn off the automatisation ? 

I didnt use the world "close" over the PR, but even like that when I merged the first PR , the git closed the issue

**Comment by tmetzke** [comment]
> @tmetzke Is there a way to change/improve the git automation ?
> 
> I didnt use the world "close" over the PR, but even like that when I merged the first PR , the git closed the issue

It's a GitHub thing, one PR per issue. You can write "related to <#issue-number>", then it does not link the issue with a "deep link" that closes the issue when the PR is merged.
