### ISSUE TITLE
Camunda Authentication module supports persistent session storage in ES/OS (for Tasklist/Operate)

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#22729]
### Description
In the current implementation, the Operate and Tasklist components use ES to support sharing sessions for persistent sessions. This is to support a pod shutting down and not forcing the user to login again. We need to be able to consider this within the Camunda Authentication module such that if a user has an existing session then this is loaded into the security context.

Additional considerations:
- Can the components use the same persistent storage?

```[tasklist]
### Implementation
- [x] https://github.com/camunda/camunda/issues/23760
- [x] https://github.com/camunda/camunda/issues/23761
- [x] https://github.com/camunda/camunda/issues/23762
- [ ] https://github.com/camunda/camunda/issues/23765
- [x] https://github.com/camunda/camunda/issues/23763
```

**Comment by RomanJRW** [comment]
@Ben-Sheppard - is there expectation or plans for this to be extended to Optimize too?

**Comment by romansmirnov** [comment]
@Ben-Sheppard, can this issue be closed? I implemented the persistent sessions for C8 and think all tasks are done here.

IMO, in terms of Optimize, once Optimize is part of a single application and uses the same security filter chains, there is nothing to do. The sessions will be persistent and independent of the component. I don't see anything specific that needs to be done for Optimize.
