### ISSUE TITLE
Implement `Get Form for Process Definition`

### ISSUE THREAD

**Issue by nathansandi** [camunda/camunda#22733]
### Description
Implement the `GET  /v2/process-definitions/{processDefinitionKey}/form` endpoint for retrieving a form by process definition key. This endpoint should return detailed form information including tenant ID, BPMN ID, schema, version, and more.

It is important to note that in contrast to User Tasks, for Processes it should retrieve the highest version of the deployed form, which means `bpmnId` from the form should be added to `process-definitions`.

---

### Endpoint
`GET /v2/process-definitions/{processDefinitionKey}/form`

#### Request
- **Path Parameter:**
  - `processDefinitionKey` (Long): The unique key for the process where the form that should be retrieved.

#### Response
- **Success (200 OK):**
  - Returns a JSON object representing the form with the following fields:
    - `formKey`: The unique key of the form.
    - `tenantId`: The tenant ID associated with the form.
    - `bpmnId`: The BPMN ID of the form.
    - `schema`: The schema representing the form.
    - `version`: The version of the form.

  **Example Response:**
  ```json
  {
    "formKey": 1,
    "tenantId": "tenant-1",
    "bpmnId": "bpmn-1",
    "schema": {},
    "version": 1
  }

Tasks:
- Implement the Service
- Implement the Rest endpoint
- Implement the Client
- Implement the integration Tests

**Comment by tmetzke** [comment]
>It is important to note that in contrast to User Tasks, for Processes it should retrieve the highest version of the deployed form, which means bpmnId from the form should be added to process-definitions.

That is currently the case but with https://github.com/camunda/camunda/issues/20067 we might also get deployment binding for start forms (which is also supported in C7). Thus, only having the `formId` and resolving to the latest version isn't enough in the long run. We need to at least keep in mind that resolution might have to happen by `formKey` as well if it's present (it basically trumps the `formId` if present).

**Comment by tmetzke** [comment]
@aleksander-dytko, can we clarify the following from a product perspective ASAP:
* Which version of the form related to the start event of the process definition will be fetched by this endpoint?
* Options:
  1. Fixed version of a form, available at deployment time (`deployment` binding)
    - Pro: The provided form is stable
    - Con: Users must redeploy their process when they want it associated with a new form
  2. Always the latest form version (`latest` binding)
    - Pro: Users get the latest version of the linked form, no redeployment needed
    - Con: Provided form is not stable, can change when a new form version is deployed outside of a process application deployment
* Currently, I believe we use `latest` binding in Tasklist

**Comment by tmetzke** [comment]
_From @aleksander-dytko_

@nathansandi, currently, when I model a process definition with a user task, I can select between binding:
-   latest
-   version
-   deployment

Can we reflect this somehow in the binding?

**Comment by tmetzke** [comment]
@aleksander-dytko, this is true for user task forms but not for the form of the start event of a process definition. There, we cannot adjust the binding.

What do you mean by "Can we reflect this somehow in the binding?" specifically? This is basically an instruction from the user on which form version to use when creating a user task instance. We use this information to find the correct form version and bind its `key` to the user task instance when the latter is created.

We don't have this for the process start form (currently, it's on the roadmap). Thus, we need to define the default behavior for process start forms when a user fetches the start form. Do we always use the then-latest form version or the latest version upon process definition deployment-time?

**Comment by tmetzke** [comment]
_from @nathansandi_

Hey @aleksander-dytko,

Following our Slack discussion, I wanted to recap how things work in **V1**. Currently, we extract the formId from the XML at the start event and retrieve the latest version of the form using that formId.

This approach is no longer possible in **V2**. As discussed, @tmetzke mentioned that we won’t have this information on the exporter side. While we could potentially use the formKey, this would require redeploying the process to update the form version, resulting in a different journey than what exists today.

The goal here is to define the ideal process for **starting a process by form**. From the user’s perspective, as it works today, they expect to get the latest version of the form when starting a process. However, this poses a limitation related to the formKey.

Given this, I’d like to raise another question: Is it possible for Zeebe to carry the formId for start events? If not, would the form binding automatically update the formKey for already deployed processes?

From a product perspective, @aleksander-dytko, what is the ideal user journey for this? As I understand it, the current goal is to retrieve the latest form version. However, if we document that redeployment is necessary and the form binding would occur after Zeebe’s implementation, would this make sense for the user journey?

**Comment by tmetzke** [comment]
@megglos and I talked about this a bit.

This would be our verdict and proposal:
* We keep the `latest` binding for forms in process definitions.
* We need the `formId` in the `*-process` index as an attribute.
* Upon API request for the process start form, we fetch the process definition.
* We use the `formId` of the process definition to find the latest version of the form, e.g. doing a second ES/OS request with a form search sorted DESC by `version` and taking the first item of the result list.

When we implement https://github.com/camunda/camunda/issues/20067, we can differentiate in the search:
* The exporter needs to either fill the `formId` (version binding `latest`) or `formKey` (version binding `versionTag` or `deployment`).
* The REST API returns the form by `formKey` if present in the process definition. Otherwise, the latest form by `formId` is fetched.

@aleksander-dytko and @marcosgvieira, can you please provide your input for this proposal?
@nathansandi, assuming this is the way to go, do you need anything else to implement this endpoint?

**Comment by tmetzke** [comment]
For transparency, the `formId` has been added to the `*-process` index with https://github.com/camunda/camunda/pull/23846
