### ISSUE TITLE
Operate schema creation is not working from Camunda exporter

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#22804]
### Description

When working on #22802 I noticed that [ElasticsearchEngineClient#putIndexTemplateRequest](https://github.com/camunda/camunda/blob/6bcbab0ed0e50d3e45a8d1742703622f7d5af629/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/schema/ElasticsearchEngineClient.java#L195) expects json schema files to contain only template mappings, but some of them contain also settings. This is the reason that e.g. `list-view` is failing to be created currently.

To run exporter with Operate schema creation you need to uncomment descriptors initialization in [DefaultExporterResourceProvider](https://github.com/camunda/camunda/blob/main/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/DefaultExporterResourceProvider.java) (after #22802 is merged) and run StandaloneBroker with following parameters:

```
ZEEBE_BROKER_EXPORTERS_OPERATE_ARGS_ELASTICSEARCH_CREATESCHEMA=true;ZEEBE_BROKER_EXPORTERS_OPERATE_ARGS_ELASTICSEARCH_INDEXPREFIX=newoperate;ZEEBE_BROKER_EXPORTERS_OPERATE_ARGS_ELASTICSEARCH_URL=http://localhost:9200;ZEEBE_BROKER_EXPORTERS_OPERATE_CLASSNAME=io.camunda.exporter.CamundaExporter
```

### TODO

*  fix template creation to be able to read both mappings and settings from json file

**Comment by EuroLew** [comment]
This should fix it, although only for index templates if you need the fix for indices as well I can do it. https://github.com/camunda/camunda/pull/22821, maybe rebase the exp branch against main to show the real diffs? I'm not sure what's going on there
