### ISSUE TITLE
Fix Operate 8.5 integration tests

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#22824]
### Description

* 8.5 integration tests are currently broken: https://github.com/camunda/camunda/actions/runs/11038762829/job/30662723811
* Seems related to an automated patch level update of Lucene: https://github.com/camunda/camunda/commit/a5a7a0f9dde8edc3d161345c55bde06162b8dd1d
* Not broken on main because Lucene wasn't update there

### TODO

* Decide between:
  * Update Lucene both on 8.5 and main and make the build work
  * Revert the Lucene patch level update and prevent Renovate from bumping it (compare config that we use on main)

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by kristinkomschow** [comment]
I'm gonna revert the lucene update and change the config of Renovate, because the used lucene version needs to be compatible with the elasticsearch v7 version we are using and there seem to be no newer versions for the dependencies where we use this.
