### ISSUE TITLE
Add metrics for CamundaExporter

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#22867]
- [x] Identify relevant metrics that helps us with performance tuning and debugging 
- [x] Add the metrics to the exporter
- [x] Make the new metrics available in grafana dashboard

**Comment by EuroLew** [comment]
<img width="726" alt="image" src="https://github.com/user-attachments/assets/9982abe0-8ede-46b9-9da9-3431f6df22cc">
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/4a1478c8-4041-4070-bbe9-f3e1733805c3">

metrics get exported to prometheus actuator and then grafana
