### ISSUE TITLE
Enable concurrency mode in main and 8.6 Operate importer

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#22899]
### Description

Under the assumption that we would make the exporter architecture change with the 8.6.0 release, we only introduced the concurrency mode in the importer on the 8.5 version. We need to also do it on 8.6 and main (future 8.7; the importer will continue to run for a while after the version update). The original change was made with https://github.com/camunda/operate/issues/6477

* Fix on main and 8.6 stable branch

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

**Comment by Zelldon** [comment]
We decided agains this and will run Importing/Exporter in sequence https://github.com/camunda/camunda/issues/24440
