### ISSUE TITLE
Investigate Optimize test coverage in monorepo

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#22909]
### Context

As Optimize was forked to be a part of the monorepo, we cannot replicate most of our ITs to run in C8 only environment. We need to find alternative way of testing.

### Acceptance Criteria

Find an replacement for ITs to test Optimize application (mostly API endpoints)

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RomanJRW** [comment]
Will close this as no clear direction is determined
