### ISSUE TITLE
Identify which APIs can be replaced with unified API in Optimize

### ISSUE THREAD

**Issue by misiekhardcore** [camunda/camunda#22908]
### Context

As Optimize gains access to unified API, we want to replace existing Optimize APIs with those.
This issue is to list all the possible replacements.

**After this is done, issues have to be created in #22906 to replace each listed API and either remove or deprecate the old one.**

Here is a list of what can be replaced:

- **ADD ITEMS**

After this discovery 

### Links

- part of #22906 

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RomanJRW** [comment]
I will close this as a separate topic. The future Optimize architecture is not yet well enough known in order for this issue to be correctly specified
