### ISSUE TITLE
Adapt Tasklist's Importer

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#23044]
### Description
Disable/remove Tasklist's current importer.

_Decision to be made depending on whether the new exporter and the old importer will be required to run in parallel in regards to the data migration process._

Reference on how it was done on Operate Indexes: https://docs.google.com/document/d/1Z-3jykjuTn5egjLEaOJZUbnvg1YIyPyjT474dPYnM2s/edit

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Ensure that Tasklist existing logic is still operational without the old Importers

### Definition of Ready - Checklist
- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by ChrisKujawa** [comment]
Importer and exporter are running in sequence
