### ISSUE TITLE
Remove/adapt old Tasklist indices from Archiver routine (Pending Decision)

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#23078]
As part of harmonizing the indices related to Tasklist, we need to ensure that the Archiver is not archiving old Indices and the new harmonized indices are covered in Operate Archiver or Tasklist Archiver.

**Decision Pending/Options**

- Remove Tasklist Archiver and move to a centralized place (Operate Archiver for example - preferrable)
- Keep the Archiver running only for "Tasklist owned" indices like Tasklist-Task

**Comment by npepinpe** [comment]
Hm, did we remove the tasklist archiver yet? If so, yes.

**Comment by ChrisKujawa** [comment]
Yes we did :) Thanks 👍🏼
