### ISSUE TITLE
Remove/Adapt old Tasklist indices from Backup routine (Pending Decision)

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#23077]
As part of harmonizing the indices on Tasklist, we need to ensure that the Backup is not taking Snapshots of old Indices.

**Decision Pending/Options**
- Remove Tasklist Backup and move to a centralized place (Operate for example)
- Keep the snapshots only for "Tasklist owned" indices like `Tasklist-list-view` and `Forms`

**Comment by Zelldon** [comment]
supersed by https://github.com/camunda/camunda/issues/24456
