### ISSUE TITLE
SchemaManager must set the number of replicas and shards for indices

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#23083]
`SchemaManager` is configuring the number of replicas and shards for index templates. But this is not done for indices. This is not ideal because by default Elasticsearch set the number of replicas to be 1. 

Goal:
The number of replicas and shards are also configurable for Indices similar to IndexTemplates.

**Comment by deepthidevaki** [comment]
@EuroLew I assigned this to you. Let me know if you don't have capacity.

**Comment by EuroLew** [comment]
> [@EuroLew](https://github.com/EuroLew) I assigned this to you. Let me know if you don't have capacity.

I have capacity, will pick it up this week
