### ISSUE TITLE
c8run redefine when ES_JAVA_HOME should be set and unify it between linux+windows (only when JAVA_HOME is set?)

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda#23126]
Elasticsearch comes with a built-in SDK  that we do not want to use because in Mac OS environments, that JDK will provide an error message about the SDK not being trusted with no way to "run anyway".   We originally got around this issue by setting ES_JAVA_HOME, however, ES_JAVA_HOME will only be set if JAVA_HOME is set. 

As a user, if JAVA_HOME is not set, I would expect ES_JAVA_HOME to be set equal to the location of the `java` binary. (ex.  if java is located at `/usr/local/opt/openjdk@23/bin/java`, then ES_JAVA_HOME should be `/usr/local/opt/openjdk@23`. )  However, in linux environments, it may be that java is installed at `/usr/bin/java`, in which case there isn't a clear `JAVA_HOME` to extract from that.

**Comment by jessesimpson36** [comment]
Windows ES_JAVA_HOME is not set even if JAVA_HOME is set. Should be solved as part of this issue.

**Comment by theburi** [comment]
I find that messages that c8Run prints in the output is very difficult to see and they get lost with other output logs.
few customer reported issues starting C8Run just because they did not see JAVA_Home error

One option could be formatting  C8Run output as a log format
Setting JAVA property to /opt/homebrew/Cellar/openjdk@21/21.0.4/libexec/openjdk.jdk/Contents/Home/bin/java
2024-11-06 09:21:02.126 [] [camunda/c8run] [] INFO Setting JAVA property to /opt/homebrew/Cellar/openjdk@21/21.0.4/libexec/openjdk.jdk/Contents/Home/bin/java
Option 2
print errors in a bigger box
-----------------------
ERROR JAVA_HOME is not set.....
------------------

**Comment by jessesimpson36** [comment]
There's a few issues contained within this github issue. 

1. `ES_JAVA_HOME` must always be set to a directory 2 levels higher than a java binary.  that's all JAVA_HOME means in this context.  So in the case of /usr/bin/java,  /usr acting as JAVA_HOME would work (even if that is a little hacky).  `ES_JAVA_HOME` must be set to avoid the Mac unsigned dialogue from appearing.
2. not all JDK's install with a bin folder. in one installation type, I found that on OpenJDK's windows installation, the directory for java home was `C:\Program Files\Common Files\Oracle\Java\` and `java.exe` was found in `javapath\java.exe`. therefore, going 2 directories higher than the java binary is more reliable than searching for a bin folder.
3. I'm wondering if the `java --version` check is even necessary in the c8run level. If the application crashes due to the java version being old, we can simply let the application crash. And a prettier error message could be created in the java level rather than in c8run if necessary.
4. I need to quote the filepath to account for spaces in the path.

I think if I address those 4 topics, we'll be in a much better position with `JAVA_HOME` issues.

But I will need to implement a fix for:
- [ ] stable/8.6
- [ ] main
- [ ] feature branch unifying the app into a golang script

**Comment by jessesimpson36** [comment]
> I'm wondering if the java --version check is even necessary in the c8run level.

I find that the application-level error message looks like this:

```
Error: LinkageError occurred while loading main class io.camunda.application.StandaloneCamunda
	java.lang.UnsupportedClassVersionError: io/camunda/application/StandaloneCamunda has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```
for reference. 

To convert this java class version to a java version , you have to use this table:
https://javaalmanac.io/bytecode/versions/

and you can see 65 == Java 21   and my current version 61 == Java 17 (in my test instance where I purposefully installed a lower JDK version)

**Comment by jessesimpson36** [comment]
After talking to QA + PM, we decided to keep the java version checking in c8run  until we can at a later point propose a version checking + proper error message in the application-level.

**Comment by jessesimpson36** [comment]
This is now complete
