### ISSUE TITLE
Implement Combined reports for OS

### ISSUE THREAD

**Issue by oleksandr-kriuchenko-lohika** [camunda/camunda#23152]
Engineering DRI: @grlimacan

### Context

Implement Combined reports for OS

### Acceptance Criteria

- Combined Reports work in C7

### Testing Notes

- Functionality of combined reports in C7 with OpenSearch is equivalent to that of ElasticSearch
- No QA for C8, since Combined Reports are not supported in C8

### Links

Subtask for https://github.com/camunda/camunda-optimize/issues/12903

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14617
- [ ] https://github.com/camunda/camunda/pull/24288
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
**Successfully tested agains 3.15.0-SNAPSHOT**


Combined process report working as expected ✅ 
CRUD ✅ 

<img width="1715" alt="image" src="https://github.com/user-attachments/assets/f16c249b-cfdc-4afb-a7b2-19dc79eb8f36">

<img width="1715" alt="image" src="https://github.com/user-attachments/assets/089c57ea-3c0c-4f2e-a817-76176009b55f">


https://github.com/user-attachments/assets/d274215c-92c4-493c-8c86-54fcd417868c



Sharing combined reports working as expected ✅ 
<img width="1715" alt="image" src="https://github.com/user-attachments/assets/cc69ce64-ed6b-42ad-9aac-c31082bd8080">

<img width="1715" alt="image" src="https://github.com/user-attachments/assets/3c6239fc-0b6f-4558-aa6d-7463280fdb21">


Combined Report inside Collections ✅ 
CRUD ✅ 

<img width="1715" alt="image" src="https://github.com/user-attachments/assets/d695d0c2-8422-4fbc-bf57-b60974f2b6eb">

<img width="1715" alt="image" src="https://github.com/user-attachments/assets/581e9d81-f363-42b3-bfff-05b3cc1b8e98">

<img width="1715" alt="image" src="https://github.com/user-attachments/assets/e8b4f196-e121-4004-8694-9edfda669629">
