### ISSUE TITLE
Make ILM policy name configurable in Operate

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#23190]
### Description

In Camudna exporter we will create the ILM policy with configurable name. Therefore we need to make the policy name configurable also in Operate (we will use it in archiver to add policy to indices).

### TODO

* add configuration parameter to store ILM policy name
* use it[ in Archiver](https://github.com/camunda/camunda/blob/main/operate/archiver/src/main/java/io/camunda/operate/archiver/ElasticsearchArchiverRepository.java#L174) instead of hardcoded value (both Elastic and Opensearch)

### Additional Information

Related to https://github.com/camunda/camunda/pull/22668

**Comment by Zelldon** [comment]
@sdorokhova @ThorbenLindhauer I think we can close this as we move the archiver to the exporter right?

**Comment by Zelldon** [comment]
Closing this issue. We should make use of the common ILM policy name when moving archiver to the exporter
