### ISSUE TITLE
Incident recovery for Execution Listeners does not work when retries are exhausted

### ISSUE THREAD

**Issue by kristinkomschow** [camunda/camunda#23383]
Part of #21974 epic.

### Describe the bug

Operate currently does not allow for resolving an incident in an Execution Listener that has run out of retries. The operation will always fail, due to the [code that updates the number of retries](https://github.com/camunda/camunda/blob/668c60f199598ee3f2758e238f682ac91f028b05/operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/ResolveIncidentHandler.java#L44-L46) being skipped.

This happens because Execution Listener incidents have an own error type "[EXECUTION_LISTENER_NO_RETRIES](https://github.com/camunda/camunda/blob/36b799887aff7aaa11abc0f5fb57265d52e291c6/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ErrorType.java#L25)".

Needs backport to 8.6

Workarounds:

* Change the job retries via API
* Change the error type in the incident's Elasticsearch document from `UNKNOWN` to `JOB_NO_RETRIES`

### To Reproduce

1. Fail an Execution Listener job with no retries left
2. Attempt to resolve the incident in the operate incident view
3. The retry will always fail again

### Current behavior

Incident resolution for Execution Listener jobs with no retries always fails due to no retries left.

### Expected behavior

Operate updates the amount of retries before attempting the incident resolution.

### Environment

- OS: [e.g. MacOS]
- Browser: [e.g. chrome, safari]
- Operate Version: [e.g. 8.1]

### Additional context

Report of the bug in slack: https://camunda.slack.com/archives/C06CNGWTBAS/p1728461807862369
Discussion about bug details and how we want to fix it: https://camunda.slack.com/archives/C06CNGWTBAS/p1728461829921679

Pull requests:

* Main: https://github.com/camunda/camunda/pull/24140
* 8.6: https://github.com/camunda/camunda/pull/24162

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Incident resolution for Execution Listeners with no more retries updates the number of retries before attempting a retry
- [ ] The solution contains an end-to-end test that checks this behavior

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

#### :mag: Root Cause Analysis

Retries do not get updated for anything other than the `JOB_NO_RETRIES` error type:
https://github.com/camunda/camunda/blob/668c60f199598ee3f2758e238f682ac91f028b05/operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/ResolveIncidentHandler.java#L44-L46

#### :thought_balloon: Proposed Solution

1. Write an end-to-end test that reproduces failing an Execution Listener job in zeebe with no retries left and resolves it via the operate API
2. Add EXECUTION_LISTENER_NO_RETRIES to operate [ErrorType](https://github.com/camunda/camunda/blob/main/webapps-schema/src/main/java/io/camunda/webapps/schema/entities/operate/ErrorType.java)
3. Create a HashSet for JOB_NO_RETRIES type errors (name e.g. `RETRY_ERRORS`) that contains JOB_NO_RETRIES, EXECUTION_LISTENER_NO_RETRIES (TASK_LISTENER_NO_RETRIES will be added to this once task listeners are available)
4. Change the [if-clause that is responsible for executing the retry code](https://github.com/camunda/camunda/blob/668c60f199598ee3f2758e238f682ac91f028b05/operate/webapp/src/main/java/io/camunda/operate/webapp/zeebe/operation/ResolveIncidentHandler.java#L44-L46) to check if the error is part of the Hashset `if (RETRY_ERRORS.contains(incident.getErrorType())) {...}`

**NOTE**: On main, this needs to be fixed in both the importer and the new exporter

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

### :green_book: Link to the test case

[User can resolve an incident with left retry in an Execution listener](https://camunda.testrail.com/index.php?/cases/view/530070)

**Comment by ThorbenLindhauer** [comment]
@Szik could you please perform a manual test that incidents raised by execution listeners can now be successfully resolve (i.e. retries are incremented, the job worker can then complete the job successfully, and the process continues)?

I'm already forwarding it to you (so that I don't forget tomorrow), however on `main` we still need to wait for https://github.com/camunda/camunda/pull/24140 to be merged (currently in the merge queue) before you can test. On 8.6 you can already test it.

**Comment by ThorbenLindhauer** [comment]
Never mind, the main PR just got merged too. So once new snapshots are available, it should be ready to test on both branches :)

**Comment by Szik** [comment]
[test case](https://camunda.testrail.com/index.php?/cases/view/530070) has been created
[execListStart.bpmn.tar.gz](https://github.com/user-attachments/files/17647592/execListStart.bpmn.tar.gz) is used for testing with jopType "test" for Execution Listener (retries 10) listening on "Start".

to fail the job, "zbctl" is jused with this command
```
zbctl create instance "$(zbctl deploy execListStart.bpmn --address localhost:26500 --insecure | \
 awk -F'"' '/
processDefinitionKey/ 
{print $(NF-1); exit}')" --address localhost:26500 --insecure && \
( zbctl create worker test --handler "false" --address localhost:26500 --insecure & sleep 2 ; kill $! )
```
