### ISSUE TITLE
`PartitionInactiveException` is not handled gracefully

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#23446]
When a `PartitionInactiveException` occurs (introduced in https://github.com/camunda/camunda/pull/19876), the `GrpcErrorMapper` does not handle this exception gracefully, eventually leading to an error log about an unexpected error.

Error group: https://console.cloud.google.com/errors/detail/CLLEq6jc8LnF6QE;service=zeebe;time=P7D;locations=global?project=camunda-saas-dev

**Comment by lenaschoenburg** [comment]
The `GrpcErrorMapper` should treat it similarly to `NoTopologyAvailableException`.

**Comment by npepinpe** [comment]
Not sure why this is on our side, as the gRPC stuff is owned by ZPA (at least the mapping). Still, it's a low hanging fruit 🤷
