### ISSUE TITLE
Implement OutlierAnalysis for OpenSearch

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23559]
Engineering DRI: @grlimacan

### Context

Implement OutlierAnalysis for OpenSearch, this mostly consists of the implementation of DurationOutliersReaderOS. This needs to be backported to C7 as well

### Acceptance Criteria

- OutlierAnalysisIT, OutlierAnalysisFilterIT, OutlierAnalysisAuthorizationIT are passing
- The feature is working properly in the Optimize UI

### Testing Notes

Outlier Analysis is working in the Optimize UI

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14541
- [ ] https://github.com/camunda/camunda/pull/23903
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
**Successfully tested again C7 3.15.0-SNAPSHOT**

OutlierAnalysis/Task Analysis working as expected ✅ 
Without filter process instance
![image](https://github.com/user-attachments/assets/14a3fe25-1c7e-434c-b895-998595443226)


OutlierAnalysis/Task Analysis working as expected ✅ 
With filter process instance
![image](https://github.com/user-attachments/assets/fe1524d7-6919-428c-a048-fa979db36ec6)



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Instance Date
![image](https://github.com/user-attachments/assets/3fdc5b21-c298-4b71-b20b-13e2df4121a2)




OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Flow node date
![image](https://github.com/user-attachments/assets/ef8ea1d1-9c7f-464a-9fc8-9fdcdaaadbf5)




OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Instance duration
![image](https://github.com/user-attachments/assets/ea847343-ff4e-4eb2-85ba-a89845a06a93)



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Flow node execution 
![image](https://github.com/user-attachments/assets/e32631f2-cc58-4e44-bf98-341a42f78ca2)



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Incident 
![image](https://github.com/user-attachments/assets/72de8ca4-e398-456e-b692-77ffe217dc29)



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Assignee
![image](https://github.com/user-attachments/assets/08441158-bb2b-4d51-b4a9-b30c9830d337)
![image](https://github.com/user-attachments/assets/5c98f6e2-1a80-4904-b80a-5236a67f8fc3)



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Candidate group
![image](https://github.com/user-attachments/assets/5d53feb9-9f9f-4003-a119-562beb8bfba7)
![image](https://github.com/user-attachments/assets/7cfd1640-538c-4063-a8d1-22fddae06112)



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Variable
![image](https://github.com/user-attachments/assets/750007ea-80e1-40f7-ac89-4af3851a4702)



**Successfully tested again C8 8.7.0-SNAPSHOT**


OutlierAnalysis/Task Analysis working as expected ✅ 
Without filter process instance


OutlierAnalysis/Task Analysis working as expected ✅ 
With filter process instance



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Instance Date



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Flow node date



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Instance duration



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Flow node execution 



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Incident 



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Assignee



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Candidate group



OutlierAnalysis/Task Analysis working as expected ✅ 
With filter Variable
