### ISSUE TITLE
Fix PublicApiReportExportIT

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23572]
Engineering DRI: @grlimacan

### Context

ElasticSearch requests and client is being used directly in the test setup. Make PublicApiReportExportIT.rawDataExportPaginatingWithExpiredScrollId database independent. This is just an issue with the test setup, and not the underlying functionality, therefore not high priority

### Acceptance Criteria

C7: PublicApiReportExportIT.rawDataExportPaginatingWithExpiredScrollId is passing and is database independent
C8: Export Report still works

### Testing Notes

There have been changes to the Report Export as JSON via public API, please test it

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14594
- [ ] https://github.com/camunda/camunda/pull/24183
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Tested agains C8-8.7.0-SNAPSHOT AND C7-3.15.0-SNAPSHOT

Export Report works as expected ✅ 


<img width="1713" alt="image" src="https://github.com/user-attachments/assets/8aa3f5bb-29ca-467c-bfb1-fbc65caf7a0b">

<img width="1713" alt="image" src="https://github.com/user-attachments/assets/da2961cc-c827-4c91-aeba-627c47f60862">
