### ISSUE TITLE
Verify that Backup API and hot backups are working with OpenSearch

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23581]
Engineering DRI: @grlimacan

### Context

All ITs related to backups are already passing with OpenSearch. Verify that the functionality is working from an end-to-end perspective and, if not working, implement whatever might be missing

### Acceptance Criteria

1. Hot backups work with OpenSearch
2. [This setting](https://docs.camunda.io/optimize/self-managed/optimize-deployment/configuration/system-configuration/#opensearch-backup-settings) has been tested and validated as working

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by grlimacan** [comment]
The implementation of the required components is already complete, just validation of the functionality is needed.

**Comment by RobertDorlan** [comment]
**Tested agains C7 3.15.0-Snapshot with OS ✅** 
**Tested agains C8 8.7.0-Snapshot with OS ✅** 

FYI @grlimacan Test has been completed and passed
Backups working as expected

**Comment by RomanJRW** [comment]
@michaldytko - the 8.7.0-alpha2 release and 8.7.0 release actually come from completely different branches. The decision was made to not backport OpenSearch changes back to 8.7 generally as there would simply be too many, and we were not confident of being able to get this working without considerable further effort. If @felix-mueller believes that it is high priority to get the backups working for 8.7, then we can revisit whether backporting the necessary subset of features is reasonable.

@grlimacan might be able to say whether fixing _just_ the backups endpoint is something that could easily be backported. He has FTO at the moment, but tagging so he can provide input on his return

**Comment by felix-mueller** [comment]
@RomanJRW / @grlimacan can you provide a high level estimate about complexity to backport the backups for Opensearch to 8.7 branch?

**Comment by grlimacan** [comment]
> [@RomanJRW](https://github.com/RomanJRW) / [@grlimacan](https://github.com/grlimacan) can you provide a high level estimate about complexity to backport the backups for Opensearch to 8.7 branch?

Hello @felix-mueller, backporting Backups for OpenSearch to our 8.7 branch is a somewhat complex operation, because it had quite a few dependencies on the way we read and store snapshots. Moreover the 8.7 branch has a completely different file structure than the `main` branch due to the modifications done for the single jar project, so backporting requires a fair amount of manual conflict resolution on the codebase. I estimate this would take 1 to 2 weeks of Engineering effort. Please keep in mind that with our current team setup the implementation would need to be done by me, which means taking resources away from the unified configuration epic. Please let me know if you would like me to do this implementation.
