### ISSUE TITLE
Implement KPI report functionality for OpenSearch in C7 and C8

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#23580]
Engineering DRI: @grlimacan

### Context

Identify what is still missing for [KPI reports](https://docs.camunda.io/optimize/components/userguide/process-KPIs/) to work with OpenSearch and implement it. All related ITs are already passing

### Acceptance Criteria

KPI is working as intended

### Breakdown

```[tasklist]
### Pull Requests
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
**Successfully tested agains C7-3.15.0-SNAPSHOT**

KPI Report - Automation rate ✅ 
CRUD ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/748f8aad-5045-42a8-80e1-3d9b57fb71bf">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/b63c2d4f-0b35-4845-902d-32626bd346a0">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/0c31137d-14d0-4d4f-921d-66305d6c38c0">



KPI Report - Throughput time ✅ 
CRUD ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/007f59a3-dd68-40dc-9077-bf657069966f">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/39bf59c5-51e7-4593-b835-16ee1e866718">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/39a3e5bc-cd9c-4227-b13d-cb9387cc2fa0">



----------------------------------------------------------------------------------------------------------------------------


**Successfully tested agains C8-SNAPSHOT**


KPI Report - Automation rate ✅ 
CRUD ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/880a3943-31b3-4005-9efb-56ccf0833798">



Hey @grlimacan could you please take a look at this.
Selecting end event for Automation rate/Throughput time ❌ 
https://github.com/user-attachments/assets/d5e077dd-718d-4487-b188-5d1e3a697b68

**Comment by grlimacan** [comment]
> Hey @grlimacan could you please take a look at this. Selecting end event for Automation rate/Throughput time ❌ https://github.com/user-attachments/assets/d5e077dd-718d-4487-b188-5d1e3a697b68

@RobertDorlan I've analyzed this and the backend responses seem fine. This error is also occurring with ElasticSearch. And it seems to have been working with 8.6.2. This looks like a general Front-End bug unrelated to OpenSearch. Can you please verify that this is the case and create a bug ticket for Front-End accordingly?

**Comment by RobertDorlan** [comment]
**Successfully tested agains C8-SNAPSHOT**

KPI Report - Automation rate ✅ 
CRUD ✅ 
![image](https://github.com/user-attachments/assets/98ae7df7-8333-4136-b4ce-83a443025cf1)
![image](https://github.com/user-attachments/assets/9f0ac25f-588d-4a49-b644-92203155c37b)
![image](https://github.com/user-attachments/assets/0873ffa8-963c-4e3f-9e77-5b30a297c69b)
![image](https://github.com/user-attachments/assets/9f5cf3e7-ff62-47f7-b071-959dddeb0903)




KPI Report - Throughput time ✅ 
CRUD ✅ 
![image](https://github.com/user-attachments/assets/348df0f4-9b7e-4983-8708-f2cb1dd575d1)
![image](https://github.com/user-attachments/assets/172f9601-1e6e-4aa4-af70-415cd0375411)
![image](https://github.com/user-attachments/assets/77aa5459-ce77-4c09-abf9-2979ef79d01a)
![image](https://github.com/user-attachments/assets/afea9aa0-10e2-442f-94d0-46fc5e2cb5c5)
