### ISSUE TITLE
Unify C8Run scripts between windows and linux

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda#23591]
**Describe the issue:**

C8Run has platform-specific parts of it, and as result, we ended up with 2 different projects,  we have a
* bash script representing how the project works on linux + mac
* golang script representing how the project works on windows

**Historical justification**

C8Run began by adapting the camunda 7 run distribution scripts, which features a bash script for linux+mac and a **batch** script for windows.  For C8Run, I started with the same premise. I successfully created a bash script, however, I found that I was exceeding the capabilities of the batch scripting language, and made the decision to switch to Golang for the windows version.  I also had this idea that I was being consistent with the scripts in the camunda repo  (download camunda-zeebe .tar.gz file and untar it, and there's a bash and batch script for `./bin/camunda`), which means that other Camunda developers would be able to contribute to it easier. However,  it turned out that those scripts were created by bots, and bash + batch are not languages  many camunda developers is familiar with.

**What are our hopes for unifying these scripts?**

There's some logic that is identical between the windows and linux versions. I'd prefer if these bits of logic were not duplicated.  I also want the packaging process to be identical for both, and would like to be able to do things like cross-compile a package, such as a windows build but on a linux machine.

Furthermore, there is some functionality that is implemented for Linux, that is not implemented for Windows. If this was one script, the hope would be that there would not be any left-out functionality.

**Comment by hisImminence** [comment]
Done!
