### ISSUE TITLE
Move operate importer integration tests for migrated ExporterHandlers to Camunda-Exporter

### ISSUE THREAD

**Issue by mustafadagher** [camunda/camunda#23616]
Based on [this procedure](https://camunda.slack.com/archives/C06F0GLJNFM/p1728553416415679), we should start importing all Operate Importer Integration Tests (Type # 1 below) to Camunda exporter.

The procedure as described by @deepthidevaki  is as follows:

Analysing the existing Operate importer IT in io.camunda.operate.zeebeimport, I see following types of tests
1. Integration tests, where data is injected into Zeebe and verify that importer has imported that data.
Eg: ProcessInstanceZeebeImportIT#testProcessInstanceCreated - verifies a process instance created in Zeebe is imported by Operate and has the expected data/state.
3. Testing query/search API
Eg: FlowNodeInstanceZeebeImportIT:testFlowNodeInstanceTreeFailsWithWrongSearchafter
Eg: ErrorMessageZeebeImportIT#testFilterErrorMessagesBySubstring
4. Specific logic of importing/exporting a record
Eg:- ErrorMessageZeebeImportIT#testErrorMessageIsTrimmedBeforeSave This tests creates an incident and verifies that the errormessage stored in the operate index is trimmed.
5. Importer specific tests
Importing is idempotent
Process instance completed next day is imported correctly

My recommendation is:
- Type # 1 tests should be included in the exporter integration tests.
- Type # 2 tests should be part of the rest api client tests (That means, we don't do anything as part of exporter tests.)
- Type # 3 should be part of unit tests of exporter handlers.
  - This means, when adding the handlers to the main, we should ensure that such cases are covered by the unit tests of corresponding handlers.
- Type # 4 not sure about these. Some of them may not be relevant anymore for the exporters. Would have to check it case by case.

So the test cases covered by integration tests will be reduced, and more cases should be moved to unit tests.

Here is a reference [PR](https://github.com/camunda/camunda/pull/23439) with the handler for decision record and the integration tests.

**Comment by EuroLew** [comment]
Alternative approach I didn't have much success with but posted here for documentation purposes.

the operate `zeebeImportIT` rely on an elasticsearch exporter for its records and manually calling the importer to batch for specific records in `ElasticsearchTestRuleProvider.processRecordsAndWaitFor`. Therefore a possible solution is 

1. Enable the camunda exporter alongside the Elasticsearch exporter along the lines of #23820 
2. Change the `ElasticsearchTestRuleProvider.processRecordsAndWaitFor` method to not manually import specific records (actually make it do nothing), but still wait for the predicate condition to be true.
3. The predicate conditions will eventually become true as the camunda exporter will export records and change the state of the elasticsearch engine eventually.

**Comment by Zelldon** [comment]
We decided against this concept, and will keep the IT for Camunda Exporter simple. We are testing events get consumed and written to ES/OS. 

REST API project team will build more round-trip style e2e tests https://camunda.slack.com/archives/C05QBRGMA9F/p1729604011992119
