### ISSUE TITLE
Move UserTaskHandler

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#23623]
Pending decision regarding this Exporter Handler as Operate should migrate to the new `tasklist-task` index as part of the index harmonization process.

Yet unknown if Operate team(or @panagiotisgts) has capacity to achieve this for 8.7

**Comment by Zelldon** [comment]
> Pending decision regarding this Exporter Handler as Operate should migrate to the new `tasklist-task` index as part of the index harmonization process.
> 
> Yet unknown if Operate team(or [@panagiotisgts](https://github.com/panagiotisgts)) has capacity to achieve this for 8.7

We have to achieve this for 8.7 there is no way around. 

What is blocking us here? Can we skip this handler? As we implement this with tasklist?

**Comment by Zelldon** [comment]
We will use the Tasklist-task index, already part of exporter thanks to @panagiotisgts https://github.com/camunda/camunda/issues/23042


Operate BE needs to be ported in https://github.com/camunda/camunda/issues/23891 

I will close this.
