### ISSUE TITLE
IncidentQueryTest is flaky

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda#23706]
**Summary**

- How often does the test fail? - at least 3 times
- Does it block your work? - yes, CI does not pass, merge queues are blocked
- Do we suspect that it is a real failure? - no, just a missing wait statement probably in the test setup

**Failures**

* Error message: `IncidentQueryTest.beforeAll:73 ? NoSuchElement`
* Introduced in https://github.com/camunda/camunda/pull/23567

**Hypotheses**

In the test setup, we probably need to wait until the incidents have been created as well before trying to access them.

**Logs**

n/a

**Comment by tmetzke** [comment]
Failed here: https://github.com/camunda/camunda/actions/runs/11385789427
[Test results for [IT] Root Integration Tests.zip](https://github.com/user-attachments/files/17415167/Test.results.for.IT.Root.Integration.Tests.zip)

**Comment by ralfpuchert** [comment]
Should be solved by introduction of waiting for incidents in `QueryTest::waitUntilProcessInstanceHasIncidents` in PR https://github.com/camunda/camunda/pull/23488
