### ISSUE TITLE
Add integration tests for from/limit paging method

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#23722]
### Description

Currently paging is tested for client api with searchBefore/searchAfter approach.
Integration tests for from/limit are needed for query endpoints

### TODO

- [x] Process definition
- [x] Process instance
- [x] Decision definition
- [x] Decision instance
- [x] Decision requirements
- [x] Flow node instance
- [x] Incident
- [x] Variable

**Comment by nathansandi** [comment]
@ralfpuchert 
I added the integration tests, and left a non blocking issue over there to discuss related to one of the tests that was not working in incidents (related to the job key), we can later open a separate issue to fix that one.
