### ISSUE TITLE
`UpdateRoleMultiPartitionTest.shouldDistributeRoleUpdateCommand` is flaky 

### ISSUE THREAD

**Issue by mustafadagher** [camunda/camunda#23758]
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? so far, once [here](https://github.com/camunda/camunda/actions/runs/11438049438?pr=23754) 
- Does it block your work? no
- Do we suspect that it is a real failure? IDK

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
  shouldDistributeRoleUpdateCommand: io.camunda.zeebe.engine.processing.authorization.UpdateRoleMultiPartitionTest

Expecting actual to contain the specified subsequence but failed to find the element at subsequence index 0 in actual:
subsequence element not found in actual:
  (UPDATE, COMMAND, 1)
actual:
  [(CREATE, COMMAND, 1),
    (CREATED, EVENT, 1),
    (STARTED, EVENT, 1),
    (ENQUEUED, EVENT, 2),
    (DISTRIBUTING, EVENT, 2),
    (ENQUEUED, EVENT, 3),
    (DISTRIBUTING, EVENT, 3),
    (ACKNOWLEDGE, COMMAND, 2),
    (ACKNOWLEDGE, COMMAND, 3),
    (ACKNOWLEDGED, EVENT, 2),
    (ACKNOWLEDGED, EVENT, 3),
    (FINISH, COMMAND, 1),
    (FINISHED, EVENT, 1)]
subsequence:
  [(UPDATE, COMMAND, 1), (UPDATED, EVENT, 1), (STARTED, EVENT, 1)]
java.lang.AssertionError: 
Expecting actual to contain the specified subsequence but failed to find the element at subsequence index 0 in actual:
subsequence element not found in actual:
(UPDATE, COMMAND, 1)
actual:
[(CREATE, COMMAND, 1),
(CREATED, EVENT, 1),
(STARTED, EVENT, 1),
(ENQUEUED, EVENT, 2),
(DISTRIBUTING, EVENT, 2),
(ENQUEUED, EVENT, 3),
(DISTRIBUTING, EVENT, 3),
(ACKNOWLEDGE, COMMAND, 2),
(ACKNOWLEDGE, COMMAND, 3),
(ACKNOWLEDGED, EVENT, 2),
(ACKNOWLEDGED, EVENT, 3),
(FINISH, COMMAND, 1),
(FINISHED, EVENT, 1)]
subsequence:
[(UPDATE, COMMAND, 1), (UPDATED, EVENT, 1), (STARTED, EVENT, 1)]
at io.camunda.zeebe.engine.processing.authorization.UpdateRoleMultiPartitionTest.shouldDistributeRoleUpdateCommand(UpdateRoleMultiPartitionTest.java:63)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[LOGS](https://drive.google.com/file/d/1Um-HDhjrEB_EOvbxseNUmkgrLZr-R7-q/view?usp=drive_link)

**Comment by npepinpe** [comment]
As this is an engine test, I'm hoping that's something the ZPA team can take this.

**Comment by mustafadagher** [comment]
also [retrying the first run](https://github.com/camunda/camunda/actions/runs/11438049438/job/31829042326?pr=23754) failed too

**Comment by nicpuppa** [comment]
@mustafadagher it should be resolved by https://github.com/camunda/camunda/pull/23755, can you double check ?

**Comment by mustafadagher** [comment]
@nicpuppa passes after rebase. Thanks 👍

**Comment by mustafadagher** [comment]
@nicpuppa I just rebased this [PR](https://github.com/camunda/camunda/pull/23820) and it failed again [here](https://github.com/camunda/camunda/actions/runs/11463929681/job/31898963601?pr=23820)
