### ISSUE TITLE
Implement `Usage Metric` REST API

### ISSUE THREAD

**Issue by megglos** [camunda/camunda#23812]
## Description

We decided to migrate the former actuator endpoints from [Tasklist](https://docs.camunda.io/docs/next/self-managed/tasklist-deployment/usage-metrics/) and [Operate](https://docs.camunda.io/docs/next/self-managed/operate-deployment/usage-metrics/) to the C8 REST API. 

This will make access to the metrics API easier, as the user is not depending on the management port which switched to default to 9600 with the 8.6 release for Tasklist and Operate.

The usage metrics endpoint should provide the Usage metrics as defined [in the public documentation](https://docs.camunda.io/docs/next/reference/usage-metrics/#definition-of-metrics).

We want to consolidate the former dedicated usage metrics endpoints into one single usage metrics endpoint.
We accept that we may need to perform two queries to `operate-metric-1.0.0_` and `tasklist-metric-1.0.0_` to build the result, as both indices will stay (see [this (🔒 internal) discussion](https://docs.google.com/spreadsheets/d/1XuzUmht3hML32QOfWiz_5lNo9B5lakqDz1tOM16oAUI/edit?gid=0#gid=0&range=E12)).

The endpoint should be implemented as described in the [REST API Developer Guide](https://github.com/camunda/camunda/blob/main/docs/rest-controller.md)

### Endpoint

* Summary: Query usage metrics
* Description: Search for usage metrics with defined criteria, e.g. for a specific date range.
* Path: `POST /v2/usage-metrics/search`
* Request body: search request with the following filter attributes
  * `startTime` - type `string[date]` - required, no default - the start time of the date range to fetch the metrics for
  * `endTime` - type `string[date]` - required, no default - the end time of the date range to fetch the metrics for
* Response:
  * `200 OK` - type `application/json` - a JSON object representing the usage metrics with the following fields
    * `assignees` - type `long` - the amount of unique active users
    * `processInstances` - type `long` - the amount of created process instances
    * `decisionInstances` - type `long` - the amount of executed decision instances
  * example response
    ```json
    {
      "assignees": 15,
      "processInstances": 12345,
      "decisionInstances": 5354365
    }
    ```

### Acceptance Criteria

- [x] Service Layer for Metrics search
- [x] REST API endpoint incl. OpenAPI spec
- [x] Integration tests

### Excluded from Scope

- Java client support - not doing as this endpoint has no use-case within process automation

### Related resources

* PDP epic: https://github.com/camunda/product-hub/issues/2544

### Implementation notes

- Tasklist uses [TermsAggregation](https://github.com/camunda/camunda/blob/50d3a76829a966858a77cb2100ab87409d0d97d3/tasklist/els-schema/src/main/java/io/camunda/tasklist/store/elasticsearch/TaskMetricsStoreElasticSearch.java#L100-L100)
  - for counting assignees  
- Operate uses [TermsAggregation](https://github.com/camunda/camunda/blob/50d3a76829a966858a77cb2100ab87409d0d97d3/operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/dao/Query.java#L50-L50) in a abstraction layer `Query` 
  - for counting process instances
  - for counting decision instances 
- C8 API needs aggregations (at least `TermsAggregation`)
  - [PR]() for adding aggregations
#### Current solution
Apply distinct count in service layer until aggregations are integrated in search module.

### Pull requests

- [OpenAPI definition, Rest controller, Service infrastructure](https://github.com/camunda/camunda/pull/25690)

**Comment by megglos** [comment]
To clarify with @aleksander-dytko :
- is there a need for the include params or can we just always return all of them - this relates to the fact that previously there were dedicated endpoints for each
- is there a need for the unique user names?

**Comment by megglos** [comment]
synced with @aleksander-dytko

> is there a need for the include params or can we just always return all of them - this relates to the fact that previously there were dedicated endpoints for each

 there is no need to toggle these separately, we can always return them

> is there a need for the unique user names?

not that we are aware of, we will not include them

**Comment by tmetzke** [comment]
API planning:
* @danielkelemen will look into this after #24077

**Comment by tmetzke** [comment]
Follow-up for production readiness: https://github.com/camunda/camunda/issues/26106

**Comment by ThorbenLindhauer** [comment]
Note: unlike stated in the ticket description, this is implemented as GET `/v2/usage-metrics`, see https://docs.camunda.io/docs/next/apis-tools/camunda-api-rest/specifications/get-usage-metrics/
