### ISSUE TITLE
Remove breadcrumbs from the navbar

### ISSUE THREAD

**Issue by OmranAbazid** [camunda/camunda#23830]
Engineering DRI: @OmranAbazid

### Context

See https://github.com/camunda/camunda-optimize/issues/6864

### Acceptance Criteria

- The breadcrumbs are removed from the navbar

### Testing Notes

- Create any entity in Optimize (report / collection/dashboard)
- Navigate to the created entity
- Check that the navigation bar does not show the sub tab link (previously, it used to be e.g. Link<Collection> > Link<New Collection>. Now should be just Link<Collection>)

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/23854
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Successfully tested agains C8 - 8.7.0-SNAPSHOT



 Optimize 
 Report does not show the sub tab link as expected ✅ 
![image](https://github.com/user-attachments/assets/f7734aa2-2b6d-41b7-b5f6-6bf5e7526ded)


 Collection does not show the sub tab link as expected ✅ 
 ![image](https://github.com/user-attachments/assets/31a3d859-b72f-4034-a5f6-f3d957ce3a69)

 
 Dashboard does not show the sub tab link as expected ✅ 
![image](https://github.com/user-attachments/assets/346e136e-ca4e-4626-9899-177dea2aa6f6)
