### ISSUE TITLE
Number of threads created in Gateway for blocking identity calls causing "too many concurrent streams" error

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/camunda#23853]
**Describe the bug**

After upgrading from Camunda 8.5.2 to Camunda 8.6.2, a customer started to see frequent 500 errors coming from Identity. The error message is `java.io.IOException: too many concurrent streams` caused by Identity SDK's http client. The error message is originated from Zeebe gateway.

This is due to switching to use virtual threads instead of a configured number of threads in a thread pool for Zeebe Gateway (see https://github.com/camunda/camunda/issues/18697). That means now we allow creating unlimited number of threads per blocking identity call. Since Zeebe gateway doesn't limit number of threads created for execution, identity SDK can now create unlimited number of streams but Identity SDK's HttpClient itself fails to handle it.

**Expected behavior**

Identity SDK's Http client shouldn't fail with `too many concurrent streams`.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Exception:
java.util.concurrent.CompletionException
Message:
java.io.IOException: too many concurrent streams
Stacktrace:
java.util.concurrent.CompletableFuture.encodeRelay
java.util.concurrent.CompletableFuture.uniComposeStage
java.util.concurrent.CompletableFuture.thenCompose
jdk.internal.net.http.MultiExchange.responseAsyncImpl
jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2
com.dynatrace.agent.introspection.threading.completable.FunctionWrapper.apply(FunctionWrapper.java:22)
java.util.concurrent.CompletableFuture$UniCompose.tryFire
java.util.concurrent.CompletableFuture.postComplete
java.util.concurrent.CompletableFuture$AsyncSupply.run
jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute
java.util.concurrent.CompletableFuture.completeAsync
jdk.internal.net.http.MultiExchange.responseAsync
jdk.internal.net.http.HttpClientImpl.sendAsync
jdk.internal.net.http.HttpClientImpl.send
jdk.internal.net.http.HttpClientFacade.send
io.camunda.identity.sdk.impl.rest.RestClient.send(RestClient.java:119)
io.camunda.identity.sdk.impl.rest.RestClient.request(RestClient.java:106)
io.camunda.identity.sdk.impl.TenantsImpl.forToken(TenantsImpl.java:38)
jdk.internal.reflect.DirectMethodHandleAccessor.invoke
java.lang.reflect.Method.invoke
io.camunda.identity.sdk.annotation.AnnotationProcessor.lambda$apply$0(AnnotationProcessor.java:33)
jdk.proxy2.$Proxy134.forToken
io.camunda.zeebe.gateway.interceptors.impl.IdentityInterceptor.interceptCall(IdentityInterceptor.java:99)
io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:269)
io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:701)
io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:408)
io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:613)
io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603)
io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run
java.lang.VirtualThread.run
```

</p>
</details>

Related support case: [SUPPORT-24047](https://jira.camunda.com/browse/SUPPORT-24047)

**Comment by npepinpe** [comment]
that would mitigate it, but could just push the problem downstream. worth a try

**Comment by npepinpe** [comment]
imo we should fix it, and the error message should reflect the possible actions to take. ultimately it can also mean identity backend is not fast enough to handle the load

**Comment by npepinpe** [comment]
:information_source: If scaling up the gateways doesn't help, it could be that Identity is the bottleneck - in which case more gateways means more requests hitting it, and they will all block fairly fast. So you may also need to scale up your Identity pods, whether vertically or horizontally (or a combination of both).

**Comment by npepinpe** [comment]
We will schedule this and attempt to get it into the next wave of patches in November (though it's a very tight deadline).

**Comment by megglos** [comment]
Solution approach proposal by @npepinpe 
> basically use a semaphore to control contention of the SDK (or at least, usage of that method, since I guess not all of the SDK needs to be locked), and fail gracefully:
> * wait X seconds for the lock instead of failing immediately
> * if failing to grab it, indicate in the error message Identity is currently unable to handle the load
>
> it will greatly improve the UX, indicate a possible solution, and hopefully will also reduce the rate of the error by hopefully keeping identity snappy (but that's a theory).

**Comment by megglos** [comment]
@koevskinikola will block a time slot next week. @npepinpe can you offer pairing on this to make this slot most effective potentially creating a fix?

**Comment by npepinpe** [comment]
@koevskinikola - can we close this?

**Comment by koevskinikola** [comment]
Yup, thanks for the ping.
