### ISSUE TITLE
Extend test coverage of the Camunda exporter

### ISSUE THREAD

**Issue by EuroLew** [camunda/camunda#23885]
**Description**

The specific business logic of how records are exported and that the handlers write entities to the expected indices should be tested.

Also a test that verifies the exporter can trigger schema creation.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/23886
- [ ] https://github.com/camunda/camunda/issues/23888
```

**Comment by Zelldon** [comment]
@EuroLew can this issue be closed ? Or is there more to be done?

**Comment by EuroLew** [comment]
> @EuroLew can this issue be closed ? Or is there more to be done?

once this is merged we can close it.
https://github.com/camunda/camunda/pull/24405
