### ISSUE TITLE
Add new error types to ErrorType enum

### ISSUE THREAD

**Issue by vitorwtavares** [camunda/camunda#23945]
Part of #21974 epic.

### Description
New types of errors were added on the Zeebe side along with the User Tasks. `EXTRACT_VALUE_ERROR` and `TASK_LISTENER_NO_RETRIES` need to be added to [ErrorType enum](https://github.com/camunda/camunda/blob/main/webapps-schema/src/main/java/io/camunda/webapps/schema/entities/operate/ErrorType.java) to treat them correctly.

Relates to https://github.com/camunda/camunda/issues/23946

### Acceptance Criteria

- [ ]

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

**Comment by kristinkomschow** [comment]
I merged this into https://github.com/camunda/camunda/issues/23946
