### ISSUE TITLE
Optimize quits if it goes over the nested document limit

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#24059]
Engineering DRI: @grlimacan

### Describe the bug

Optimize quits if it goes over the nested document limit

### Expected behaviour

If when importing Optimize goes over the nested document limit, then it should display an error message but keep running. Moreover if CAMUNDA_OPTIMIZE_IMPORT_DATA_SKIP_DATA_AFTER_NESTED_DOC_LIMIT_REACHED=true, then Optimize is expected to remove the affected documents and do an import run again

### To Reproduce

1. Set the nested document limit to a very low number, e.g. CAMUNDA_OPTIMIZE_OPENSEARCH_SETTINGS_INDEX_NESTED_DOCUMENTS_LIMIT=5
CAMUNDA_OPTIMIZE_ELASTICSEARCH_SETTINGS_INDEX_NESTED_DOCUMENTS_LIMIT=5
2. LEt the importer run

### Environment observed:

- Optimize mode(s): Only C8
- Optimize version(s): 8.6.1
- Database(s) (Elasticsearch/OpenSearch): Elasticsearch/OpenSearch

### Breakdown

```[tasklist]
### Pull Requests
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [ ] Yes. If so:
  - [ ] The bug description is clear
  - [ ] The steps to reproduce are clear
  - [ ] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by grlimacan** [comment]
Investigation conclusion: it's only a problem when that limit is so artificially low that it will cause an error during Optimize init, while it is initializing the Management Dashboard. Optimize then quits because the init of Optimize itself fails, which makes sense. If we instead use a more realistic value (e.g. > 10), the nested doc limit works properly in the importer both on ES and OS - i.e. even when importing records that go beyond the set nested document limit, this situation gets handled as designed and Optimize does not quit, therefore closing the issue

**Comment by RobertDorlan** [comment]
Successfully verified agains C8 - 8.7.0-SNAPSHOT


Elasticsearch
<img width="1705" alt="image" src="https://github.com/user-attachments/assets/c88541d5-bc92-402a-b13c-047f3b9ac9e9">


OpenSearch
<img width="1705" alt="image" src="https://github.com/user-attachments/assets/1dd0e88c-5171-4c1e-8470-51c79dc6f372">
