### ISSUE TITLE
Deal with changed format of `flowNodeId` in `treePath`

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda#24063]
### Description

Before 8.7 `treePath` for process instances and incidents looked like this:
```
PI_100/FN_call1/FNI_101/PI_102/FN_call2/FNI_103/PI_104/FN_servicetask/FNI_105
```
where the value prefixed with `FN_` is the `elementId` (or `flowNodeId`) of the corresponding flow node (can be either call activity or any node with an incident).

[Now](https://github.com/camunda/camunda/pull/20293) we get the field `callingElementPath` in exported incident record which contains the encoded values of `elementId`. "The Element Ids are encoded by lexicographically sorting all calling activity elements in one deployment resource, and using the index of each call activity Id in this sorted list as the respective encoded value."

To resolve `flowNodeId` from encoded value, we need to store call activity ids in process cache and use it in corresponding export handlers.

### TODO

* add list of call activity ids to process cache: they must be sorted lexicographically for ease of use
* resolve element id from process cache in export handlers which store tree paths for incident and process instance

**Comment by Zelldon** [comment]
We (@ThorbenLindhauer @sdorokhova and I) discussed the TreePath topic today again. Especially regarding handling the lexicographic index handling. 

* Thorben mentioned that it was planned that we use the ProcessCache for such.

**Comment by Zelldon** [comment]
We (@ThorbenLindhauer @sdorokhova and I) discussed the TreePath topic today again. Especially regarding handling the lexicographic index handling. 

* Thorben mentioned that
  * it was planned that we use the ProcessCache for such. Was questioning whether we have actual data that we should not do this
  * In general we should try to use the element id as it makes debugging also easier
  * We should try to avoid adding more things into post-importer, as it delays also data availability
* Chris:
  * Agrees and says it is ok to do the simplest/easiest for now and iterate. Lets have it working and get some data whether it is a problem.
  * Post importer / Archiver might be an option if we need to improve resource consumption. In general, it is better UX to have some data available and lazy load more then having nothing for a while. But to make a decision we need some more data.
* Svetlana:
  * So we need the ProcessCache work. 
  * @sdorokhova will reach out to @deepthidevaki 
  * ProcessCache will also only contain information for CallActivities so likely not much, especially nothing if no Call Activities available.


Later we discussed also the open issues, and whether we can split them and distribute. There is a chance that we can do this with https://github.com/camunda/camunda/issues/24061 
>  fill in "intra" treePath in flow node instances in list-view and flow-node-instance indices

@sdorokhova will fill in more details what to do.

**Comment by Zelldon** [comment]
FYI I documented the decision here https://docs.google.com/document/d/1w1VzwyvvBzu0vnjCUj4UcLxTCVae8iMXAMA5_m6xs1s/edit?tab=t.0#bookmark=id.lym0ol9vq9la
