### ISSUE TITLE
Add Archiver configuration to Camunda Exporter configuration

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#24078]
**Description**

The goal is to add a new sub-configuration item in the `ExporterConfiguration` of the Camunda Exporter. The new class should contain the following properties:

- `rolloverEnabled`: controls if we run the archiver or not (failsafe)
- `rolloverDateFormat`: this format will be used to create timed indices. It must correspond to the `rolloverInterval` parameter.
- `elsRolloverDateFormat`: Rollover date format for ELS
- `rolloverInterval`: Interval description for "date histogram" aggregation, which is used to group finished instances.
- `rolloverBatchSize`: Maximum size of items to process in an archiving batch
- `waitPeriodBeforeArchiving`
- `delayBetweenRuns`: In case archiver runs without delays, two subsequent runs may try to process the same process entities (because of Elasticsearch refresh behaviour). In general, it's fine, but there are two side effects: 1. We do the job, that is not needed anymore -> wasting CPU time 2. Metrics will become incorrect, as it's not possible to distinguish such (duplicated) calls from normal ones.

**Open questions**

> [!Note]
> These should be answered before any PR is accepted.

- Assumption is ILM or retention settings were already migrated to the exporter, but this needs to be double checked.
- Do we want to keep the `rollover` prefix for the config?
- How easy should the migration from the old config to the new one be (impact on property names)?

**Comment by rodrigo-lourenco-lopes** [comment]
Currently in the archiver properties we dont seem to be using `elsRolloverDateFormat ` and `waitPeriodBeforeArchiving`. Should we still keep them in case we want to use them later?

**Comment by npepinpe** [comment]
You mean this is not used anywhere in the code base?

**Comment by rodrigo-lourenco-lopes** [comment]
No we use it, sorry, we have another method that gets the same property but appends "now-" to it: `getArchivingTimepoint`

**Comment by npepinpe** [comment]
I'm not sure I get it :smile:
