### ISSUE TITLE
Make SO_SNDBUF & SO_RCVBUF configurable in NettyMessagingService

### ISSUE THREAD

**Issue by entangled90** [camunda/camunda#24104]
Currently SO_SNDBUF & SO_RCVBUF used in `NettyMessagingService`  are not configurable.
The current default value is set to 1MB.

A user should be able to configure them using the following keys:
#### broker
-  zeebe.broker.network.so_sndbuf
- zeebe.broker.network.so_rcvbuf
#### gateway
-  zeebe.gateway.network.so_sndbuf
- zeebe.gateway.network.so_rcvbuf

The configs must be added to the `NetworkCfg` class (used by both broker & gateway), then mapped to `MessagingConfig`.

The docs must be updated as well to include these new configurations.

**Comment by npepinpe** [comment]
Do you think it would be worth adding this and then benchmarking different values? Could be a good benchmark onboarding for Filipe maybe?

**Comment by npepinpe** [comment]
Putting it in the backlog for now though - let's say what you think.

**Comment by entangled90** [comment]
I don't know if we can find any performance gain as it may depend on the workload but it's good task for getting to know the how you can run benchmarks!
I guess that also having this option configurable it's pretty standard, so it's probably a good addition :+1:

**Comment by npepinpe** [comment]
@filipecampos - as we discussed, this can be your benchmark onboarding task, and Carlo will onboard you (just for this task). As it's likely less time consuming than the dynamic topology one, let's do this first if possible.

**Comment by filipecampos** [comment]
We decided to make the size of sockets' receive and send buffers configurable. To assess if there are some noticeable differences in performance and behavior, we decided to run some benchmarks with different sizes for these buffers with no further changes to other parameters.

### Hypothesis
By increasing the size of the buffers we should see a decrease in CPU usage and overall latency shouldn't be affected.


### Configuration

The _values-realistic-benchmark.yaml_ file was used with a single change, _zeebe.resources.limits.cpu_ was set to 2500m.

We executed the following command in a pod to retrieve the maximum allowed sizes for each buffer.
> $ grep . /proc/sys/net/ipv4/tcp*mem
> /proc/sys/net/ipv4/tcp_rmem:4096        87380   6291456
> /proc/sys/net/ipv4/tcp_wmem:4096        16384   4194304
> 

This translates to a maximum of 6MB for SO_RCVBUF and 4MB for SO_SNDBUF. In a initial batch of benchmarks
Therefore, we decided to run a benchmark for the following combinations of buffer sizes for both the Broker and the Gateway. We initially decided to increase by 1MB the default size of both buffers up to the maximum values and then decided to also assess the behavior with 256KB and 512KB.

**First run**
|  | **Broker** |  | **Gateway** |  | **Grafana** |
| --- | --- | --- | --- | --- | --- |
|  | **socketReceiveBuffer** | **socketSendBuffer** | **socketReceiveBuffer** | **socketSendBuffer** |  |
| **1MB - Baseline** | 1MB | 1MB | 1MB | 1MB | https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=fc-socket-params-1a&var-pod=All&var-partition=All&from=1732799460000&to=1732803060000 |
| **2MB** | 2MB | 2MB | 2MB | 2MB | https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=fc-socket-params-2&var-pod=All&var-partition=All&from=1732790880000&to=1732794480000 |
| **3MB** | 3MB | 3MB | 3MB | 3MB | [https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=fc-socket-params-3b&var-pod=All&var-partition=All&from=1732801920000&to=1732805220000](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=fc-socket-params-3b&var-pod=All&var-partition=All&from=1732801920000&to=1732805520000) |
| **4MB** | 4MB | 4MB | 4MB | 4MB | https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=fc-socket-params-4&var-pod=All&var-partition=All&from=1732791000000&to=1732794600000 |
| **6+4MB** | 6MB | 4MB | 6MB | 4MB | [https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=fc-socket-params-6a&var-pod=All&var-partition=All&from=1732800900000&to=1732804800000](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=fc-socket-params-6a&var-pod=All&var-partition=All&from=1732800900000&to=1732804500000) |

**Second run**
|  | **Broker** |  | **Gateway** |  | **Grafana** |
| --- | --- | --- | --- | --- | --- |
|  | **socketReceiveBuffer** | **socketSendBuffer** | **socketReceiveBuffer** | **socketSendBuffer** |  |
| **256KB** | 256KB | 256KB | 256KB | 256KB | https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=fc-socket-params-256&var-pod=All&var-partition=All&from=1733142600000&to=1733146200000 |
| **512KB** | 512KB | 512KB | 512KB | 512KB | https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=fc-socket-params-512&var-pod=All&var-partition=All&from=1733156400000&to=1733160000000 |


### Preconditions
- Waited for the cluster to be balanced (each pod was leader of 1 partition)
- Waited for the nodes to enter into a steady state
- Decided to inspect around 1 hour of regular functioning for each scenario

### Results

There aren’t that many significant differences in the metrics by looking at the various Grafana dashboards, including General Overview, Throughput, Memory, CPU, IO, Messaging, Latency, Raft, Camunda Exporter.


With this in mind let's go over the noticeable differences:

- Processing
The size of the processing queue for the various partitions in the 1MB scenario are very close to 0 with very rare spikes up to 200-300. In the 2MB scenario, only one partition is frequently closer to 0 and the other two partitions vary a lot. We see similar results to 1MB in the remaining scenarios but with more frequent and bigger spikes.
**256KB**
![proc256](https://github.com/user-attachments/assets/43cd7f2c-1fa0-43a2-9e4a-a6fef26c1866)

**512KB**
![proc512](https://github.com/user-attachments/assets/13e31bc1-90fa-4722-9c41-ab94ae42a7cf)

**Baseline - 1MB**
![proc1](https://github.com/user-attachments/assets/337fa08c-720d-459a-9631-4090b9b4826d)

**2MB**
![proc2](https://github.com/user-attachments/assets/f418407f-1664-408c-a95d-69ac2b3e1bf2)

**3MB**
![proc3](https://github.com/user-attachments/assets/2f3e5ec9-dcff-402c-92c4-d85ebc9e3f06)

**4MB**
![proc4](https://github.com/user-attachments/assets/0b95ac54-2155-4fd9-9500-cf2691fa609d)

**6+4MB**
![proc6](https://github.com/user-attachments/assets/26587a62-4058-411b-bfc5-49145cc8c644)


- Raft
There's a slight degradation in the average AppendEntry latency on all other scenarios compared to the baseline, which is the only one where the average remains below the median.

**256KB**
![latency256](https://github.com/user-attachments/assets/921ce00b-5400-4c67-bec2-2f947e1b38be)

**512KB**
![latency512](https://github.com/user-attachments/assets/e5507dd9-9220-4114-8d21-ffa9ce55dc52)

**Baseline - 1MB**
![latency1](https://github.com/user-attachments/assets/5d9d84a3-c016-444c-85f8-e55f391ac556)

**2MB**
![latency2](https://github.com/user-attachments/assets/b58fede4-bae1-4936-a8fd-76bfb33b1f67)

**3MB**
![latency3](https://github.com/user-attachments/assets/6aac7247-ebf9-4b93-a066-d794418e875e)

**4MB**
![latency4](https://github.com/user-attachments/assets/11ffd2dd-5fd6-4452-875e-8eca7b3125cd)

**6+4MB**
![latency6](https://github.com/user-attachments/assets/9657183a-09c8-4c88-bc9c-31bbe611c204)


- Latency
The commit latency quantiles on the 1MB baseline scenario look more stable than in the remaining scenarios with p99 more than 90% below 25ms and never going over 35ms whereas on the other scenarios some p99 reach over 150ms. The 256KB, 512KB and 3MB scenarios are close to 1MB with some slight bumps below 60ms.
Regarding the full results of Commit latency, one can see that the 256KB scenario has more hits below 10ms than the other scenarios and that all its hits are below 500ms like in the 512KB and 4MB scenarios. The 1MB and 6+4MB scenarios have some hits above that 500ms limit but much less than in 2MB and 3MB.

**256KB**
![commit256](https://github.com/user-attachments/assets/7fcde96a-ae0a-4661-a002-0b2f1cc3122e)

**512KB**
![commit512](https://github.com/user-attachments/assets/e9cfb97f-10ea-4afa-bbdc-960c2da9ddbe)

**Baseline - 1MB**
![commit1](https://github.com/user-attachments/assets/d8a8892d-9e87-4efe-8394-b9878eb507bf)

**2MB**
![commit2](https://github.com/user-attachments/assets/39d3d117-9245-4f89-b48e-c9c61113ab6a)

**3MB**
![commit3](https://github.com/user-attachments/assets/bcab60ba-6208-4e99-baa9-260500af485a)

**4MB**
![commit4](https://github.com/user-attachments/assets/f9cf1236-3f8e-4edb-a573-47160c0a6675)

**6+4MB**
![commit6](https://github.com/user-attachments/assets/fc7a108a-f743-4427-ae90-63a8b33f96c4)

For more details, check the [PR](https://github.com/camunda/camunda/pull/24778).

### Takeaways

First of all, we did not notice any significant change on the CPU usage and other parameters but we did notice that latency changed in a limited way.
It seems the default value of 1MB is a good compromise to ensure lower latency for the majority of the requests, but it can be reduced to 256KB or 512KB to increase the percentage of requests with lower latency. However, this must be carefully evaluated with the workload that will be used in the analyzed scenario to assess if the size of messages doesn't affect other factors like the size of the processing queue which will eventually increase overall latency.
