### ISSUE TITLE
Search engine not retrieving user for Process Owner/ Send email to Error -> The server could not find the requested resource. 

### ISSUE THREAD

**Issue by RobertDorlan** [camunda/camunda#24186]
Engineering DRI: @OmranAbazid

### Describe the bug

When trying to select a user from the dropdown on the Configure Process Dashboard (Process Owner) and from the Collection-Alert (Send email to) the dropdown is not retrieving the users 

### Expected behaviour

A list of user should be displayed when selecting the dropdown on the Configure Process Dashboard (Process Owner) and from the Collection-Alert (Send email to) 

### To Reproduce

**Update:** Process Dashboard Bug was solved with https://github.com/camunda/camunda/issues/23793
_Process Dashboard (Process Owner)
1. Select Dashboard tab
2. On the Process dashboard and KPIs select the configure wheel
3. Select dropdown_

**Collection-Alert (Send email to)**
1. Select Collection tab
2. Select Create new and create a collection 
3. Inside the Collection Create a Dashboard
4. Select Alert tab
5. On the "When report" select a report
6.  Select dropdown 

### Environment observed:

- Optimize mode(s): C8-SM 
- Optimize version(s): 8.7.0-SNAPSHOT
- Database(s) (Elasticsearch/OpenSearch): ES/OS
### Links

https://github.com/user-attachments/assets/efdf81dc-c903-4fcb-9950-cf3b982d2199
![image](https://github.com/user-attachments/assets/67367bb1-6cec-48c6-aa26-9cb56eced785)

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/24272
- [ ] https://github.com/camunda/camunda/pull/24273
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [x] Yes. If so:
  - [x] The bug description is clear
  - [x] The steps to reproduce are clear
  - [x] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by oleksandr-kriuchenko-lohika** [comment]
For the Process Dashboard scenario the issue is same as in https://github.com/camunda/camunda/issues/23793 (fix is provided for it).

For the Collection-Alert scenario - it works fine for me locally if I enter a valid Keycloak user email.

**Comment by grlimacan** [comment]
Hello @OmranAbazid , this looks like a Front-End error. For some reason the front-end is infinitely trying to fetch a report with id `undefined`. To reproduce it, run Optimize with
[this docker file](https://github.com/user-attachments/files/17589118/docker-compose.ccsm-with-optimize.yml.zip), I needed to compress it because github wont allow me uploading yml files

**Comment by grlimacan** [comment]
<img width="1478" alt="image" src="https://github.com/user-attachments/assets/8e991154-16c0-4994-bf1e-7c49428abecd">
@OmranAbazid Here is the call that it is making

**Comment by OmranAbazid** [comment]
@RobertDorlan @grlimacan I think this got fixed with this change:
https://github.com/camunda/camunda/commit/1f3714b016df97de4c03e61ed4c6d1ac278e1b04

**Comment by grlimacan** [comment]
> @RobertDorlan @grlimacan I think this got fixed with this change: [1f3714b](https://github.com/camunda/camunda/commit/1f3714b016df97de4c03e61ed4c6d1ac278e1b04)

I don't think it did. I just double-checked and the new SNAPSHOT with the fix was created around 2 hours ago and that's the one I used to test. Can you pls check?

**Comment by OmranAbazid** [comment]
@grlimacan I think it is partially fixed. I thought this issue about the process owner.
For the alerts, it is still there i think.
I will create a fix shortly.

**Comment by RobertDorlan** [comment]
Successfully tested agains C8 -SM- 8.7.0-alpha1-rc2

No error displayed when creating an alert as expected
<img width="1712" alt="image" src="https://github.com/user-attachments/assets/da842e77-b659-4db8-a2b0-1e817b13342e">
<img width="1712" alt="image" src="https://github.com/user-attachments/assets/01328fae-d1d4-43dc-a3ae-2806dd07cd83">

**Comment by misiekhardcore** [comment]
FYI, the `/qa approve` failed because of [this line](https://github.com/camunda/camunda/actions/runs/11631813742/workflow#L113) in the workflow.
