### ISSUE TITLE
Consistent date-time format in request & result

### ISSUE THREAD

**Issue by danielkelemen** [camunda/camunda#24218]
## Description

REST API `date-time` format should be consistent both in what the APIs accept and what they return.

Currently, it looks like we only accept ISO-8601 ([RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6)) but return a slightly different format without colon in the offset part (`2024-06-05T08:29:15.027+0000`). This wouldn't be accepted in a request as we use [OffsetDateTime](https://docs.oracle.com/javase/8/docs/api/index.html?java/time/OffsetDateTime.html) and that expects a colon!

## Acceptance criteria

- Accept and return dates in the same date time format.
- This format should be the [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6) specified one that the [OpenAPI date-time](https://swagger.io/docs/specification/v3_0/data-models/data-types/#strings) also uses.
  - Accepts `2024-06-05T08:29:15.027+00:00`, `2024-06-05T08:29:15.027Z`

```[tasklist]
### Tasks

```

**Comment by tmetzke** [comment]
## Assumption

We use the date string we receive from the data layer (Elasticsearch, OpenSearch, RDBMS) and return it as is.

## Proposal

* For date-time types, we work with `OffsetDateTime` in the search layer, not `String`
* The date-time String we fetch from the data layer is parsed into an `OffsetDateTime` so we don't have to care about different formats from the data layer and ship a consistent value in the APIs.
