### ISSUE TITLE
Benchmark Log4j2 AsyncLogger in Zeebe

### ISSUE THREAD

**Issue by entangled90** [camunda/camunda#24222]
Run a benchmark using Log4j2 async loggers (*important not async appenders as they are not garbage free*).

Note that the settings for garbage-free logging should already be set.

To test it, it should be enough to set the java property
```bash
-Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
```
It's important to also find a good minimum size for the ring buffer:
```log4j2.asyncLoggerConfigRingBufferSize```

If the benchmark is successful, we should also set these properties to manage what to do in case the ring buffer is full:
> See the details for system properties [log4j2.asyncQueueFullPolicy and log4j2.discardThreshold](https://logging.apache.org/log4j/2.12.x/manual/configuration.html#asyncQueueFullPolicy).

Reference: [Log4j Doc](https://logging.apache.org/log4j/2.12.x/manual/async.html)

**Comment by lenaschoenburg** [comment]
Note that the disruptor jar also needs to be in the classpath:
>  Log4j-2.9 and higher require disruptor-3.3.4.jar or higher on the classpath. Prior to Log4j-2.9, disruptor-3.0.0.jar or higher was required.

**Comment by entangled90** [comment]
Results: [Grafana](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-async-logger&var-pod=All&var-partition=All&from=1731316136890&to=1731334190412) 

All metrics look very similar over a long period (6 hours), probably we don't log frequently enough to see an improvement.
