### ISSUE TITLE
Multi-instance task instances return empty list of listeners

### ISSUE THREAD

**Issue by vitorwtavares** [camunda/camunda#24279]
### Describe the bug

In the process instance page, on the Instance History panel, if a multi-instance task is selected, the Listeners tab does not appear. That is because even though the request is done correctly passing the `flowNodeInstanceId` corresponding to that multi-instance task's instance, the response is always an empty list of listeners with a total count of zero.

A multi-instance task can have many instances, so it would be unreasonable to have the only option be clicking each one individually to check their listeners. We also can't use the `flowNode` because that would include listeners for all other instances of the multi-instance task (and its "children").

### Root Cause
Multi-Instance tasks have a `flowNodeInstanceId` of their own that is separate from the `flowNodeInstanceId` of their child instances.

### To Reproduce

1. Go to the Process Instance page
2. Select a process with a multi-instance task and a listener attached
3. Click on the task flow node instance in the Instance History panel
4. Observe no "Listeners" tab appears on the right side.

### Current behavior

When selecting a multi-instance task in the process instance page, on the Instance History panel, we get a response with an empty list of listeners, causing the "Listeners" tab not to show up.

### Expected behavior

When selecting a multi-instance task in the process instance page, on the Instance History panel, we get a response with a list of listeners corresponding to all the listeners for that instance (and its children's), causing the "Listeners" tab to show up, filled with the correct data.
### Environment

- OS: MacOS
- Browser: Chrome
- Operate Version: 8.7.0-SNAPSHOT

### Additional context

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

**Comment by kristinkomschow** [comment]
Issue was closed because after evaluation the consensus was: No work will be done regarding multi-instance tasks, as the body of a multi-instance task can not have listeners and we don't want the diagram and the instance history panel to have duplicated functions.

Slack thread with the full discussion is [here](https://camunda.slack.com/archives/C0622NWC9LK/p1730834378189169)
