### ISSUE TITLE
[Doc Handling] Add a cryptographic hash of the file contents to the document reference

### ISSUE THREAD

**Issue by chillleader** [camunda/camunda#24284]
**Description**

The first iteration of Document Handling does not cover authorization. Although process-definition-based authorizaiton will be handled centrally for the whole Camunda, we can introduce an intermediary solution to prevent attackers from accessing documents from a foreign process by brute-forcing the document ID.

- The document reference should include a cryptographic hash of the document content (e.g. SHA-256)
- In document content get requests, the hash value should be passed along with the document ID
- The server has to check the hash value to ensure only those who have access to the original document reference object can download the file.

**Comment by sbuettner** [comment]
As discussed: We should store the hash also in the meta-data store of the respective object store.

**Comment by wollefitz** [comment]
Cross-referencing https://github.com/camunda/product-hub/issues/2521#issuecomment-2517815153 and https://camunda.slack.com/archives/C0835HPLB7F/p1733302586680909?thread_ts=1733152797.807889&cid=C0835HPLB7F here: Web Modeler **depends** on this approach for caching references between subsequent IDP training runs - let's please always consider the IDP perspective when making changes to the doc handling permissions concept going forward.
