### ISSUE TITLE
Webapps cannot be loaded with single jar distribution

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#24285]
### TODO

Check if the parameter is being sent correctl to  the build so Tasklist FE is built correctly.
Context: https://camunda.slack.com/archives/C043W5V88M7/p1729534233737219

### Additional Information

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria

**Comment by Langleu** [comment]
Roughly 1-2 weeks ago the frontend was still part of the snapshot artifact that's pushed to Artifactory on every `main` commit.

Example:
https://artifacts.camunda.com/ui/native/zeebe/io/camunda/camunda-zeebe/8.7.0-SNAPSHOT/
Download any of the artifacts, unpack.

Start Elasticsearch:
```
docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "xpack.security.enabled=false"  docker.elastic.co/elasticsearch/elasticsearch:8.14.0
```

Start Camunda
```
./camunda-zeebe-8.7.0-SNAPSHOT/bin/camunda
```

```
      io.camunda.application.StandaloneCamunda - The following 4 profiles are active: "operate", "tasklist", "broker", "auth
```

Try to curl the frontend of Tasklist:
```
curl localhost:8080/tasklist

{ "type": "about:blank", "status": 500, "title": "Filter issue", "detail": "Request processing failed: org.thymeleaf.exceptions.TemplateInputException: Error resolving template [tasklist/index], template might not exist or might not be accessible by any of the configured Template Resolvers", "instance": " /tasklist" }
```

**Comment by houssain-barouni** [comment]
I found a [JAR](https://artifacts.camunda.com/artifactory/zeebe/io/camunda/camunda-zeebe/8.7.0-SNAPSHOT/camunda-zeebe-8.7.0-20241104.123752-329.tar.gz) that has the opposite issue, Tasklist webapp can be loaded but not Operate's 

It seems that this JAR is built by [tasklist-ci](https://github.com/camunda/camunda/actions/runs/11664204658/job/32474240381) workflow but not the common CI. This is why Operate frontend was not built.

**Comment by Langleu** [comment]
Thanks a lot!
I can confirm it's available now, as expected.

Interesting find also with Operate, guess I always gut unlucky to have the Tasklist missing snapshot in my tests.
