### ISSUE TITLE
Execution listeners on processes or participants are not shown in Operate UI

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda#24287]
[SUPPORT-24288](https://jira.camunda.com/browse/SUPPORT-24288)

### Describe the bug

Instance listeners can not be inspected in the Operate UI when they are defined on a process root or on a participant.

### To Reproduce (case A: execution listener on root process)

1. Deploy execution-listener-on-root.bpmn (from [example-diagrams.zip](https://github.com/user-attachments/files/17600153/example-diagrams.zip))
2. Create a task worker with type `foo`
3. Create an instance for execution-listener-on-root.bpmn process
4. Navigate to instance details view for this instance

### Current behavior

When clicking on the root process in the instance history or deselect any element from the diagram, there is no execution listener tab visible, even though there are execution listeners on the root of the process.

### Expected behavior

The execution listener tab should be visible and contain listeners when clicking on the root process in the instance history or deselect any element from the diagram.

---

### To Reproduce (case B: execution listener on participant)

1. Deploy execution-listener-on-participant.bpmn [example-diagrams.zip](https://github.com/user-attachments/files/17600153/example-diagrams.zip))
2. Create a task worker with type `foo`
3. Create an instance for execution-listener-on-participant.bpmn process
4. Navigate to instance details view for this instance

### Current behavior

The participant on the diagram is not clickable, so the execution listener tab is never shown for listeners on the participant.

### Expected behavior

Participants should be selectable and show related listeners when selected.

### Environment

- OS: [e.g. MacOS]
- Browser: [e.g. chrome, safari]
- Operate Version: [e.g. 8.1]

### Additional context

[example-diagrams.zip](https://github.com/user-attachments/files/17600153/example-diagrams.zip)

---------------------------------------------------------------------------------------------

### Acceptance Criteria

* Backport to 8.6

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] The issue has been labeled with an appropriate `Bug-area` label
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### :point_right: Handover Dev to QA

- Changed components:
- Side effects on other components:
- Handy resources:
  BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc :
  
- Example projects:

- Commands/Steps needed to test; Versions to validate:

- Docker file / HELM chart : in case that it needed to be tested via docker share the version contain the fixed along with version of other services .

- Release version ( in which version this fixed/feature will be released):

### :green_book: Link to the test case

[User can see the Listeners tab in the details view when a listener is added to root process or participant elements](https://camunda.testrail.com/index.php?/cases/view/547227)

**Comment by vitorwtavares** [comment]
@ArezooAzar To test this you can simply follow the same steps to reproduce and example bpmn processes listed in the description of this issue. The expected behavior is also described there (basically the listeners attached to the process or participant (root flow node on Instance History panel) should be visible.

**Comment by ArezooAzar** [comment]
@vitorwtavares : please review  the test case[ here. ](https://camunda.testrail.com/index.php?/cases/view/547227)
