### ISSUE TITLE
Optimize client build failed due to Node JS download error

### ISSUE THREAD

**Issue by cmur2** [camunda/camunda#24305]
## Description

The Optimize client uses the https://github.com/eirslett/frontend-maven-plugin to build its frontend, the plugin downloads Node on the fly to then use in the build process, the CDN for node can be unreliable at times which leads to the builds failing for reasons that are not related to our tests etc.

The Optimize CI is relevant e.g. for building and deploying preview environments.

In https://github.com/camunda/camunda/issues/19085 Operate experienced the same issues and opted to split the FE build from maven in the CI, so maybe the same approach could be applied to the Optimize client build. #23890 is also related since Identity faces the same issue.

An example of the failing build can be found [here](https://github.com/camunda/camunda/actions/runs/11664356665/job/32474714203?pr=24253)

**Comment by pedesen** [comment]
In Operate we now have a composite action which can be used to build the frontend with yarn: https://github.com/camunda/camunda/pull/20880/files#diff-7c93d98beaa91b58ef95b4a7fbec19b6cd17b2f36aa544e19a66498ea689bb62

**Comment by cmur2** [comment]
https://github.com/camunda/camunda/pull/24317 addressed the problem so issue can be closed
