### ISSUE TITLE
Add logging for REST API v2 calls

### ISSUE THREAD

**Issue by mihail-ca** [camunda/camunda#24332]
## Description

Currently, the REST API v2 has no logging implemented, not even at `DEBUG` level. This would help in support cases investigation, or in investigating any other issues reported by customers. Examples of possible logs to add:
- Log `500 Internal Server` errors, with full stack trace, at ERROR level
- Log `400 Bad Request` and `401 Unauthorized` errors (al least) at DEBUG level - some customers may also need this for audit
- Log long running requests (more than 10 seconds, or configurable ?) at WARN level
- Log all incoming requests at TRACE level (disabled by default). ElasticSearch has a similar feature, called [HttpTracer](https://www.elastic.co/guide/en/elasticsearch/reference/7.7/modules-http.html#_rest_request_tracer). This is especially useful in cloud / distributed systems, where customers have different layers between client and server, layers which may alter the incoming request to the server. NOTE: An actual support case was raised in Operate because of this issue (layers between client and ES server, that caused the request to be modified between client and server), very hard to debug.

**Comment by tmetzke** [comment]
@mihail-ca, does https://github.com/camunda/camunda/pull/24432 fulfill the requirements?
If so, let's close this, if not, let's specify here what is still missing 🙏

**Comment by mihail-ca** [comment]
Ok, I will close this.
