### ISSUE TITLE
Make sure configurations on OpenSearch files are pulled from OpenSearch config

### ISSUE THREAD

**Issue by grlimacan** [camunda/camunda#24355]
Engineering DRI: @grlimacan

### Context

In these OpenSearch files, we are accidentally pulling configurations for ElasticSearch.
`SnapshotRepositoryOS`
`BackupReaderOS`
`AbstractProcessDistributedByModelElementInterpreterOS`
`DecisionGroupByMatchedRuleInterpreterOS`
`GroupByIncidentFlowNodeInterpreterOS`
`AbstractProcessGroupByIdentityInterpreterOS`
`DecisionViewRawDataInterpreterOS`

### Acceptance Criteria

All OpenSearch configurations are being pulled properly for C7 and C8

### Testing Notes

From QA the only files that can be tested are the ones concerning backup. So please test C7 + C8 that the property `opensearch.backup.repositoryName` is being used correctly

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/14627
- [ ] https://github.com/camunda/camunda/pull/24373
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT C7-3.15.0-SNAPSHOT

After I manage to do the backup @oleksandr-kriuchenko-lohika helped me out to verify that the that the property opensearch.backup.repositoryName is being used correctly ✅ 

<img width="1262" alt="image" src="https://github.com/user-attachments/assets/caf05667-d38d-401a-9e70-ac946b0c9700">

<img width="1242" alt="image" src="https://github.com/user-attachments/assets/0a6a343e-2a21-4e35-9ee4-e8397abe675b">
