### ISSUE TITLE
Optimize - Show Non-Commerical License information on the front-end

### ISSUE THREAD

**Issue by matthewBearCamunda** [camunda/camunda#24389]
Engineering DRI: @OmranAbazid

### Context

Implement functionality to show the status of non-commerical licenses on the front end

The [C3 Header component was recently updated](https://add-license-expiration-tags.camunda-composite-components.pages.dev/?path=/story/uishell-c3navigation--non-production-non-commercial-with-expiry-license-tag) with functionality to show the status of the non-commerical license. Two props were added to the component, isCommercial and expiresAt. These two props map directly to the new fields from the API

The `/ui-configuration` endpoint https://github.com/camunda/camunda/issues/24339, isCommercial and expiresAt

The C3 Header component will show the non-commerical license tag only when the isCommercial field is false

There are a few different cases for this tag, and each one will display different information to the user
- When expiresAt is more than 30 days in the future. Standard information will show. [See here for an example](https://add-license-expiration-tags.camunda-composite-components.pages.dev/?path=/story/uishell-c3navigation--non-production-non-commercial-with-expiry-license-tag)
- When expiresAt is in less than 30 days, a warning should show. And the user should be shown how many days until expiration. [See here for an example](https://add-license-expiration-tags.camunda-composite-components.pages.dev/?path=/story/uishell-c3navigation--non-production-non-commercial-about-to-expire-license)
- When expiresAt is in the past, an expired messaged should how. [See here for an example](https://add-license-expiration-tags.camunda-composite-components.pages.dev/?path=/story/uishell-c3navigation--non-production-non-commercial-license-is-expired)
- When isCommercial is true, the tag for non-commerical will not show in the header

### Acceptance Criteria

- The header shows non-commerical tags when a passed license is non-commerical
- Data is coming from the isCommercial and expiresAt fields on the `/ui-configuration` endpoint

### Links

- Backend work for Optimize was done with https://github.com/camunda/camunda/issues/24339
- Parent implementation epic: https://github.com/camunda/product-hub/issues/2550

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/24623
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT


Non-commercial license - expired ✅ 
![image](https://github.com/user-attachments/assets/e31a0f1f-aa3f-4574-8a38-152b20cb6b4d)


Non- commercial license ✅ 
![image](https://github.com/user-attachments/assets/bdc7d572-50c4-40b5-825c-cfb5cb0ae78a)
