### ISSUE TITLE
Tasklist E2E tests are failing

### ISSUE THREAD

**Issue by houssain-barouni** [camunda/camunda#24429]
### Describe the bug

Tasklist E2E are failing on main branch example: https://github.com/camunda/camunda/actions/runs/11702282217
Failing test:
```
task details page
task completion with date and time form
tests/task-details.spec.ts:407
```

It started to fail since the merge of https://github.com/camunda/camunda/pull/24086

**Comment by thisisrenan** [comment]
Hi @houssain-barouni, I'd like to contribute could you assign it to me?

**Comment by houssain-barouni** [comment]
> Hi @houssain-barouni, I'd like to contribute could you assign it to me?

Hi @thisisrenan , thanks for volunteering, feel free to take it, but be aware we currently have limitations on PRs from forks https://github.com/camunda/camunda/issues/19222
