### ISSUE TITLE
Design Backups API

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#24457]
Update [backup-management-api.yaml](https://github.com/camunda/camunda/blob/300c5c768584c32e13689c91cc3c545e60f4ac7c/dist/src/main/resources/api/backup-management-api.yaml) to align with the new backups strategy.

- [x] Update current Zeebe backup endpoints
  - [x] POST / should be POST /backup-runtime - to create backups
  - [x] GET / shoud be GET /backup-runtime
  - [x] GET /{backupId} should be GET /backup-runtime/backupId}
  - [x] DELETE /{backupId} should be DELETE /backup-runtime/{backupId}
- [x] Add WebApps backup endpoints
  - [x] POST /backup-history to start webapps backup
  - [x] GET /backup-history to retrieve all webapps backups
  - [x] GET /backup-history/{backupId} to retrieve webapps backups by id
  - [x] DELETE /backup-history/{backupId} to delete webapps backup by Id

When designing the structure of requests and response take [Operate backups](https://github.com/camunda/camunda/blob/4cf854cb77ad186d2f9fd9ef2d2a8cc77996052c/operate/webapp/src/main/java/io/camunda/operate/webapp/management/BackupController.java) as an example 

### Acceptance Criteria

- [x] All Zeebe endpoints specification should now have /backup-runtime
- [x] WebApps Backup specification should contain
  - [x] POST /backup-history
  - [x] GET /backup-history
  - [x] GET /backup-history/{backupId}
  - [x] DELETE /backup-history/{backupId}
- [ ] Align and review the specification with REST API team - ask for @tmetzke review

**Comment by entangled90** [comment]
Edited the issue to reflect the new backup names:
- backup-runtime (for zeebe)
- backup-history (for tasklist + operate)
- backup-optimize (for optimize)

**Comment by tmetzke** [comment]
@marcosgvieira, the changes generally look good to me 👍 
Are we going to write about this in the upgrade guide somewhere? This is a breaking change after all because we removed a public API endpoint. There is a replacement for it so that should be OK. But we need to inform our users about this.

**Comment by entangled90** [comment]
We decided to keep backward compatibility when apps are run in standalone mode, see for [zeebe](https://github.com/camunda/camunda/issues/24850). I will do a similar thing for operate & tasklist when I will move the endpoints.
In the guide we need to mention this for users that may want to change how they deploy the services

**Comment by tmetzke** [comment]
> We decided to keep backward compatibility when apps are run in standalone mode, see for [zeebe](https://github.com/camunda/camunda/issues/24850). I will do a similar thing for operate & tasklist when I will move the endpoints. In the guide we need to mention this for users that may want to change how they deploy the services

Ah, I see, perfect, thanks, @entangled90  👍
