### ISSUE TITLE
Create common API to trigger webapps Backups

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#24465]
Create common API to take backups of Optimize, Identity, Tasklist and Operate together. The implementation should be similar as what [Operate/Tasklist are current doing](https://github.com/camunda/camunda/blob/4cf854cb77ad186d2f9fd9ef2d2a8cc77996052c/operate/webapp/src/main/java/io/camunda/operate/webapp/management/BackupController.java#L38), but should include indices from all the components

### Acceptance Criteria
- [ ] POST /webapps should trigger a backup of all webapps indices together
- [ ] POST /webapps should return a list of all scheduled snapshots:
```
{
  "scheduledSnapshots": [
    "camunda_webapps_8.7.0_part_1_of_6",
    "camunda_webapps_8.7.0_part_2_of_6",
    "camunda_webapps_8.7.0_part_3_of_6",
    "camunda_webapps_8.7.0_part_4_of_6",
    "camunda_webapps_8.7.0_part_5_of_6",
    "camunda_webapps_8.7.0_part_6_of_6",
    "camunda_webapps_8.7.0_part_6_of_7"
  ]
}
```
- [ ] Below error codes should be returned (but not restricted only to this list)

Code | Description
-- | --
200 OK | Backup was successfully started, snapshots will be created asynchronously. List of snapshots is returned in the response body (see example above). This list must be persisted together with the backup id to be able to restore it later.
400 Bad Request | In case something is wrong with backupId, e.g. the same backup id already exists.
500 Server Error | All other errors, e.g. ES returned error response when attempting to create a snapshot.
502 Bad Gateway | Elasticsearch or OpenSearch is not accessible, the request can be retried when it is back.

**Comment by npepinpe** [comment]
@marcosgvieira - I thought we were not harmonizing Optimize yet with the other web apps until they are also using the same indices. Is that not correct?
