### ISSUE TITLE
Change Zeebe endpoints to backup-runtime

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#24462]
Update Zeebe Management API to comply with https://github.com/camunda/camunda/issues/24457

### Acceptance Criteria
- [ ] Zeebe Backups API should not change their behavior or implementation only endpoints
- [ ] Endpoint to create backups for Zeebe should be POST /backup-runtime
- [ ] Endpoint to retrieve all Zeebe backups should be GET /backup-runtime
- [ ] Endpoint to retrieve Zeebe Backups by Id should be GET /backup-runtime/{backupId}
- [ ] Endpoint to delete Zeebe backups should be DELETE /backup-runtime/{backupId}

**Comment by entangled90** [comment]
Edited the endpoints' names the reflect the final decision
