### ISSUE TITLE
Create common API to delete webapps Backups by id

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#24475]
Create common API to delete a webapp backup. This implementation can be based on [Tasklist/Operate](https://github.com/camunda/camunda/blob/4cf854cb77ad186d2f9fd9ef2d2a8cc77996052c/operate/webapp/src/main/java/io/camunda/operate/webapp/management/BackupController.java#L67).

### Acceptance Criteria
- [ ] When calling DELETE /webapps/{backupId} with a valid Backup Id, the snapshots of that id should be deleted from ES/OS
- [ ] The following http codes should be returned at minimum:

Code | Description
-- | --
204 No Content | All commands to delete corresponding ELS snapshots were successfully sent to ELS. ELS will continue deletion asynchronously.
404 Not Found | Not a single snapshot corresponding to given ID exist.
500 Server Error | All other errors, e.g. ES returned error response when attempting to execute the query.
502 Bad Gateway | Elasticsearch/OpenSearch is not accessible, the request can be retried when it is back.

**Comment by entangled90** [comment]
Implemented in #24992 for operate & tasklist

**Comment by entangled90** [comment]
Implemented in #26196 for optimize
