### ISSUE TITLE
Create common API to retrieve webapps Backups by id

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#24474]
Create common API to get an existing webapp backup by Id (GET /webapps/{backupId}). This endpoint should also return the status of the current backup (it may be in progress for example), and it's used by Console/Customers to determine if the backup was sucessful or not. This can be based on [Tasklist/Operate implementation](https://github.com/camunda/camunda/blob/4cf854cb77ad186d2f9fd9ef2d2a8cc77996052c/operate/webapp/src/main/java/io/camunda/operate/webapp/management/BackupController.java#L53).

### Acceptance Criteria
- [ ] When calling GET /webapps/{backupId} with an existing backupId, details of the backup should be returned. Example Response:

```
{
  "backupId": 123,
  "state": "COMPLETED",
  "failureReason": null,
  "details":  [
    //here goes the list of all Elasticsearch snapshots included in the backup
    {
      "snapshotName": "camunda_webapps_8.7.0_part_1_of_6",
      "state": "SUCCESS",
      "startTime": "2023-01-01T10:10:10.100+0000",
      "failures": []
    },
    <..>
  ]
}
```

- [ ] The below HTTP codes should be returned at minimum:

Code | Description
-- | --
200 OK | Backup state could be determined and is returned in the response body.
404 Not Found | Backup with given id does not exist.
500 Server Error | All other errors, e.g. ES returned error response when attempting to execute the query.
502 Bad Gateway | Elasticsearch is not accessible, the request can be retried when it is back.

**Comment by entangled90** [comment]
Implemented in #26196 for optimize
