### ISSUE TITLE
Reiterate over how the current Integration Tests are written, and consider if they need to be changed or improved

### ISSUE THREAD

**Issue by mustafadagher** [camunda/camunda#24502]
Refer to discussion points in https://github.com/camunda/camunda/pull/24405#pullrequestreview-2417839329 and https://github.com/camunda/camunda/pull/24405#pullrequestreview-2421432800 .

The changes to move from the current setup to the one I suggested should be fairly simple.

We already have a setup where we take a handler and we generate a record that fits this handler, then we also generate an expected entity, and we assert that the exporter exports an record similar to the expected.

Now we will still generate a record that has a specific value type and we export it, the changes will be:
- Rather than mocking the exporter provider, we use the real default one, so all handlers should be picked up and ran for this record
- Rather than expecting one entity as a result, it could be several, it could mean doing different updates to the same entity. 
 
Which is how we think of exporting in principal, we want to manipulate some documents based on some zeebe states, do we do it using handlers, or do we embed it directly in exporter export(), the IT shouldn't care.

**Comment by Zelldon** [comment]
Maybe we should step back and ask ourself what we actually want to test with it. 

We could also do it via start zeebe with exporter und deploy and create an instance with user task.


Then we simply check that data is written in some expected indices and nothing more. This allows to verify that camunda export runs inside zeebe can consume records schemas are created and data is exported and written to indicies.

All the rest can be tested based on UT. Also that all handlers are part of the resource provider or what handlers return is tested via UT.
