### ISSUE TITLE
Camunda exporters support the assigning/removal of entities to groups

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#24580]
### Description 
To be able to keep data consistent between our Zeebe stores and Elasticsearch, we need to process `GroupIntent.ENTITY_ADDED` and `GroupIntent.ENTITY_REMOVED` events.

An example of an exporter handler can be found [here](https://github.com/camunda/camunda/blob/main/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers/UserDeletedHandler.java)

### Acceptance Criteria
- [x] A `GroupEntityAddRemoveHandler` exists [here](https://github.com/camunda/camunda/tree/main/zeebe/exporters/camunda-exporter/src/main/java/io/camunda/exporter/handlers)
- [x] A unit test is added to check behaviours - hint: [here](https://github.com/camunda/camunda/blob/main/zeebe/exporters/camunda-exporter/src/test/java/io/camunda/exporter/handlers/UserDeletedHandlerTest.java)

**Comment by koevskinikola** [comment]
Hey @Ben-Sheppard, currently the `GroupRecord` support any (i.e. `USER` and `MAPPING`) entity keys. The `GroupEntity` class has a property `assignedMemberKeys`.

Should we only add `USER` keys in the `assignedMemberKeys` set?

If yes, what should we do with the `MAPPING` keys? Should we ignore them?

**Comment by koevskinikola** [comment]
Update (from Slack-internal discussion with @Ben-Sheppard):

We add all entity keys to the `assginedMemberKeys` set, ignoring the `entityType`. If the requirements change in the future, we can adjust the handler's behavior.
