### ISSUE TITLE
Docs links are not working in Optimize

### ISSUE THREAD

**Issue by OmranAbazid** [camunda/camunda#24668]
Engineering DRI: @OmranAbazid

### Describe the bug

The doc links redirect to docs.camunda.io/optimize/8.x.x which is not supported by the docs. It used to work in the past because we previously were using the 3.x.x version even for C8 versions. It seems that after forking Optimize, we started using 8.x.x everywhere, which broke the docs.

The bug was detected from this slack message:
https://camunda.slack.com/archives/C55U06YRG/p1731452551106389

### Expected behaviour

Docs links work correctly in Optimize

### To Reproduce

- In the home page of Optimize, go "the Process dashboards and KPIs" section
- Click on one of the "i" icon in the table header to see the tooltip
- Click on the docs link in the tooltip
- the link will open a 404 page

### Environment observed:
- Optimize mode(s): CCSM and SaaS
- Optimize version(s): 8.6 and snapshot
- Database(s) (Elasticsearch/OpenSearch): any

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/24674
- [ ] https://github.com/camunda/camunda/pull/24681
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [x] Yes. If so:
  - [x] The bug description is clear
  - [x] The steps to reproduce are clear
  - [x] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by OmranAbazid** [comment]
To give more technical context:

In the past, if we start Optimize in C8 mode, Optimize UI config endpoint return different versioning scheme:
- optimizeVersion =>  8.x.x-(snapshot/alpha1)
- optimizeDocsVersion =>  3.x.x

After we forked Optimize, it seems that they both return:
- optimizeVersion =>  8.x.x-(snapshot/alpha1)
- optimizeDocsVersion =>  8.x.x

Since the camunda docs does not support optimize links with 8.x.x, the docs do not work anymore.

**Comment by RobertDorlan** [comment]
**Successfully validated agains C8-SM 8.7.0-SNAPSHOT  8.6.1**

![image](https://github.com/user-attachments/assets/7ef3f687-9a25-4f33-bdd0-e60f4e65f7d9)




**Successfully validated agains C8-Saas 8.7.0-alpha1 8.6.1**

![image](https://github.com/user-attachments/assets/e8872069-3429-4f89-946e-b3b6d8aa3064)

**Comment by OmranAbazid** [comment]
We decided to do  a short term fix of just always pointing to the latest doc. 

Once the [docs epic](https://github.com/camunda/product-hub/issues/1247) to support the fork is done, we could reintroduce the versioning back.

**Comment by RomanJRW** [comment]
Sounds reasonable to me 👍 
Do we need some version labels here too?

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT


Docs links work correctly in Optimize ✅ 
https://github.com/user-attachments/assets/8b5c9c41-2691-49aa-bea8-0e118fc0edf3

**Comment by RomanJRW** [comment]
@RobertDorlan - I created https://github.com/camunda/camunda/pull/25001 to fix the qa approve workflow
