### ISSUE TITLE
How to write io.camunda. zeebe. client. app. worker JobHandler implementation class is required to trigger CompensateEvent

### ISSUE THREAD

**Issue by bugbugmaker** [camunda/camunda#24663]
How to write io.camunda. zeebe. client. app. worker JobHandler implementation class is required to trigger CompensateEvent

**Comment by korthout** [comment]
Hi @bugbugmaker  👋 Short answer: Please read the documentation on [triggering compensation events](https://docs.camunda.io/docs/next/components/modeler/bpmn/compensation-events/), [compensation handlers](https://docs.camunda.io/docs/next/components/modeler/bpmn/compensation-handler/). They connect to any activity, that includes [service tasks](https://docs.camunda.io/docs/next/components/modeler/bpmn/service-tasks/) which needs a [job worker](https://docs.camunda.io/docs/next/components/concepts/job-workers/). In Java, a job worker implementation [could look like this](https://docs.camunda.io/docs/next/apis-tools/java-client/job-worker/).

For questions like these, it is always better to open a help request topic on the Camunda forums: [https://forum.camunda.io/](https://forum.camunda.io/). By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.

I'm closing this issue as we aim to use the GitHub issues for development purposes only.
