### ISSUE TITLE
Incorrect timezone handling in OS reports

### ISSUE THREAD

**Issue by oleksandr-kriuchenko-lohika** [camunda/camunda#24690]
Engineering DRI: @oleksandr-kriuchenko-lohika 

### Describe the bug

When Ireland/Dublin timezone is setup an error occurs during the following report evaluations:

- FlowNode: Start date/End date
- Process Instance : Start date/End date
- User Task: Start date/End date 

### Expected behaviour

No errors encountered when evaluating reports using Ireland/Dublin timezone

### To Reproduce

1. Setup Ireland/Dublin timezone
2. Evaluate FlowNode: Start date/End date report

### Environment observed:

- Optimize mode(s):
- Optimize version(s): 8.SNAPSHOT
- Database(s) (Elasticsearch/OpenSearch): OpenSearch

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/24691
- [ ] https://github.com/camunda/camunda-optimize/pull/14680
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [x] Yes. If so:
  - [x] The bug description is clear
  - [x] The steps to reproduce are clear
  - [x] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by RobertDorlan** [comment]
**Successfully tested agains C7 3.15.0-SNAPSHOT**

FlowNode: Start date/End date ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/ced6ad27-7c4c-4005-869e-a9450fb161fd">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/37aba348-0874-4105-84a2-137d3f86f4c7">



Process Instance : Start date/End date ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/33a59f8f-3128-4b13-9fd0-d5da90d75d78">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/533233cb-5fdf-4ee3-a1e2-7da8deeeb9ae">



User Task: Start date/End date ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/c2051820-4bc4-4c56-af2d-be6ac9ba1033">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/079fd394-fabe-4610-a17e-1c951135688b">




**Successfully tested agains C8 -SNAPSHOT**

FlowNode: Start date/End date ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/5e238ad9-9feb-4520-bdeb-d1b3ad93adcd">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/98b266c6-e5c4-4033-8b3f-221b91d777d3">



Process Instance : Start date/End date ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/9107ad27-e26d-4d0a-aeb2-4ab8c2a7c5e5">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/8a171bc9-f7d3-4082-a948-1e4d085f26eb">




User Task: Start date/End date ✅ 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/20a36f9c-de9c-4b7b-b845-d5687e301cb2">
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/74b4dcd0-33c0-4f7d-b99f-c5a0850f145e">
