### ISSUE TITLE
Flaky shouldExportToCorrectIndexWithElasticsearchNotReachable test.

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#24725]
**Summary**

```
org.opentest4j.AssertionFailedError: 

expected: 1
 but was: 0
	at io.camunda.zeebe.exporter.ElasticsearchExporterIT$IndexSettingsTest.shouldExportToCorrectIndexWithElasticsearchNotReachable(ElasticsearchExporterIT.java:431)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
	
	
- How often does the test fail? Only once so far. 
- Does it block your work? It recovered after so it did not block work.
- Do we suspect that it is a real failure? I don't know. 

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Paste the failure here
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by mustafadagher** [comment]
happened again [here](https://github.com/camunda/camunda/actions/runs/11897609610?pr=24823)

**Comment by EuroLew** [comment]
> Happened again [here](https://github.com/camunda/camunda/actions/runs/11897609610?pr=24823).
> 
> @EuroLew is that something you were working on?

Is that the right link? I can't see the failing logs

**Comment by mustafadagher** [comment]
> Is that the right link? I can't see the failing logs
@EuroLew the [[IT] Zeebe Module Integration Tests](https://github.com/camunda/camunda/actions/runs/11897609610/job/33152366434?pr=24823) shows as successful for some reason, but the test is flaky. You can see the failure in the [[IT] Zeebe Module Integration Tests summary](https://github.com/camunda/camunda/actions/runs/11897609610?pr=24823#summary-33152366434)

**Comment by korthout** [comment]
@mustafadagher To report logs, it's best to download the raw logs and store them in [this Google Drive folder](https://drive.google.com/drive/folders/1_5JpW6NvCn16LgwclycXOwOUIwP2AC8a). The logs on GitHub expire after some time.

**Comment by mustafadagher** [comment]
[here](https://github.com/camunda/camunda/actions/runs/11897299647?pr=24823#summary-33151448810) is another failure. you can find downloaded logs [here](https://drive.google.com/drive/folders/13HumfG9nbSuaVTz4N-EhBwf0HUS0BYCk)
