### ISSUE TITLE
Resource state is managed with Zeebe

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#24765]
<h2>Description</h2>

We need to introduce an `ResourceState` to Zeebe in which we can store RPA files.

- [ ] Create a `DbResourceState` which implements the `MutableResourceState` interface which implements the `ResourceState` interface.
    - Look at the [`DbFormState`](https://github.com/camunda/camunda/blob/main/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbFormState.java#L28) as a template.
- [ ] Like in the `DbFormState`, a [cache](https://github.com/camunda/camunda/blob/4a1c4f6bd7bb26a8c5e7b8d09dd5acca14c7ef8c/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/deployment/DbFormState.java#L73) should be provided.
- [ ] Unit tests should be provided ([example](https://github.com/camunda/camunda/blob/4d89b09deb3c57e5344eef3bf2c8cf8d6e187768/zeebe/engine/src/test/java/io/camunda/zeebe/engine/state/deployment/FormStateTest.java#L21)).

**Comment by koevskinikola** [comment]
I generalized this so that we have a `Resource` state instead of `Rpa`. This is more maintainable for additional resource types.

**Comment by kzraitel** [comment]
Related PR https://github.com/camunda/camunda/pull/24775
