### ISSUE TITLE
Apply `ResourceIntent.CREATED` events

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#24766]
<h2>Description</h2>

In Zeebe we modify our state by applying events. We need to create a new `ResourceCreatedApplier`:

An example can be found [here](https://github.com/camunda/camunda/blob/4d89b09deb3c57e5344eef3bf2c8cf8d6e187768/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/FormCreatedV2Applier.java#L15).

**Comment by kzraitel** [comment]
See related PR https://github.com/camunda/camunda/pull/25460

**Comment by kzraitel** [comment]
Backport PR: https://github.com/camunda/camunda/pull/27463
