### ISSUE TITLE
Support RPA file deployment in `DeploymentCreateProcessor` class

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#24772]
We need to support RPA file deployments through the `DeploymentRecord` and the `DeploymentCreatedProcessor`:

- [ ] Include Resource metadata to `DeploymentRecord`
- [ ] Implement `RpaResourceTransformer` and include it in `DeploymentTransformer` ([example](https://github.com/camunda/camunda/blob/46163c715fd8dfe6ac591c9430a1e487920ba364/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/transform/FormResourceTransformer.java#L31))
- [ ] Transform deployed RPA file in `DeploymentCreateProcessor` class ([forms example](https://github.com/camunda/camunda/blob/9390158dca8098722013d4f1add8e7229cdaf803/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/DeploymentCreateProcessor.java#L253-L267))

**Comment by natanielstrack** [comment]
Just as a reference, this features is being implemented in a more generic way to support more than just RPA ([reference](https://github.com/camunda/camunda/issues/24764#issuecomment-2504225699)).

@koevskinikola can you confirm? Thank you.

**Comment by koevskinikola** [comment]
Hi @natanielstrack, yes, internally we're implementing a more generic "resource" feature with the idea of supporting additional resource types in the future. This doesn't cause any additional effort, it's just a naming change.

However, resource transformation/validation before the `DeploymentCreateProcessor` must be type-specific (I.e. we need RPA-specific transformers), at least until we develop additional mechanisms to generalize them.

**Comment by kzraitel** [comment]
Related PR https://github.com/camunda/camunda/pull/25918

**Comment by kzraitel** [comment]
Backport PR https://github.com/camunda/camunda/pull/27465
