### ISSUE TITLE
User Tasks with linked forms started with the WebModeler's `Play` not being persisted correctly

### ISSUE THREAD

**Issue by panagiotisgts** [camunda/camunda#24771]
### Describe the bug

When deploying a process with a linked form using the WebModeler's `Play` functionality, occasionally the created User Tasks do not have correct reference on the linked form. 

### To Reproduce

1. Create a form in the WebModeler but do not deploy it
2. Create a simple BPMN process with a User Task and link it to the previous form
3. Use WebModeler's `Play` functionality to deploy and run all components

### Actual behavior
Sometimes, the fields `formId` and `formVersion` are not being included in the User Task flushed record. Persisting only the `formKey` results in Tasklist OOTB FE to not be able to fetch the form, thus displaying `Task has no variables` message.

### Expected behavior
The `formId` and `formVersion` are always populated in the User Task record. Tasklist OOTB can retrieve the relevant form.

### Environment

- OS: [SaaS]
- Browser: [e.g. chrome, safari]
- Tasklist Version: Verified on 8.6 and 8.5, reported also for 8.4 and 8.3

### Additional context
Reported on slack: https://camunda.slack.com/archives/C043W5V88M7/p1731394875251639

---------------------------------------------------------------------------------------------

### Definition of Ready - Checklist

- [ ] The bug has been reproduced by the assignee in the environment compatible with the provided one; otherwise, the issue is closed with a comment
- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] Necessary screenshots, screen recordings, or files are attached to the bug report

For UI changes required to solve the bug:

- [ ] Design input has been collected by the assignee

### After solving the issue - Answer and document in the comments the questions below

- [ ] What was the root cause for this bug?
- [ ] Is there anything we should do for the error to not happen anymore?

**Comment by esraagamal6** [comment]
@panagiotisgts Tested OK on SNAPSHOT SaaS
