### ISSUE TITLE
Ensure Logging works in Optimize in the single application

### ISSUE THREAD

**Issue by RomanJRW** [camunda/camunda#24825]
### Context

In moving to the Single Application, it is assumed that a single logging framework will be required. Optimize currently has relatively highly configurable logging. In the single application, we should ensure that Optimize logging still works, and that preferably in can be configured as before.

It is also acceptable for Optimize to confirm to the existing single application architecture, as long as any breaking changes are documented.

**Problem:**
- Optimize uses logback, reading from a prioritized list of logging configuration files. The mono repo uses log4j2. These two things clash in maven and in implementation (only one can be used)

### Acceptance Criteria

- Optimize logs as configured in the Single Application without clashing libraries
- Breaking changes to logging configuration are clearly documented in the upgrade guide
- Optimize can log at the determined levels

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/25204
```

## Task Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by buccarel** [comment]
This has been solved together with the inclusion of Optimize in the single JAR.
