### ISSUE TITLE
Outbound Connectors Cannot Complete in Operate

### ISSUE THREAD

**Issue by slolatte** [camunda/camunda#24851]
**Describe the issue:**

After deploying an outbound connector, for example a REST connector, the connector will never complete in Operate.

**Actual behavior:**

The connector is never completing in Operate, indicating that there is an issue with the connector runtime. 

**Expected behavior:**

There should be no problem with the connector runtime and the outbound connector should be able to complete.

**How to reproduce:**

**Logs:**

[elasticsearch.log](https://github.com/user-attachments/files/17815962/elasticsearch.log)
[connectors.log](https://github.com/user-attachments/files/17815964/connectors.log)
[camunda.log](https://github.com/user-attachments/files/17815965/camunda.log)

**Environment:**

Using the main branch of camunda/camunda repository. 

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform:   Mac, Windows, Linux 
- Architecture:  x86, ARM
- Version:  main branch of camunda/camunda repository

**Comment by gbetances089** [comment]
discussion about this issue [here](https://camunda.slack.com/archives/C06BN4SRB6C/p1733836094672309)

**Comment by gbetances089** [comment]
Related to: fix: https://github.com/camunda/camunda/pull/25939

**Comment by gbetances089** [comment]
This was fix [here](https://camunda.slack.com/archives/C06BN4SRB6C/p1733940121893539?thread_ts=1733836094.672309&cid=C06BN4SRB6C)
