### ISSUE TITLE
Change default values for tree path and level fields to null

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#25223]
### Description (required on creation)

The default values for the tree path level properties in the list view and flow node instance indexes should be `null` or a null constant. Currently we set them to a default value that is wrong in some cases (e.g. we set the level to 1, but as soon as a flow node instance is in a subprocess, the value is not correct). These wrong values will be hard to work with in the future (e.g. if we want to debug a problem and know how that value was set; when we develop the feature further, engineers must know this complex default behavior).

### Acceptance Criteria (required on creation)

* Set the fields to `null` or a null constant (e.g. String `NULL`) by default
  * Decide based on if we ever want to query by the null constant in the future. If it's true null, we can never specify a query like "give me all documents where property is null"
* Review all of the following Operate internal API endpoints and make them tolerate null values
  * `POST /api/flow-node-instances`
  * `POST /api/process-instances/{processInstanceId}/flow-node-metadata`
  * `GET /api/process-instances/{id}/incidents`
  * `POST /api/process-instances`
  * `GET /api/process-instances/{id}`
  * `POST /api/process-instances/batch-operation` (for delete process instance operations, particularly `ProcessInstanceWriter.deleteProcessInstanceAndDependants`)
* Write test cases for the above endpoints with null values

### Links

```[tasklist]
### Pull Requests
```

**Comment by sdorokhova** [comment]
This change is not needed any more, as we continue having full treePath for process instance entities.
