### ISSUE TITLE
Store root process instance key in list view index

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda/camunda#25233]
### Description (required on creation)

Once https://github.com/camunda/camunda/issues/25232 is implemented, we need to store the root process instance key in the list view index to return it in the `POST /api/process-instances` and `GET /api/process-instances/{id}` APIs.

This is required for the following Operate UI features:

* Process instance breadcrumb (see #24729)
* When users attempt to cancel a process instance that is not a root process instance (which is not possible), we give them a link to the root instance

### Acceptance Criteria (required on creation)

* Add root process instance key to list view schema and populate it in the exporter
* In the endpoint implementations, extract the root process instance key either from the property or as fallback (pre 8.7 data) from the tree path

### Links

```[tasklist]
### Pull Requests
```

**Comment by sdorokhova** [comment]
This change is not needed any more, as we continue having full treePath for process instance entities.
