### ISSUE TITLE
Adjust Task Search by Variables implementation

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#25287]
### Description

The goal of this task is to adjust the user task search by variables to achieve Iteration 1 and Iteration 2 of this doc: https://docs.google.com/document/d/1YtC5W3Ln93M-BTwzq1iC-Ne1Qlvf5C7zqeo0DK6pjKc/edit?tab=t.0

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/25290
- [ ] https://github.com/camunda/camunda/issues/25291
- [ ] https://github.com/camunda/camunda/issues/25292
- [ ] https://github.com/camunda/camunda/issues/25293
```

**Comment by ChrisKujawa** [comment]
Feature has been completed
