### ISSUE TITLE
Adjust exporter and REST API V1 and V2 to avoid migration

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#25293]
As part of exporter we need to support User Tasks records that were created before using the importer. The current problem is that because we are improving the User Task Search by Variables, we are changing the way the `ids` and `_routing` are stored in the UserTask indice. The consequence of that is potential failures when trying to update records (Assigning/completing user Tasks), as the shard may be different than expected.

To overcome this challenge we need to have a way of identifying what record has the "old" id and what record has the "new" id in operations that are updating the user tasks.

- [ ] As the first step of the exporter, store the highest sequence of the user task on `tasklist-import-position-8.2.0_` (if still not stored)
- [ ] When generating the id of the UserTask entity, check if the sequence is higher or lower than the sequence stored
   - [ ] If higher, the id of the entity should be the `ElementInstanceKey`
   - [ ] If lower/equals, the id of the entity should be the `UserTaskKey`
- [ ] When flushing the UserTask we should compare the id to decide the value of the routing
   - [ ] If the id is equals as the FlowNodeInstanceId it means that the routing should be the processInstanceKey
   - [ ] If the id is equals as the UserTaskKey, it means that the routing should be the UserTaskKey

**Acceptance Criteria**
- [ ] Assigning a Zeebe User Task using v2 where this task was created on version 8.6, should work as expected and reflect in ES/OS.
- [ ] Assigning a Zeebe User Task using v2 where this task was created on version 8.7, should work as expected and reflect in ES/OS.
- [ ] Assigning a Zeebe User Task using v1 where this task was created on version 8.6, should work as expected and reflect in ES/OS.
- [ ] Assigning a Zeebe User Task using v1 where this task was created on version 8.7, should work as expected and reflect in ES/OS.
- [ ] Completing a Zeebe User Task using v2 where this task was created on version 8.6, should work as expected and reflect in ES/OS.
- [ ] Completing a Zeebe User Task using v2 where this task was created on version 8.7, should work as expected and reflect in ES/OS.
- [ ] Completing a Zeebe User Task using v1 where this task was created on version 8.6, should work as expected and reflect in ES/OS.
- [ ] Completing a Zeebe User Task using v1 where this task was created on version 8.7, should work as expected and reflect in ES/OS.
- [ ] Assigning a Job User Task using v1 where this task was created on version 8.6, should work as expected and reflect in ES/OS.
- [ ] Assigning a Job User Task using v1 where this task was created on version 8.7, should work as expected and reflect in ES/OS.
- [ ] Completing a Job User Task using v1 where this task was created on version 8.6, should work as expected and reflect in ES/OS.
- [ ] Completing a Job User Task using v1 where this task was created on version 8.7, should work as expected and reflect in ES/OS.
- [ ] Updating a Zeebe User Task using v2 where this task as created on version 8.6, should work as expected and reflect in ES/OS.
- [ ] Updating a Zeebe User Task using v2 where this task as created on version 8.7, should work as expected and reflect in ES/OS.

**Comment by romansmirnov** [comment]
> As the first step of the exporter, store the highest sequence of the user task on tasklist-import-position-8.2.0_ (if still not stored)

* It should store the first key (or any other key) of the first user task created with 8.7. That way, we know any updates to user tasks with a lower key follow the old data structure (in terms of ID and routing) if it is higher than the new data structures apply.
* For Job-based User Tasks nothing should change, meaning it will store data following the old data structure.

**Comment by panagiotisgts** [comment]
@romansmirnov Can you, or someone else that you can direct me to provide some info regarding how to use RocksDB for that specific case? Never used it before in the context of Zeebe.

**Comment by romansmirnov** [comment]
> Can you, or someone else that you can direct me to provide some info regarding how to use RocksDB for that specific case? Never used it before in the context of Zeebe.

Just for context, it would not be necessary to interact with RocksDB directly. There is already some infrastructure to store metadata when acknowledging a position. Again, this is meant as an alternative instead of storing it in ES/OS.

**Comment by panagiotisgts** [comment]
The same has to be done regarding Variables, right?

When importing (via the CamundaExporter) Variables related to 8.6 records these should not be persisted in the `tasklist-task` index, rather in the old-fashioned `operate-variable` index (which replaces `tasklist-variable`) . So we also have to store the first Variable record key that arrives in the CamundaExporter.

Assuming we store the User Task `key` and the Variable record `key`, we'd have the following:

For Variables:
- Variable `UPDATED/MIGRATED` intent related to 8.6 record, meaning `record.Key < storedVariableKey` 
- - Do nothing, let `operate-variable` ExportHandler handle the record as normal
- Variable `CREATED` intent (will only be 8.7 record, `record.key > storedVariableKey`)
- - Write the variable to `tasklist-task` index using the new mapping

For UserTasks:
- Any not `CREATED` intent related to 8.6 record, meaning `record.Key < storedTaskKey` 
- - Set ID to `record.Key` (User Task key)
- - Set routing to `record.Key` (User Task key)
- Any intent related to 8.7 record,  meaning `record.Key > storedTaskKey` 
- - Set ID to `ElementInstanceKey` 
- - Set routing to `ProcessInstanceKey`

**Comment by romansmirnov** [comment]
> When importing (via the CamundaExporter) Variables related to 8.6 records these should not be persisted in the tasklist-task index, rather in the old-fashioned operate-variable index (which replaces tasklist-variable) . So we also have to store the first Variable record key that arrives in the CamundaExporter.

I don't fully understand. Variables will be stored in the `operate-variable` index, this continues with the new camunda exporter. In 8.6, the `tasklist-task` didn't store any variables, but starting with 8.7, it will. I think, as long as they are routed by variables and an upsert is done (when storing in `tasklist-task`, everything should be fine.
