### ISSUE TITLE
Allow Tasklist to handle rejections

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#25419]
When dealing with UserTasksListeners it may be the case that the OOTB Tasklist tries to complete or assign a task meanwhile a listener is being executed. When this happens C8 REST API is going to reject the assignment/completion command and an error is going to be returned:

```
{
    "type": "about:blank",
    "title": "INVALID_STATE",
    "status": 409,
    "detail": "Command 'COMPLETE' rejected with code 'INVALID_STATE': Expected to complete user task with key '2251799813686157', but it is in state 'COMPLETING'",
    "instance": "/v2/user-tasks/2251799813686157/completion"
}
```

When this happens, Tasklist should display and handle this error gracefully as described here: https://docs.google.com/document/d/1BxvvkdDJurzblKcnjbP00sUE3FCv5rDM81IOG4OG_cM/edit?tab=t.0#heading=h.ak839ldyiwxs

Another scenario that can happen is the TaskListener taking longer than expected to be executed, causing a time-out. When this happens Tasklist should also communicate that the operation is taking longer than expected. [See the design](https://docs.google.com/document/d/1BxvvkdDJurzblKcnjbP00sUE3FCv5rDM81IOG4OG_cM/edit?tab=t.0).

As part of this task is also expected that the following metrics are created to track the usage:
- How many times a Task was rejected due to UserTask Listeners when assigning and completing
- How many times a Task timed-out due to UserTask Listeners when assigning and completing

**Acceptance Criteria**
- [ ] When assigning/completing a Zeebe User Task using Tasklist OOTB considering that this UserTask has a Listener, in case the listener is succesful, the task assignment/completion should executed with success.
- [ ] When assigning/completing a Zeebe User Task using Tasklist OOTB considering that this UserTask has a Listener, in case the listener takes longer than expected and this results in a time-out, an error explaining the scenario should be displayed in Tasklist OOTB
- [ ] When assigning/completing a Zeebe User Task using Tasklist OOTB considering that this UserTask has already changed the state to ASSIGNING/COMPLETING, the operation should be rejected and an error explaining the sceario should be dusplayed in Tasklist OOTB
- [ ] We have mixpanel metrics to count rejections and time-outs of tasks

**Comment by esraagamal6** [comment]
Link to test cases: [here](https://camunda.testrail.com/index.php?/suites/view/476&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=79779)
