### ISSUE TITLE
Remove GraphQL from Tasklist

### ISSUE THREAD

**Issue by marcosgvieira** [camunda/camunda#25492]
### Description

We are retiring Tasklist GraphQL, so this task goal is to remove GraphQL and adapt integration tests to not use anything from GraphQL.

**Acceptance Criteira**
- [ ] Tasklist to not support GraphQL endpoints
- [ ] Integration Tests to not use any reference to GraphQL

**Comment by ChrisKujawa** [comment]
closed by https://github.com/camunda/camunda/pull/25500
