### ISSUE TITLE
Resource cache is not filled correctly and stays empty

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#25507]
`DbResourceState` defines `resourcesByTenantIdAndIdCache` as a loading cache, with the intention presumably being that any cache lookup would automatically compute ("load") the value.

However, the only cache lookup is a `getIfPresent`  call which does _not_ load the cache.

In effect, the cache is only populated in `storeResourceInResourceColumnFamily`, i.e. when deploying resources. After a restart, the cache remains empty and useless.

A simple fix to swap the non-loading `getIfPresent` with a loading `get` will not work because the `CacheLoader` is defined recursively, where a load would first start with a cache lookup. This is rejected by the Guava cache with `java.lang.IllegalStateException: Recursive load`.

**Comment by koevskinikola** [comment]
@kzraitel we have another bug with the `DbResourceState` cache, I'll book some of the RPA time to resolve it while you work on the feature part.
