### ISSUE TITLE
Use gerunds as User Task Listener Event Types in Operate

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#25545]
Operate can adjust their representations and don't need to be backward compatible with the previous naming

**Comment by korthout** [comment]
https://github.com/camunda/camunda/issues/25541#issuecomment-2514850067

**Comment by korthout** [comment]
https://github.com/camunda/camunda/issues/25541#issuecomment-2535307749

**Comment by kristinkomschow** [comment]
This will be implemented with https://github.com/camunda/camunda/pull/25557

Our issue for the implementation is here: https://github.com/camunda/camunda/issues/23728

I'm still leaving this issue also open until that fix is merged for better visibility around this topic.

**Comment by kristinkomschow** [comment]
Implemented here for the supported user tasks of this iteration: https://github.com/camunda/camunda/pull/25557#event-15719291378

**Comment by kristinkomschow** [comment]
Implemented here for the supported user tasks of this iteration: https://github.com/camunda/camunda/pull/25557
