### ISSUE TITLE
Remove `treePath` from C8 API 

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#25599]
### Description 

`treePath` and `level` fields are currently used in internal API of Operate.
It is not necessary yet to expose it to C8 API.

### Acceptance Criteria

- [x] Remove `treePath` and `level` from OpenAPI description, filters, and response items:
    - [x] ProcessInstance 
    - [x] FlowNodeInstance
    - [x] Incident 
- [x] Remove `treePath` and `level` from [C8 API documentation](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit?tab=t.0#heading=h.ct4eck1q9lyq)

### Links

```[tasklist]
### Pull Requests
```

**Comment by ChrisKujawa** [comment]
@ralfpuchert (\cc @tmetzke )

I would like to close the issue from our side [here](https://github.com/camunda/camunda/issues/25237), as I think it is part of your project so we can use your issue.

We just need to make sure that not only `treePath` is deleted but also `level`, are you aware of this?


Previous issue:

> **Description**
> 
> The queries for incidents, process instances and flow nodes should no longer accept and return the tree path and level properties. These properties are only populated for incidents and have a meaning only for the implementation of internal API endpoints. Their values are not particularly useful for end users and don't make a robust API concept.
> 
> **Acceptance Criteria**
> Any references to the tree path and the level property are removed from the V2 endpoints for incidents, process instances and flow nodes

**Comment by tmetzke** [comment]
I wasn't aware, no, thanks for pointing that out, @ChrisKujawa 👍

**Comment by ralfpuchert** [comment]
Thanks @sdorokhova for adding `level` to fields that needs to be removed.

**Comment by mihail-ca** [comment]
> Thanks @sdorokhova for adding `level` to fields that needs to be removed.

@ralfpuchert where is this level field ? I could not find anything in rest-api.yaml
<img width="803" alt="image" src="https://github.com/user-attachments/assets/07f4b582-2c38-4dee-ade7-41da8b2d49b2">

**Comment by tmetzke** [comment]
@mihail-ca, I think you're right, I can't find this anywhere in V2 either.
@ThorbenLindhauer, your [original issue](https://github.com/camunda/camunda/issues/25237) mentioned the `level` attribute as well. Did you encounter this anywhere explicitly where you think this should be removed?

**Comment by ThorbenLindhauer** [comment]
It's in the Operate internal API and an attribute of the flow node instance index. If that attribute is not exposed in V2, then all good. I assumed we exposed all attributes by default.

**Comment by tmetzke** [comment]
Thanks, @ThorbenLindhauer, that makes sense. We actually don't expose all data layer attributes by default to exactly avoid shipping internals directly 👍

**Comment by saig0** [comment]
I'm unhappy to see that the `treePath` was removed from the API. I need the `treePath` to implement a feature for CPT: https://github.com/camunda/camunda/issues/23136. 

I created a new issue to add the `treePath` back to the API: https://github.com/camunda/camunda/issues/26277.
