### ISSUE TITLE
Channel closed when a response times out in NettyMessagingService

### ISSUE THREAD

**Issue by entangled90** [camunda/camunda#25596]
In `NettyMessagingService` when a response times out (usually around 15 seconds)  the channel is closed because it's interpreted as if the channel is no longer alive. Then, all requests waiting for a reply on that channel are completed exceptionally.

This is particularly problematic with commands that may take more than 15 seconds to complete such as `CreateProcessInstanceWithResult` which waits for the process instance to complete. 
However, this may happen in any situation where the timeout is breached such as banned instances or a general slowdown.

We should introduce independent heartbeats for each channel and check if these heartbeats time out.

Note that Channels are pooled by topic, i.e. broad type of message + partition, usually. 

Keep in mind that we already have heartbeats in raft between brokers, so we may not want to add heartbeats between them.

A potential implementation of these heartbeats may use [IdleStateHandler](https://netty.io/4.0/api/io/netty/handler/timeout/IdleStateHandler.html).

Relates to https://jira.camunda.com/browse/SUPPORT-24733

**Comment by lenaschoenburg** [comment]
> Keep in mind that we already have heartbeats in raft between brokers, so we may not want to add heartbeats between them.

By using `IdleStateHandler` this is already solved because it would only trigger if there are no other requests on that channel. So raft heartbeats would automatically disable pings sent by `IdleStateHandler`.

**Comment by entangled90** [comment]
Good point, that's even easier :-)
