### ISSUE TITLE
Same-site auth cookie is not being attached to the home page request after successful authentication

### ISSUE THREAD

**Issue by buccarel** [camunda/camunda#25644]
Engineering DRI: @buccarel

### Describe the bug

When authenticating against Identity, Optimize redirects the user to the home page using a see-other (HTTP 303) automatic redirection. This causes the same-site auth cookie not to be attached to the navigation to the home page.

This behavior is described in the [official draft of the RFC 6265 bis, in the last paragraph of section 4.1.2.7](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis#section-4.1.2.7):

> The "SameSite" attribute affects cookie creation as well as delivery. Cookies which assert "SameSite=Lax" or "SameSite=Strict" cannot be set in responses to cross-site subresource requests, or cross-site nested navigations. They can be set along with any top-level navigation, cross-site or otherwise.

In particular, the sentence "Cookies... cannot be set in responses to cross-site subresource requests, or cross-site nested navigations" extends the definition of same-site navigation, effectively limiting it to requests initiated by the users, such as typing the URL in the top bar and pressing enter or clicking a link with their mouse. As automatic redirections are detected as "nested navigation" mechanisms, they do not attach the cookie.

The absence of the auth cookie results in the home page looping back to the authentication system, triggering an infinite loop that is stopped by the browser after a certain number of retries.

### Expected behaviour

The home page should be loaded after a successful authentication against Identity.

### To Reproduce

The detailed steps on how to reproduce the bug can be found in the support ticket https://jira.camunda.com/browse/SUPPORT-24651

### Potential solution

There is more than one solution to the problem. Two effective ways to solve the problems are the following:
* instead of redirecting to the home page, directly serve the index.html file
* instead of redirecting to the home page via see-other, redirect to a web page that performs the javascript operation
```javascript
window.location = targetUrl;
```
where targetUrl is the desired home page. This solution would work because the modification of `window.location` is interpreted similarly as the user typing the URL in the address bar of a browser.

### Environment observed:

- Optimize mode(s): self-managed
- Optimize version(s): 8.5, 8.6
- Database(s) (Elasticsearch/OpenSearch): n/a

### Links

* https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis#section-4.1.2.7
* https://jira.camunda.com/browse/SUPPORT-24651

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda-optimize/pull/15002
- [ ] https://github.com/camunda/camunda/pull/25647
- [ ] https://github.com/camunda/camunda/pull/25648
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [x] Yes. If so:
  - [x] The bug description is clear
  - [x] The steps to reproduce are clear
  - [x] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [x] All code targeting the main branch has been reviewed by at least one Engineer
- [x] The PR targeting the main branch has been approved by the reviewing Engineer
- [x] If the API has changed, the API documentation is updated
- [x] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [x] The change is implemented as described on all target environments/versions/modes
- [x] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

**Comment by shaarmann** [comment]
Hi @buccarel,
Can this change also be backported to 8.5.? Since one of the customers affected by this bug is on 8.5. and cannot upgrade to 8.6. quickly?

**Comment by RomanJRW** [comment]
As per the thread [here](https://camunda.slack.com/archives/C55U06YRG/p1733827097518269), this was already backported but was missing the appropriate release version label

**Comment by RobertDorlan** [comment]
Successfully tested agains C8-SNAPSHOT


The home page should be loaded after a successful authentication against Identity. ✅
