### ISSUE TITLE
[General][Engine] create default user independently from authorizations enabled

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda#25700]
### Description
Currently, when the single application starts we [initialise Identity with a default user](https://github.com/camunda/camunda/blob/main/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/user/IdentitySetupInitializer.java) however this is only run when authorizations are enabled. 

The creation of a user should be independent of authorizations being enabled.

### Acceptance criteria
- [ ] When the single application is started, the demo user is created (with role)

**Comment by lenaschoenburg** [comment]
@Ben-Sheppard Should we also create the default tenant in that case? If we are creating a user and a role - why not a tenant?

**Comment by Ben-Sheppard** [comment]
Good questions @lenaschoenburg 

> @Ben-Sheppard Should we also create the default tenant in that case? If we are creating a user and a role - why not a tenant?

I think creating the default tenant is fine yea, the tenant always exists from an engine perspective AFAIK so if we create it then multitenancy is switched on we have the tenant ready to go as well

> @Ben-Sheppard And another question: By default we assign the default role all wildcard permissions. I'd assume that we can just keep doing that because it does no harm when authorization is disabled anyway?

Yea that would be my expectation too, once again, if we get to a stage where authorizations are turned on then the default user can still function as expected
