### ISSUE TITLE
Transform a purge request into scale down and restore cluster change operations

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#25964]
## Description

The goal here is to implement a handler for the `PurgeRequest` on the coordinator node (in `ClusterConfigurationRequestServer`), which transforms the request into a series of planned change operations that results in the data _in Zeebe only_ to be deleted.

To do so, we need to ensure we register a new handler in `ClusterConfigurationRequestServer` and implement a decoder for the `PurgeRequest` added in #25961.

To handle the request, we will implement a new `purge` method in the `ClusterConfigurationManagementApi`. The implementation will be largely delegated to a new `PurgeTransformer`.

This class will take as input the current topology, and produce a sequence of operations which is essentially every broker leaving all their partitions, followed by restoring the current topology as it was.

> [!Warning]
> When bootstrapping partitions, they _must_ be bootstrapped in order of ID ascending. Meaning partition 1 first, then 2, then 3, etc., contiguously.

Broken down, it would be:

- For every broker `B` and partition `P`, there will be a `PARTITION_LEAVE(B,P)` command.
- For every partition `P` _ordered by partition ID ascending_, we will pick a single primary broker `B` out of the brokers in this partition, and produce a `PARTITION_BOOTSTRAP(B,P,<priority>)`, where `<priority>` is the priority that node for this partition as existing in the current topology.
- For every partition `P` (order does not matter here), and for all non-primary brokers `B` out of the brokers in this partition, we will produce a `PARTITION_JOIN(B,P,<priority>)`, where `<priority>` is the priority that node for this partition as existing in the current topology.

This means the returned expected topology should be the _exact same_ as before.

## Acceptance criteria

- [x] The coordinator node has a new handler for the `cluster-purge` topic to handle incoming `PurgeRequest`.
- [x] The handler delegates logic to a new `PurgeTransformer`.
- [x] The `PurgerTransformer` produces a sequence of operations which consists of every broker leaving all of its partitions, and then the topology being restored in the right order.
- [x] For every partition, there is a single `PartitionBootstrapOperation`.
  - [x] These bootstrap operations are for a broker that was already part of this partition.
  - [x] The priority is the same as it was previously.
  - [x] The bootstrap operations are all after the leave operations.
  - [x] The bootstrap operations are ordered by partition ID ascending amongst themselves.
- [x] For every partition, and all other non-primary brokers part of it, there is a single `PartitionJoinOperation` with the same priority as before.
  - [x] All join operations are after the bootstrap operations.

**Comment by srsp** [comment]
> The bootstrap operations are ordered by partition ID ascending amongst themselves.

So the order of the `PartitionBootstrapOperation`s should be 
```
PartitionBootstrapOperation(member0, partition0),
PartitionBootstrapOperation(member1, partition1),
PartitionBootstrapOperation(member0, partition2),
```
instead of 
```
PartitionBootstrapOperation(member0, partition0),
PartitionBootstrapOperation(member0, partition2),
PartitionBootstrapOperation(member1, partition1),
```
?

**Comment by npepinpe** [comment]
Correct, ordered by partition ID
