### ISSUE TITLE
Rename the java client artifact

### ISSUE THREAD

**Issue by houssain-barouni** [camunda/camunda#26102]
Redo https://github.com/camunda/camunda/issues/19482

* Rename the artifact from `zeebe-client-java` to `camunda-client-java`
* This will not be backward compatible, no mirroring of `zeebe-client-java` is required

**Comment by houssain-barouni** [comment]
@tmetzke , I think we need to coordinate with @camunda/connectors-dev  team to switch to `camunda-client-java` in alpha3. As we agreed, there won't be `zeebe-client-java` in alpha3

**Comment by tmetzke** [comment]
> @tmetzke , I think we need to coordinate with @camunda/connectors-dev team to switch to `camunda-client-java` in alpha3. As we agreed, there won't be `zeebe-client-java` released in alpha3 or 8.7.0 minor https://github.com/camunda/connectors/blob/542f8fdc44a09bfe539b53def1edbb95d923e8cd/parent/pom.xml#L285-L289

Yes, that is a very good point, thanks for highlighting that 👍

**Comment by houssain-barouni** [comment]
> > @tmetzke , I think we need to coordinate with @camunda/connectors-dev team to switch to `camunda-client-java` in alpha3. As we agreed, there won't be `zeebe-client-java` released in alpha3 or 8.7.0 minor https://github.com/camunda/connectors/blob/542f8fdc44a09bfe539b53def1edbb95d923e8cd/parent/pom.xml#L285-L289
> 
> Yes, that is a very good point, thanks for highlighting that 👍

Also, this will impact this pull request from optimize https://github.com/camunda/camunda/pull/25204/files
