### ISSUE TITLE
Implement `Exporter#purge` for the RDBMS exporter

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#26154]
## Description

Since CPT is the first main use case for purging, and it will use only the Camunda exporter, we will first implement `CamundaExporter#purge`.

The first step is figuring out what data we need to delete. Data that we clearly need to delete:

- All tables managed by C8.

Maybe some other things?

## Acceptance criteria

- [ ] All data that must be deleted is discovered and defined
- [ ] All data that must be deleted is deleted from the configured RDBMS after `CamundaExporter#purge` returns.
- [ ] Any data that was _not_ managed by C8 is still available.

**Comment by npepinpe** [comment]
Superseded by: https://github.com/camunda/camunda/issues/26129

**Comment by p-wunderlich** [comment]
This issue was solved with https://github.com/camunda/camunda/issues/26129
