### ISSUE TITLE
[REST API] Expose the treePath of flow-node instances

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#26277]
## Description

The [search API](https://docs.camunda.io/docs/next/apis-tools/camunda-api-rest/specifications/find-flow-node-instances/) and the [get API](https://docs.camunda.io/docs/next/apis-tools/camunda-api-rest/specifications/get-flow-node-instance/) for flow-node instance should return the [tree-path](https://github.com/camunda/camunda/issues/25474) in the response. The tree-path represents the flow-node instance in the process instance, including its parent-child relation to other flow-node instances (e.g. `/process-instance-key/flow-node-instance-key`, `/process-instance-key/sub-process-instance-key/flow-node-instance-key`).

The tree-path is important to build a flow-instance instance tree that shows the active and completed flow-node instance of a process instance, like the tree in Operate. 

Currently, the response contains only `flowNodeInstanceKey`, `flowNodeId`, `flowNodeName`, `type`, and `state`. If a process has a sub-process or a multi-instance activity, the tree-path is necessary to show the correct parent-child relationship. 

In `8.7.0-alpha2`, the tree-path was part of the response ([ref](https://github.com/camunda/camunda/blob/8.7.0-alpha2/zeebe/gateway-protocol/src/main/proto/rest-api.yaml#L3971)) but it was removed with https://github.com/camunda/camunda/issues/25599.

**Comment by tmetzke** [comment]
Thanks, @saig0, for opening this. For transparency, it was [recently assessed](https://github.com/camunda/camunda/issues/25237) that the `treePath` property is not a good fit to be exposed publicly in the API.

Looping in @ChrisKujawa and maybe @ThorbenLindhauer here to see if there is more to it and also to discuss if there are other ways of achieving what you'd like to do differently without exposing this in the API.

**Comment by ChrisKujawa** [comment]
First of all, it was removed on purpose. 

Second why:

 1. It is a completely internal data structure, to be used by our current webapps
 3. It does not solve any explicit user problem when having it in the API
 4. We don’t introduce/explain the concept of tree path in general
 5. When we have this in the public-facing API we can't iterate/change it easily (as we need to be backwards compatibility), which might block us or slow us down on further improvements


It might make more sense to discuss on the actual problem you want to solve. Maybe you can use a different approach. For example an exporter, which has this as part of the API.

**Comment by saig0** [comment]
@tmetzke and @ChrisKujawa thank you for your input. :+1: 

I understand the reasoning. However, it solved the following user problem. The `treePath` doesn't need to be the solution but it was a good fit. I'm open to alternative ideas. 

**User problem**
I want to visualize the flow-node instances of a process instance in a tree, similar to the Instance History in Operate (see the screenshot below). The tree represents the parent-child relationship between the flow-node instances that correlates to the flow scopes (e.g. sub-processes) in the process.  

![Screenshot from 2024-12-19 13-47-23](https://github.com/user-attachments/assets/740baecf-182a-4f85-a00f-b0177d5bc66c)

![Screenshot from 2024-12-19 13-46-56](https://github.com/user-attachments/assets/6a7c56fc-9ac8-4cdc-a68c-6d4b923bf288)

If the flow-node of an instance is inside a sub-process, it should have a reference to the instance of the sub-process, similar for an multi-instance activity. 

For the stream processor and the exporter, the [ProcessInstanceRecordValue](https://github.com/camunda/camunda/blob/main/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ProcessInstanceRecordValue.java) (i.e. a flow-node instance) has a reference to its parent as [flowScopeKey](https://github.com/camunda/camunda/blob/main/zeebe/protocol/src/main/java/io/camunda/zeebe/protocol/record/value/ProcessInstanceRecordValue.java#L63) (and some new references since 8.7). 

**Use cases**
For Camunda-Process-Test, I want to print the flow-node instance tree if a test fails. The tree would help to reason about a test failure. Read more about this case in: https://github.com/camunda/camunda/issues/23136

```
Process instance: 123 [process-id: 'tree-demo']

Active elements:
|-- start [name: 'Start']
|-- task_a [name: 'A']
|-- multi-instance [name: 'For each'] 
|   |-- start_m [name: '']
|   |-- task_b [name: 'B'] 
```

For monitoring applications, like [zeebe-simple-monitor](https://github.com/camunda-community-hub/zeebe-simple-monitor) or [zeebe-play](https://github.com/camunda-community-hub/zeebe-play).

> Maybe you can use a different approach. For example an exporter, which has this as part of the API.

Technically, it would be possible to use a custom exporter. However, by design Camunda-Process-Test should consume the API to be close a production environment and reduce maintenance costs.

**Comment by ChrisKujawa** [comment]
Maybe it would be possible for you to use the internal api from operate for now until we find a better and supported way

**Comment by saig0** [comment]
I created a new issue to focus on extending the REST API by a new field to represent the parent-child relationship: https://github.com/camunda/camunda/issues/26332. I'm closing this issue in favor of the feature request.

We will consider alternatives if we can't build the new feature in time.
