### ISSUE TITLE
Zeebe fails to become healthy after enabling RBA for Snapshot

### ISSUE THREAD

**Issue by hilalbursalii** [camunda/camunda#26280]
**Describe the bug**
When enabling RBA for SNAPHOST cluster on INT, Zeebe does not become healthy, even after waiting ~20 minutes. 

**To Reproduce**

1. Create a cluster using a SNAPSHOT generation(`Cross Component Test Suite`, `Zeebe Snaphost`, etc)
2. Enable RBA for the cluster
3. Observe that Zeebe does not get healthy.

**Expected behavior**
Zeebe should become healthy within a reasonable timeframe after enabling RBA.

**Actual behavior**
Zeebe fails to become healthy after enabling RBA. 

**Log/Stacktrace**
[Here](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-int%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.cluster_name%3D%22worker-3%22%0Aresource.labels.namespace_name%3D%2233ffcbdb-1fdb-4e2f-a48a-545e2d5f830b-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%20severity%3E%3DDEFAULT%0Aseverity%3DERROR;storageScope=project;pinnedLogId=2024-12-19T09:45:28.893725120Z%2F3gmppfcbu111tppu;cursorTimestamp=2024-12-19T09:45:28.893725120Z;duration=PT1H?inv=1&invt=Abkhzw&project=camunda-saas-int) is the log link for my cluster and below is a log that might be related, but I’m not entirely sure:

<img width="1088" alt="Screenshot 2024-12-19 at 10 52 15" src="https://github.com/user-attachments/assets/368d22ff-d312-4094-9466-cb887eb0b2b0" />

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by remcowesterhoud** [comment]
I've created a fix on the operator side: https://github.com/camunda-cloud/camunda-operator/pull/3614
