### ISSUE TITLE
Add tests for exported metrics

### ISSUE THREAD

**Issue by menski** [camunda/camunda#2695]
Goal:
- ensure we don't accidentally remove metrics or change label names
- ensure we don't remove metrics usage, i.e. values are not increased anymore etc.

**Comment by vvkpd** [comment]
I would like to work on this card

**Comment by npepinpe** [comment]
Before anyone starts on this, I'd like to see a proposal as to how we could test metrics in general. At least to me it's unclear what's the right way to test instrumentation - just unit tests that access the registries directly?
