### ISSUE TITLE
Elasticsearch Exporter : Configurable DateTime Pattern for index

### ISSUE THREAD

**Issue by bhowmikdebarshi** [camunda/camunda#3136]
**Is your feature request related to a problem? Please describe.**

To keep elatsicsearch space under control, we delete the data with prev date's index. But sometime it exports almost 6-8 GB data to elasticsearch in a single day under heavy load. In that situation we need to delete data of few hours old. 

We have customized `ElasticsearchClient`  so that it creates the index on hourly basis instead of daily basis. 
From `this.formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd").withZone(ZoneOffset.UTC);` to `this.formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd-HH").withZone(ZoneOffset.UTC);`

But for this small change, we have to maintain the whole source code. 

**Describe the solution you'd like**

Change in `ElasticsearchClient` class - 

```
public ElasticsearchClient(final ElasticsearchExporterConfiguration configuration, Logger log) {
    this.configuration = configuration;
    this.log = log;
    this.client = createClient();
    this.bulkRequest = new BulkRequest();
    this.formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd-HH").withZone(ZoneOffset.UTC);
  }
```

If we want, we can have the pattern configurable. For that, we need to change in `ElasticsearchExporterConfiguration` as follows - 

```
public static class IndexConfiguration {
    // prefix for index and templates
    public String prefix = "zeebe-record";
    // create index hourly basis 
    public String dateTimePattern= "yyyy-MM-dd"; 
    // update index template on startup
    public boolean createTemplate = true;
```

And in `ElasticsearchClient` class - 

```
public ElasticsearchClient(final ElasticsearchExporterConfiguration configuration, Logger log) {
    this.configuration = configuration;
    this.log = log;
    this.client = createClient();
    this.bulkRequest = new BulkRequest();    
    this.formatter = DateTimeFormatter.ofPattern(configuration.dateTimePattern).withZone(ZoneOffset.UTC);
  }
```

**Comment by dostalradim** [comment]
Configurable DateTime Pattern for index sounds useful to me too. We have some small zeebe instances which creates only tens of documents per day and feed the entire index with shard in elasticsearch is unnecessary.

**Comment by npepinpe** [comment]
This is currently supported. I assume we missed closing this. See: https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/exporters/elasticsearch-exporter/#configuration

Specifically, `indexSuffixDatePattern` configuration.
