### ISSUE TITLE
Remove ActorControl methods

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#3666]
**Description**

I would like to refactor the `ActorControl`, such that we have only methods we really need. It is currently somehow confusing for us and also for starters, which methods is used when. We should trim down the interface to only needed methods like only have a `submit` or `run` method.

**Comment by npepinpe** [comment]
What's the state on this? I can see some work was done, but it wasn't clear how much was required from the issue.

**Comment by Zelldon** [comment]
Not done. Actually I wanted to limit the existing methods to a minimum to reduce the confusion around that API. I had not much time to spent on this in the last quarter. I removed somethings where I saw it was not used but the merging of method seem to be more complicated. Should I take a closer look at this? @npepinpe

**Comment by npepinpe** [comment]
Sorry for the very late reply, but no, I would say this isn't high priority at the moment.

**Comment by Zelldon** [comment]
Might be worth to take a look again? @npepinpe or close it if you thing it is fine for now

**Comment by npepinpe** [comment]
We do need to work somewhat here.

I ran into some issue renaming submit/run, and replacing the usages. One of the issues is that during the closing phase, we don't execute jobs submitted via `submit`, but we do execute jobs submitted via `run`. So it's not just that they have append/prepend semantics, it's also that some are executed and some aren't depending on the phases. I find this in general confusing but I couldn't imagine the reasoning behind it, so I didn't feel comfortable just changing it.

But I do agree - we should remove methods we don't use (though I think we use most of them?), and potentially remove dangerous ones (like `runAtFixedRate` :smile:).

**Comment by npepinpe** [comment]
We already removed a few:

- runUntilDone
- runAtFixedRate
