### ISSUE TITLE
LeaderRole does not retry appends on StorageException

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#4151]
In `LeaderRole::append` there is a retry logic to retry appends when storage exceptions. 

```java
      try {
        resultingFuture = tryToAppend(entry);
      } catch (StorageException storageException) {

        // storage exception wraps IOException's
        retries++;
        if (retries > MAX_APPEND_ATTEMPTS) {
          // only solution is to step down now
          raft.transition(Role.FOLLOWER);
          resultingFuture = Futures.exceptionalFuture(storageException);
        }
```

But this retry is never executed because `tryToAppend` completes the future exceptionally and transition to follower. 

We should consolidate this logic. With the current status, it probably doesn't make sense to retry because we are not triggering a compaction in between. So it would make sense to just remove this retry code.

**Comment by npepinpe** [comment]
Correct me if I'm wrong, but this catches potentially all I/O exceptions, no? We would most likely want to retry them as they may be transient, no? Or do we expect another component to take care of the retry?

**Comment by Zelldon** [comment]
@deepthidevaki @npepinpe is this still a thing we want to take a look at?

**Comment by deepthidevaki** [comment]
The code has not changed. So we should look into it and find the correct way of handling this exception. May be as @npepinpe said, retrying is the correct way. But it is not clear to me. Atleast refactoring the code to make it more readable would be nice. Error handling is done at multiple different places.

**Comment by filipecampos** [comment]
It seems this area of the code has already been refactored by @npepinpe in `LeaderRole::appendEntry` and `LeaderRole::appendWithRetry`. Is there anything to refactor at this moment in time?

**Comment by lenaschoenburg** [comment]
Agreed, the error handling in `LeaderRole::appendWithRetry` looks correct to me now, retrying `JournalException` and `UncheckedIOException`. `JournalException.OutOfDiskSpace` is handled by attempting compaction first. If compaction is not possible, the append is not retried.

There are no futures involved anymore that `append` could complete (exceptionally) to prevent retries.

**Comment by filipecampos** [comment]
Closing issue as it seems to have been addressed by the atomix refactor in February 2023. Just for reference here is the commit:
commit 89fa324a5ed777f750e1ed655b4644a990cd4ed7
Author: Nicolas Pepin-Perreault <nicolas.pepin-perreault@camunda.com>
Date:   Wed Feb 1 17:19:35 2023 +0100

    refactor(atomix): remove blocking usage of futures
    
    Removes unnecessary usage of futures in the append pipeline. We were
    previously creating futures, but they were always completed and
    processed in a blocking fashion. Since the cost of exceptions is less
    throwing them and more creating them, we weren't really saving anything
    there. Plus, we still had to handle the exception if it were to bubble
    up. Finally, in all error cases, we were stepping down as well.
