### ISSUE TITLE
Investigate: Idle time of ActorScheduler is higher then expected

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#4231]
**Description**

During the engine latency investigation we saw that the ActorScheduler is even under high load in some tests around ~15% of the samples idle, which was not expected. It might an issue of to many threads or to much IO? I think it makes sense to investigate that further.

See for example this flamegraph https://github.com/Zelldon/perf-tests/blob/master/mmap/flame-mmap-ssd-entry64kb-segment128mb.svg

We could try to reduce the thread count as a first step.

**Comment by Zelldon** [comment]
Maybe something also interesting for the hackweek

**Comment by npepinpe** [comment]
A good performance day topic, but I don't see it as important right now as this has been the status quo forever.

**Comment by Zelldon** [comment]
I don't see me working on this in the next months / years 😆 I will remove my assingment

**Comment by npepinpe** [comment]
We introduced configuration to change the idle strategy, and via changes, saw reduction of the CPU usage during idle. I would mark this as done via https://github.com/camunda/camunda/issues/14404

**Comment by npepinpe** [comment]
Or rather: https://github.com/camunda/camunda/pull/14523
