### ISSUE TITLE
Improve Swim protocol tests

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#4619]
**Description**

Currently we have only one test class which tests some properties of the swim protocol, but not really the protocol itself nor all properties.

For example what is not tested:

 * that members should probe other members every X interval 
 * send a ping to another member to check whether member B exist

We should increase the test coverage to make sure that it works as expected.

**Comment by npepinpe** [comment]
Closing. As I said, if we do this, it will be in the context of extending/refactoring our Swim protocol implementation.
