### ISSUE TITLE
Possibility to send  job timeout renewal/extension command from job handler

### ISSUE THREAD

**Issue by ialexandrov** [camunda/camunda#4627]
Hi Guys,

Our jobs of given type can last from several minutes to several hours.  So it is quite hard to set the right job timeout to match longest jobs and also not to delay retries of short jobs which got lost due to pod failures or restarts (we are running on Kubernetes).
We don't want to split those jobs to different job types as that would complicate the workflow diagram and not necessary solve the problem.

We think it would be great to have a possibility to extend the job timeout from worker side via command. This would let us to have reasonably short original job timeout and then let the work handler to extend that timeout (maybe even several times) when it's progressing with the job.

**Comment by saig0** [comment]
Hi @ialexandrov,

thank you for raising this up! This sounds like a useful feature :+1: 

There something similar for Camunda BPM (https://blog.camunda.com/post/2017/10/extending_locks_of_external_tasks/).

**Comment by ialexandrov** [comment]
Hi @saig0,
Yep, at the moment we are evaluating both Camunda and Zeebe. We see Camunda as more mature and feature rich product. Although, as we are running micro-services on K8s, we hope Zeebe could cover some gaps in the nearest feature and let us choose it as product for orchestrating our  workloads:)

**Comment by sstro** [comment]
Hi guys,

Any chance this feature gets scheduled/implemented sometime soon ? At the moment, it's a bit of a blocker for us to start using Zeebe/Camunda for workload orchestration (which otherwise would be a very good fit).

**Comment by saig0** [comment]
@sstro no. We don't plan to implement this feature soon. Currently, we're working on other big topics like process instance migration. 

However, we are happy to receive contributions :)

**Comment by jonathanlukas** [comment]
In addition to the Camunda 7 Extend Lock Duration API call, I would like to see a field timeout in the response that can be used to schedule another call.

**Comment by quangtd95** [comment]
I hope this feature would be implemented soon; it is blocking our migration 😔

**Comment by npepinpe** [comment]
I believe this is done via the update job timeout command. https://docs.camunda.io/docs/apis-tools/zeebe-api/gateway-service/#updatejobtimeout-rpc
