### ISSUE TITLE
Add back pressure observed base RTT metric

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#4720]
**Description**

It would be interesting when tuning back pressure to know what's the current observed base RTT, especially when using model based algorithms such as Vegas, even more so if they are windowed.

A simple gauge can be used, and a graph mapping that over time on the dashboard would be enough.

**Comment by Zelldon** [comment]
Due you think this is still useful @npepinpe ?

**Comment by npepinpe** [comment]
Closing, we have nice back pressure and flow control metrics now :)
