### ISSUE TITLE
Handle internal load from timer events gracefully

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#4783]
**Description**

If the timer events are generated at rate faster than the stream processor can process them, this can lead to
* increased processing latency for client commands
* Eventually lead to out of disk space because Stream processor is way behind and as a result cannot compact the logs fast enough. 

To prevent this case, we need some kind of back pressure when writing timer events.

**Comment by deepthidevaki** [comment]
Related to #8991

**Comment by npepinpe** [comment]
I think the scheduled command cache and the new write limits should cover this. If you come across this, you may want to look into https://docs.camunda.io/docs/next/self-managed/operational-guides/configure-flow-control/
