### ISSUE TITLE
Migrate SwimMembershipProtocol to ActorScheduler

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#4829]
**Description**

Currently we have multiple approaches how to run things. Mostly in our components we use our ActorScheduler. In the atomix module the ExecutorServices are widely used. This brings several problems with:

 * it is not easy testable, since you can't alter the time so scheduling of jobs can't be done in unit tests without waiting
 * it makes harder to maintain since it works differently then the actor scheduler
 * if we want to switch to another scheduling framework it would be helpful when already all components use only one scheduling approach

I think it would be a good start to migrate the SwimMembershipProtocol, since it should be straightforward and makes it possible to test is better.

**Comment by npepinpe** [comment]
Will in the long run improve stability has we can now better test it and gain confidence in it.

**Comment by npepinpe** [comment]
Closing for now. I think this should be part of a specific scoped topic, where we try to solve specific problems with the membership protocol implementation. In a vacuum, it's hard to justify prioritization.
