### ISSUE TITLE
Running Exporters seems to have impact on throughput

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#5085]
**Description**

On our last chaos day we found out that running brokers without exporters seems to have an bigger impact on throughput.
Expected was that given enough resources it should not have an impact. I would like to investigate this further.

See summary of the chaos day https://github.com/zeebe-io/zeebe-chaos/blob/master/chaos-days/2020-07-30/README.md

**Comment by Zelldon** [comment]
Might be interesting whether it makes a difference to assign more resources to our default benchmark.

**Comment by npepinpe** [comment]
Prioritized as low as it's not currently one of our focus, but is something we should investigate.

**Comment by npepinpe** [comment]
I'm closing this for now. We will rarely run without exporters, so we should rather focus on optimizing the existing ones. I was told (and want to believe!) we will do so with the new Camunda exporter :crossed_fingers:
