### ISSUE TITLE
Refactoring to avoid invalid state in FileBasedSnapshotStoreFactory / FileBasedSnapshotStore

### ISSUE THREAD

**Issue by pihme** [camunda/camunda#5383]
**Problem Description**

Currently the two classes `FileBasedSnapshotStoreFactory` and `FileBasedSnapshotStore` run into an inconsistent state after `delete()` is called on `FileBasedSnapshotStore`:
*  `FileBasedSnapshotStore` is unaware that it has already been deleted and when used again will complain that the folders aren't there anymore
* `FileBasedSnapshotStoreFactory` is unaware that the store was deleted, keeps it in its internal cache and returns it when requested

This behavior was discovered while analyzing the cause for a flaky test.

**Desired Outcome**
* It should not be possible to use a `FileBasedSnapshotStore` after it has been deleted
* Deleted ``FileBasedSnapshotStore` objects whould be purged from the cache in `FileBasedSnapshotStoreFactory`

**Comment by npepinpe** [comment]
Closing as not planned.
