### ISSUE TITLE
Add means for a client to figure out whether a deployment was successful

### ISSUE THREAD

**Issue by pihme** [camunda/camunda#5474]
**Is your feature request related to a problem? Please describe.**
Currently there is no way for a client to know whether a successful deployment has been distributed to all partitions. 

The return of the deploy command only means that it has been added to one partition. 

It will be distributed to other partitions, but this can take some time.

During that time, it is a game of chance whether a new workflow will be created on a partition that already has the workflow or not.

**Describe the solution you'd like**
I want some way that an ordinary client (all supported languages) can query whether a given workflow in a given version has been distributed to all partitions. 

**Describe alternatives you've considered**
* exporters - not available to customers in the cloud
* return command after distribution - might time out, because it can take long; then the workflow is deployed although the command timed out, which is also surprising

**Comment by pihme** [comment]
Note that this issue manifested itself in the Zeebe cluster testbench. However, resolving this issue is not required to fix the issue in the Zeebe cluster testbench.

**Comment by epollum** [comment]
This issue was mentioned in a support case - [https://jira.camunda.com/browse/SUPPORT-17298](https://jira.camunda.com/browse/SUPPORT-17298)

**Comment by npepinpe** [comment]
We will implement GET endpoints for such use cases in the future, so I will close this in favor of those.
