### ISSUE TITLE
Find a good value for max append per follower

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#5478]
**Description**

The [MAX_APPENDS](https://github.com/zeebe-io/zeebe/blob/develop/atomix/cluster/src/main/java/io/atomix/raft/cluster/impl/RaftMemberContext.java#L34) is used to limit how many appends are send to one follower at once. Currently it is static and set to two. It is likely that this configure can help to improve the throughput. We should evaluate and benchmark different values to get an better understand how it impacts the performance and what would be a good value.

Blocked by #5477

**Comment by npepinpe** [comment]
As with the other one, we can revise the priority if we see that this could help us reach our current performance goal sooner.

**Comment by megglos** [comment]
relates to https://github.com/camunda/product-hub/issues/642
https://github.com/camunda/product-hub/issues/643

**Comment by megglos** [comment]
@falko do you have any input in this?

**Comment by entangled90** [comment]
I ran some benchmarks with different values for MAX_APPENDS in both the default scenario (with 150 PI/s) and the realistic scenario.

# Preconditions
- I waited for the cluster to be balanced (each pod was leader of 1 partition)
- I waited for the nodes to enter into a steady state
- I checked that the in the panel "Inflight request count" the number of requests reached the configured value

# Results 
## Default Scenario
In this scenario, the payload is fixed 32KB (same as the MAX_BATCH_SIZE): all batches will contain only one record.

- [MAX_APPEND=2 (default value)](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-appends&var-pod=All&var-partition=All&from=1728314454000&to=1728315795000)
![image](https://github.com/user-attachments/assets/8656c24e-5773-41e0-b9e6-9fea4e1f638a)

- [MAX_APPEND=4](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-appends&var-pod=All&var-partition=All&from=1728316554000&to=1728317715000)
![image](https://github.com/user-attachments/assets/00ea24af-4f94-40ee-a42c-61d8f571ada2)

- [MAX_APPEND=6](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-appends&var-pod=All&var-partition=All&from=1728372135257&to=1728373196730)
![image](https://github.com/user-attachments/assets/571d239f-5c57-451f-9e37-6ebb7afa8901)

- [MAX_APPEND=10](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-appends&var-pod=All&var-partition=All&from=1728374683971&to=1728375969892)
![image](https://github.com/user-attachments/assets/0f7fdb8c-d408-48d0-8e03-06bc19ec54c0)
When using this setting the number of inlight requests rarely goes above 6:
![image](https://github.com/user-attachments/assets/0f4f71ae-fc22-4264-bc42-359774f6655e)

- [MAX_APPEND=16](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-appends&var-pod=All&var-partition=All&from=1728376633673&to=1728378187953)
![image](https://github.com/user-attachments/assets/e3812454-ffe4-4a3c-9f0f-ab4a42fe34d4)
When using this setting the number of inlight requests rarely goes above 10:
![image](https://github.com/user-attachments/assets/1b602845-5245-4cd7-9d8d-0e9dfaeadf6b)

By looking at these charts the best value is MAX_APPEND=10 if we can tolerate a slight increase in memory used/committed by the JVM.

## Realistic scenario
In this scenario the avg payload is around 1KB, with a MAX_BATCH_SIZE of 32 KB: each batch will probably contain between 20/25 messages.


- [MAX_APPEND=2 (default)](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-appends&var-pod=cs-max-appends-zeebe-0&var-pod=cs-max-appends-zeebe-1&var-pod=cs-max-appends-zeebe-2&var-partition=All&from=1728380745855&to=1728381615780)
![image](https://github.com/user-attachments/assets/ed78d379-047e-4102-800f-25e6cb13071f)

- [MAX_APPEND=6](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-appends&var-pod=cs-max-appends-zeebe-0&var-pod=cs-max-appends-zeebe-1&var-pod=cs-max-appends-zeebe-2&var-partition=All&from=1728382934000&to=1728384025000)
![image](https://github.com/user-attachments/assets/17e1d025-33bc-42db-a8e2-2043457874b9)

- [MAX_APPEND=10](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-appends&var-pod=cs-max-appends-zeebe-0&var-pod=cs-max-appends-zeebe-1&var-pod=cs-max-appends-zeebe-2&var-partition=All&from=1728389919923&to=1728391203605)
![image](https://github.com/user-attachments/assets/760e23cb-ec0d-4488-adb9-e75f255123c6)

By looking at these charts the best value is probably MAX_APPEND=6 (potentially between 2  and 6, so I could test with MAX_APPEND=4 as well).

### Main takeaways
- this parameter is strictly correlated with the payload size and the MAX_BATCH_SIZE, so we should probably change the default value of these two parameter together running a matrix of benchmarks.
- the current default is a bit too low, we could bump it to 4 without too many risks (if we keep BATCH_SIZE the same)
- Some panels in the Zeebe dashboard can be improved:
   - Inflight message request is missing a namespace/pod filter
   - Some latency metrics are missing higher percentiles (90 & 99) and should be moved to a logarithmic scale
   - there is no metric for number of messages in a batch
- I think that the max number of bytes in flight should not exceed some fraction (say 1/2 as an example) of the socket write buffer size. Currently it is hardcoded as 1MB (which is not a small value) but nonetheless in the **default scenario** with 16 requests in flight we reached 512KB. Making the socket write buffer size configurable could be another parameter to add to the tests and making it configurable is probably good for end users.
