### ISSUE TITLE
ElasticsearchExporterException: Failed to put index template (connection closed)

### ISSUE THREAD

**Issue by pihme** [camunda/camunda#5514]
**Describe the bug**
Observed as error in production logs

**Expected Behavior**
* Connection is reestablished when closed/lost/broken

**Log/Stacktrace**
https://console.cloud.google.com/errors/CPG6hcnFn5vaoAE?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CJ2d_LTPvY3JxwE?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CO39mITZ6tTvfg?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CJ3qk8b6-8CVTg?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CNqluvjrzr3tIg?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

**Comment by pihme** [comment]
Exporter was unable to export. This happened 5 minutes after startup. After this error the broker shuts down (not sure if it is related to the error, but strange nonetheless)

**Comment by npepinpe** [comment]
Let's verify if the Elastic client needs to be reopened if the connection is closed, or if we closed the client in Zeebe and tried to reuse it.

**Comment by npepinpe** [comment]
Closing as stale, please reopen if we see it again.
