### ISSUE TITLE
Refactor BrokerCfgTest to use central point for default configuration assertions

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#5944]
**Description**

Many configuration options are tested to ensure that the expected defaults are set. This is done by testing against two configuration files - an empty one, and a default one. However this is duplicated everywhere in the test, meaning every default must implicitly know to test against both files. This is brittle and not easily extensible.

Also questionable is why both files? Having a copy `default.yaml` means it may get out of sync - should we test only with the empty file to test defaults?

Either way, either make use of the helper `assertWithDefaultConfigurations` or test only against `empty` and simplify the helper as well so all default tests use the same configuration.

**Comment by Zelldon** [comment]
Did we ever think about testing with golden files? Like we do in the helm charts. What I mean is create a config object serialize it and write it to a file, the golden file, next runs we always compare it against that file. Here we will detect any changes in defaults, or additions and can either regenerate the golden file IF the change is expected and intentional. I think with this we would avoid a lot of these test cases. Wdyt @npepinpe

**Comment by npepinpe** [comment]
Golden files would probably make it a lot easier in the long run :+1: It's probably a ZDP issue because it's related to the application shell :shrug: 

Honestly I'm not sure why we test the configuration of the broker like that. We're just testing Spring mostly :shrug: 

I would rather each module exposes an immutable configuration interface, and the dist module/applications have the Spring Boot beans which produces such config. We can then evaluate if the deserialized config beans are correct. Also probably with golden files.

Anyway, doing that is a lot of tedious work since all our test utilities still expect to be able to configure the broker/gateway from a single `BrokerCfg`/`GatewayCfg`, so I'm not super keen on doing that :smile: Just the golden files thing is already a good step :+1:

**Comment by npepinpe** [comment]
Closing - we will harmonize configuration across C8 in the next year, so I don't see much value investing here at the moment.
