### ISSUE TITLE
Test clients against Camunda Cloud

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#5968]
**Description**

We recently updated our Go client to use TLS 1.3, which breaks against Camunda Cloud. While that was incorrect in itself - we can assume most people are on 1.2 at least, but we can't assume everyone's on 1.3 - it showed a clear issue, which is we never tested the Go client against Camunda Cloud at any point before the release. We primarily use the Java client, and zbctl in testbench - however the zbctl used is not the one part of the distribution under test.

I'd like to brainstorm a little on what's the best approach here - should we do these kind of tests for the clients in testbench? Directly (as in, a client test) or indirectly (as in, the tests use a mix of all clients)? Or is there a different alternative?

**Comment by saig0** [comment]
I like the idea a lot. I also thought about this kind of test. 

A mix of all clients could verify that the different clients play nicely together. Like a smoke test. It could be easy to start with this first.

The environment of the test could be the testbench. But I see also value in having a long-running workflow (i.e. a sample application) that uses all clients. Here, we can observe the behavior when the clients run for a longer period.

**Comment by npepinpe** [comment]
While it's unlikely we'll manage to do this before 0.26, there will be patch releases anyway, so I would like this as soon as possible, even if it ends up rolling over to Q1.

**Comment by pihme** [comment]
FYI as part of working on the documentation for 0.26 the get started repos for Java + Go also received PRs which modify the code to work with cloud and local. So testing it as part of release process should become easier.

**Comment by npepinpe** [comment]
We now have more E2E, QA, etc. which tests clients in SaaS. What's missing is the Go client, but we are deprecating it. So I will close this.
