### ISSUE TITLE
Java job worker doesn't deal with non-transient errors correctly

### ISSUE THREAD

**Issue by MiguelPires** [camunda/camunda#6167]
**Describe the bug**
Related to #5812. The Java client logs errors and eventually retries the job activation. If the request was rejected this is almost certainly not a transient error and retrying will not fix the issue instead entering a loop of failing and logging exceptions. 

**Expected behavior**
The worker doesn't retry after getting a permanent error (like an INVALID_STATE rejection), informs the user and then closes.

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: [e.g. 0.20.0]
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
Closing: we now do back off on error, and we have a service policy defining how to retry based on error type.

**Comment by amitonlentra** [comment]
@npepinpe - we want to disable retries on any errors but are unable to configure the java zeebe client to do so. Fortunately i came across this issue that states that there are retries based on error type - could you please guide me on how to disable them? We tried `zeebe.client.useDefaultRetryPolicy: 'true'` but that didn't help.

**Comment by npepinpe** [comment]
@megglos do we have any functionality for this from the client? I don't think so, but I'm not so involved anymore.

**Comment by megglos** [comment]
@amitonlentra let's follow-up on the issue you created https://github.com/camunda/camunda/issues/35609
