### ISSUE TITLE
Remove demote and promote from Raft

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#6212]
**Description**

Currently we have a feature to promote or demote a Raft member, which means you can put a member from ACTIVE to PASSIVE or vice versa. This includes an configuration change, since if the node is PASSIVE/INACTIVE it is not part of the quorum anymore.

We currently not use this feature and only support static configurations. For the reason of reducing tech debt and increasing maintainability we should remove these stuff until we really need it.

**Comment by npepinpe** [comment]
I understand we want to get rid of it, and I agree, but is it causing any issue in terms of complexity? We removed join/leave mostly because join was actually used and was buggy - I don't believe we call promote/demote (correct me if I'm wrong), and we don't expose this, so this is probably something we can do after the next release without breaking backwards compat no?

**Comment by megglos** [comment]
@npepinpe 
is this about removing promote/demote only from the https://github.com/camunda/zeebe/blob/main/atomix/cluster/src/main/java/io/atomix/raft/cluster/RaftMember.java#L58-L96
interface or also from the RaftServer?

As for the RaftServer, promote seems to be the only way to set a server as leader.

**Comment by npepinpe** [comment]
Both. At the moment, I believe we only use promote/demote in testing. You can start by removing the unused parts (including their specific tests), and leave the "used" parts. The next step would be to evaluate the value of having such features like leadership transfer which are only used in few tests (and thus aren't properly tested), but I think that might be a bit much to do when starting out in the code base.

Eventually (at a later point), we should remove the leader ship transfer feature, as we don't use it and it's likely poorly tested and thus only subtracts value from the project - or of course, we can decide to actually invest in it :)

**Comment by Zelldon** [comment]
✋️ 

Didnt we use this in integration tests? For testing how system reacts on leader changes? 🤔

**Comment by npepinpe** [comment]
Yup, we do in some places. But that uses the annoint API. Like I said, we should evaluate if this is the right thing to use for our tests, and if we weren't simply making use of something that already existed. As we don't use this feature(s) in production, and with our experience with Atomix, I wouldn't trust it that much, I'd rather get rid of it - or if we think it's a feature in prod we want, put time and effort into it.

**Comment by Zelldon** [comment]
Agree.

**Comment by npepinpe** [comment]
We now support dynamic configuration, so closing this :)
