### ISSUE TITLE
Pin child process version to parent process

### ISSUE THREAD

**Issue by enamrik** [camunda/camunda#6275]
### Is your feature request related to a problem? Please describe.

Yes this feature request is related to a problem.

The BPMN documentation says:

> The new instance of the defined workflow will be created of its latest version - at the point when the call activity is activated.

This is a problem for my development team. If we implement a change in a child process that makes it incompatible with older versions of the parent process, then we see two issues:

1. Since deploying multiple files is not atomic, the new parent version could arrive first, be picked up and used with an older version of the child process.
1. An incomplete, old workflow instance based on an older version of the parent process will pick up the new incompatible child which will break the workflow.

We could abandon using subprocesses in child process files but that would cause massive duplication.

### Describe the solution you'd like

I imagine it would take a combination of features to solve this issue.

**Allow the user to specify a workflow's child workflow version resolution strategy:**

1. `ParentVersion`: use the version of the parent. Fail if can't find a child version matching the parent's version. This requires version be writable:
```
zbctl deploy parent.bpmn --version 1
zbctl deploy child1.bpmn --version 1
zbctl deploy child2.bpmn --version 1
```
3.  `LatestChildVersion`: pick whatever is the last version of the child process. This is currently the default behavior and would remain so.

But `ParentVersion` still doesn't completely solve the problem. If the parent process version=1 gets deployed, the release script fails and a workflow is instantiate with parent process version=1, the missing child1 version=1 will cause an error. 

**Introduce the concept of releases**

The problem is there is no concept of an atomic release. To solve this, `ParentVersion` could be `ParentRelease` and would require the follow:

1.  If we could execute:
```
zbctl create release --name 1
zbctl deploy child.bpmn --release 1
zbctl deploy parent.bpmn --release 1
zbctl publish release --name 1

OR

zbctl publish release  --name 1 child.bpmn parent.bpmn
```
then:
1. We wouldn't have to worry about failures mid-script since the release was never published and so no workflows got started with processes in release `1`.
2. `zbctl publish release` would be an atomic operation so it won't be possible for the parent process of a release to ever exist without child processes.
3. All existing workflows before the release will complete with the child process versions with which they were deployed.

### Describe alternatives you've considered

If this feature feels out of scope for Zeebe, then just allowing pinning of child processes would help:

```
zbctl deploy parent.bpmn --child-process-version child1=1,child2=1
```
Using just this feature, the community could build tools to make atomic releases possible.

**Comment by saig0** [comment]
Related forum post: https://forum.zeebe.io/t/how-do-i-pin-child-bpmn-file-version-to-parent-bpmn-version/1997

**Comment by npepinpe** [comment]
I believe this will be done via version binding: https://github.com/camunda/camunda/issues/19384
