### ISSUE TITLE
Export events only

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#6749]
**Is your feature request related to a problem? Please describe.**

Yesterday the discussion, during our "engine migration sync", came up that other systems should only be interested in events instead of commands, since they mark the state change. My suggestions would be to export events only, which would make the exporting also faster again.

**Describe the solution you'd like**

Only export events instead of all records.

**Describe alternatives you've considered**

Not sure, if we expect that users should only consume events then in my opinion we should restrict it in such a way.

**Additional context**

The discussion came up because we thought about dropping later the complete command for the start event, which might be a breaking change if people rely on exported commands.

**Comment by Zelldon** [comment]
Based on our default config I would assume that operate doesnt consume it:


 * https://github.com/camunda-cloud/zeebe/blob/develop/dist/src/main/config/broker.standalone.yaml.template#L471
 * https://github.com/camunda-cloud/zeebe/tree/develop/exporters/elasticsearch-exporter#index

**Comment by pihme** [comment]
Counter argument: Zeebe analytics might want to look at commands. E.g. in the context of "Start Process from Anywhere" we want to track normal PI creation vs. the PI creation with start instructions. The start instruction would be optional fields on a create PI command. Reverse engineering this information from only events seems too cumbersome to be viable.

**Comment by npepinpe** [comment]
I would like to keep the commands for observability, but we could have a default be to export only events.

**Comment by npepinpe** [comment]
Default is now only events, so I will close this.
