### ISSUE TITLE
Restarted node took hours to complete the startup

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#7339]
We observed that in some clusters a restarted node took hours to complete the startup. On further investigation we observed the following:
There is an inflight request in the leader which is sent to the follower at the time the follower was restarted. This inflight request is not completed or timed out. Hence the leader does not sent any more heartbeat because there is a limit on number of inflight requests. The requests are expected to timeout with in a specified timeout. But that did not happen here even after a few hours. Since the restarted follower does not receive any heartbeat it cannot join the cluster. The follower tries to trigger a new election, but that does not succeed because it does not have the latest log. 

More details about this issue are [here](https://docs.google.com/document/d/1mLd4wGqe332WwuXXfaafB8kljEohVzN2Q89s42Y6fqo/edit?usp=sharing)

The only way to recover from this is to restart the leader.

**To Reproduce**

Haven't tried to reproduce it. But we could try to restart a pod repeatedly and check if it happens.  Note that it does not happen always. 

**Expected behavior**

1. The leader should always send heartbeat to a follower.
2. The inflight requests should complete successfully or fail within a specified timeout.

**Environment:**
 - OS: Camunda cloud
 - Zeebe Version: 1.0.0

**Comment by npepinpe** [comment]
I'm tentatively marking this as solved via #7362. It's not 100% clear, but the bug described in #7360 could definitely have triggered this, so as it is fixed, let's see if this will keep occurring.

**Comment by korthout** [comment]
This happened again on production cluster `c85f3270-9cf0-496b-9e25-f55bc14c1ec9`, but it quickly resolved itself.

## What happened?
On the 16th of November 2021 at 13:00 CET a paging alert `ZeebeStatefulSetReplicasMismatch` regarding this cluster was fired, meaning that for more than 1 hour not all zeebe brokers were up and running.

Cluster `c85f3270-9cf0-496b-9e25-f55bc14c1ec9` has 3 brokers and 2 partitions with replication factor 3. At the time of the problem it looked like this:
- `broker-0` is leader for partition 2
- `broker-1` is leader for partition 1
- `broker-2` is crashlooping

`zeebe-2` is unable to become ready and is crashlooping. It is able to find leader 1 every time it is rebooted, but is unable to find the leader for partition 2 which is supposed to be `zeebe-0`. The logs of `zeebe-0` don’t show anything strange (as far as I can tell).

We think the same thing happed as described in this issue. The proposed solution was to restart `zeebe-0` which happened automatically at around 15:30 CET and resolved the problem.

Before it restarted, we made a heapdump ([runbook](https://github.com/camunda-cloud/runbook/blob/master/zeebe/runbook.md#creating-a-heap-dump)) of the `zeebe-0` broker and enabled trace logging on `io.atomix.raft` [runbook](https://github.com/camunda-cloud/runbook/blob/master/zeebe/runbook.md#change-log-level-on-a-running-cluster).

## Links
- [Alert fired](https://camunda.slack.com/archives/CQZGZL03X/p1637064048010200)
- [Alert resolved](https://camunda.slack.com/archives/CQZGZL03X/p1637073498022400)
- [Grafana](https://grafana-worker-1.internal.camunda.io/d/I4lo7_EZk/zeebe?orgId=1&from=1637056189387&to=1637077418253&var-DS_PROMETHEUS=Prometheus&var-namespace=c85f3270-9cf0-496b-9e25-f55bc14c1ec9-zeebe&var-pod=All&var-partition=All)
- [Logs](
https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%22c85f3270-9cf0-496b-9e25-f55bc14c1ec9-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0A;timeRange=2021-11-16T10:27:43.758Z%2F2021-11-16T15:27:43.758Z;pinnedLogId=2021-11-16T13:54:26.115245Z%2Ffntt5z7l8fkeucwj;cursorTimestamp=2021-11-16T13:54:37.235746Z?authuser=0&project=camunda-cloud-240911)
- [Heapdump](https://drive.google.com/file/d/11dNYzbELZevL9OSN2qE0C0KF-FJMhLnK/view?usp=sharing)

**Comment by menski** [comment]
Potentially an issue for next quarter. Right now it seems to not happen that often, we will monitor if similar alerts happen in prod and re-evaluate the priority if needed.

**Comment by Zelldon** [comment]
@deepthidevaki didn't you fixed some issues in RAFT in the last quarters is this maybe resolved?

**Comment by deepthidevaki** [comment]
Not sure. It might be also related to the netty channel issues that you worked on recently.

**Comment by npepinpe** [comment]
I'm closing this for now, mostly as we haven't even pulled this up in 2 years, so either it is fixed or the likelihood is very low, or we're missing something. But I don't foresee us working on this unless someone reproduces it, so let's close it.
