### ISSUE TITLE
Create partitions in parallel and register them one by one 

### ISSUE THREAD

**Issue by pihme** [camunda/camunda#7541]
**Description**

Depends on #7539 

Goal of this issue is to refactor the partition bootstrapping in two ways:
* Start all partitions in parallel
* Once a partition is bootstrapped, add it as local partition to the partition manager

Currently the sequence is:
1. `PartitionService#start()`
2. `ManagedPartitionGroup#join(...)`
3. Loop over partitions
4. `RaftPartition.open()->initServer(...)->createServer(...)` 
5. `new RaftPartitionServer(...)`

This call chain needs to be refactored such that 
* the loop over all partitions is part of the bootstrapping logic
* The creation of the `RaftPartitionServer` becomes a dedicated partition bootstrap step (and `RaftPartitionServer` is added to `PartitionBootstrapContext`)

Then, once the bootstrapping for a partition has completed, it can be supplied to the `PartitionManager`

**Comment by pihme** [comment]
See also @npepinpe comment on https://github.com/camunda-cloud/zeebe/issues/7535. It probably is more important to consider for this issue.

**Comment by pihme** [comment]
Maybe a few comments on how I hope it will come together.

Next steps here can be done after #7599 and #7629 is merged.

Once these two are in place we could start separating partition bootstrap steps and transition steps.

1. Once the Raft partition group loop is unwound, we can add as a first true bootstrap step the step to create the Raft server
2. Then we can refactor the startup sequence of the partition from:
```
partition = new ZeebePartition();
actorScheduler.submitActor(zeebePartition);
  zeebePartition.onActorStarting()
   onRoleChange(...)
     transition.transitionToX();
```

to: 
```
partition = new ZeebePartition();
actorScheduler.submitActor(zeebePartition);
zeebePartition.onActorStarting()
  partitionStartupProcess.start().whenComplete( (sucess, failure) {
    onRoleChange(...)
     transition.transitionToX();
  })
```

Then, continuing with the migration to the new model of separate steps for bootstrapping vs.  transition, we can iteratively drain the `LEADER_STEPS`, `FOLLOWER_STEPS` and add corresponding steps to `STARTUP_STEPS`.

Once we have isolated all startup steps, we can then work on harmonizing the leader and follower transition steps. Once those two lists are quasi-identical we can migrate them over to transition steps and rewire them.

**Comment by npepinpe** [comment]
I believe this was done in https://github.com/camunda/camunda/pull/13819
