### ISSUE TITLE
Extract reading and writing of segment descriptor out of the JournalSegmentDescriptor

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#7650]
Extract reading and writing of segment descriptor out of the JournalSegmentDescriptor. We can also think of having a `SegmentDescriptorLoader` which knows how to read,write and serialize segment descriptors. This is only needed when loading or creating a segment. Once the segment is created we always refer to the in memory `JournalSegmentDescriptor`. 

Follow up #6221 
Related #7604

**Comment by entangled90** [comment]
Is part of this issue solved by https://github.com/camunda/camunda/commit/0c3e8c87aff18daf66fcf731a6aacb2ad229d780 regarding reading a SegmentDescriptor?
