### ISSUE TITLE
Problems with follower installing on abort install request

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#7700]
**Description**

Currently we implemented the reaction of install requests with a listener which reacts on the first chunk to go to inactive state and when the install request is complete we install the follower services again.

We have some issues we need to solve with that:

1. Issue: We don't await the transition (the call is async), this might lead to issues if we immediately complete the install req or abort it. Verify whether this is an issue
  1. One problem it might cause is that we are not removed all services yet and already delete the log, since this happens concurrently.
2. Issue: When we abort a install request we notify our listeners and install all follower services again. I feel in the most cases this is not useful. 

Example for 2.: We get an install request and become Leader, we abort the snapshot which cause installing follower services and then to install leader services.

Another Example for 2: We abort install request because we get a new install request. We install follower services, uninstall them again and then install them if we are done. 

There are several other examples, where I feel on aborting we should not install the follower services. @deepthidevaki any thought an this one?

**Comment by Zelldon** [comment]
I think we should not install follower services on abort in general, because eventually we need to complete an install request otherwise we can't continue anyway. If we complete it this should then the only place where we install the follower services again.

**Comment by deepthidevaki** [comment]
> 
> We have some issues we need to solve with that:
> 
>     1. Issue: We don't await the transition (the call is async), this might lead to issues if we immediately complete the install req or abort it. Verify whether this is an issue
> 

What issues can it cause? Some of the known issue with concurrently deleting the log is already handled. Are there anything else?

>     2. One problem it might cause is that we are not removed all services yet and already delete the log, since this happens concurrently.

Concurrent deletion of log is expected, and we have handled it. The assumption is that the services will be eventually deleted and new services are installed. So it starts using the new snapshot and the log. 

> 
>     3. Issue: When we abort a install request we notify our listeners and install all follower services again. I feel in the most cases this is not useful.

I agree this is not ideal. But I don't think it is problematic. It doesn't lead to any incorrect state. We can definitely improve it, but not a high priority at the moment.

> 
> 
> Example for 2.: We get an install request and become Leader, we abort the snapshot which cause installing follower services and then to install leader services.

This case never happens because this node is lagging behind. So it can never become the leader before receiving the snapshot.

> 
> Another Example for 2: We abort install request because we get a new install request. We install follower services, uninstall them again and then install them if we are done.

This is not ideal  but not problematic.

**Comment by npepinpe** [comment]
Due to holidays, I'm moving this back in the planned column so we can focus on the bugs we've found.

**Comment by Zelldon** [comment]
I will remove this from the milestone. I think we can improve this later if we see a real need.

**Comment by npepinpe** [comment]
Closing. I guess we never saw a real need :smile:
