### ISSUE TITLE
Improve Exporter IT Test coverage

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#7731]
**Description**

I have the feeling that the test coverage regarding Exporters is quite low, we seem to have no IT tests, especially no clustered ones, for exporters. 

Matter of interest would be for me:

 * exporters should work after fail-over 
   * exporter start on last know position - which verifies our "at least once" exporting guarantee (extracted from https://github.com/camunda-cloud/zeebe/issues/7696)
   * we should not miss an record after fail-over
 *  pause and resume
   * exporting works after resuming; starts with the next
   * combination of pausing and resume and fail-over
 * install request handling
   * follower receives install request -> becomes leader and can export

**Comment by Zelldon** [comment]
@npepinpe was this done by your recent changes?

**Comment by npepinpe** [comment]
No, those were only about the Elastic exporter, and don't test general exporter behavior. I think this is a good issue, but I'm surprised we don't have tests for these things :thinking:

**Comment by npepinpe** [comment]
Done by the way :+1:

**Comment by npepinpe** [comment]
Sorry, wrong issue :see_no_evil:

**Comment by npepinpe** [comment]
Small update: I think pause/resume has been improved by @oleschoenburg with the refactoring. What would be missing is install request handling and fail over.

**Comment by npepinpe** [comment]
We added many integration tests now, especially since you pause, soft pause, disable, enable, resume, etc., which all have to stop/restart, test the metadata, etc.
