### ISSUE TITLE
Raft thread is blocked during the registration and start of the partition manager

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda#8281]
**Describe the bug**
Only after all Raft partitions are `READY`, the [partition manager and Zeebe partitions](https://github.com/camunda-cloud/zeebe/blob/d1271e8a5e09ea35238d008ec88284457aff2368/broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java#L119-L162) are started (see #5209). The starting of the Zeebe partitions blocks the Raft thread assigned to the last Raft partition changing the state from `ACTIVE` to `READY`.

According to the logs, the registration and start happening with the Raft thread can be seen with the following log statements:
1. [`Registering Partition Manager`](https://github.com/camunda-cloud/zeebe/blob/d1271e8a5e09ea35238d008ec88284457aff2368/broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java#L130) - see thread name `raft-server-2-raft-partition-partition-3`:
```
{
  "jsonPayload": {
    "context": {
        "partitionId": "3"
        "loggerName": "io.camunda.zeebe.broker.partitioning.PartitionManagerImpl",
        "threadName": "raft-server-2-raft-partition-partition-3"
      },
      "message": "Registering Partition Manager"
    },
    "timestamp": "2021-11-17T10:37:28.792033251Z",
  ...
}
```
2. [`Starting Partitions`](https://github.com/camunda-cloud/zeebe/blob/d1271e8a5e09ea35238d008ec88284457aff2368/broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java#L136) - see thread name `raft-server-2-raft-partition-partition-3`:
```
{
  "jsonPayload": {
    "context": {
        "loggerName": "io.camunda.zeebe.broker.partitioning.PartitionManagerImpl",
        "partitionId": "3",
        "threadName": "raft-server-2-raft-partition-partition-3"
    },
    "message": "Starting partitions"
  },
  "timestamp": "2021-11-17T10:37:28.794763587Z",
  ...
}
```

Actually, starting the Zeebe partitions happens asynchronously but the Raft thread is being blocked until all Zeebe partitions are started, therefore, it waits for the [completion of all futures](https://github.com/camunda-cloud/zeebe/blob/d1271e8a5e09ea35238d008ec88284457aff2368/broker/src/main/java/io/camunda/zeebe/broker/partitioning/PartitionManagerImpl.java#L159).

As a consequence, of blocking the Raft thread, no heartbeats are sent to the followers. Subsequently, the followers start sending poll requests to the members, and they could potentially start a new election so that a new leader could get elected. This would force the current leader to transition back to the follower role.

**Expected behavior**
* The registration and start of the partition manager and the Zeebe partitions do not happen in the Raft thread. So that the Raft thread is not blocked and continues sending heartbeats to the followers.

**Possible solutions**
* When notifying any Raft listener (e.g., `RaftRoleChangeListener`, State change listener, ...), the listeners are executed with another thread than the Raft thread itself.
* Use `#thenApplyAsync()` (instead of `#thenApply()`) and provide a dedicated `Executor` to control that the execution of the callback happens with an expected thread.

**Environment:**
 - Zeebe Version: 1.2.4
 - Configuration: This issue occurs in a cluster with multiple partitions.

**Comment by npepinpe** [comment]
@lenaschoenburg - I believe with the refactoring you did, this is not the case anymore, correct? Partitions start fully independently, and we don't join on the caller thread anymore.

**Comment by lenaschoenburg** [comment]
Yes, this should be fixed already :+1:
