### ISSUE TITLE
Ensure all locks are released properly

### ISSUE THREAD

**Issue by romansmirnov** [camunda/camunda#8382]
**Description**

Based on the discussion in https://github.com/camunda-cloud/zeebe/pull/8372#discussion_r768416274, this issue is about checking the usage of the locking mechanism, especially, its proper release in all circumstances (like failure cases).

This issue includes the following tasks:

- [ ] Check the code-base for the usage of locking mechanisms (e.g., `StampedLock`)
- [ ] Ensure the corresponding locks are released properly in all cases
- [ ] Decide if the locking concern should be separated in a different class to use it as a composite in the certain places
  - [ ] Create a separate class that handles acquiring/releasing locks
  - [ ] Use that class wherever the locking mechanism is used
  - [ ] Check for existing test cases if they are still required (e.g., https://github.com/camunda-cloud/zeebe/pull/8372#discussion_r768421624)

**Comment by npepinpe** [comment]
I'm not sure it's worthwhile looking combing the code base for lock usage at the moment, unless we have specific suspicions. I would rather invest time into tooling that can help prevent misuses in the future (though I don't think we can can 100% prove that). I'm not aware of any in particular, but if you have any ideas please share it.

AFAIK, we use locks only in the journal, and in the actor scheduler (ignoring testing code). I'm not sure if this is something urgent at the moment, but let me know what you think.

**Comment by romansmirnov** [comment]
@npepinpe, IMO this is not urgent.

**Comment by npepinpe** [comment]
As we haven't touched it in years, I would close it for now. I'm definitely open to suggestions in the future, but until then, it's very unlikely we will plan capacity for this.
