### ISSUE TITLE
Read only metadata on seek

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#8602]
**Description**

Currently if we seek for an index we read all records one by one to find the index. 
https://github.com/camunda-cloud/zeebe/blob/develop/journal/src/main/java/io/camunda/zeebe/journal/file/MappedJournalSegmentReader.java#L89-L90

I think the main issue here is that the index is not part of the metadata https://github.com/camunda-cloud/zeebe/blob/develop/journal/src/main/java/io/camunda/zeebe/journal/file/record/RecordMetadata.java it is part of the RecordData https://github.com/camunda-cloud/zeebe/blob/develop/journal/src/main/java/io/camunda/zeebe/journal/file/record/RecordData.java
This means we always need to first read the metadata then the data, only to check whether the index is the index we looking for. 

Ideally we would be able to just jump to the meta data and check for the index and if this is the right one read the rest otherwise continue. i think this would improve our read performance.

**Comment by npepinpe** [comment]
Let's leave it for now in the backlog as it was already previously like this, and working on this doesn't fit our current focus for this quarter.

**Comment by npepinpe** [comment]
Looked briefly at this with @entangled90, and we came to the conclusion we don't need to do this issue, as we don't seek very often (mostly only when the follower has issues), and seek is already relatively fast (compared to the use cases where it's required).

I'll look for another issue for @filipecampos to get familiar with benchmarks 👍
