### ISSUE TITLE
Simplify configuration of threads in relation to partition count

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#8741]
**Is your feature request related to a problem? Please describe.**

Users have issues to understand or see the relation between CPU and IO threads and partition counts on a node. We should try to make the users life easier and simplify this configuration or made it possible to configure with one thing multiple configurations, similar to the maxMessageSize, which sets also several properties in Zeebe.

Example: https://camunda-cloud.slack.com/archives/C6WGNHV2A/p1644039751236089?thread_ts=1643807352.592009&cid=C6WGNHV2A 

**Describe the solution you'd like**

I would like to we have a property like the partition count per node, which directly also sets the need threads. For example if I set two partitions that I get two threads for processing (cpu threads) and two for exporting (io threads). Ideally if needed I could still configure them separately. 

**Describe alternatives you've considered**

 1. Rename the properties to make the purpose or usage more clearer. 
 2. Do nothing and cry

**Additional context**

I think it would make sense to make the users life in certain places easier, Zeebe is already complicated enough.

**Comment by aivinog1** [comment]
I'm voting for that thread count should be equal by default partitions count. But it should be documented somehow of course :)

**Comment by Zelldon** [comment]
I did a small test and saw that with our current benchmarks for example we also get better results if they are equal to the partition count.

**Thread count == Partition Count (=3)**

![threadeq](https://user-images.githubusercontent.com/2758593/152806753-1d3ee3d7-1b32-4f92-bfd4-b03d0fbc34d1.png)

**Our normal medic benchmark, where thread count is 4 and partition count 3.**

![medic](https://user-images.githubusercontent.com/2758593/152806881-454254fb-c2a7-4eaa-94a6-c1c2e002c6b0.png)

**Comment by npepinpe** [comment]
Seems reasonable, however ease of configuration isn't a main focus at the moment. I'm happy to consider a more concrete proposal and accept a PR for it, but at this time we probably won't work on this.

**Comment by npepinpe** [comment]
I still think this is a good feature, however with dynamic scaling, this becomes a little more complicated, since our scheduler's thread pool is not dynamic =/ Additionally, we did think about moving towards virtual threads (i.e. each job is executed in a virtual thread), so idk.

I would close this for now, I doubt we'll work on it in the near future. I'm still open for a concrete proposal however, but please open a new issue.
