### ISSUE TITLE
GHA: Extract SARIF Files from Spotbugs

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#9311]
**Description**

As pointed out by @npepinpe spotbugs can produce SARIF files https://camunda.slack.com/archives/C037RS2JHB8/p1651820555884689?thread_ts=1651812559.248919&cid=C037RS2JHB8

For that this line https://github.com/camunda/zeebe/blob/main/parent/pom.xml#L1641 need to be changed to

```diff
-              <xmlOutput>true</xmlOutput>
+             <sarifOutput>true</sarifOutput>
```

The problematic part is that spotbugs will create a SARIF file for each module it runs, located under `target/`. E.g. we will find a SARIF file in `engine/target/` but also under `snapshot/target/` etc.

We need to combine them and upload them see https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github

**Comment by oleschoenburg** [comment]
Let's apply this suggestion as well: https://github.com/camunda/zeebe/pull/9310#discussion_r866820161
It's a bit unrelated but whatever.

**Comment by oleschoenburg** [comment]
Merging all the sarif files like we do here: https://github.com/camunda/zeebe/pull/9301 does not work, instead it generates an empty sarif file:

```json
{
  "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
  "version": "2.1.0",
  "runs": []
}
```

This might be because spotbugs doesn't find any issues? I'm not sure.

**Comment by npepinpe** [comment]
I would leave this out for now. I think it's not ideal, but we rarely need to fix Spotbugs issues, and when we do, the logs are fine.
